use common::*;

fn show_help() -> String {
    let mut h = String::new();
    h.push_str("\n  \x1b[1mCommands:\x1b[0m\n");
    h.push_str("    sylow <n>                  Sylow p-subgroups of Z/nZ for each prime p | n\n");
    h.push_str("    count_sylow <order> <p>    constraints on n_p: n_p | (n/p^a) and n_p ≡ 1 mod p\n");
    h.push_str("    simple_check <n>           use Sylow to check if order-n group MUST be non-simple\n");
    h.push_str("    classify <n>               classify groups of order n <= 30 using Sylow analysis\n");
    h.push_str("    p_group <p> <a>            groups of order p^a: non-trivial center, nilpotency\n");
    h.push_str("    sylow_conj <n> <p>         all Sylow p-subgroups of Z/nZ are conjugate (trivial, abelian)\n");
    h.push_str("    demo                       demonstrate Sylow analysis on current group order\n");
    h.push_str("    help                       show this help\n");
    h.push_str("    quit                       exit\n");
    h
}

/// Find p^a || n (largest power of p dividing n)
fn p_part(n: u64, p: u64) -> (u64, u32) {
    let mut a = 0u32;
    let mut m = n;
    while m % p == 0 { a += 1; m /= p; }
    (p.pow(a), a)
}

fn cmd_sylow(args: &[&str]) -> String {
    let mut out = String::new();
    let n_str = args.first().copied().unwrap_or("12");
    let n = match n_str.parse::<u64>().ok().filter(|&v| v >= 2) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} n must be >= 2.\n", red("✗"))); return out; }
    };

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ Sylow Subgroups of Z/{}Z\x1b[0m\n", n));
    out.push_str(&format!("  Z/{}Z is cyclic of order {}.\n", n, n));
    out.push_str("  For each prime p dividing n, there is a unique Sylow p-subgroup.\n");
    out.push_str("  (Z/nZ is abelian, so Sylow subgroups are unique and normal.)\n");
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    let facts = factor(n);
    if facts.is_empty() {
        out.push_str(&format!("  {} n = 1 has no non-trivial Sylow subgroups.\n", red("✗")));
        return out;
    }

    out.push_str(&format!("  Factorization: {} = {}\n",
        n,
        facts.iter().map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
             .collect::<Vec<_>>().join(" * ")));
    out.push('\n');

    for &(p, a) in &facts {
        let p_a = p.pow(a);
        let m = n / p_a;
        let gen = m;

        out.push_str(&format!("  {}\n", bold(&format!("Prime p = {}, p^a = {}^{} = {}:", p, p, a, p_a))));
        out.push_str(&format!("    Sylow {}-subgroup: H = <{}>  (generated by {} in Z/{}Z)\n", p, gen, gen, n));

        let sub: Vec<u64> = {
            let mut v = Vec::new();
            let mut cur = 0u64;
            loop {
                v.push(cur);
                cur = (cur + gen) % n;
                if cur == 0 { break; }
                if v.len() > n as usize { break; }
            }
            v.sort();
            v
        };

        let sub_str: Vec<String> = sub.iter().map(|x| x.to_string()).collect();
        out.push_str(&format!("    H = {{ {} }}  |H| = {}\n", sub_str.join(", "), sub.len()));
        out.push_str(&format!("    [Z/{}Z : H] = {}/{} = {}\n", n, n, p_a, m));
        out.push_str(&format!("    n_{} = 1 (unique, since group is abelian)\n\n", p));
    }

    out.push_str(&format!("  {} For abelian groups, each Sylow p-subgroup is unique and normal.\n", yellow("◆")));
    out.push_str(&format!("  {} The Sylow p-subgroup of Z/nZ is <n/p^a> where p^a || n.\n", yellow("◆")));
    out
}

fn cmd_count_sylow(args: &[&str]) -> String {
    let mut out = String::new();
    if args.len() < 2 {
        out.push_str(&format!("  {} Usage: count_sylow <order> <p>\n", red("✗")));
        return out;
    }
    let n = match args[0].parse::<u64>().ok().filter(|&v| v >= 2) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} order must be >= 2.\n", red("✗"))); return out; }
    };
    let p = match args[1].parse::<u64>().ok().filter(|&v| v >= 2 && is_prime(v)) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} p must be a prime number.\n", red("✗"))); return out; }
    };

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ Sylow p-subgroup count n_{} for group of order {}\x1b[0m\n", p, n));

    let (p_a, a) = p_part(n, p);
    let m = n / p_a;

    out.push_str(&format!("  |G| = {} = {}^{} * {}  (p^a * m)\n", n, p, a, m));

    if p_a == 1 {
        out.push_str(&format!("  p = {} does not divide |G| = {} -- no Sylow {}-subgroup.\n", p, n, p));
        return out;
    }

    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));
    out.push_str(&format!("  {}Sylow's Theorem constraints on n_{}:{}\n", bold(""), p, ""));
    out.push_str(&format!("  1. n_{} divides m = {}\n", p, m));
    out.push_str(&format!("  2. n_{} ≡ 1 (mod {})\n", p, p));
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    let divisors_m = divisors(m);
    let mut valid_np: Vec<u64> = divisors_m.iter()
        .filter(|&&d| d % p == 1)
        .cloned()
        .collect();
    valid_np.sort();

    out.push_str(&format!("  Divisors of m = {}:  {}\n", m,
        divisors_m.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", ")));
    out.push_str(&format!("\n  Possible values of n_{} (satisfying both constraints):\n", p));
    if valid_np.is_empty() {
        out.push_str("    (none satisfying n_p | m and n_p ≡ 1 mod p)\n");
    } else {
        for &np in &valid_np {
            let is_1 = np == 1;
            out.push_str(&format!("    n_{} = {}  {}  {}\n",
                p, np,
                if is_1 { "-> unique Sylow subgroup, normal" } else { "" },
                if is_1 { green("(unique)") } else { "".to_string() }));
        }
    }

    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));
    if valid_np == vec![1] {
        out.push_str(&format!("  {} n_{} = 1 is the only possibility: G has a unique (normal) Sylow {}-subgroup.\n", green("✓"), p, p));
    } else if !valid_np.is_empty() {
        out.push_str(&format!("  {} n_{} in {:?}. The actual count depends on the specific group.\n", yellow("◆"), p, valid_np));
    }

    out.push_str(&format!("  {} Sylow III: n_p | m  and  n_p ≡ 1 (mod p).\n", yellow("◆")));
    out.push_str(&format!("  {} If n_p = 1, the Sylow subgroup is normal (characteristic subgroup).\n", yellow("◆")));
    out
}

fn cmd_simple_check(args: &[&str]) -> String {
    let mut out = String::new();
    let n_str = args.first().copied().unwrap_or("12");
    let n = match n_str.parse::<u64>().ok().filter(|&v| v >= 2) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} n must be >= 2.\n", red("✗"))); return out; }
    };

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ Simplicity Check for Group of Order {}\x1b[0m\n", n));

    if n == 1 {
        out.push_str(&format!("  {} Trivial group is simple (vacuously).\n", yellow("◆")));
        return out;
    }

    let facts = factor(n);

    if is_prime(n) {
        out.push_str(&format!("  {} n = {} is prime: all groups of prime order are simple (cyclic).\n", green("✓"), n));
        return out;
    }

    out.push_str(&format!("  n = {} = {}\n",
        n,
        facts.iter().map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
             .collect::<Vec<_>>().join(" * ")));
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    let mut reasons: Vec<String> = Vec::new();

    for &(p, a) in &facts {
        let p_a = p.pow(a);
        let m = n / p_a;
        let divisors_m = divisors(m);
        let valid_np: Vec<u64> = divisors_m.iter()
            .filter(|&&d| d % p == 1)
            .cloned()
            .collect();

        out.push_str(&format!("  {}Prime p = {}:{}  p^a = {}, m = {}\n", bold(""), p, "", p_a, m));
        out.push_str(&format!("    Possible n_{}: {:?}\n", p,
            valid_np.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", ")));

        if valid_np == vec![1] {
            reasons.push(format!(
                "n_{} must be 1 (only possibility): unique normal Sylow {}-subgroup", p, p));
            out.push_str(&format!("    -> n_{} = 1 forced: normal Sylow {}-subgroup exists!\n", p, p));
        } else {
            out.push_str(&format!("    -> n_{} could be > 1, no forced normal subgroup from p={}\n", p, p));
        }
    }

    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));
    if !reasons.is_empty() {
        out.push_str(&format!("  {} Group of order {} CANNOT be simple.\n", red("✗"), n));
        for r in &reasons {
            out.push_str(&format!("  Reason: {}\n", r));
        }
    } else {
        out.push_str(&format!("  {} Sylow analysis alone does NOT force non-simplicity for |G| = {}.\n", yellow("◆"), n));
        out.push_str(&format!("  {} Further analysis needed (e.g., |G| = 60 = |A_5| which is simple).\n", yellow("◆")));
    }

    if n == 60 || n == 168 || n == 360 {
        out.push_str(&format!("  {} Note: |G| = {} is the order of a known simple group (A_5, PSL(2,7), A_6).\n", yellow("◆"), n));
    }

    out.push_str(&format!("  {} A group is simple if its only normal subgroups are {{e}} and G itself.\n", yellow("◆")));
    out
}

fn cmd_classify(args: &[&str]) -> String {
    let mut out = String::new();
    let n_str = args.first().copied().unwrap_or("12");
    let n = match n_str.parse::<u64>().ok().filter(|&v| v >= 2 && v <= 30) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} n must be between 2 and 30.\n", red("✗"))); return out; }
    };

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ Group Classification for Order {}\x1b[0m\n", n));

    let facts = factor(n);
    out.push_str(&format!("  |G| = {} = {}\n",
        n,
        facts.iter().map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
             .collect::<Vec<_>>().join(" * ")));
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    match n {
        1 => out.push_str("  G = {e} (trivial group, unique).\n"),
        2 | 3 | 5 | 7 | 11 | 13 | 17 | 19 | 23 | 29 => {
            out.push_str(&format!("  |G| = {} is prime.\n", n));
            out.push_str(&format!("  {} G ≅ Z/{}Z  (unique cyclic group of prime order)\n", green("✓"), n));
        }
        4 => {
            out.push_str("  |G| = 4 = 2^2. Two groups of order 4:\n");
            out.push_str("  (a) Z/4Z  (cyclic)\n");
            out.push_str("  (b) Z/2Z x Z/2Z  (Klein four-group V4)\n");
            out.push_str(&format!("  {} Both are abelian. Distinguish by: does G have an element of order 4?\n", yellow("◆")));
        }
        6 => {
            out.push_str("  |G| = 6 = 2 * 3. Two groups of order 6:\n");
            out.push_str("  (a) Z/6Z  (cyclic, abelian)\n");
            out.push_str("  (b) S_3 ≅ D_3  (non-abelian)\n");
            out.push_str(&format!("  {} n_3 divides 2 and n_3 ≡ 1 mod 3, so n_3 = 1.\n", yellow("◆")));
            out.push_str(&format!("  {} n_2 divides 3 and n_2 ≡ 1 mod 2, so n_2 in {{1,3}}.\n", yellow("◆")));
            out.push_str(&format!("  {} If n_2 = 3: G ≅ S_3. If n_2 = 1 and G abelian: G ≅ Z/6Z.\n", yellow("◆")));
        }
        8 => {
            out.push_str("  |G| = 8 = 2^3. Five groups of order 8:\n");
            out.push_str("  (a) Z/8Z\n  (b) Z/4Z x Z/2Z\n  (c) Z/2Z x Z/2Z x Z/2Z\n");
            out.push_str("  (d) D_4  (dihedral)\n  (e) Q_8  (quaternion group)\n");
            out.push_str(&format!("  {} Groups (a)-(c) are abelian; (d)-(e) are non-abelian.\n", yellow("◆")));
        }
        12 => {
            out.push_str("  |G| = 12 = 2^2 * 3. Five groups of order 12:\n");
            out.push_str("  (a) Z/12Z  (cyclic)\n");
            out.push_str("  (b) Z/2Z x Z/6Z ≅ Z/2Z x Z/2Z x Z/3Z\n");
            out.push_str("  (c) A_4  (alternating group, non-abelian)\n");
            out.push_str("  (d) D_6 = D_{12/2}  (dihedral, non-abelian)\n");
            out.push_str("  (e) Dic_3  (dicyclic, non-abelian)\n");
            out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));
            out.push_str("  Sylow analysis:\n");
            out.push_str("  n_3 | 4 and n_3 ≡ 1 mod 3: n_3 in {1,4}.\n");
            out.push_str("  n_2 | 3 and n_2 ≡ 1 mod 2: n_2 in {1,3}.\n");
            out.push_str(&format!("  {} If n_3 = 4: G has 8 elements of order 3; could be A_4.\n", yellow("◆")));
            out.push_str(&format!("  {} If n_3 = 1: unique normal Sylow 3-subgroup; G is a semidirect product.\n", yellow("◆")));
        }
        p if is_prime(p) => {
            out.push_str(&format!("  {} G ≅ Z/{}Z  (unique group of prime order)\n", green("✓"), p));
        }
        _ => {
            out.push_str("  Sylow analysis:\n");
            for &(p, a) in &facts {
                let p_a = p.pow(a);
                let m = n / p_a;
                let valid: Vec<u64> = divisors(m).iter()
                    .filter(|&&d| d % p == 1).cloned().collect();
                out.push_str(&format!("  p={}: p^a={}, m={}, possible n_p={:?}\n", p, p_a, m,
                    valid.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")));
            }
            out.push_str(&format!("  {} Further analysis needed. Use 'simple_check' to test simplicity.\n", yellow("◆")));
        }
    }

    out.push_str(&format!("  {} Sylow theory + abelian structure theorem classify most small groups.\n", yellow("◆")));
    out
}

fn cmd_p_group(args: &[&str]) -> String {
    let mut out = String::new();
    if args.len() < 2 {
        out.push_str(&format!("  {} Usage: p_group <p> <a>\n", red("✗")));
        return out;
    }
    let p = match args[0].parse::<u64>().ok().filter(|&v| is_prime(v)) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} p must be prime.\n", red("✗"))); return out; }
    };
    let a = match args[1].parse::<u32>().ok().filter(|&v| v >= 1 && v <= 5) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} a must be between 1 and 5.\n", red("✗"))); return out; }
    };
    let order = p.pow(a);

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ p-Groups of Order p^a = {}^{} = {}\x1b[0m\n", p, a, order));
    out.push_str(&format!("  {}Theorem:{} Every group of order p^a (p prime) is a p-group.\n", bold(""), ""));
    out.push_str(&format!("  {}Key property:{} p-groups always have non-trivial center.\n", bold(""), ""));
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    out.push_str(&format!("  {}Non-trivial center:{}\n", bold(""), ""));
    out.push_str("  Proof sketch: G acts on itself by conjugation.\n");
    out.push_str("  Class equation: |G| = |Z(G)| + Sum_{non-central g} [G:C_G(g)]\n");
    out.push_str("  Each [G:C_G(g)] is divisible by p (since g not central means C_G(g) < G).\n");
    out.push_str("  So p | Sum_{non-central}, and p | |G|, thus p | |Z(G)|.\n");
    out.push_str("  Hence |Z(G)| >= p > 1.\n");
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    out.push_str(&format!("  {}Known p-groups of order {}^{} = {}:{}\n", bold(""), p, a, order, ""));
    match (p, a) {
        (p, 1) => {
            out.push_str(&format!("  Unique: Z/{}Z  (all groups of prime order are cyclic)\n", p));
        }
        (2, 2) => {
            out.push_str("  (a) Z/4Z  (cyclic)\n");
            out.push_str("  (b) Z/2Z x Z/2Z  (Klein four-group)\n");
            out.push_str("  Both have Z(G) = G (abelian).\n");
        }
        (2, 3) => {
            out.push_str("  (a) Z/8Z\n  (b) Z/4Z x Z/2Z\n  (c) Z/2Z x Z/2Z x Z/2Z\n");
            out.push_str("  (d) D_4  |Z(D_4)| = 2\n  (e) Q_8  |Z(Q_8)| = 2\n");
        }
        (p, 2) => {
            out.push_str(&format!("  (a) Z/p^2Z  (cyclic)\n  (b) Z/pZ x Z/pZ  (elementary abelian)\n"));
            if p > 2 {
                out.push_str("  (c) Non-abelian group of order p^2 (does not exist!)\n");
                out.push_str(&format!("  {} Fact: all groups of order p^2 are abelian!\n", green("✓")));
            }
        }
        _ => {
            out.push_str(&format!("  Many groups of order {}^{} = {} exist.\n", p, a, order));
            out.push_str("  All have non-trivial center by the class equation argument.\n");
        }
    }

    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));
    out.push_str(&format!("  {}Lower central series (nilpotency):{}\n", bold(""), ""));
    out.push_str("  G = G_0 >= G_1 >= G_2 >= ... >= G_c = {e}\n");
    out.push_str("  where G_{i+1} = [G, G_i] (commutator subgroup).\n");
    out.push_str(&format!("  p-groups are nilpotent: this series terminates after at most {} steps.\n", a));

    out.push_str(&format!("  {} Every p-group is nilpotent of class at most {}.\n", yellow("◆"), a));
    out.push_str(&format!("  {} Nilpotent groups are extensions of abelian groups.\n", yellow("◆")));
    out
}

fn cmd_sylow_conj(args: &[&str]) -> String {
    let mut out = String::new();
    if args.len() < 2 {
        out.push_str(&format!("  {} Usage: sylow_conj <n> <p>\n", red("✗")));
        return out;
    }
    let n = match args[0].parse::<u64>().ok().filter(|&v| v >= 2) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} n must be >= 2.\n", red("✗"))); return out; }
    };
    let p = match args[1].parse::<u64>().ok().filter(|&v| is_prime(v)) {
        Some(v) => v,
        None => { out.push_str(&format!("  {} p must be prime.\n", red("✗"))); return out; }
    };

    out.push_str(&format!("\n  \x1b[1m\x1b[33m▸ Sylow p-subgroup Conjugacy in Z/{}Z (p = {})\x1b[0m\n", n, p));
    out.push_str(&format!("  {}Sylow II:{} All Sylow p-subgroups are conjugate.\n", bold(""), ""));
    out.push_str("  In an abelian group, conjugation is trivial: gHg^{-1} = H for all g.\n");
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    let (p_a, a) = p_part(n, p);
    if p_a == 1 {
        out.push_str(&format!("  {} {} does not divide {}: no Sylow {}-subgroup.\n", red("✗"), p, n, p));
        return out;
    }

    let m = n / p_a;
    let gen = m as usize;

    out.push_str(&format!("  |G| = {} = {}^{} * {}  (p^a = {}, m = {})\n", n, p, a, m, p_a, m));
    out.push_str(&format!("  Sylow {}-subgroup: H = <{}>  (order {})\n", p, gen, p_a));

    let sub: Vec<u64> = {
        let mut v = Vec::new();
        let mut cur = 0u64;
        loop {
            v.push(cur);
            cur = (cur + gen as u64) % n;
            if cur == 0 { break; }
            if v.len() > n as usize { break; }
        }
        v.sort();
        v
    };
    let sub_str: Vec<String> = sub.iter().map(|x| x.to_string()).collect();
    out.push_str(&format!("  H = {{ {} }}\n", sub_str.join(", ")));
    out.push_str(&format!("  {}\n", dim(&"─".repeat(60))));

    out.push_str(&format!("  {}Verifying conjugation g*H*g^{{-1}} = H for all g in Z/{}Z:{}\n", bold(""), n, ""));
    out.push_str("  In Z/nZ: g*h*(-g) = h  (addition is commutative)\n");
    out.push_str("  So gHg^{-1} = H for ALL g -- confirms H is normal.\n\n");
    out.push_str(&format!("  n_{} = 1 (unique Sylow p-subgroup, automatically normal).\n", p));
    out.push_str(&format!("  {} All (1) Sylow p-subgroups are trivially conjugate.\n", green("✓")));

    out.push_str(&format!("  {} Sylow II says all Sylow p-subgroups are conjugate in ANY group.\n", yellow("◆")));
    out.push_str(&format!("  {} In abelian groups, conjugacy classes have size 1, so uniqueness follows.\n", yellow("◆")));
    out
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "sylow" => {
            if let Some(&n_s) = args.first() {
                if let Ok(n) = n_s.parse::<i64>() {
                    state_set_int(state, "group_n", n);
                }
            }
            cmd_sylow(args)
        }
        "count_sylow" => {
            if let (Some(&n_s), Some(&p_s)) = (args.first(), args.get(1)) {
                if let (Ok(n), Ok(p)) = (n_s.parse::<i64>(), p_s.parse::<i64>()) {
                    state_set_int(state, "group_n", n);
                    state_set_int(state, "prime_p", p);
                }
            }
            cmd_count_sylow(args)
        }
        "simple_check" => {
            if let Some(&n_s) = args.first() {
                if let Ok(n) = n_s.parse::<i64>() {
                    state_set_int(state, "group_n", n);
                }
            }
            cmd_simple_check(args)
        }
        "classify" => {
            if let Some(&n_s) = args.first() {
                if let Ok(n) = n_s.parse::<i64>() {
                    state_set_int(state, "group_n", n);
                }
            }
            cmd_classify(args)
        }
        "p_group" => {
            if let (Some(&p_s), Some(&a_s)) = (args.first(), args.get(1)) {
                if let (Ok(p), Ok(a)) = (p_s.parse::<i64>(), a_s.parse::<i64>()) {
                    state_set_int(state, "prime_p", p);
                    state_set_int(state, "group_n", p.pow(a as u32));
                }
            }
            cmd_p_group(args)
        }
        "sylow_conj" => {
            if let (Some(&n_s), Some(&p_s)) = (args.first(), args.get(1)) {
                if let (Ok(n), Ok(p)) = (n_s.parse::<i64>(), p_s.parse::<i64>()) {
                    state_set_int(state, "group_n", n);
                    state_set_int(state, "prime_p", p);
                }
            }
            cmd_sylow_conj(args)
        }
        "demo" => {
            let n: u64 = state_get_int(state, "group_n").unwrap_or(12) as u64;
            let mut out = String::new();
            out.push_str(&format!("=== Sylow Analysis Demo for |G| = {} ===\n", n));

            if n < 2 {
                out.push_str("  n must be >= 2.\n");
                return out;
            }

            let facts = factor(n);
            out.push_str(&format!("  {} = {}\n", n,
                facts.iter().map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
                     .collect::<Vec<_>>().join(" * ")));

            for &(p, a) in &facts {
                let p_a = p.pow(a);
                let m = n / p_a;
                let divs = divisors(m);
                let valid: Vec<u64> = divs.iter().filter(|&&d| d % p == 1).cloned().collect();
                out.push_str(&format!("  p={}: p^a={}, m={}, n_p in [{}]\n",
                    p, p_a, m,
                    valid.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")));
                if valid == vec![1] {
                    out.push_str(&format!("    -> unique normal Sylow {}-subgroup\n", p));
                }
            }
            out
        }
        "help" | "h" => show_help(),
        _ => format!("  \x1b[31m✗\x1b[0m Unknown command '{}'. Type 'help'.\n", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { print!("{out}"); }
    true
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_int(&mut s, "group_n", 12);
    state_set_int(&mut s, "prime_p", 2);
    s
}

fn visualize_svg(canvas: &mut SvgCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n: u64 = state_get_int(state, "group_n").unwrap_or(12) as u64;

    let facts = factor(n);

    canvas.text_bold(350.0, 30.0, &format!("Sylow Subgroups of Z/{}Z", n), 18.0, "#222", "middle");

    if facts.is_empty() {
        canvas.text(350.0, 200.0, "n must be >= 2", 14.0, "#888", "middle");
        return;
    }

    let fact_str = facts.iter()
        .map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
        .collect::<Vec<_>>().join(" x ");
    canvas.text(350.0, 55.0, &format!("{} = {}", n, fact_str), 13.0, "#555", "middle");

    let colors = ["#4a90d9", "#e87040", "#50b86c", "#9b59b6"];
    let box_w = 140.0f64;
    let box_h = 80.0f64;
    let start_x = 350.0 - (facts.len() as f64 * (box_w + 20.0)) / 2.0 + box_w / 2.0;
    let box_y = 130.0f64;

    for (i, &(p, a)) in facts.iter().enumerate() {
        let p_a = p.pow(a);
        let m = n / p_a;
        let gen = m;
        let cx = start_x + i as f64 * (box_w + 20.0);

        let color = colors[i % colors.len()];
        canvas.rect(cx - box_w/2.0, box_y, box_w, box_h, color, "#fff", 1.0);

        canvas.text_bold(cx, box_y + 22.0,
            &format!("Syl_{}(G)", p), 14.0, "white", "middle");
        canvas.text(cx, box_y + 42.0,
            &format!("|H| = {}^{} = {}", p, a, p_a), 12.0, "white", "middle");
        canvas.text(cx, box_y + 58.0,
            &format!("gen = {}", gen), 11.0, "white", "middle");
        canvas.text(cx, box_y + 72.0,
            "n_p = 1 (normal)", 10.0, "white", "middle");
    }

    canvas.rect(300.0, 240.0, 100.0, 40.0, "#34495e", "#fff", 1.0);
    canvas.text_bold(350.0, 265.0, &format!("G = Z/{}Z", n), 13.0, "white", "middle");

    for (i, _) in facts.iter().enumerate() {
        let cx = start_x + i as f64 * (box_w + 20.0);
        canvas.arrow(350.0, 280.0, cx, box_y + box_h, "#aaaaaa", 1.5);
    }

    canvas.text(350.0, 350.0, "Sylow I: Sylow p-subgroups exist", 12.0, "#555", "middle");
    canvas.text(350.0, 368.0, "Sylow II: All Sylow p-subgroups are conjugate", 12.0, "#555", "middle");
    canvas.text(350.0, 386.0, "Sylow III: n_p | m and n_p ≡ 1 (mod p)", 12.0, "#555", "middle");
    canvas.text(350.0, 410.0, "(For abelian groups: n_p = 1 always)", 11.0, "#888", "middle");
}

fn visualize_dot(graph: &mut DotGraph, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n: u64 = state_get_int(state, "group_n").unwrap_or(12) as u64;
    let facts = factor(n);

    graph.node("G", &[
        ("label", &format!("G = Z/{}Z\\n|G| = {}", n, n)),
        ("shape", "box"),
        ("style", "filled"),
        ("fillcolor", "#34495e"),
        ("fontcolor", "white"),
    ]);

    for (i, &(p, a)) in facts.iter().enumerate() {
        let p_a = p.pow(a);
        let m = n / p_a;
        let gen = m;
        let node_id = format!("syl{}", p);
        let label = format!("Syl_{}(G)\\n|H|={}\\n<{}>", p, p_a, gen);
        graph.node(&node_id, &[
            ("label", &label),
            ("shape", "ellipse"),
            ("style", "filled"),
            ("fillcolor", if i % 2 == 0 { "#4a90d9" } else { "#e87040" }),
            ("fontcolor", "white"),
        ]);
        graph.edge("G", &node_id, &[("label", "contains"), ("color", "#aaaaaa")]);
    }

    graph.node("e", &[
        ("label", "{e}"),
        ("shape", "circle"),
        ("style", "filled"),
        ("fillcolor", "#ecf0f1"),
    ]);
    for &(p, _) in &facts {
        graph.edge(&format!("syl{}", p), "e", &[("color", "#cccccc")]);
    }
}

fn visualize_tex(doc: &mut TikzDoc, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n: u64 = state_get_int(state, "group_n").unwrap_or(12) as u64;
    let facts = factor(n);

    doc.node("G", 0.0, 3.0, &format!("$G = \\mathbb{{Z}}/{}\\mathbb{{Z}}$", n), "draw,rectangle");

    let n_facts = facts.len() as f64;
    for (i, &(p, a)) in facts.iter().enumerate() {
        let p_a = p.pow(a);
        let x = (i as f64 - (n_facts - 1.0) / 2.0) * 3.0;
        let node_id = format!("syl{}", p);
        doc.node(&node_id, x, 1.0,
            &format!("$\\mathrm{{Syl}}_{{{}}}(G)$, $p^a={}$", p, p_a), "draw,ellipse");
        doc.arrow("G", &node_id, "", "-stealth");
    }

    doc.node("e", 0.0, -1.0, "$\\{e\\}$", "draw,circle");
    for &(p, _) in &facts {
        doc.arrow(&format!("syl{}", p), "e", "", "-stealth");
    }
}

fn visualize_ascii(canvas: &mut AsciiCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n: u64 = state_get_int(state, "group_n").unwrap_or(12) as u64;
    let facts = factor(n);

    canvas.text_at(0, 0, &format!("Sylow Subgroups of Z/{}Z:", n));

    let fact_str = facts.iter()
        .map(|(p, a)| if *a == 1 { format!("{}", p) } else { format!("{}^{}", p, a) })
        .collect::<Vec<_>>().join(" * ");
    canvas.text_at(0, 1, &format!("  {} = {}", n, fact_str));
    canvas.text_at(0, 2, &format!("  G = Z/{}Z", n));

    let mut row = 4;
    for &(p, a) in &facts {
        let p_a = p.pow(a);
        let m = n / p_a;
        let divs = divisors(m);
        let valid: Vec<u64> = divs.iter().filter(|&&d| d % p == 1).cloned().collect();
        canvas.text_at(0, row, &format!("  Syl_{}(G): |H| = {}^{} = {}, gen = {}, n_p in [{}]",
            p, p, a, p_a, m,
            valid.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(",")));
        row += 1;
        if valid == vec![1] {
            canvas.text_at(0, row, &format!("    -> n_{} = 1: unique normal Sylow subgroup", p));
            row += 1;
        }
    }

    row += 1;
    canvas.text_at(0, row, "Sylow Theorems:");
    canvas.text_at(0, row + 1, "  I:   Sylow p-subgroups exist");
    canvas.text_at(0, row + 2, "  II:  All Sylow p-subgroups are conjugate");
    canvas.text_at(0, row + 3, "  III: n_p | m  and  n_p ≡ 1 (mod p)");
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };

    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg => {
                    let mut c = SvgCanvas::new(700.0, 450.0);
                    visualize_svg(&mut c, cmd, &args_ref, &state);
                    c.build()
                }
                OutputFormat::Dot => {
                    let mut gr = DotGraph::digraph("ch17");
                    visualize_dot(&mut gr, cmd, &args_ref, &state);
                    gr.build()
                }
                OutputFormat::Tex => {
                    let mut t = TikzDoc::standalone();
                    visualize_tex(&mut t, cmd, &args_ref, &state);
                    t.build()
                }
                OutputFormat::Ascii => {
                    let mut a = AsciiCanvas::new(80, 30);
                    visualize_ascii(&mut a, cmd, &args_ref, &state);
                    a.render()
                }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner(
                "Chapter 17",
                "The Sylow Theorems",
                "Sylow subgroups · Counting · Simplicity · Group classification",
            );
            print_info("Explore the structure of groups through prime-power subgroups.");
            print!("{}", show_help());
            repl("ch17> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
