"""
Static question bank — 150+ questions across 29 topics of
Computational Systems & Synthetic Biology.
"""
from __future__ import annotations

import uuid
from .models import Question


def _q(ch, ph, kind, text, choices, answer, explanation,
       tags=None, diff="intermediate") -> Question:
    return Question(
        chapter=ch, phase=ph, kind=kind, text=text,
        choices=choices, answer=answer, explanation=explanation,
        tags=tags or [], difficulty=diff,
        question_id=str(uuid.uuid4()),
    )

def mc(ch, ph, text, choices, ans, expl, tags=None, diff="intermediate"):
    return _q(ch, ph, "mc", text, choices, ans, expl, tags, diff)

def tf(ch, ph, text, ans_bool, expl, tags=None, diff="intermediate"):
    return _q(ch, ph, "tf", text, ["True", "False"],
              0 if ans_bool else 1, expl, tags, diff)

def blank(ch, ph, text, synonyms, expl, tags=None, diff="intermediate"):
    return _q(ch, ph, "blank", text, synonyms, synonyms[0].lower(), expl, tags, diff)


def build() -> list[Question]:
    Q: list[Question] = []

    # ══════════════════════════════════════════════════════════════════
    # Tier 0 — Bedrock
    # ══════════════════════════════════════════════════════════════════

    # Ch 0 — Mathematics
    Q += [
        mc(0, 0,
           "The Jacobian matrix J of a vector function F: ℝⁿ → ℝᵐ has dimensions:",
           ["m × n", "n × m", "n × n", "m × m"], 0,
           "Jᵢⱼ = ∂Fᵢ/∂xⱼ — m rows (outputs) by n columns (inputs).",
           ["calculus", "jacobian"], "beginner"),
        tf(0, 0,
           "A fixed point of an ODE system ẋ = f(x) where all eigenvalues of the Jacobian have strictly negative real parts is asymptotically stable.",
           True,
           "Lyapunov linearisation: if all eigenvalues of Df(x*) have Re(λ) < 0, x* is asymptotically stable.",
           ["odes", "stability"], "intermediate"),
        blank(0, 0,
           "The ___ number characterises the ratio of diffusion timescale to reaction timescale in a reaction-diffusion system.",
           ["Damköhler", "Damkohler"],
           "The Damköhler number Da = reaction rate / diffusion rate. Da ≫ 1 means reaction-limited.",
           ["reaction-diffusion"], "advanced"),
        mc(0, 0,
           "For a system of ODEs, a bifurcation occurs when:",
           ["the qualitative behaviour changes as a parameter varies", "the system becomes linear", "all eigenvalues become zero", "the Jacobian becomes singular permanently"], 0,
           "Bifurcation: qualitative change in dynamics (e.g., saddle-node, Hopf) at a critical parameter value.",
           ["bifurcations", "dynamical-systems"], "intermediate"),
        mc(0, 0,
           "The probability density function of a Poisson process with rate λ gives the probability of k events in time t as:",
           ["e^{-λt}(λt)^k/k!", "λ^k·e^{-λ}/k!", "e^{-λ}λ^k", "(λt)^k/k!"], 0,
           "Poisson distribution: P(X=k) = e^{-μ}μ^k/k! where μ = λt.",
           ["probability", "stochastic"], "beginner"),
        tf(0, 0,
           "The Fourier transform of the convolution of two functions equals the pointwise product of their Fourier transforms.",
           True,
           "Convolution theorem: F{f * g} = F{f} · F{g}. This underlies signal processing and Green's function methods.",
           ["fourier", "convolution"], "intermediate"),
    ]

    # Ch 1 — Chemistry
    Q += [
        mc(1, 0,
           "The Henderson-Hasselbalch equation relates pH to the pKa and the ratio of:",
           ["[A⁻]/[HA] (base/acid)", "[HA]/[A⁻] (acid/base)", "[H⁺]/[A⁻]", "[HA]/[H⁺]"], 0,
           "pH = pKa + log([A⁻]/[HA]). Buffer capacity is greatest when pH ≈ pKa.",
           ["acid-base", "buffers"], "beginner"),
        blank(1, 0,
           "The ___ principle states that a system at equilibrium resists changes: adding reactants shifts the equilibrium toward products.",
           ["Le Chatelier", "Le Chatelier's"],
           "Le Chatelier's principle: equilibrium shifts to oppose external perturbations.",
           ["equilibrium"], "beginner"),
        tf(1, 0,
           "Covalent bonds are generally stronger than hydrogen bonds.",
           True,
           "Covalent bonds: ~200-400 kJ/mol. Hydrogen bonds: ~5-30 kJ/mol. But H-bonds are critical in biology.",
           ["bonding"], "beginner"),
        mc(1, 0,
           "The Gibbs free energy change ΔG° for a reaction relates to the equilibrium constant K by:",
           ["ΔG° = -RT ln K", "ΔG° = RT ln K", "ΔG° = -RT/K", "ΔG° = RT·K"], 0,
           "ΔG° = -RT ln Keq. Spontaneous reactions have ΔG < 0 and Keq > 1.",
           ["thermodynamics", "gibbs-energy"], "intermediate"),
        mc(1, 0,
           "ATP hydrolysis (ATP → ADP + Pi) drives biosynthetic reactions because it has a large negative:",
           ["ΔG°' (standard Gibbs free energy change)", "ΔH (enthalpy)", "ΔS (entropy)", "Km"], 0,
           "ΔG°' = -30.5 kJ/mol for ATP hydrolysis under standard conditions; cells use it to drive unfavourable reactions.",
           ["bioenergetics", "atp"], "intermediate"),
        tf(1, 0,
           "Michaelis-Menten kinetics assume the enzyme-substrate complex ES reaches quasi-steady state rapidly compared to ES → P.",
           True,
           "The QSSA assumes d[ES]/dt ≈ 0, giving v = Vmax[S]/(Km + [S]).",
           ["enzyme-kinetics", "qssa"], "intermediate"),
        mc(1, 0,
           "The Haldane relationship for an enzyme-catalysed reversible reaction A⇌B constrains the kinetic parameters because:",
           ["Keq = (Vmax_f · Km_B) / (Vmax_r · Km_A) — thermodynamics fixes the ratio of kinetic constants", "all four parameters can be set independently of thermodynamics", "only Vmax values are thermodynamically constrained", "Km values are always equal for reversible reactions"], 0,
           "The Haldane relationship links forward/reverse Michaelis-Menten parameters to the equilibrium constant; an enzyme cannot violate thermodynamics.",
           ["haldane", "enzyme-kinetics", "thermodynamics"], "advanced"),
    ]

    # Ch 2 — Biology
    Q += [
        mc(2, 0,
           "The central dogma of molecular biology describes the flow of information as:",
           ["DNA → RNA → Protein", "RNA → DNA → Protein", "Protein → RNA → DNA", "DNA → Protein → RNA"], 0,
           "Central dogma (Crick 1958): genetic info flows DNA → transcription → RNA → translation → Protein.",
           ["central-dogma"], "beginner"),
        blank(2, 0,
           "The process by which mRNA sequence is converted into amino acid sequence at the ribosome is called ___.",
           ["translation"],
           "Translation: mRNA codons are read by tRNA anticodons at the ribosome, producing a polypeptide chain.",
           ["translation", "protein-synthesis"], "beginner"),
        mc(2, 0,
           "Which of the following best describes the role of a promoter in gene expression?",
           ["A DNA sequence where RNA polymerase binds to initiate transcription", "A protein that activates translation", "The start codon of an mRNA", "A regulatory RNA that silences genes"], 0,
           "Promoters are DNA sequences (e.g., TATA box) that recruit RNA polymerase and transcription factors.",
           ["gene-expression", "promoters"], "beginner"),
        tf(2, 0,
           "Eukaryotic mRNA is processed by capping, polyadenylation, and splicing before export from the nucleus.",
           True,
           "Pre-mRNA processing: 5' 7-methylguanosine cap + splicing of introns + 3' poly(A) tail.",
           ["mrna-processing"], "intermediate"),
        mc(2, 0,
           "The lac operon in E. coli is an example of:",
           ["negative transcriptional regulation (repressor blocks transcription)", "positive feedback", "post-translational regulation", "epigenetic silencing"], 0,
           "The lac repressor binds the operator to block RNA polymerase when lactose is absent.",
           ["operons", "gene-regulation"], "intermediate"),
        mc(2, 0,
           "Protein folding is primarily driven by:",
           ["the hydrophobic effect (burial of non-polar residues)", "covalent bond formation", "electrostatic attraction only", "random thermal fluctuations"], 0,
           "Hydrophobic collapse: non-polar residues bury themselves to minimise contact with water, driving folding.",
           ["protein-folding"], "intermediate"),
        tf(2, 0,
           "CRISPR-Cas9 can be used to edit the genomes of both prokaryotes and eukaryotes.",
           True,
           "CRISPR-Cas9 is a programmable nuclease applicable to any cell type with accessible DNA.",
           ["crispr", "genome-editing"], "beginner"),
        mc(2, 0,
           "Cell-to-cell variability in gene expression (transcriptional noise) arises primarily from:",
           ["stochastic bursting of mRNA production — genes switch between active and inactive states", "deterministic differences in cell size only", "uniform translation rates across all cells", "errors in DNA replication"], 0,
           "Transcriptional noise: genes switch on/off stochastically (two-state promoter model), creating mRNA bursts and Fano factor > 1.",
           ["gene-expression-noise", "stochastic"], "advanced"),
    ]

    # Ch 3 — Computer Science
    Q += [
        mc(3, 0,
           "The time complexity of binary search in a sorted array of n elements is:",
           ["O(log n)", "O(n)", "O(n log n)", "O(1)"], 0,
           "Binary search halves the search space each step: T(n) = T(n/2) + O(1) → O(log n).",
           ["algorithms", "complexity"], "beginner"),
        tf(3, 0,
           "Dynamic programming solves problems by breaking them into overlapping subproblems and storing results (memoisation).",
           True,
           "DP: overlapping subproblems + optimal substructure → tabulate/memoize to avoid recomputation. E.g., sequence alignment.",
           ["dynamic-programming", "algorithms"], "beginner"),
        blank(3, 0,
           "Version control with Git tracks changes as ___, each identified by a SHA-1 hash of the file tree.",
           ["commits"],
           "Git commits are snapshots of the repository state; each has a unique SHA-1 hash and parent pointers.",
           ["version-control", "git"], "beginner"),
        mc(3, 0,
           "A graph G = (V, E) is bipartite if and only if it contains no:",
           ["odd-length cycles", "even-length cycles", "cycles of length ≥ 4", "self-loops"], 0,
           "Bipartite ↔ 2-colourable ↔ no odd cycles. Relevant to protein interaction network analysis.",
           ["graphs", "bipartite"], "intermediate"),
        mc(3, 0,
           "In machine learning, regularisation (e.g., L2 / ridge) is used to:",
           ["prevent overfitting by penalising large weights", "speed up gradient descent", "increase model capacity", "reduce training set size"], 0,
           "L2 regularisation adds λ‖w‖² to the loss, shrinking weights and reducing overfitting.",
           ["machine-learning", "regularisation"], "intermediate"),
        tf(3, 0,
           "A relational database uses SQL and stores data in tables with rows (records) and columns (fields).",
           True,
           "Relational databases (PostgreSQL, MySQL) organise data as relations (tables); SQL is the query language.",
           ["databases"], "beginner"),
        mc(3, 0,
           "The NP-hardness of optimal de novo genome assembly motivates using de Bruijn graph assemblers (e.g., SPAdes) because they:",
           ["trade guaranteed optimality for polynomial-time tractability on read graphs", "solve the problem exactly for any genome size", "require no error correction of reads", "only work for short genomes < 1 Mbp"], 0,
           "Optimal assembly from error-prone reads is NP-hard; de Bruijn graph assemblers use heuristics to produce high-quality assemblies efficiently.",
           ["genome-assembly", "algorithms", "np-hard"], "advanced"),
    ]

    # ══════════════════════════════════════════════════════════════════
    # Tier 1 — Bioinformatics
    # ══════════════════════════════════════════════════════════════════

    # Ch 4 — Sequence Analysis
    Q += [
        mc(4, 1,
           "The Smith-Waterman algorithm finds:",
           ["the optimal local alignment between two sequences", "the optimal global alignment", "approximate BLAST-like alignments", "a multiple sequence alignment"], 0,
           "Smith-Waterman: dynamic programming for optimal local alignment. Slower than BLAST but guaranteed optimal.",
           ["alignment", "smith-waterman"], "beginner"),
        tf(4, 1,
           "BLAST is guaranteed to find the optimal alignment for every query-subject pair.",
           False,
           "BLAST uses heuristic seeding (k-mer hits) and extension; it can miss optimal alignments for speed.",
           ["blast", "heuristics"], "intermediate"),
        blank(4, 1,
           "The ___ scoring matrix is commonly used for scoring amino acid substitutions in protein alignments, derived from observed substitution frequencies in related proteins.",
           ["BLOSUM62", "BLOSUM"],
           "BLOSUM62 (Henikoff 1992) scores amino acid substitutions based on blocks of aligned sequences at 62% identity.",
           ["substitution-matrices", "protein-alignment"], "intermediate"),
        mc(4, 1,
           "In pairwise sequence alignment, the gap penalty function for affine gaps is:",
           ["gap open + (k−1)·gap extend", "k·gap cost", "gap open + k·gap extend", "log(k)·gap cost"], 0,
           "Affine gap penalty: gap open (α) for starting a gap + (k−1)×extension (β) for each additional gap character.",
           ["gap-penalty", "alignment"], "intermediate"),
        mc(4, 1,
           "The E-value in BLAST indicates:",
           ["the expected number of alignments with that score by random chance", "the percentage identity", "the p-value for the alignment", "the alignment score normalised by sequence length"], 0,
           "E-value: expected number of hits with this score or better in a random database of the same size.",
           ["blast", "e-value"], "intermediate"),
        tf(4, 1,
           "Progressive multiple sequence alignment methods (e.g., ClustalW) can produce suboptimal results because they commit to early pairwise alignments.",
           True,
           "Progressive alignment builds on a guide tree; errors in early alignments propagate. Iterative methods (e.g., MUSCLE) partially correct this.",
           ["multiple-alignment", "clustalw"], "advanced"),
        mc(4, 1,
           "Profile hidden Markov models (profile-HMMs, as used in HMMER) improve over position weight matrices for detecting distant protein homologues because they:",
           ["explicitly model insertions and deletions with state transitions, capturing evolutionary indel patterns", "use larger scoring matrices", "run faster than BLAST on all inputs", "require structural information to build"], 0,
           "Profile-HMMs have insert and delete states; the Viterbi and forward algorithms integrate over all alignment paths, giving superior sensitivity for distant homologues.",
           ["hmmer", "profile-hmm", "homology-detection"], "advanced"),
    ]

    # Ch 5 — Genomics
    Q += [
        mc(5, 1,
           "Short-read sequencing (Illumina) typically produces reads of:",
           ["75–300 bp", "10–50 bp", "1000–10000 bp", "whole chromosomes"], 0,
           "Illumina sequencing by synthesis: 75-300 bp reads, high throughput, low error rate (~0.1%).",
           ["sequencing", "illumina"], "beginner"),
        blank(5, 1,
           "The process of determining the sequence of a genome from many overlapping short reads is called ___ assembly.",
           ["genome", "de novo"],
           "Genome assembly: align and merge overlapping sequencing reads to reconstruct the original sequence.",
           ["genome-assembly"], "beginner"),
        mc(5, 1,
           "Variant calling (SNP/indel detection) typically requires aligning reads to a reference genome and then:",
           ["identifying positions where reads differ from the reference", "de novo assembling the reads", "removing adapter sequences", "normalising read depth"], 0,
           "Variant calling: after read alignment, compare pile-up at each position to the reference and apply statistical filters.",
           ["variant-calling", "snps"], "intermediate"),
        tf(5, 1,
           "Long-read sequencing (PacBio, Oxford Nanopore) has higher per-base error rates than short-read Illumina sequencing.",
           True,
           "Nanopore: ~5-15% error rate. PacBio HiFi: ~0.1% with CCS. Illumina: ~0.1%. Long reads enable structural variant detection.",
           ["long-read-sequencing"], "intermediate"),
        mc(5, 1,
           "The reference human genome (GRCh38) is used as a reference for read alignment. Reads from a new individual that differ at a position are called:",
           ["variants (SNPs or indels if small)", "mutations (all differences are pathogenic)", "errors (all differences indicate sequencing error)", "isoforms"], 0,
           "Genetic variants include SNPs (single nucleotide polymorphisms), indels, CNVs, and structural variants.",
           ["human-genome", "variants"], "intermediate"),
        blank(5, 1,
           "ChIP-seq is a method that combines ___ precipitation with sequencing to identify protein-DNA interaction sites genome-wide.",
           ["chromatin immunoprecipitation", "chromatin"],
           "ChIP-seq: crosslink protein-DNA, shear chromatin, immunoprecipitate with antibody, sequence.",
           ["chip-seq", "epigenomics"], "advanced"),
        mc(5, 1,
           "Hi-C sequencing captures genome-wide chromatin conformation by:",
           ["crosslinking spatially proximate chromatin, fragmenting, ligating adjacent ends, and sequencing chimeric products", "immunoprecipitating histones and sequencing associated DNA", "cutting chromatin with accessible Tn5 transposase and sequencing", "sequencing all RNA transcribed from open chromatin"], 0,
           "Hi-C: formaldehyde crosslink → restriction digest → end-fill (biotin) → proximity ligation → pull-down biotin → sequence pairs.",
           ["hi-c", "chromatin-conformation", "3d-genome"], "advanced"),
    ]

    # Ch 6 — Transcriptomics
    Q += [
        mc(6, 1,
           "RNA-seq measures gene expression by:",
           ["sequencing cDNA reverse-transcribed from RNA and counting reads per gene", "hybridising RNA to microarray probes", "measuring fluorescence of labelled transcripts", "quantifying RNA mass by gel electrophoresis"], 0,
           "RNA-seq: extract RNA → reverse-transcribe to cDNA → sequence → count reads mapping to each gene.",
           ["rna-seq"], "beginner"),
        blank(6, 1,
           "Differential expression analysis uses statistical models (e.g., DESeq2, edgeR) that assume read counts follow a ___ distribution.",
           ["negative binomial"],
           "RNA-seq counts are overdispersed relative to Poisson; the negative binomial model accounts for biological variability.",
           ["deseq2", "differential-expression"], "intermediate"),
        tf(6, 1,
           "TPM (transcripts per million) normalisation accounts for both sequencing depth and gene length.",
           True,
           "TPM = (reads/gene_length_kb) / (total_reads/10⁶). Both RPK-normalised. Unlike RPKM, TPM sums to 10⁶ per sample.",
           ["normalisation", "tpm"], "intermediate"),
        mc(6, 1,
           "Single-cell RNA-seq (scRNA-seq) provides expression profiles at single-cell resolution, enabling:",
           ["identification of cell types and states within a heterogeneous tissue", "only bulk expression measurement", "protein-level quantification", "genome-wide methylation profiling"], 0,
           "scRNA-seq: cluster cells by transcriptional similarity, identify marker genes, discover rare cell types.",
           ["scrna-seq", "single-cell"], "intermediate"),
        mc(6, 1,
           "The 'dropout' problem in single-cell RNA-seq refers to:",
           ["zero counts for expressed genes due to low mRNA capture efficiency", "cell death during sample preparation", "batch effects between experiments", "high ribosomal RNA contamination"], 0,
           "Dropout: genes are expressed but not captured, producing false zeros. Imputation methods (MAGIC, scVI) address this.",
           ["dropout", "scrna-seq"], "advanced"),
        tf(6, 1,
           "ATAC-seq measures chromatin accessibility by sequencing DNA near nucleosome-free regions.",
           True,
           "ATAC-seq uses Tn5 transposase to preferentially insert sequencing adapters into open chromatin.",
           ["atac-seq", "chromatin"], "intermediate"),
        mc(6, 1,
           "RNA velocity (La Manno et al.; scVelo) estimates the future transcriptional state of a cell by:",
           ["comparing unspliced (nascent) to spliced (mature) mRNA ratios to infer whether each gene is accelerating or decelerating", "measuring the rate of ribosome elongation along mRNAs", "comparing two time-point snapshots of the same cell", "integrating bulk RNA-seq time-course data"], 0,
           "RNA velocity: d[s]/dt = β·u − γ·s; the ratio u/s relative to steady-state predicts whether a gene is being induced or repressed.",
           ["rna-velocity", "scrna-seq", "trajectory"], "advanced"),
    ]

    # Ch 7 — Proteomics and Metabolomics
    Q += [
        mc(7, 1,
           "In shotgun proteomics, proteins are first digested with trypsin and then identified by:",
           ["LC-MS/MS (liquid chromatography coupled to tandem mass spectrometry)", "2D gel electrophoresis followed by Edman sequencing", "NMR spectroscopy", "protein microarrays"], 0,
           "Shotgun proteomics: digest → separate peptides by LC → fragment by MS/MS → search spectral databases.",
           ["proteomics", "mass-spectrometry"], "beginner"),
        blank(7, 1,
           "The ratio of the m/z peak in mass spectrometry corresponds to mass divided by ___.",
           ["charge", "z"],
           "m/z = mass / charge. Multiply observed m/z by charge state to get molecular mass.",
           ["mass-spectrometry"], "beginner"),
        mc(7, 1,
           "SILAC (stable isotope labelling by amino acids in cell culture) is used to:",
           ["quantify relative protein abundance between two conditions", "identify post-translational modifications", "determine protein structure", "purify low-abundance proteins"], 0,
           "SILAC: label one condition with heavy isotopes (¹³C, ¹⁵N amino acids), mix and compare m/z ratios.",
           ["silac", "quantitative-proteomics"], "intermediate"),
        tf(7, 1,
           "Metabolomics can use either targeted (known metabolites) or untargeted (global profiling) approaches.",
           True,
           "Targeted metabolomics: measure specific known metabolites. Untargeted: profile all detectable features by MS or NMR.",
           ["metabolomics"], "beginner"),
        mc(7, 1,
           "Flux balance analysis (FBA) predicts steady-state metabolic fluxes by solving:",
           ["a linear program optimising an objective function subject to stoichiometric constraints", "a system of nonlinear ODEs", "a maximum likelihood estimation", "a Markov chain steady state"], 0,
           "FBA: maximise/minimise an objective (e.g., growth) subject to Sv = 0 (steady-state) and flux bounds.",
           ["fba", "metabolic-modeling"], "advanced"),
        mc(7, 1,
           "Post-translational modifications (PTMs) such as phosphorylation are typically detected by:",
           ["mass spectrometry with phosphopeptide enrichment", "western blotting only", "RNA-seq", "confocal microscopy"], 0,
           "Phosphoproteomics: enrich phosphopeptides (TiO₂, IMAC), then identify by LC-MS/MS.",
           ["ptm", "phosphoproteomics"], "intermediate"),
    ]

    # Ch 8 — Structural Bioinformatics
    Q += [
        mc(8, 1,
           "The Protein Data Bank (PDB) stores 3D protein structures determined primarily by:",
           ["X-ray crystallography, cryo-EM, and NMR", "homology modelling", "molecular dynamics simulation", "mass spectrometry"], 0,
           "PDB: ~90% X-ray, ~10% cryo-EM, small fraction NMR. AlphaFold2 predicted structures are in AlphaFold DB.",
           ["pdb", "structural-biology"], "beginner"),
        blank(8, 1,
           "AlphaFold2 predicts protein 3D structure from amino acid sequence using attention-based ___ learning.",
           ["deep", "machine"],
           "AlphaFold2 uses deep learning (Evoformer architecture) trained on PDB structures to predict protein folds.",
           ["alphafold", "deep-learning"], "intermediate"),
        mc(8, 1,
           "The Ramachandran plot shows allowed combinations of backbone dihedral angles:",
           ["φ (phi) and ψ (psi)", "χ1 and χ2 (side-chain)", "ω (omega) and φ (phi)", "all four backbone torsion angles"], 0,
           "Ramachandran: φ (N-Cα) and ψ (Cα-C) define backbone conformation. Most residues cluster in α-helix or β-sheet regions.",
           ["ramachandran", "protein-structure"], "intermediate"),
        tf(8, 1,
           "Homology modelling uses a known structure of a homologous protein as a template to model an unknown protein's structure.",
           True,
           "Homology modelling: align target to template, copy backbone coordinates, model loops, optimise side chains.",
           ["homology-modelling"], "beginner"),
        mc(8, 1,
           "Cryo-electron microscopy (cryo-EM) has recently enabled near-atomic resolution structures of:",
           ["large macromolecular complexes that resist crystallisation", "small molecules < 1 kDa", "lipid bilayers only", "nucleic acids only"], 0,
           "Cryo-EM revolution: single-particle analysis now routinely gives 2-4 Å resolution, especially for large complexes.",
           ["cryo-em"], "intermediate"),
        mc(8, 1,
           "Hydrogen-deuterium exchange mass spectrometry (HDX-MS) is used to study protein dynamics because:",
           ["amide hydrogens exchange with solvent at rates that reflect local hydrogen bonding and solvent exposure, reporting on conformational flexibility", "it directly images the protein backbone at atomic resolution", "deuterium labels all carbon atoms uniformly", "it requires crystalline protein samples"], 0,
           "HDX-MS: backbone NH protons in unprotected, flexible regions exchange rapidly with D₂O; protected regions (secondary structure, buried core) exchange slowly.",
           ["hdx-ms", "protein-dynamics", "structural-biology"], "advanced"),
    ]

    # Ch 9 — Phylogenetics
    Q += [
        mc(9, 1,
           "Maximum likelihood phylogenetics finds the tree that:",
           ["maximises P(data | tree, model)", "minimises pairwise distances", "minimises the number of character state changes", "maximises posterior probability"], 0,
           "ML: find the tree topology and branch lengths that maximise the likelihood of observing the sequence data.",
           ["maximum-likelihood", "phylogenetics"], "intermediate"),
        blank(9, 1,
           "The ___ model of nucleotide substitution assumes equal rates between all pairs of nucleotides.",
           ["Jukes-Cantor", "JC69"],
           "Jukes-Cantor: simplest model with one rate parameter. GTR is the most general reversible model.",
           ["substitution-models"], "beginner"),
        mc(9, 1,
           "Bootstrap support in phylogenetics measures:",
           ["how often a clade appears in trees inferred from resampled datasets", "the number of parsimony characters supporting a split", "the posterior probability of a clade", "the likelihood ratio comparing two trees"], 0,
           "Bootstrap: resample alignment columns, repeat tree inference, count frequency each clade appears (0-100%).",
           ["bootstrap", "phylogenetics"], "intermediate"),
        tf(9, 1,
           "The molecular clock hypothesis assumes that the rate of nucleotide substitution is approximately constant over time.",
           True,
           "Neutral molecular clock (Zuckerkandl & Pauling): substitutions accumulate at roughly constant rates, enabling dating.",
           ["molecular-clock"], "intermediate"),
        mc(9, 1,
           "Bayesian phylogenetic inference uses MCMC to sample from:",
           ["the posterior distribution P(tree|data)", "the likelihood surface P(data|tree)", "bootstrap replicates", "parsimony tree space"], 0,
           "Bayesian inference (MrBayes, BEAST): sample tree topology and parameters from the posterior using MCMC.",
           ["bayesian-phylogenetics", "mcmc"], "advanced"),
        mc(9, 1,
           "Incomplete lineage sorting (ILS) in phylogenomics causes gene trees to differ from the species tree because:",
           ["ancestral polymorphisms can persist across multiple speciation events, resulting in deep coalescence", "sequencing errors introduce false substitutions", "recombination always erases phylogenetic signal", "horizontal gene transfer is universal"], 0,
           "ILS: if a population is polymorphic at a locus when it speciates, the two alleles can coalesce before the speciation event, producing a gene tree discordant with the species tree.",
           ["incomplete-lineage-sorting", "coalescent", "phylogenomics"], "advanced"),
    ]

    # ══════════════════════════════════════════════════════════════════
    # Tier 2 — Systems Biology
    # ══════════════════════════════════════════════════════════════════

    # Ch 10 — Mathematical Modeling
    Q += [
        mc(10, 2,
           "In Michaelis-Menten kinetics, the rate v = Vmax·[S]/(Km + [S]). When [S] = Km, v equals:",
           ["Vmax/2", "Vmax", "2·Vmax", "Km"], 0,
           "Substitute [S] = Km: v = Vmax·Km/(2·Km) = Vmax/2. This is the definition of Km.",
           ["michaelis-menten", "enzyme-kinetics"], "beginner"),
        blank(10, 2,
           "A limit cycle in a nonlinear ODE system is an isolated closed trajectory in ___ space.",
           ["phase", "state"],
           "A limit cycle is a periodic attractor in phase space. Example: the oscillations of a genetic toggle switch.",
           ["limit-cycles", "oscillations"], "intermediate"),
        mc(10, 2,
           "Stochastic chemical kinetics simulates reactions using the Gillespie algorithm, which models individual:",
           ["reaction events as Poisson processes", "concentration trajectories as ODEs", "protein folding transitions", "diffusion of molecules in 3D"], 0,
           "Gillespie SSA: exact stochastic simulation of discrete molecule counts using exponentially distributed waiting times.",
           ["gillespie", "stochastic-kinetics"], "intermediate"),
        tf(10, 2,
           "Positive feedback in gene regulatory networks can create bistability (two stable steady states).",
           True,
           "Positive feedback → bistability: two stable steady states with an unstable state between them (toggle switch, lysis/lysogeny decision).",
           ["positive-feedback", "bistability"], "intermediate"),
        mc(10, 2,
           "The Hill function n_H = 1 corresponds to standard Michaelis-Menten kinetics; n_H > 1 indicates:",
           ["cooperative binding (sigmoidal response)", "competitive inhibition", "substrate inhibition", "product inhibition"], 0,
           "Hill equation: v = Vmax·[S]^n/(K^n + [S]^n). n > 1 → cooperative; n = 1 → hyperbolic; n < 1 → anti-cooperative.",
           ["hill-equation", "cooperativity"], "intermediate"),
        mc(10, 2,
           "Sensitivity analysis in a mathematical model measures:",
           ["how much model outputs change in response to parameter perturbations", "the stability of numerical integration", "the convergence rate of optimisation", "the number of free parameters"], 0,
           "Sensitivity analysis: ∂output/∂parameter, globally (Sobol) or locally (partial derivatives).",
           ["sensitivity-analysis"], "advanced"),
        mc(10, 2,
           "The Fano factor (variance/mean) of molecule number in a stochastic gene expression model exceeds 1 (super-Poissonian) primarily when:",
           ["transcription occurs in bursts — genes stochastically switch between inactive and active states", "translation rate equals degradation rate", "the mRNA lifetime is much shorter than the protein lifetime", "the Hill coefficient equals 1"], 0,
           "Bursty expression: the two-state promoter model gives Fano = 1 + k_on·k_off/(k_on+k_off)²·burst_size > 1.",
           ["fano-factor", "bursty-expression", "stochastic-gene-expression"], "advanced"),
    ]

    # Ch 11 — Metabolic Modeling
    Q += [
        mc(11, 2,
           "The stoichiometric matrix S in flux balance analysis has rows representing ___ and columns representing ___.",
           ["metabolites; reactions", "reactions; metabolites", "genes; metabolites", "enzymes; pathways"], 0,
           "S is m×r (m metabolites, r reactions). Each entry Sᵢⱼ = net stoichiometric coefficient of metabolite i in reaction j.",
           ["stoichiometric-matrix", "fba"], "beginner"),
        tf(11, 2,
           "Flux balance analysis assumes metabolic steady state: Sv = 0.",
           True,
           "FBA steady-state constraint: production = consumption for every metabolite; Sv = 0.",
           ["fba", "steady-state"], "beginner"),
        blank(11, 2,
           "The maximum rate of growth supported by a metabolic model when optimising biomass production using FBA is called the ___ growth rate.",
           ["optimal", "predicted maximum"],
           "FBA optimises an objective function (e.g., biomass) subject to stoichiometric and capacity constraints.",
           ["fba", "growth-rate"], "intermediate"),
        mc(11, 2,
           "Constraint-based metabolic models (e.g., GEMs) determine feasible flux distributions by:",
           ["applying thermodynamic and capacity constraints without kinetic parameters", "solving ODEs with all kinetic parameters", "simulating stochastic reactions", "fitting parameters to time-course data only"], 0,
           "GEMs use steady-state mass balance and capacity constraints, requiring no kinetic parameters.",
           ["gems", "constraint-based"], "intermediate"),
        mc(11, 2,
           "Ensemble modelling and kinetic modelling of metabolism differ in that kinetic models:",
           ["require explicit kinetic rate laws (Michaelis-Menten etc.) for each reaction", "use only stoichiometric information", "are limited to steady-state analysis", "cannot incorporate allosteric regulation"], 0,
           "Kinetic models require Vmax, Km, and regulatory parameters; FBA/GEMs only need stoichiometry and bounds.",
           ["kinetic-models"], "advanced"),
        mc(11, 2,
           "Thermodynamic flux balance analysis (thermo-FBA) improves upon standard FBA by:",
           ["eliminating thermodynamically infeasible internal cycles by enforcing ΔG < 0 constraints on reaction directions", "using kinetic parameters for every enzyme", "optimising for both growth and entropy simultaneously", "adding constraints only on exchange reactions"], 0,
           "Thermo-FBA: combine standard FBA with thermodynamic feasibility (ΔrG < 0) to eliminate futile cycles and improve flux predictions.",
           ["thermo-fba", "thermodynamics", "metabolic-modeling"], "advanced"),
    ]

    # Ch 12 — Gene Regulatory Networks
    Q += [
        mc(12, 2,
           "A feed-forward loop (FFL) in a gene regulatory network is a motif in which:",
           ["a master regulator controls both a target gene and an intermediate regulator that also controls the target", "two genes mutually repress each other", "a gene positively autoregulates itself", "three genes form a mutual activation cycle"], 0,
           "FFL: X→Y, X→Z, Y→Z. The coherent type-1 FFL acts as a sign-sensitive delay.",
           ["ffl", "network-motifs"], "intermediate"),
        blank(12, 2,
           "A genetic ___ switch consists of two mutually repressing genes, each capable of maintaining two stable expression states.",
           ["toggle", "bistable"],
           "Toggle switch (Gardner 2000): two promoters mutually repressing; bistable — positive feedback enables two stable states.",
           ["toggle-switch", "bistability"], "intermediate"),
        tf(12, 2,
           "Negative autoregulation (a gene product represses its own transcription) speeds up the response to a stimulus compared to simple regulation.",
           True,
           "Negative autoregulation: faster response time, lower response variability. Demonstrated by Rosenfeld et al. 2002.",
           ["negative-autoregulation", "network-motifs"], "intermediate"),
        mc(12, 2,
           "Boolean network models of gene regulation represent gene states as:",
           ["on/off (1/0) values updated by logical rules", "continuous ODE variables", "Markov chain states", "probability distributions"], 0,
           "Boolean networks: each gene is 0 or 1, updated synchronously or asynchronously by logic functions (AND/OR/NOT).",
           ["boolean-networks"], "beginner"),
        mc(12, 2,
           "ChIP-seq and ATAC-seq data are commonly integrated with RNA-seq to build:",
           ["gene regulatory network models that link TF binding to target gene expression", "protein-protein interaction networks", "metabolic flux maps", "chromosome conformations only"], 0,
           "Multi-omics integration: TF motifs in accessible chromatin + TF ChIP-seq peaks + target gene expression → GRN edges.",
           ["grn", "multi-omics"], "advanced"),
        mc(12, 2,
           "In the repressilator model, a Hopf bifurcation occurs at a critical Hill coefficient because:",
           ["below the critical n, the unique steady state is stable; above it, the steady state loses stability and a limit cycle (oscillation) emerges", "the protein production rate exceeds degradation at high n", "mRNA lifetimes diverge at the bifurcation point", "the system becomes bistable rather than oscillatory"], 0,
           "Hopf bifurcation: complex eigenvalues of the Jacobian cross the imaginary axis as n increases, destabilising the steady state and creating sustained oscillations.",
           ["repressilator", "hopf-bifurcation", "oscillators"], "advanced"),
    ]

    # Ch 13 — Signaling Networks
    Q += [
        mc(13, 2,
           "The MAPK cascade (Raf → MEK → ERK) exhibits ultrasensitivity due to:",
           ["zero-order ultrasensitivity from kinase/phosphatase competition", "positive feedback only", "direct cooperative binding of Ras", "mRNA stability changes"], 0,
           "Goldbeter-Koshland: when kinase and phosphatase operate near saturation, the switch is ultrasensitive (sigmoidal).",
           ["mapk", "ultrasensitivity"], "advanced"),
        blank(13, 2,
           "Second messengers like cAMP transduce signals from cell surface receptors to intracellular ___ such as PKA.",
           ["effectors", "kinases", "targets"],
           "cAMP activates PKA (protein kinase A), which phosphorylates downstream targets, amplifying the signal.",
           ["second-messengers", "signaling"], "beginner"),
        mc(13, 2,
           "Receptor tyrosine kinases (RTKs) become activated when:",
           ["ligand binding induces receptor dimerisation and trans-autophosphorylation", "cyclic AMP binds the receptor", "G proteins are exchanged", "the receptor is internalised"], 0,
           "RTK activation: ligand → dimerisation → transphosphorylation of intracellular tyrosines → recruit SH2-domain proteins.",
           ["rtk", "phosphorylation"], "intermediate"),
        tf(13, 2,
           "Crosstalk between signaling pathways can cause a drug targeting one pathway to have off-target effects on another.",
           True,
           "Signaling networks are highly interconnected; e.g., MAPK/PI3K crosstalk means BRAF inhibitors can activate PI3K.",
           ["crosstalk", "drug-targets"], "intermediate"),
        mc(13, 2,
           "Scaffold proteins in signaling (e.g., KSR in the MAPK cascade) function by:",
           ["colocalising pathway components to increase local effective concentrations", "directly phosphorylating substrates", "sequestering inhibitory proteins", "activating second messenger production"], 0,
           "Scaffolds organise kinase cascades spatially, preventing cross-talk and increasing specificity and efficiency.",
           ["scaffolds", "signaling"], "intermediate"),
        mc(13, 2,
           "Perfect adaptation in E. coli chemotaxis means the steady-state tumbling frequency is independent of background attractant concentration. This requires:",
           ["integral feedback control — implemented by the methylation/demethylation cycle of chemoreceptors", "pure proportional control of flagellar motor switching", "a fixed threshold concentration for receptor activation", "direct competition between attractant and repellent binding"], 0,
           "Perfect adaptation requires integral control: the CheB/CheR methylation system integrates the error signal, ensuring the output returns to baseline regardless of stimulus magnitude.",
           ["chemotaxis", "perfect-adaptation", "integral-control", "signaling"], "advanced"),
    ]

    # Ch 14 — Multiscale and Whole-Cell
    Q += [
        mc(14, 2,
           "The whole-cell model of Mycoplasma genitalium (Karr et al. 2012) integrates sub-models for all cellular processes and is parameterised by data from:",
           ["literature and experimental measurements for each sub-model", "a single large parameter fit", "genome sequence alone", "crystal structures only"], 0,
           "The Karr WC model integrates ~28 sub-models spanning metabolism, gene expression, replication, and division.",
           ["whole-cell-model"], "advanced"),
        blank(14, 2,
           "___ modelling connects molecular-level (biochemical) and cellular/tissue-level dynamics across multiple scales of space and time.",
           ["multiscale"],
           "Multiscale modelling: link stochastic molecular events to deterministic cell-level behaviour to tissue dynamics.",
           ["multiscale"], "beginner"),
        tf(14, 2,
           "Agent-based models (ABMs) simulate individual entities (cells, molecules) with local rules to study emergent population-level behaviour.",
           True,
           "ABMs: each agent follows rules; population behaviour emerges. Used for tissue growth, biofilm formation, tumour modelling.",
           ["agent-based-models"], "intermediate"),
        mc(14, 2,
           "Spatial stochastic simulations (e.g., MCell, STEPS) differ from well-mixed stochastic simulations by:",
           ["explicitly tracking molecular positions and diffusion in 3D space", "using fewer random numbers", "only simulating equilibrium states", "requiring no input parameters"], 0,
           "Spatial SSA: accounts for diffusion, localisation, and reaction-diffusion coupling that well-mixed Gillespie ignores.",
           ["spatial-stochastic", "reaction-diffusion"], "advanced"),
        mc(14, 2,
           "The Virtual Cell (VCell) modelling platform allows users to:",
           ["specify reaction kinetics and spatial geometry, then automatically derive ODE, PDE, or stochastic sub-models", "predict protein 3D structures from sequence alone", "perform genome-scale metabolic flux analysis", "annotate SBML files with gene ontology terms"],
           0,
           "VCell: geometry-aware modelling; users draw compartments and specify reactions; the platform generates and solves the corresponding math model.",
           ["vcell", "modelling-platform"], "beginner"),
        tf(14, 2,
           "Physiologically-based pharmacokinetic (PBPK) models partition the body into compartments (tissue, blood, liver, kidney) and predict drug distribution from cellular uptake kinetics to whole-organism plasma profiles.",
           True,
           "PBPK models: mechanistic multiscale approach widely used in drug development to predict tissue concentrations from in vitro kinetic data.",
           ["pbpk", "multiscale", "pharmacokinetics"], "intermediate"),
        blank(14, 2,
           "In multiscale modelling, the ___ method couples a coarse-grained solver with fine-scale patches that supply effective closure laws at selected points in the coarse domain.",
           ["heterogeneous multiscale method", "HMM"],
           "The heterogeneous multiscale method (E and Engquist): fine-scale model patches run inside the coarse solver to provide missing closure information without resolving the full fine-scale domain.",
           ["hmm", "multiscale-coupling"], "advanced"),
    ]

    # ══════════════════════════════════════════════════════════════════
    # Tier 3 — Synthetic Biology
    # ══════════════════════════════════════════════════════════════════

    # Ch 15 — Genetic Parts and Devices
    Q += [
        mc(15, 3,
           "The BioBrick standard defines DNA parts with standardised flanking restriction sites to enable:",
           ["modular assembly of biological parts in a consistent framework", "fluorescence measurement", "PCR amplification only", "CRISPR-based regulation"], 0,
           "BioBricks (MIT iGEM): EcoRI/XbaI upstream, SpeI/PstI downstream — compatible sticky ends for standardised assembly.",
           ["biobricks", "standard-parts"], "beginner"),
        blank(15, 3,
           "A ___ is a synthetic DNA part that inserts between a promoter and the ribosome binding site to control translation initiation.",
           ["5' UTR", "riboregulator", "translational regulator"],
           "5' UTR regulatory elements and riboregulators (toehold switches) modulate access of ribosomes to the start codon.",
           ["riboregulators", "translation"], "intermediate"),
        mc(15, 3,
           "The relative strength of a promoter is typically measured by:",
           ["reporter gene expression (e.g., GFP fluorescence or luciferase activity)", "mRNA stability", "protein half-life", "plasmid copy number"], 0,
           "Promoter characterisation: drive a reporter gene, measure output in Relative Promoter Units (RPUs).",
           ["promoters", "characterisation"], "beginner"),
        mc(15, 3,
           "A riboswitch is a regulatory element that controls gene expression in response to:",
           ["direct binding of a small molecule ligand to the mRNA", "a transcription factor binding to DNA", "a microRNA", "a protein repressor"], 0,
           "Riboswitches: aptamer domain in 5' UTR binds ligand, inducing conformational change that affects transcription or translation.",
           ["riboswitches"], "intermediate"),
        tf(15, 3,
           "Retroactivity (loading) occurs when a synthetic part affects upstream components by drawing on shared regulatory resources.",
           True,
           "Retroactivity (Del Vecchio): adding output loads onto a module can impair its upstream driver's function.",
           ["retroactivity", "parts"], "advanced"),
        mc(15, 3,
           "Toehold switch riboregulators (Green et al. 2014) outperform earlier riboregulators as genetically encoded sensors because:",
           ["they use a transactivating RNA (taRNA) to unfold a stem-loop blocking the RBS, achieving >100-fold dynamic range with low leakage", "they directly phosphorylate downstream targets", "they require protein cofactors for activation", "they function only in eukaryotes"], 0,
           "Toehold switches: a hairpin sequesters the RBS; cognate trigger RNA invades via a toehold, unfolds the hairpin, and activates translation. Near-orthogonal, programmable.",
           ["toehold-switches", "riboregulators", "cell-free"], "advanced"),
    ]

    # Ch 16 — Genetic Circuit Design
    Q += [
        mc(16, 3,
           "A genetic oscillator (like the repressilator) requires at least how many repressors in a cycle to function?",
           ["3", "2", "1", "4"], 0,
           "Repressilator (Elowitz 2000): 3 mutually repressing genes in a cycle create sustained oscillations.",
           ["repressilator", "oscillators"], "beginner"),
        blank(16, 3,
           "The NOT gate in a genetic circuit is implemented by a ___, which represses downstream gene expression when it is present.",
           ["repressor", "transcriptional repressor"],
           "A repressor protein bound to an operator prevents RNA polymerase transcription — the biological NOT gate.",
           ["logic-gates", "repressors"], "beginner"),
        mc(16, 3,
           "CRISPR interference (CRISPRi) uses a catalytically dead Cas9 (dCas9) to:",
           ["repress gene expression without cutting DNA", "activate gene expression", "edit DNA sequences", "sequence genomic DNA"], 0,
           "dCas9 + sgRNA blocks RNA polymerase or transcription factors without DSBs (CRISPRi) or activates with transcriptional activators (CRISPRa).",
           ["crispri", "gene-repression"], "intermediate"),
        tf(16, 3,
           "Genetic circuits often exhibit context dependence: the behaviour of a part can change depending on surrounding genetic context.",
           True,
           "Context effects: transcriptional read-through, RBS competition for ribosomes, metabolic burden all affect part function.",
           ["context-dependence", "circuits"], "intermediate"),
        mc(16, 3,
           "Design-Build-Test-Learn (DBTL) cycles in synthetic biology describe:",
           ["an iterative engineering process to optimise genetic circuits", "a quality control process for DNA synthesis", "a regulatory pathway for biosafety review", "an algorithm for whole-genome design"], 0,
           "DBTL: engineer → build (DNA synthesis, assembly) → test (assay phenotype) → learn (model, redesign) → iterate.",
           ["dbtl", "engineering-cycle"], "beginner"),
        mc(16, 3,
           "The metabolic burden imposed on bacteria by a high-copy synthetic circuit arises primarily from:",
           ["competition for limited cellular resources — ribosomes, RNA polymerase, and amino acids — that reduces host fitness", "direct toxicity of the circuit's protein products", "plasmid integration disrupting essential genes", "increased mutation rate from circuit expression"], 0,
           "Resource competition: synthetic circuits draw from a shared pool of transcriptional/translational machinery, creating retroactivity and growth impairment.",
           ["metabolic-burden", "resource-competition", "circuit-design"], "advanced"),
    ]

    # Ch 17 — Genome Editing
    Q += [
        mc(17, 3,
           "CRISPR-Cas9 creates double-strand breaks in DNA guided by:",
           ["a single guide RNA (sgRNA) that base-pairs with the target", "a restriction enzyme recognition site", "a DNA primer", "an antisense RNA"], 0,
           "CRISPR-Cas9: sgRNA provides specificity via Watson-Crick base pairing to the 20-nt target + PAM site recognition.",
           ["crispr-cas9"], "beginner"),
        tf(17, 3,
           "Base editing can introduce C→T or A→G changes in genomic DNA without creating double-strand breaks.",
           True,
           "Base editors (CBE: C→T; ABE: A→G) use a nickase Cas9 fused to a deaminase, avoiding DSBs and HDR.",
           ["base-editing"], "intermediate"),
        mc(17, 3,
           "Non-homologous end joining (NHEJ) DNA repair after a DSB typically produces:",
           ["small insertions or deletions (indels) that can disrupt the reading frame", "perfect repair of the cut site", "large chromosomal rearrangements only", "single nucleotide substitutions only"], 0,
           "NHEJ is error-prone: small indels can cause frameshifts, creating knockout alleles.",
           ["nhej", "dna-repair"], "intermediate"),
        blank(17, 3,
           "Prime editing uses a reverse transcriptase fused to Cas9 nickase and a ___ guide RNA that encodes the desired edit sequence.",
           ["pegRNA", "prime editing guide RNA"],
           "Prime editing (Anzalone 2019): pegRNA contains 3' template encoding the edit; reverse transcriptase writes the edit.",
           ["prime-editing"], "advanced"),
        mc(17, 3,
           "The PAM sequence (e.g., NGG for SpCas9) is required because:",
           ["Cas9 must recognise it to distinguish target DNA from the sgRNA itself", "it marks the cleavage site", "it is required for NHEJ repair", "it defines the start of the protospacer"], 0,
           "PAM recognition lets Cas9 interrogate dsDNA; the PAM is absent from the sgRNA, preventing self-cutting.",
           ["pam", "crispr"], "intermediate"),
        mc(17, 3,
           "Epigenome editing using dCas9 fused to DNMT3A or TET1 enables:",
           ["writing or erasing DNA methylation at specific loci to alter gene expression without changing the DNA sequence", "introducing point mutations at the target site", "permanently deleting the targeted genomic region", "activating NHEJ repair at CpG islands"], 0,
           "dCas9-DNMT3A methylates CpG sites → silencing; dCas9-TET1 demethylates → activation. No DSB, no sequence change.",
           ["epigenome-editing", "dna-methylation", "crispr"], "advanced"),
    ]

    # Ch 18 — Metabolic Engineering
    Q += [
        mc(18, 3,
           "The goal of metabolic engineering is to:",
           ["redirect metabolic fluxes to overproduce a desired compound", "eliminate all byproduct pathways", "maximise cell growth only", "express foreign proteins at high levels"], 0,
           "Metabolic engineering: rationally modify enzyme expression, cofactor balance, and pathway topology to overproduce target metabolites.",
           ["metabolic-engineering"], "beginner"),
        blank(18, 3,
           "Eliminating competing pathways that consume the precursor of a desired product is called ___ of carbon flux.",
           ["redirecting", "channelling", "flux channelling"],
           "Flux redirection: knock out competing routes, overexpress rate-limiting steps, balance cofactors.",
           ["flux-redirection"], "intermediate"),
        mc(18, 3,
           "The maximum theoretical yield of a product in metabolic engineering is constrained by:",
           ["stoichiometry and thermodynamics of the metabolic network", "the speed of DNA synthesis", "the promoter strength only", "the protein folding rate"], 0,
           "Theoretical maximum yield: determined by pathway stoichiometry and thermodynamic feasibility under steady-state.",
           ["theoretical-yield", "fba"], "intermediate"),
        tf(18, 3,
           "Dynamic metabolic engineering uses inducible promoters or biosensors to shift metabolism between growth and production phases.",
           True,
           "Dynamic regulation avoids the growth-production trade-off: first grow the culture, then redirect flux to product.",
           ["dynamic-metabolic-engineering"], "advanced"),
        mc(18, 3,
           "Retrosynthetic analysis in metabolic engineering identifies biosynthetic routes by:",
           ["working backwards from the target molecule to available precursors", "forward simulation of all pathways", "random combinatorial search of enzyme space", "fitting kinetic models to yield data"], 0,
           "Retrobiosynthesis (e.g., RetroPath, XTMS): enumerate reactions that could produce target from available metabolites.",
           ["retrosynthesis"], "intermediate"),
        mc(18, 3,
           "Cofactor imbalance (e.g., NADH accumulation) limits product yield in metabolic engineering because:",
           ["the cell cannot reoxidise excess NADH fast enough, inhibiting glycolysis and limiting carbon flux to the product", "NADH directly inhibits the product biosynthesis enzyme", "excess NADH causes DNA damage", "cofactors are consumed irreversibly and cannot be regenerated"], 0,
           "Redox balance: NADH must be reoxidised (via respiration or fermentative pathways); accumulation inhibits NAD⁺-dependent steps and reduces ATP yield.",
           ["cofactor-balance", "nadh", "metabolic-engineering"], "advanced"),
    ]

    # Ch 19 — Directed Evolution
    Q += [
        mc(19, 3,
           "Directed evolution mimics natural selection by iterating between:",
           ["random mutagenesis (diversity) and selection/screening for improved variants", "rational design and molecular dynamics simulation", "homology modelling and docking", "gene synthesis and expression"], 0,
           "Directed evolution: mutate → express → screen/select → repeat. No protein structure required.",
           ["directed-evolution"], "beginner"),
        blank(19, 3,
           "Error-prone PCR introduces random mutations by reducing the fidelity of ___ through altered Mg²⁺/Mn²⁺ ratio or biased dNTP concentrations.",
           ["DNA polymerase", "polymerase"],
           "epPCR: use low-fidelity Taq polymerase conditions (Mn²⁺, unbalanced dNTPs) to introduce ~1-2 mutations per gene.",
           ["error-prone-pcr", "mutagenesis"], "intermediate"),
        mc(19, 3,
           "DNA shuffling (Stemmer 1994) creates diversity by:",
           ["fragmenting and reassembling homologous genes from multiple parents", "random point mutagenesis of a single gene", "inserting transposons randomly", "saturation mutagenesis at a single codon"], 0,
           "DNA shuffling: digest multiple homologous genes, reassemble by primerless PCR → recombined libraries.",
           ["dna-shuffling"], "intermediate"),
        tf(19, 3,
           "Machine learning can guide directed evolution by building fitness landscape models to prioritise variants for experimental testing.",
           True,
           "ML-guided directed evolution: train models on experimental fitness data, predict high-fitness variants, test, iterate.",
           ["ml-directed-evolution"], "advanced"),
        mc(19, 3,
           "Fluorescence-activated cell sorting (FACS) enables high-throughput screening in directed evolution by:",
           ["sorting individual cells based on fluorescence linked to the desired activity", "sequencing all variants simultaneously", "measuring enzyme kinetics in microplates", "selecting colonies on solid media"], 0,
           "FACS can screen 10⁷–10⁸ variants per day when activity is coupled to a fluorescent signal.",
           ["facs", "high-throughput"], "intermediate"),
        mc(19, 3,
           "Phage-assisted continuous evolution (PACE, Liu lab) achieves dramatically higher throughput than conventional directed evolution by:",
           ["linking the desired protein activity to phage propagation, so active variants replicate continuously without human intervention", "using high-fidelity DNA polymerases to reduce background mutations", "applying CRISPR to introduce mutations into the phage genome", "expressing all library variants simultaneously in the same cell"], 0,
           "PACE: activity → phage infectivity → propagation. Runs continuously at ~1 cycle/hr; can complete >200 rounds in one week.",
           ["pace", "continuous-evolution", "phage"], "advanced"),
    ]

    # Ch 20 — Cell-Free Systems
    Q += [
        mc(20, 3,
           "Cell-free gene expression (CFGE) systems use:",
           ["cell lysates or purified transcription/translation machinery to express genes outside living cells", "intact cells with silenced ribosomes", "synthetic ribosomes only", "viral capsids for expression"], 0,
           "CFGE: cell-free transcription-translation (TX-TL) using E. coli or wheat germ extracts or the PURE system.",
           ["cell-free", "cfge"], "beginner"),
        tf(20, 3,
           "Cell-free protein synthesis allows the incorporation of non-canonical amino acids by adding suppressor tRNAs and non-canonical amino acids to the reaction.",
           True,
           "Open CFPS system: add orthogonal tRNA/aaRS pairs and ncAAs → site-specific incorporation at amber codons.",
           ["cell-free", "non-canonical-aa"], "intermediate"),
        blank(20, 3,
           "The ___ system is a minimal cell-free protein synthesis system composed of purified components rather than cell lysate.",
           ["PURE", "PURExpress"],
           "PURE system (Shimizu 2001): ~36 purified proteins + ribosomes + tRNAs. Minimal but expensive and less active than lysates.",
           ["pure-system", "cell-free"], "intermediate"),
        mc(20, 3,
           "One advantage of cell-free systems for prototyping genetic circuits is:",
           ["rapid (1-2 hour) and open systems that allow direct addition of components", "lower cost than in vivo expression", "ability to evolve cells over generations", "higher protein yield than in vivo"], 0,
           "CFGE: fast, open (add/remove components), no cell viability constraints, easy debugging of genetic circuits.",
           ["cell-free", "circuit-prototyping"], "intermediate"),
        mc(20, 3,
           "The primary energy limitation of in vitro TX-TL (cell-free) reactions is addressed by regeneration systems (e.g., phosphocreatine/creatine kinase or PEP/pyruvate kinase) because:",
           ["ATP and NTPs are rapidly depleted as transcription and translation proceed, halting the reaction after ~2-4 hours without regeneration", "GTP is the only energy currency needed for protein synthesis", "NADH must be continuously supplied to drive ribosomes", "energy regeneration prevents mRNA degradation by RNases"], 0,
           "TX-TL reactions consume ATP/GTP for transcription, translation, and amino acid activation; regeneration systems regenerate ATP from ADP to extend reaction duration.",
           ["cell-free", "energy-regeneration", "tx-tl"], "advanced"),
        mc(20, 3,
           "Cell-free expression is particularly advantageous for producing which class of proteins?",
           ["Toxic or membrane proteins that would kill or harm host cells in vivo", "Proteins requiring glycosylation for function", "Chromosomally integrated gene products", "Proteins that need chaperone-assisted folding unavailable in lysates"],
           0,
           "No cell viability constraint: cell-free systems can produce cytotoxic proteins, membrane proteins reconstituted into liposomes, and proteins with non-canonical amino acids without host cell death.",
           ["cell-free", "applications"], "beginner"),
        tf(20, 3,
           "E. coli crude lysate TX-TL systems generally achieve higher protein yields per reaction than the reconstituted PURE system.",
           True,
           "Lysate TX-TL: energetically robust due to endogenous energy regeneration; typically yields 1-2 mg/mL protein. PURE system yields are lower and per-reaction costs are higher.",
           ["cell-free", "pure-system", "lysate"], "intermediate"),
        blank(20, 3,
           "Paper-based cell-free diagnostics preserve TX-TL activity for months at room temperature by ___ the reaction components during manufacture.",
           ["freeze-drying", "lyophilising", "lyophilization"],
           "Lyophilisation (freeze-drying) of TX-TL reactions: removes water while preserving enzyme activity, enabling portable point-of-care diagnostic strips (e.g., SHERLOCK-based sensors).",
           ["lyophilization", "diagnostics", "cell-free"], "advanced"),
    ]

    # Ch 21 — Biosafety and Ethics
    Q += [
        mc(21, 3,
           "Biosafety Level 2 (BSL-2) is required for work with agents that:",
           ["pose moderate hazard to personnel and environment but have available vaccines or treatment", "pose minimal risk and are not associated with disease in healthy adults", "cause serious disease with limited treatment options", "require pressurised suits and air locks"], 0,
           "BSL-2: moderate risk (e.g., Staphylococcus aureus, hepatitis B); standard PPE + biosafety cabinet.",
           ["biosafety-levels"], "beginner"),
        tf(21, 3,
           "The Asilomar Conference (1975) established voluntary moratorium and safety guidelines for recombinant DNA research.",
           True,
           "Asilomar: scientists self-imposed a moratorium on rDNA work, then established NIH RAC guidelines.",
           ["asilomar", "biosafety-history"], "intermediate"),
        mc(21, 3,
           "Gene drive systems raise biosafety concerns because they can:",
           ["spread a genetic modification through a wild population in a self-propagating manner", "increase antibiotic resistance in the host", "create novel pathogens directly", "permanently contaminate laboratory air"], 0,
           "Gene drives (CRISPR-based) bias inheritance to spread a trait rapidly through a wild population, raising ecological concerns.",
           ["gene-drives", "ethics"], "intermediate"),
        blank(21, 3,
           "The ___ framework in bioethics provides the minimal ethical requirements for human subjects research: respect for persons, beneficence, and justice.",
           ["Belmont Report", "Belmont"],
           "Belmont Report (1979): three core principles for human subjects research in biomedical fields.",
           ["belmont-report", "bioethics"], "advanced"),
        mc(21, 3,
           "Biological containment strategies for engineered organisms (e.g., auxotrophies, kill switches, synthetic base pair dependency) differ from physical containment because they:",
           ["prevent survival of the organism outside controlled conditions even if it escapes the physical facility", "are cheaper to implement than BSL-2 facilities", "only apply to BSL-4 pathogens", "replace the need for regulatory approval"], 0,
           "Biological containment: safeguard-encoded lethality outside the lab (e.g., require synthetic amino acid, activate toxin on escape). Layered with physical containment.",
           ["biological-containment", "biosafety", "kill-switches"], "advanced"),
        blank(21, 3,
           "A Class II ___ cabinet provides personnel and product protection using HEPA-filtered downward laminar airflow and negative pressure to contain aerosols.",
           ["biosafety cabinet", "BSC", "biosafety"],
           "Class II BSC: recirculates HEPA-filtered air over the work surface; negative pressure and HEPA exhaust prevent outward aerosol leakage — standard for BSL-2/3 work.",
           ["biosafety-cabinet", "bsc", "containment"], "beginner"),
        mc(21, 3,
           "Dual-use research of concern (DURC) refers to research that:",
           ["generates knowledge or technologies that could be misused to pose a significant threat to public health, agriculture, or national security", "involves classified government contracts by definition", "requires informed consent from all study participants", "is funded by private industry rather than public agencies"],
           0,
           "DURC: HHS/USDA policies identify 15 categories of concern including enhancing transmissibility, pathogenicity, or defeating countermeasures of a select agent.",
           ["durc", "dual-use", "biosecurity"], "intermediate"),
        tf(21, 3,
           "Responsible innovation frameworks in synthetic biology require that ethical, legal, and societal implications (ELSI) be considered during research design rather than only after a product is developed.",
           True,
           "Responsible innovation: anticipatory governance, reflexivity, and stakeholder engagement integrated throughout the research cycle — not retrofitted at commercialisation.",
           ["responsible-innovation", "elsi", "synthetic-biology-ethics"], "advanced"),
    ]

    # ══════════════════════════════════════════════════════════════════
    # Tier 4 — Computational Tools
    # ══════════════════════════════════════════════════════════════════

    # Ch 22 — Scientific Computing
    Q += [
        mc(22, 4,
           "The Runge-Kutta 4 (RK4) method for integrating ODEs has a global error of order:",
           ["O(h⁴)", "O(h⁵)", "O(h²)", "O(h)"], 0,
           "RK4 is 4th-order: global error O(h⁴), local truncation error O(h⁵). Standard for non-stiff ODEs.",
           ["runge-kutta", "numerical-odes"], "intermediate"),
        blank(22, 4,
           "In numpy, the function ___ computes the matrix product of two 2D arrays using the Einstein summation convention.",
           ["einsum"],
           "np.einsum('ij,jk->ik', A, B) computes matrix multiplication. Also handles tensor contractions.",
           ["numpy", "einsum"], "intermediate"),
        tf(22, 4,
           "Stiff ODE systems require implicit integration methods (e.g., backward Euler, Radau) because explicit methods require prohibitively small step sizes.",
           True,
           "Stiffness: widely separated time scales. Explicit methods require Δt ≪ 1/|λ_max|; implicit methods are A-stable.",
           ["stiff-odes", "implicit-integration"], "intermediate"),
        mc(22, 4,
           "Monte Carlo methods estimate integrals or probabilities by:",
           ["repeated random sampling from probability distributions", "analytical integration", "polynomial approximation", "fast Fourier transform"], 0,
           "Monte Carlo: use random samples to estimate expectation values. Error scales as 1/√N regardless of dimension.",
           ["monte-carlo"], "beginner"),
        mc(22, 4,
           "Sparse matrix formats (CSR, CSC) are preferred for large biological network models because:",
           ["they store only non-zero elements, saving memory and enabling fast operations", "they are easier to construct than dense matrices", "they allow faster computation for any matrix", "they support GPU acceleration only"], 0,
           "Biological networks (GRN, PPI, metabolic) are sparse; CSR/CSC format reduces memory from O(n²) to O(nnz).",
           ["sparse-matrices", "networks"], "intermediate"),
        mc(22, 4,
           "Automatic differentiation (autodiff), as implemented in JAX or PyTorch, differs from both numerical and symbolic differentiation because it:",
           ["applies the chain rule exactly to elementary operations at runtime, producing machine-precision derivatives without symbolic expression explosion", "approximates derivatives with finite differences", "constructs a closed-form symbolic derivative expression", "requires the user to supply analytical Jacobians"], 0,
           "Autodiff (forward/reverse mode): exact chain-rule application at each elementary operation; no approximation error (unlike finite differences), no expression swell (unlike symbolic).",
           ["automatic-differentiation", "autodiff", "neural-networks"], "advanced"),
    ]

    # Ch 23 — Machine Learning in Biology
    Q += [
        mc(23, 4,
           "A convolutional neural network (CNN) is particularly suited for genomic sequences because:",
           ["convolutions can detect local sequence motifs independent of position", "sequences are 3D images", "CNNs require no training data", "genomic sequences are always short"], 0,
           "CNNs learn position-invariant motif detectors (e.g., TF binding motifs); used in DeepBind, DeepSEA, Enformer.",
           ["cnn", "genomics-ml"], "intermediate"),
        blank(23, 4,
           "The ___ algorithm is the standard method for training neural networks, computing gradients via the chain rule through the network.",
           ["backpropagation", "backprop"],
           "Backpropagation: compute ∂L/∂w for all weights using the chain rule, applied in reverse through the network.",
           ["backpropagation", "neural-networks"], "intermediate"),
        mc(23, 4,
           "Transfer learning in biology is exemplified by:",
           ["using ESM or ProtTrans protein language models pretrained on large sequence databases for downstream tasks", "training a model from scratch on a small dataset", "using BLAST to transfer alignments", "applying the same model to human and mouse without modification"], 0,
           "Protein language models (ESM-2, AlphaFold2) pretrained on UniRef learn general protein representations useful for many tasks.",
           ["transfer-learning", "protein-language-models"], "advanced"),
        tf(23, 4,
           "Class imbalance (e.g., 99% negative, 1% positive binding sites) can cause a classifier to achieve high accuracy by predicting all negatives.",
           True,
           "Imbalanced datasets: accuracy is misleading; use AUPRC, F1, or balanced metrics instead.",
           ["class-imbalance", "classification"], "intermediate"),
        mc(23, 4,
           "Variational autoencoders (VAEs) are used in drug discovery to:",
           ["learn a continuous latent space of molecular structures enabling generation and optimisation", "classify molecules as active/inactive", "compute molecular dynamics trajectories", "predict protein stability directly"], 0,
           "VAEs encode molecules to a latent space; decode to generate novel molecules; Bayesian optimisation in latent space.",
           ["vae", "drug-discovery"], "advanced"),
        mc(23, 4,
           "Graph neural networks (GNNs) are well suited for predicting molecular properties because:",
           ["molecules have natural graph structure (atoms = nodes, bonds = edges) and GNNs aggregate local neighbourhood features invariant to atom ordering", "molecules are best represented as images for convolutional processing", "GNNs require no training data for molecular systems", "graph representations are smaller than SMILES strings"], 0,
           "GNNs: message-passing aggregates neighbour information iteratively; permutation-invariant node embeddings → molecular fingerprints for property prediction.",
           ["gnn", "molecular-property-prediction", "drug-discovery"], "advanced"),
    ]

    # Ch 24 — Molecular Dynamics
    Q += [
        mc(24, 4,
           "Classical molecular dynamics (MD) simulations use:",
           ["Newton's equations of motion with empirical force fields", "quantum mechanical wave functions", "Brownian dynamics without bonded terms", "Lattice Boltzmann methods only"], 0,
           "Classical MD: F = ma with CHARMM/AMBER/GROMOS force fields; timestep ~1-2 fs.",
           ["molecular-dynamics", "force-fields"], "beginner"),
        blank(24, 4,
           "Enhanced sampling methods like ___ replica exchange MD run multiple copies of a system at different temperatures to help overcome energy barriers.",
           ["REMD", "replica exchange"],
           "REMD (parallel tempering): swap configurations between replicas at different temperatures to improve sampling of rare events.",
           ["remd", "enhanced-sampling"], "advanced"),
        mc(24, 4,
           "The CHARMM and AMBER force fields describe molecular interactions using potential energy terms for:",
           ["bonds, angles, dihedrals, electrostatics, and Lennard-Jones (LJ) van der Waals", "only covalent bonds", "electrostatics alone", "quantum tunnelling effects"], 0,
           "Classical force field: V = Σ(bond) + Σ(angle) + Σ(dihedral) + Σ(Coulomb) + Σ(LJ).",
           ["force-fields"], "intermediate"),
        tf(24, 4,
           "Free energy perturbation (FEP) calculates binding free energy differences between similar ligands by alchemically transforming one into another.",
           True,
           "FEP: slowly transform ligand A → ligand B in simulation, integrate ΔG via thermodynamic integration or FEP formula.",
           ["fep", "free-energy"], "advanced"),
        mc(24, 4,
           "Coarse-grained MD (e.g., MARTINI) reduces computational cost by:",
           ["grouping several atoms into single interaction sites (beads)", "running at higher temperatures", "using faster time integrators", "removing solvent entirely"], 0,
           "Coarse-grained models: ~4 heavy atoms per bead, larger timestep, 100-1000x faster, suitable for membrane/protein assembly.",
           ["coarse-grained", "martini"], "intermediate"),
        mc(24, 4,
           "The particle mesh Ewald (PME) method is used in biomolecular MD simulations to:",
           ["compute long-range electrostatic interactions efficiently in O(N log N) using a reciprocal-space Fourier grid", "apply periodic boundary conditions to the simulation box", "calculate van der Waals interactions beyond the cutoff", "parallelise bonded force calculations across CPU cores"], 0,
           "PME splits Coulomb sum into short-range (real space, cutoff) and long-range (reciprocal space, FFT) parts; essential for ionic/polar biomolecules.",
           ["pme", "electrostatics", "molecular-dynamics"], "advanced"),
    ]

    # Ch 25 — Network Analysis
    Q += [
        mc(25, 4,
           "The degree distribution of a scale-free network follows a ___ law, meaning most nodes have few connections and a few hubs have many.",
           ["power", "Gaussian", "exponential", "uniform"], 0,
           "Scale-free networks: P(k) ~ k^{-γ}. Examples: PPI networks, metabolic networks, the web.",
           ["scale-free", "degree-distribution"], "beginner"),
        blank(25, 4,
           "In a protein-protein interaction (PPI) network, a node with many connections to nodes that are not themselves connected is said to have high ___.",
           ["betweenness centrality", "centrality"],
           "Betweenness centrality: fraction of shortest paths that pass through a node. Hub proteins often have high betweenness.",
           ["betweenness-centrality"], "intermediate"),
        mc(25, 4,
           "Community detection algorithms in biological networks (e.g., Louvain, Girvan-Newman) identify:",
           ["densely connected subgraphs (modules) with sparse connections between them", "all shortest paths", "scale-free properties", "random subgraphs"], 0,
           "Community detection finds functional modules in PPI, GRN, or metabolic networks corresponding to biological pathways.",
           ["community-detection", "modules"], "intermediate"),
        tf(25, 4,
           "Hubs (highly connected nodes) in PPI networks are often essential genes — their deletion is more likely to be lethal.",
           True,
           "Price-Jeong 'centrality-essentiality rule': hubs are enriched for essential proteins (supported by yeast PPI data).",
           ["hubs", "essentiality"], "intermediate"),
        mc(25, 4,
           "Flux coupling analysis in metabolic networks identifies pairs of reactions where:",
           ["the flux through one is constrained by the flux through the other at steady state", "both reactions are knocked out together", "reactions share a substrate", "both reactions are catalysed by the same enzyme"], 0,
           "Flux coupling: reactions ri, rj are fully coupled if vi/vj is constant at all steady states.",
           ["flux-coupling", "metabolic-networks"], "advanced"),
        mc(25, 4,
           "Exponential random graph models (ERGMs) are used to study biological networks because they:",
           ["generate ensembles of networks with specified local properties (e.g., degree sequence, motif counts), allowing statistical comparison with observed networks", "find the unique network that minimises total edge length", "simulate network growth via preferential attachment", "identify communities using spectral clustering"], 0,
           "ERGMs: specify sufficient statistics (e.g., edges, triangles, degree distribution); use MCMC to sample from the ensemble; test whether observed properties are surprising given null model.",
           ["ergm", "network-statistics", "null-model"], "advanced"),
    ]

    # Ch 26 — Software Engineering for Research
    Q += [
        mc(26, 4,
           "A Snakemake or Nextflow workflow manager provides reproducibility in bioinformatics pipelines by:",
           ["defining rules with explicit inputs, outputs, and shell commands, enabling re-execution of only changed steps", "using random seeds", "storing all intermediate files in a database", "running on a single core to avoid parallelism issues"], 0,
           "Workflow managers: DAG-based execution, automatic re-run of downstream steps when inputs change, portable across HPC/cloud.",
           ["snakemake", "workflow-management"], "intermediate"),
        blank(26, 4,
           "A ___ environment manager (e.g., conda, virtualenv) isolates software dependencies so different projects do not interfere.",
           ["virtual", "conda"],
           "Conda/virtualenv: isolated Python environments with specific package versions ensure reproducibility.",
           ["conda", "environments"], "beginner"),
        mc(26, 4,
           "Containerisation (Docker, Singularity) improves reproducibility by:",
           ["packaging software, dependencies, and OS layers into a portable image", "encrypting source code", "parallelising execution automatically", "version-controlling raw data"], 0,
           "Containers bundle the entire execution environment; results are reproducible regardless of host OS.",
           ["docker", "containers"], "intermediate"),
        tf(26, 4,
           "Unit tests for a bioinformatics tool should test individual functions with known inputs and expected outputs.",
           True,
           "Unit tests: isolated tests of individual functions, comparing output to expected values. Prevent regressions.",
           ["unit-testing", "software-engineering"], "beginner"),
        mc(26, 4,
           "Semantic versioning (SemVer) uses version numbers MAJOR.MINOR.PATCH where MAJOR changes indicate:",
           ["backward-incompatible API changes", "new backward-compatible features", "backward-compatible bug fixes", "build metadata"], 0,
           "SemVer: MAJOR (breaking changes), MINOR (new features, backward-compatible), PATCH (bug fixes).",
           ["semver", "versioning"], "intermediate"),
        mc(26, 4,
           "Continuous integration (CI) in bioinformatics research software is valuable primarily because it:",
           ["automatically runs the test suite on every code push, catching regressions before they affect collaborators or published results", "generates documentation from docstrings automatically", "enforces code style without human review", "provides a GUI for running analyses"], 0,
           "CI (GitHub Actions, GitLab CI): any push triggers build + test; broken code is flagged immediately rather than discovered during peer review or paper reproduction.",
           ["continuous-integration", "ci", "software-engineering"], "advanced"),
    ]

    # ══════════════════════════════════════════════════════════════════
    # Tier 5 — Literature and Research
    # ══════════════════════════════════════════════════════════════════

    # Ch 27 — Foundational Papers
    Q += [
        mc(27, 5,
           "The Watson-Crick paper (1953) proposed the double helix structure of DNA and suggested that base pairing (A-T, G-C) implies:",
           ["a copying mechanism for the genetic material", "a triplet genetic code", "protein structure directly", "RNA as the primary genetic material"], 0,
           "Watson & Crick: 'It has not escaped our notice that the specific pairing we have postulated immediately suggests a possible copying mechanism.'",
           ["watson-crick", "dna-structure"], "beginner"),
        blank(27, 5,
           "Monod, Wyman, and Changeux (1965) proposed the ___ model of allosteric regulation, describing cooperative binding via conformational transitions between T and R states.",
           ["MWC", "concerted", "Monod-Wyman-Changeux"],
           "MWC (concerted) model: protein exists in T (tense) or R (relaxed) state; all subunits switch together.",
           ["mwc-model", "allostery"], "intermediate"),
        mc(27, 5,
           "Elowitz and Leibler (2000) built the repressilator, demonstrating that:",
           ["a synthetic gene network could generate oscillations in E. coli", "eukaryotic cells can be reprogrammed", "RNA interference silences genes", "microRNAs regulate development"], 0,
           "Repressilator: first synthetic biological oscillator. Demonstrated programmability of gene regulatory networks.",
           ["repressilator", "synthetic-biology-history"], "intermediate"),
        tf(27, 5,
           "The Human Genome Project (completed 2003) sequenced the human genome primarily using Sanger sequencing and clone-by-clone (BAC) methods.",
           True,
           "HGP used hierarchical shotgun sequencing of BAC clones by Sanger sequencing. Celera used whole-genome shotgun.",
           ["human-genome-project"], "intermediate"),
        mc(27, 5,
           "The paper by Karr et al. (2012) describing the first whole-cell model was significant because it:",
           ["integrated all known cellular processes of Mycoplasma genitalium into a single predictive model", "proved that all protein structures can be predicted computationally", "solved the protein folding problem for small proteins", "demonstrated cell-free synthesis of a minimal genome"], 0,
           "Karr WCM: 28 sub-models, 1900 parameters, predicted phenotypes including replication time and gene essentiality.",
           ["whole-cell-model", "mycoplasma"], "advanced"),
        mc(27, 5,
           "Venter et al. (2010) reported the first 'synthetic cell' (JCVI-syn1.0). The key scientific demonstration was that:",
           ["a chemically synthesised genome, transplanted into a genome-free recipient cell, could direct self-replication and express a distinct phenotype", "a complete cell was assembled from pure chemicals in a test tube", "protein-free minimal cells could be bootstrapped from nucleic acids alone", "the synthetic cell had a smaller genome than any natural organism"], 0,
           "JCVI-syn1.0: ~1 Mbp synthetic M. mycoides genome assembled from oligonucleotides → transplanted into M. capricolum recipient → replicated with synthetic-genome phenotype.",
           ["synthetic-cell", "jcvi", "minimal-genome"], "advanced"),
    ]

    # Ch 28 — Research Craft
    Q += [
        mc(28, 5,
           "A well-designed negative control in a CRISPR experiment is:",
           ["a non-targeting sgRNA (no genomic target) treated identically to experimental guides", "an untreated wild-type cell line only", "a different cell type", "a plasmid with no promoter"], 0,
           "Negative control: non-targeting sgRNA isolates Cas9 toxicity and delivery effects from on-target editing effects.",
           ["experimental-design", "controls"], "beginner"),
        blank(28, 5,
           "The statistical threshold p < 0.05 means that, assuming the ___ hypothesis is true, the probability of observing this result or more extreme is less than 5%.",
           ["null"],
           "p-value: probability of data at least as extreme as observed, given the null hypothesis is true.",
           ["statistics", "p-value"], "beginner"),
        mc(28, 5,
           "Preregistration of a study involves:",
           ["publicly registering the hypothesis, design, and analysis plan before data collection", "publishing the full dataset before the paper", "submitting to multiple journals simultaneously", "sharing all code before submission"], 0,
           "Preregistration: register hypothesis and analysis plan to prevent HARKing (Hypothesising After Results are Known) and p-hacking.",
           ["preregistration", "research-integrity"], "intermediate"),
        tf(28, 5,
           "Biological replicates (separate experiments from independently grown cultures) provide stronger statistical evidence than technical replicates (repeated measurements of the same sample).",
           True,
           "Biological replicates capture biological variability; technical replicates only capture measurement noise.",
           ["replicates", "experimental-design"], "intermediate"),
        mc(28, 5,
           "In a multi-omics study, data integration is challenging because different omics layers have:",
           ["different dimensions, noise structures, and missing data patterns", "identical experimental protocols", "the same number of features", "no systematic batch effects"], 0,
           "Multi-omics integration: genomics (4e9 positions), transcriptomics (30k genes), proteomics (10k proteins) have mismatched scales and coverage.",
           ["multi-omics", "data-integration"], "advanced"),
        blank(28, 5,
           "___ analysis quantifies how much a model's output changes in response to variation in each input parameter, identifying which parameters most influence predictions.",
           ["sensitivity"],
           "Sensitivity analysis: global (Sobol indices) or local (partial derivatives) approaches identify key parameters. Essential for model validation and experimental prioritisation.",
           ["sensitivity-analysis", "modeling"], "intermediate"),
        tf(28, 5,
           "The FAIR data principles (Findable, Accessible, Interoperable, Reusable) require that research data be made fully open to the public.",
           False,
           "FAIR ≠ open: data can be FAIR while remaining access-controlled (e.g., patient data with ethics restrictions). 'Accessible' means clear access procedures exist, not unrestricted public release.",
           ["fair-data", "open-science"], "advanced"),
        mc(28, 5,
           "Statistical power in an experiment is the probability of:",
           ["correctly rejecting the null hypothesis when it is false (detecting a real effect)", "making a type I error (false positive)", "observing p < 0.05 by chance alone", "replicating a previous experiment exactly"],
           0,
           "Power = 1 − β (type II error rate). Under-powered studies miss real effects; conventional threshold is power ≥ 0.80. Power depends on effect size, sample size, and significance threshold.",
           ["statistical-power", "experimental-design"], "advanced"),
    ]

    return Q


QUESTIONS = build()
