#!/usr/bin/env python3
"""
The James Construction and Stable Homotopy
============================================
J(X): the free monoid on a pointed space, ΩΣX ≃ J(X).

The James construction J(X) builds a space whose points are finite sequences
of points of X (with the basepoint as the identity). The remarkable theorem
is that J(X) ≃ ΩΣX — the loop space of the suspension. This gives a way
to compute stable homotopy groups and is central to the James splitting.
"""

import textwrap

def _c(code, t): return f"\033[{code}m{t}\033[0m"
bold    = lambda t: _c("1",    t)
green   = lambda t: _c("32",   t)
yellow  = lambda t: _c("33",   t)
cyan    = lambda t: _c("36",   t)
red     = lambda t: _c("31",   t)
dim     = lambda t: _c("2",    t)
magenta = lambda t: _c("35",   t)

def clear(): print("\033[2J\033[H", end="")

def wrap(text, width=70, indent="  "):
    lines = []
    for para in text.strip().split("\n"):
        if para.strip() == "":
            lines.append("")
        else:
            lines.extend(textwrap.wrap(para, width, initial_indent=indent,
                                       subsequent_indent=indent))
    return "\n".join(lines)

def box(title, width=68):
    inner = width - 2
    return (f"  ╔{'═'*inner}╗\n"
            f"  ║  {bold(title):<{inner-2}}║\n"
            f"  ╚{'═'*inner}╝")

def rule(width=70): return "  " + dim("─"*width)


def _section_free_monoid():
    clear()
    print(box("Free Monoids: Words Over an Alphabet"))
    print()
    print(wrap(
        "The FREE MONOID on a set A is the set of finite lists over A, with "
        "concatenation as the monoid operation and the empty list as the unit. "
        "It is the simplest algebraic structure generated by A."
    ))
    print()
    print(f"  {cyan('FreeMonoid(A) = List(A) = ε | a | aa | ab | aab | ...')}")
    print(f"  {cyan('multiplication = concatenation  (aab · ba = aabba)')}")
    print(f"  {cyan('unit          = ε  (empty word)')}")
    print()
    print(rule())
    print(f"\n  {bold(green('Universal property:'))}\n")
    print(f"  {cyan('FreeMonoid : Set → Monoid')}")
    print(f"  {cyan('hom from FreeMonoid(A) = function from A')}")
    print()
    print(wrap(
        "Any function f : A → M into a monoid M extends uniquely to a monoid "
        "homomorphism FreeMonoid(A) → M by: ε ↦ unit, [a₁,...,aₙ] ↦ f(a₁)·⋯·f(aₙ). "
        "This is the adjunction: Free ⊣ Forget."
    ))
    print()

    def free_extend(f, unit, mul):
        def extended(word):
            result = unit
            for letter in word:
                result = mul(result, f(letter))
            return result
        return extended

    print(f"  {bold('Example: evaluate a word in ℤ')}")
    print(f"  {dim('  f: {a,b} → ℤ  with  f(a)=3, f(b)=-1')}")
    f = lambda x: 3 if x == 'a' else -1
    extend_to_int = free_extend(f, 0, lambda x,y: x+y)
    words = ['', 'a', 'b', 'ab', 'aab', 'abba', 'aaab']
    for word in words:
        print(f"  [{', '.join(word) if word else 'ε':15}] = {extend_to_int(word):>4}  in ℤ")
    print()
    input(bold("  Press Enter to continue... "))


def _section_james_construction():
    clear()
    print(box("The James Construction J(X)"))
    print()
    print(wrap(
        "The James construction extends the free monoid idea to POINTED SPACES. "
        "Given (X, x₀), we form J(X) = the free TOPOLOGICAL monoid on (X, x₀), "
        "where the basepoint x₀ acts as the identity."
    ))
    print()
    print(f"  {cyan('J(X) = ⊔_{n≥0} Xⁿ / ~')}")
    print(f"  {dim('  where the ~ identifies sequences containing x₀ with shorter ones:')}")
    print(f"  {cyan('  (x₁,...,x₀,...,xₙ) ~ (x₁,...,x̂₀,...,xₙ)')}")
    print()
    print(rule())
    print(f"\n  {bold(green('Filtration by length:'))}\n")
    print(f"  {cyan('J₀(X) = {{ε}}                           (just the basepoint)')}")
    print(f"  {cyan('J₁(X) = J₀(X) ∪ X¹ / ~  ≃ X           (sequences of length ≤ 1)')}")
    print(f"  {cyan('J₂(X) = J₁(X) ∪ X² / ~  ≃ X ∨ X²/~    (sequences of length ≤ 2)')}")
    print(f"  {cyan('Jₙ(X) = J_{n-1}(X) ∪ Xⁿ / ~')}")
    print(f"  {cyan('J(X) = colim_n Jₙ(X)')}")
    print()
    print(wrap(
        "Each Jₙ(X) is built from J_{n-1}(X) by attaching a copy of Xⁿ "
        "along its boundary (where at least one coordinate is x₀). "
        "This gives J(X) a CW-complex structure."
    ))
    print()
    print(rule())
    print(f"\n  {bold(green('The monoid structure on J(X):'))}\n")
    print(f"  {cyan('μ : J(X) × J(X) → J(X)')}")
    print(f"  {cyan('μ([x₁,...,xₘ], [y₁,...,yₙ]) = [x₁,...,xₘ,y₁,...,yₙ]')}")
    print()
    print(wrap(
        "Concatenation is associative up to homotopy (actually up to higher "
        "homotopies — J(X) is an A∞-space, or E₁-space). The unit is the "
        "empty sequence ε. This is not a strict monoid but a HOMOTOPY MONOID."
    ))
    print()
    print(f"  {bold('Special case:')}")
    print(f"  {cyan('J(S⁰) = free monoid on {{-, +}} = ℤ≥0 copies   ≃  ΩS¹')}")
    print(f"  {dim('  (the free A∞-monoid on two elements, one being the identity)')}")
    print()
    input(bold("  Press Enter to continue... "))


def _section_omega_sigma():
    clear()
    print(box("ΩΣX ≃ J(X): The James Equivalence"))
    print()
    print(wrap(
        "The key theorem (James 1955): for a connected CW complex X, "
        "the loop space of the suspension is equivalent to the James construction:"
    ))
    print()
    print(f"  {bold(cyan('ΩΣX  ≃  J(X)'))}")
    print()
    print(wrap(
        "The proof constructs explicit maps in both directions:"
    ))
    print()
    print(f"  {bold('φ : J(X) → ΩΣX')}  (James map)")
    print(f"  {dim('  sends a word [x₁,...,xₙ] to the loop in ΣX')}")
    print(f"  {dim('  formed by going north-to-south via x₁, then north-to-south via x₂, etc.')}")
    print()
    print(f"  {bold('ψ : ΩΣX → J(X)')}  (inverse, constructed via the Hilton-Milnor theorem)")
    print()
    print(rule())
    print(f"\n  {bold(green('Intuition:'))}\n")
    print(wrap(
        "ΣX has a north pole N and a south pole S, and for each x:X a meridian "
        "from N to S. A loop in ΣX based at N is a path that starts and ends "
        "at N. Such a path can be broken into segments, each going from N to S "
        "via some meridian and then back (or forward to the next). This reads "
        "off a sequence of elements of X — which is exactly a word in J(X)."
    ))
    print()
    print(f"  {bold('Special cases:')}")
    cases = [
        ("ΩS¹ = ΩΣS⁰", "J(S⁰) ≃ ℤ≥0 copies ≃ ℤ", "π₁(S¹)=ℤ"),
        ("ΩS² = ΩΣS¹", "J(S¹)",                    "ΩS² is complicated (Hopf fibration!)"),
        ("ΩSⁿ",        "J(Sⁿ⁻¹)",                  "loop space of sphere = James on one-lower sphere"),
        ("ΩΣ(A×B)",    "J(A×B)",                    "James splitting decomposes this"),
    ]
    for lhs, rhs, note in cases:
        print(f"  {bold(cyan(lhs)):<20} ≃  {bold(yellow(rhs)):<30}  {dim(note)}")
    print()
    input(bold("  Press Enter to continue... "))


def _section_james_splitting():
    clear()
    print(box("The James Splitting"))
    print()
    print(wrap(
        "The James splitting (homology level): there is a homology equivalence"
    ))
    print()
    print(f"  {bold(cyan('ΣJ(X) ≃ ΣX ∨ ΣX² ∨ ΣX³ ∨ ⋯  =  ⋁_{n≥1} ΣXⁿ'))}")
    print()
    print(wrap(
        "The suspension of J(X) splits as a wedge of suspended smash powers "
        "of X. This is not a homotopy equivalence in general but holds "
        "in homology (with any coefficients) and in the STABLE category."
    ))
    print()
    print(rule())
    print(f"\n  {bold(green('Stable homotopy equivalence:'))}\n")
    print(f"  {cyan('Σ∞J(X)  ≃  ⋁_{n≥1} Σ∞(X^∧n)  (stably)')}")
    print()
    print(wrap(
        "In the stable homotopy category (after suspending enough times), "
        "the splitting is an actual equivalence. This is one of the fundamental "
        "computations in stable homotopy theory."
    ))
    print()
    print(rule())
    print(f"\n  {bold(green('Homology computation:'))}\n")
    print(wrap(
        "The James splitting gives a powerful way to compute H*(ΩΣX). "
        "Since H*(ΣXⁿ) = Σ H*(Xⁿ) (desuspend) and H*(Xⁿ) = H*(X)^⊗ⁿ:"
    ))
    print()
    print(f"  {cyan('H*(ΩΣX) = H*(J(X)) = ⊕_{n≥1} H*(X)^⊗ⁿ  =  T(H*(X))')}")
    print(f"  {dim('  (the free tensor algebra on H*(X))')}")
    print()
    print(f"  {bold('For X = Sⁿ:')}")
    print(f"  {cyan('H*(ΩSⁿ⁺¹) = T(H*(Sⁿ)) = ℤ[α]  (polynomial algebra, α in degree n)')}")
    print()
    print(f"  {bold('For X = S¹:')}")
    print(f"  {cyan('H*(ΩS²) = T(ℤ·α) = ℤ[α] where |α|=1')}")
    print()
    input(bold("  Press Enter to continue... "))


def _section_stable_homotopy():
    clear()
    print(box("Stable Homotopy Groups and the James Construction"))
    print()
    print(wrap(
        "The stable homotopy groups π_n^s = lim_k πₙ₊ₖ(Sᵏ) are among the "
        "most fundamental invariants in algebraic topology. The James "
        "construction is one of the main tools for computing them."
    ))
    print()
    print(rule())
    print(f"\n  {bold(green('The stable stems:'))}\n")

    stable_groups = [
        (0,  "ℤ",         "π₀^s = π₀(S⁰) = ℤ/2ℤ... wait, this is the degree"),
        (0,  "ℤ",         "The 0-stem: the identity map S^k → S^k"),
        (1,  "ℤ/2ℤ",      "Hopf map η: S³→S² generates; η² ≠ 0, η³ = 0"),
        (2,  "ℤ/2ℤ",      "η² generates the 2-stem"),
        (3,  "ℤ/24ℤ",     "ν (quaternionic Hopf): 24-fold periodicity here"),
        (4,  "0",          "The 4-stem vanishes"),
        (5,  "0",          "The 5-stem vanishes"),
        (6,  "ℤ/2ℤ",      "The 6-stem"),
        (7,  "ℤ/240ℤ",    "σ (octonionic Hopf): 240-fold periodicity"),
        (8,  "(ℤ/2ℤ)²",   "The 8-stem"),
    ]

    print(f"  {'n':6}  {'π_n^s':15}  {'Notes'}")
    print(f"  {dim('─'*60)}")
    for n, grp, note in stable_groups[1:]:
        gstr = bold(yellow(grp)) if grp != "0" else dim(grp)
        print(f"  {n:<6}  {gstr:<23}  {dim(note)}")

    print()
    print(rule())
    print(f"\n  {bold(green('The James construction in HoTT:'))}\n")
    print(wrap(
        "In HoTT, the James construction can be defined as a HIT. J(X) for "
        "pointed (X, x₀) is:"
    ))
    print()
    print(f"  {cyan('data J(X) where')}")
    print(f"  {cyan('  nil  : J(X)')}")
    print(f"  {cyan('  cons : X → J(X) → J(X)')}")
    print(f"  {cyan('  unit : ∀(xs:J(X)). cons x₀ xs = xs')}")
    print()
    print(wrap(
        "The unit constructor says: prepending the basepoint is the identity — "
        "the basepoint acts as a 'phantom' element. This makes J(X) a "
        "homotopy-coherent monoid (A∞-space)."
    ))
    print()
    print(wrap(
        "The theorem ΩΣX ≃ J(X) has been formally verified in Agda/HoTT, "
        "with the proof using the encode-decode method on J(X) and ΩΣX. "
        "This is one of the landmark formalizations in synthetic homotopy theory."
    ))
    print()
    input(bold("  Press Enter to return to menu... "))


SECTIONS = [
    ("monoid",   "Free monoids: words over an alphabet",          _section_free_monoid),
    ("james",    "The James construction J(X)",                   _section_james_construction),
    ("omega",    "ΩΣX ≃ J(X): the James equivalence",            _section_omega_sigma),
    ("splitting","The James splitting",                           _section_james_splitting),
    ("stable",   "Stable homotopy groups and the James construction", _section_stable_homotopy),
]

def main():
    idx = 0
    while True:
        clear()
        print(box("The James Construction and Stable Homotopy", width=70))
        print()
        for i, (_, title, _fn) in enumerate(SECTIONS):
            marker = bold(cyan("▶")) if i == idx else " "
            print(f"  {marker} {bold(str(i+1))}   {title}")
        print()
        print(rule())
        print(f"  {dim('1-5  jump   n  next   p  prev   q  quit')}")
        print()
        try:
            ch = input(bold("  > ")).strip().lower()
        except (EOFError, KeyboardInterrupt):
            break
        if ch in ("q", "quit", "exit"):
            break
        elif ch in ("n", ""):
            SECTIONS[idx][2]()
            idx = min(idx + 1, len(SECTIONS) - 1)
        elif ch == "p":
            idx = max(idx - 1, 0)
        else:
            try:
                v = int(ch) - 1
                if 0 <= v < len(SECTIONS):
                    idx = v
                    SECTIONS[idx][2]()
                    idx = min(idx + 1, len(SECTIONS) - 1)
            except ValueError:
                pass

if __name__ == "__main__":
    main()
