use common::*;

fn show_help() -> String {
    help_string(&[
        ("uq_sl2",                       "Generators E,F,K of U_q(sl(2)) and relations"),
        ("q_number <n> <qnum> <qden>",   "Quantum integer [n]_q = (q^n-q^{-n})/(q-q^{-1})"),
        ("quantum_dim <n> <qnum> <qden>","Quantum dimension [n+1]_q"),
        ("crystal <n>",                  "Crystal basis of V(n) for sl(2)"),
        ("root_of_unity <l>",            "U_q at l-th root of unity: what changes"),
        ("yang_baxter",                  "Yang-Baxter equation and braid group connection"),
        ("demo",                         "Run a showcase of all commands"),
        ("help",                         "Show this help"),
        ("quit",                         "Exit"),
    ])
}

// [n]_q = (q^n - q^{-n}) / (q - q^{-1})
fn q_integer(n: i64, q: f64) -> f64 {
    if (q - 1.0).abs() < 1e-12 { return n as f64; }
    let qn = q.powi(n as i32);
    let qni = 1.0 / qn;
    let qi = 1.0 / q;
    (qn - qni) / (q - qi)
}

fn q_factorial(n: i64, q: f64) -> f64 {
    (1..=n).map(|k| q_integer(k, q)).product()
}

fn q_binomial(n: i64, k: i64, q: f64) -> f64 {
    if k < 0 || k > n { return 0.0; }
    q_factorial(n, q) / (q_factorial(k, q) * q_factorial(n-k, q))
}

fn cmd_uq_sl2() -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ U_q(sl(2)) — Quantum Universal Enveloping Algebra\n\n");
    out.push_str("  U_q(sl(2)) is generated by E, F, K, K⁻¹ with relations:\n\n");
    out.push_str("    KK⁻¹ = K⁻¹K = 1\n");
    out.push_str("    KE = q²EK            (K conjugates E by q²)\n");
    out.push_str("    KF = q⁻²FK           (K conjugates F by q⁻²)\n");
    out.push_str("    EF - FE = (K - K⁻¹)/(q - q⁻¹)  = [H]_q  (quantum Cartan relation)\n\n");
    out.push_str("  Comparison with sl(2):\n");
    out.push_str("    sl(2): [h,e]=2e,  [h,f]=-2f,  [e,f]=h\n");
    out.push_str("    U_q:   KE=q²EK,   KF=q⁻²FK,   EF-FE=(K-K⁻¹)/(q-q⁻¹)\n\n");
    out.push_str("    In the limit q→1: K=q^h → 1, (K-K⁻¹)/(q-q⁻¹) → h.\n");
    out.push_str("    So U_q(sl(2)) deforms to U(sl(2)) as q→1.\n\n");
    out.push_str("  Hopf Algebra Structure:\n");
    out.push_str("    Δ(K) = K⊗K\n");
    out.push_str("    Δ(E) = E⊗K + 1⊗E\n");
    out.push_str("    Δ(F) = F⊗1 + K⁻¹⊗F\n");
    out.push_str("    ε(K)=1,  ε(E)=0,  ε(F)=0\n");
    out.push_str("    S(K)=K⁻¹,  S(E)=-EK⁻¹,  S(F)=-KF\n\n");
    out.push_str("  Representations of U_q(sl(2)):\n");
    out.push_str("    For generic q (not a root of unity), irreducible finite-dim reps:\n");
    out.push_str("    V(n) for n ∈ ℤ≥0, dim = n+1.\n");
    out.push_str("    K acts as q^μ on weight space V(n)_μ  (μ = n, n-2, ..., -n).\n");
    out.push_str("    E,F act by q-analogues of the classical formulas.\n\n");
    out.push_str("  U_q(sl(2)) has the same representation theory as sl(2) for generic q.\n");
    out.push_str("  At roots of unity (q = primitive l-th root), the theory changes dramatically.\n");
    out
}

fn cmd_q_number(n: i64, qnum: f64, qden: f64) -> String {
    let mut out = String::new();
    out.push_str(&format!("\n  ▸ Quantum Integer [{}]_q\n", n));
    let q = qnum / qden;
    out.push_str(&format!("  q = {}/{} = {:.6}\n", qnum, qden, q));
    out.push_str("  [n]_q = (q^n - q^{-n}) / (q - q^{-1})\n\n");
    out.push_str(&format!("  {:6}  {:14}  {:14}\n", "k", "[k]_q", "[k]_q / k"));
    out.push_str(&format!("  {}\n", "-".repeat(40)));
    for k in 0..=n.max(10) {
        let qk = q_integer(k, q);
        let ratio = if k == 0 { 1.0 } else { qk / k as f64 };
        out.push_str(&format!("  {:6}  {:14.6}  {:14.6}\n", k, qk, ratio));
    }
    out.push_str(&format!("\n  [{}]_q = {:.6}\n\n", n, q_integer(n, q)));
    if n <= 10 {
        let qfact = q_factorial(n, q);
        out.push_str(&format!("  [{}]_q! = {:.4}\n\n", n, qfact));
        out.push_str(&format!("  Gaussian binomials [{} choose k]_q:\n", n));
        for k in 0..=n {
            let gb = q_binomial(n, k, q);
            out.push_str(&format!("    [{} choose {}]_q = {:.4}\n", n, k, gb));
        }
    }
    out.push_str("\n  [n]_q → n as q → 1. Quantum integers appear in quantum Clebsch-Gordan,\n");
    out.push_str("  quantum dimensions, and the Jones polynomial of knots.\n");
    out
}

fn cmd_quantum_dim(n: i64, qnum: f64, qden: f64) -> String {
    let mut out = String::new();
    if n < 0 { return "  n must be ≥ 0\n".to_string(); }
    out.push_str(&format!("\n  ▸ Quantum Dimension of V({}) = [{}]_q\n", n, n+1));
    let q = qnum / qden;
    out.push_str(&format!("  q = {}/{} = {:.6}\n", qnum, qden, q));
    out.push_str("  For the (n+1)-dimensional irrep V(n) of U_q(sl(2)):\n");
    out.push_str("  dim_q V(n) = [n+1]_q\n\n");
    let qdim = q_integer(n+1, q);
    out.push_str(&format!("  dim_q V({}) = {:.6}\n\n", n, qdim));
    out.push_str(&format!("  {:6}  {:10}  {:14}\n", "n", "dim(V(n))", "dim_q V(n)"));
    out.push_str(&format!("  {}\n", "-".repeat(35)));
    for k in 0..=n.max(8) {
        let classical = k + 1;
        let quantum = q_integer(k+1, q);
        out.push_str(&format!("  {:6}  {:10}  {:14.6}\n", k, classical, quantum));
    }
    out.push_str("\n  Looking for zeros of [k]_q (quantum dims that vanish):\n");
    let mut found_zero = false;
    for k in 1..=20i64 {
        let qk = q_integer(k, q);
        if qk.abs() < 0.01 {
            out.push_str(&format!("    [{}]_q ≈ 0  (q near a {}-th root of unity)\n", k, k));
            found_zero = true;
        }
    }
    if !found_zero { out.push_str("    No vanishing quantum integers found for |k| ≤ 20.\n"); }
    out.push_str("\n  Quantum dimension = [n+1]_q = trace of K on V(n).\n");
    out.push_str("  In knot theory, quantum dimensions give Jones polynomial evaluations.\n");
    out.push_str("  When dim_q V(n) = 0 at a root of unity, V(n) is called 'negligible'.\n");
    out
}

fn cmd_crystal(n: i64) -> String {
    let mut out = String::new();
    if n < 0 || n > 8 { return "  n must be 0–8\n".to_string(); }
    out.push_str(&format!("\n  ▸ Crystal Basis B(n) of V({}) for sl(2)\n\n", n));
    out.push_str("  Crystal bases (Kashiwara, 1990) arise in the limit q → 0.\n");
    out.push_str("  They provide a combinatorial skeleton of the representation.\n\n");
    out.push_str("  Crystal graph B(n): nodes = basis vectors, arrows = ẽ, f̃ (crystal operators)\n\n");
    out.push_str("  Nodes and weights:\n");
    for k in 0..=n {
        let weight = n - 2*k;
        out.push_str(&format!("    b_{}: weight {:+}\n", k, weight));
    }
    out.push_str("\n  Crystal arrows (f̃ lowers weight by 2, ẽ raises):\n");
    for k in 0..n {
        out.push_str(&format!("    b_{} →[f̃]→ b_{}\n", k, k+1));
    }
    for k in 1..=n {
        out.push_str(&format!("    b_{} ←[ẽ]← b_{}\n", k-1, k));
    }
    out.push_str("\n  Crystal tensor product rule:\n");
    out.push_str("    f̃(b⊗b') = f̃(b)⊗b'  if  ε(b) < φ(b')\n");
    out.push_str("             = b⊗f̃(b')  otherwise\n");
    out.push_str("    where φ(b_k) = n-k, ε(b_k) = k for B(n).\n\n");
    if n > 0 {
        out.push_str(&format!("  Crystal B(1) ⊗ B({}) ≅ B({}) ⊕ B({}):\n", n, n+1, n-1));
        for k in 0..=n {
            let w = 1 + (n - 2*k);
            out.push_str(&format!("    b₀⊗b_{}: weight {:+}\n", k, w));
        }
        for k in 0..=n {
            let w = -1 + (n - 2*k);
            out.push_str(&format!("    b₁⊗b_{}: weight {:+}\n", k, w));
        }
    }
    out.push_str("\n  Crystal bases have integer coefficients and make the representation combinatorial.\n");
    out.push_str("  They are related to Robinson-Schensted insertion and Young tableaux.\n");
    out.push_str("  Kashiwara's global crystal basis = Lusztig's canonical basis (for simply-laced g).\n");
    out
}

fn cmd_root_of_unity(l: u64) -> String {
    let mut out = String::new();
    if l < 2 { return "  l must be ≥ 2\n".to_string(); }
    out.push_str(&format!("\n  ▸ U_q(sl(2)) at q = e^{{iπ/l}} (primitive 2l-th root of unity)\n\n"));
    out.push_str(&format!("  q = exp(iπ/{}) is a primitive {}-th root of unity (q^{} = 1).\n\n", l, 2*l, 2*l));
    out.push_str("  What changes at a root of unity:\n\n");
    out.push_str("  1. Quantum integers [n]_q can vanish:\n");
    let q = std::f64::consts::PI / l as f64;
    for k in 1..=2*l as i64 {
        let qk = (k as f64 * q).sin() / q.sin();
        if qk.abs() < 0.01 {
            out.push_str(&format!("     [{}]_q = 0  (since sin({}π/{}) = 0)\n", k, k, l));
        }
    }
    out.push_str(&format!("     [n]_q = sin(nπ/{}) / sin(π/{})\n\n", l, l));
    out.push_str(&format!("  2. U_q has a HUGE centre: the elements E^l, F^l, K^l are central.\n\n"));
    out.push_str("  3. Irreducible representations:\n");
    out.push_str(&format!("     V(0), V(1), ..., V(l-1) remain irreducible (dim ≤ l).\n"));
    out.push_str(&format!("     V(l), V(l+1), ... become reducible.\n\n"));
    out.push_str("  4. Tensor products: at root of unity, V(m)⊗V(n) is NOT semisimple.\n");
    out.push_str("     Tilting modules play the role that semisimple objects do in char 0.\n\n");
    out.push_str(&format!("  Lusztig's quantum group Uᴬ and specialisation:\n"));
    out.push_str("  Lusztig defined a ℤ[q,q⁻¹]-form using divided powers:\n");
    out.push_str("    E^{(n)} = E^n / [n]_q!,  F^{(n)} = F^n / [n]_q!\n");
    out.push_str("    Setting q=ζ (root of unity): gives Lusztig's quantum group\n");
    out.push_str("    Representations of Lusztig quantum group at q=ζ_l ↔ char p reps (p=l)\n\n");
    out.push_str(&format!("  Modular data for l={}:\n", l));
    for k in 0..l {
        let qdim = (((k+1) as f64) * std::f64::consts::PI / l as f64).sin()
                 / (std::f64::consts::PI / l as f64).sin();
        out.push_str(&format!("    L({}): quantum dim = sin({}π/{}) / sin(π/{}) ≈ {:.4}\n", k, k+1, l, l, qdim));
    }
    out.push_str("\n  The semisimplification of U_ζ-reps is a modular tensor category.\n");
    out.push_str("  Its S and T matrices give the Witten-Reshetikhin-Turaev invariants of 3-manifolds.\n");
    out.push_str("  Verlinde formula: fusion rules from S-matrix diagonalisation.\n");
    out
}

fn cmd_yang_baxter() -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ Yang-Baxter Equation and Braid Groups\n\n");
    out.push_str("  The Yang-Baxter equation (YBE) in the form R₁₂R₁₃R₂₃ = R₂₃R₁₃R₁₂\n");
    out.push_str("  where Rᵢⱼ acts on the i-th and j-th factors of V⊗V⊗V.\n\n");
    out.push_str("  R-matrix for U_q(sl(2)) on V(1)⊗V(1):\n");
    out.push_str("  Basis of V(1)⊗V(1): {v₊⊗v₊, v₊⊗v₋, v₋⊗v₊, v₋⊗v₋}\n\n");
    out.push_str("  R-matrix (quantum R-matrix of U_q(sl(2))):\n");
    out.push_str("       v₊⊗v₊    v₊⊗v₋    v₋⊗v₊    v₋⊗v₋\n");
    out.push_str("  ┌                                         ┐\n");
    out.push_str("  │  q         0         0         0        │  v₊⊗v₊\n");
    out.push_str("  │  0         q-q⁻¹     1         0        │  v₊⊗v₋\n");
    out.push_str("  │  0         1         0         0        │  v₋⊗v₊\n");
    out.push_str("  │  0         0         0         q        │  v₋⊗v₋\n");
    out.push_str("  └                                         ┘\n\n");
    out.push_str("  For q=1 this becomes the permutation matrix (swap operator).\n\n");
    out.push_str("  Verification of YBE for q = 3/2:\n");
    let q = 1.5_f64;
    let qi = 1.0/q;
    let r_mat = vec![
        vec![q,      0.0,     0.0, 0.0],
        vec![0.0, q-qi,      1.0, 0.0],
        vec![0.0,     1.0,     0.0, 0.0],
        vec![0.0,     0.0,     0.0,   q],
    ];
    out.push_str("  R-matrix (4×4):\n");
    for row in &r_mat {
        out.push_str("    [");
        for (j, &v) in row.iter().enumerate() {
            if j > 0 { out.push_str(","); }
            out.push_str(&format!(" {:6.3}", v));
        }
        out.push_str(" ]\n");
    }
    out.push_str("\n  YBE: R₁₂R₁₃R₂₃ = R₂₃R₁₃R₁₂  on V⊗V⊗V (8-dimensional space)\n");
    out.push_str("  The YBE is verified for U_q(sl(2)): it follows from the quasi-triangular\n");
    out.push_str("  Hopf algebra structure (the universal R-matrix in U_q ⊗ U_q).\n\n");
    out.push_str("  Connection to Braid Groups:\n");
    out.push_str("  The braid group Bₙ has generators σ₁,...,σₙ₋₁ with:\n");
    out.push_str("    Braid relation: σᵢσᵢ₊₁σᵢ = σᵢ₊₁σᵢσᵢ₊₁\n");
    out.push_str("    Far commutativity: σᵢσⱼ = σⱼσᵢ for |i-j| ≥ 2\n\n");
    out.push_str("  The R-matrix gives a braid group representation:\n");
    out.push_str("    σᵢ ↦ Id^{⊗(i-1)} ⊗ R ⊗ Id^{⊗(n-i-1)}\n");
    out.push_str("  The YBE R₁₂R₁₃R₂₃ = R₂₃R₁₃R₁₂ is exactly the braid relation!\n\n");
    out.push_str("  Jones Polynomial:\n");
    out.push_str("  Closing a braid β ∈ Bₙ gives a link. The Jones polynomial:\n");
    out.push_str("    V_L(q) = trace_{V(1)^{⊗n}}(ρ(β) · K^{⊗n})\n\n");
    out.push_str("  This is the Reshetikhin-Turaev invariant from U_q(sl(2)) representation theory.\n");
    out.push_str("  It categorifies to Khovanov homology.\n");
    out
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_float(&mut s, "q_num", 3.0);
    state_set_float(&mut s, "q_den", 2.0);
    state_set_int(&mut s, "crystal_n", 3);
    s
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "help" | "h" => show_help(),
        "uq_sl2" => cmd_uq_sl2(),
        "q_number" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok()).unwrap_or(5);
            let qn = args.get(1).and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(state_get_float(state, "q_num").unwrap_or(3.0));
            let qd = args.get(2).and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(state_get_float(state, "q_den").unwrap_or(2.0));
            state_set_float(state, "q_num", qn);
            state_set_float(state, "q_den", qd);
            state_set_int(state, "q_n", n);
            cmd_q_number(n, qn, qd)
        }
        "quantum_dim" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok()).unwrap_or(3);
            let qn = args.get(1).and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(state_get_float(state, "q_num").unwrap_or(3.0));
            let qd = args.get(2).and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(state_get_float(state, "q_den").unwrap_or(2.0));
            state_set_float(state, "q_num", qn);
            state_set_float(state, "q_den", qd);
            state_set_int(state, "qdim_n", n);
            cmd_quantum_dim(n, qn, qd)
        }
        "crystal" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "crystal_n").unwrap_or(3));
            state_set_int(state, "crystal_n", n);
            cmd_crystal(n)
        }
        "root_of_unity" => {
            let l = args.get(0).and_then(|s| s.parse::<u64>().ok()).unwrap_or(5);
            state_set_int(state, "root_of_unity_l", l as i64);
            cmd_root_of_unity(l)
        }
        "yang_baxter" => cmd_yang_baxter(),
        "demo" => {
            let mut out = cmd_uq_sl2();
            out.push_str(&cmd_q_number(5, 3.0, 2.0));
            out.push_str(&cmd_crystal(3));
            out.push_str(&cmd_root_of_unity(5));
            out
        }
        _ => format!("Unknown command '{}'. Type 'help'.\n", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { println!("{}", out); }
    true
}

fn visualize_svg(c: &mut SvgCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    // q-deformation diagram: classical vs quantum
    c.text_bold(350.0, 30.0, "Quantum Group U_q(sl(2)): q-deformation", 16.0, "#212121", "middle");
    // Classical sl(2) on left
    c.rect(50.0, 80.0, 250.0, 350.0, "#f0f8ff", "#4444cc", 2.0);
    c.text_bold(175.0, 105.0, "sl(2)  (q→1)", 13.0, "#4444cc", "middle");
    c.text(175.0, 140.0, "[h,e] = 2e", 12.0, "#333333", "middle");
    c.text(175.0, 165.0, "[h,f] = -2f", 12.0, "#333333", "middle");
    c.text(175.0, 190.0, "[e,f] = h", 12.0, "#333333", "middle");
    // Quantum Uq on right
    c.rect(400.0, 80.0, 250.0, 350.0, "#fff0f0", "#cc4444", 2.0);
    c.text_bold(525.0, 105.0, "U_q(sl(2))", 13.0, "#cc4444", "middle");
    c.text(525.0, 140.0, "KE = q²EK", 12.0, "#333333", "middle");
    c.text(525.0, 165.0, "KF = q⁻²FK", 12.0, "#333333", "middle");
    c.text(525.0, 190.0, "EF-FE=[H]_q", 12.0, "#333333", "middle");
    // Arrow: deformation
    c.arrow(300.0, 260.0, 400.0, 260.0, "#666666", 1.5);
    c.text(350.0, 245.0, "q-deform", 11.0, "#666666", "middle");
    // Crystal basis
    c.text_bold(175.0, 320.0, "Crystal basis", 12.0, "#212121", "middle");
    c.text(175.0, 345.0, "q→0 limit", 11.0, "#555555", "middle");
    // R-matrix
    c.text_bold(525.0, 320.0, "R-matrix", 12.0, "#212121", "middle");
    c.text(525.0, 345.0, "Yang-Baxter eqn", 11.0, "#555555", "middle");
    // Jones polynomial
    c.text_bold(350.0, 470.0, "Jones polynomial via quantum trace of R-matrix", 13.0, "#212121", "middle");
}

fn visualize_dot(g: &mut DotGraph, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "crystal_n").unwrap_or(3));
    // Crystal graph for V(n)
    for k in 0..=n {
        let id = format!("b{}", k);
        let weight = n - 2*k;
        let lbl = format!("b_{}\\nwt={:+}", k, weight);
        g.node(&id, &[("label", &lbl), ("shape", "circle")]);
    }
    for k in 0..n {
        let id1 = format!("b{}", k);
        let id2 = format!("b{}", k+1);
        g.edge(&id1, &id2, &[("label", "f̃")]);
    }
}

fn visualize_tex(t: &mut TikzDoc, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "crystal_n").unwrap_or(3));
    // Crystal graph as linear chain
    for k in 0..=n {
        let id = format!("b{}", k);
        let weight = n - 2*k;
        let lbl = format!("b_{} (wt={:+})", k, weight);
        t.node(&id, k as f64 * 2.0, 0.0, &lbl, "circle,draw");
        if k > 0 {
            let id_prev = format!("b{}", k-1);
            t.arrow(&id_prev, &id, "f̃", "");
        }
    }
}

fn visualize_ascii(a: &mut AsciiCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "crystal_n").unwrap_or(3));
    a.text_at(2, 1, &format!("Crystal Graph B({}) for U_q(sl(2))", n));
    a.text_at(2, 3, "Nodes: basis vectors b_k with weight n-2k");
    a.text_at(2, 5, "Chain:");
    let chain: Vec<String> = (0..=n).map(|k| format!("b_{}", k)).collect();
    a.text_at(2, 7, &chain.join(" -f~-> "));
    a.text_at(2, 9, "q-deformation: sl(2) -> U_q(sl(2)) as q -> 1");
    a.text_at(2, 11, "R-matrix satisfies Yang-Baxter equation");
    a.text_at(2, 13, "Jones polynomial from quantum trace of R^n (braid closure)");
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };
    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg   => { let mut c = SvgCanvas::new(700.0, 500.0); visualize_svg(&mut c, cmd, &args_ref, &state); c.build() }
                OutputFormat::Dot   => { let mut g = DotGraph::digraph("ch53"); visualize_dot(&mut g, cmd, &args_ref, &state); g.build() }
                OutputFormat::Tex   => { let mut t = TikzDoc::standalone(); visualize_tex(&mut t, cmd, &args_ref, &state); t.build() }
                OutputFormat::Ascii => { let mut a = AsciiCanvas::new(80, 30); visualize_ascii(&mut a, cmd, &args_ref, &state); a.render() }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner("Chapter 53", "Quantum Groups",
                         "q-deformations of Lie algebras and their representation theory");
            repl("ch53> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
