#!/usr/bin/env node
// Walks questions/ recursively, reads every .json file in sorted order,
// and writes questions-bundle.js for the browser app.
// Run with: node build.js
'use strict';
const fs   = require('fs');
const path = require('path');

function walkJson(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...walkJson(full));
    else if (entry.name.endsWith('.json')) results.push(full);
  }
  return results;
}

const questionsDir = path.join(__dirname, 'questions');
if (!fs.existsSync(questionsDir)) {
  console.error('questions/ directory not found. Run `node generate.js` first.');
  process.exit(1);
}

const files     = walkJson(questionsDir);
const questions = files.map(f => JSON.parse(fs.readFileSync(f, 'utf8')));

const banner = [
  '// Auto-generated by build.js — do not edit directly.',
  '// Edit individual files in quiz/questions/ then run: node build.js',
  `// ${questions.length} questions across ${new Set(questions.map(q => q.ch)).size} chapters`,
  '',
].join('\n');

const bundle = `${banner}const ALL_QUESTIONS = ${JSON.stringify(questions, null, 2)};\n`;
const out    = path.join(__dirname, 'questions-bundle.js');
fs.writeFileSync(out, bundle);
console.log(`Bundled ${questions.length} questions from ${files.length} files → questions-bundle.js`);
