#!/usr/bin/env node
// Writes q05.json–q08.json into each chapter's questions directory.
// Run after existing questions are in place, then run `node build.js`.
'use strict';
const fs   = require('fs');
const path = require('path');

const PART_DIRS = {
  1: 'part-i-foundations',
  2: 'part-ii-dynamical-systems',
  3: 'part-iii-information-theory',
  4: 'part-iv-bridges',
  5: 'part-v-foundations',
  6: 'part-vi-frontiers',
  7: 'part-vii-connections',
};

const CH_DIRS = {
   1: 'ch01-real-analysis',
   2: 'ch02-measure-theory',
   3: 'ch03-topology',
   4: 'ch04-ordinary-differential-equations',
   5: 'ch05-linear-algebra',
   6: 'ch06-topological-dynamics',
   7: 'ch07-ergodic-theory',
   8: 'ch08-stability-theory',
   9: 'ch09-hyperbolic-dynamics',
  10: 'ch10-bifurcation-theory',
  11: 'ch11-chaos-theory',
  12: 'ch12-symbolic-dynamics',
  13: 'ch13-complex-dynamics',
  14: 'ch14-hamiltonian-systems',
  15: 'ch15-infinite-dimensional-dynamics',
  16: 'ch16-classical-information-theory',
  17: 'ch17-entropy-generalizations',
  18: 'ch18-algorithmic-information-theory',
  19: 'ch19-network-information-theory',
  20: 'ch20-information-geometry',
  21: 'ch21-quantum-information-theory',
  22: 'ch22-entropy-in-dynamical-systems',
  23: 'ch23-ergodic-information-theory',
  24: 'ch24-symbolic-dynamics-and-information',
  25: 'ch25-chaos-randomness-computation',
  26: 'ch26-information-methods-in-cs',
  27: 'ch27-computability-and-dynamics',
  28: 'ch28-category-theory-and-dynamics',
  29: 'ch29-thermodynamics-and-information',
  30: 'ch30-optimal-transport',
  31: 'ch31-ergodic-number-theory',
  32: 'ch32-descriptive-set-theory',
  33: 'ch33-orbit-equivalence',
  34: 'ch34-sofic-entropy',
  35: 'ch35-isomorphism-problem',
  36: 'ch36-zimmer-program',
  37: 'ch37-complex-dynamics-frontiers',
  38: 'ch38-quantum-information-complexity',
  39: 'ch39-one-shot-information-theory',
  40: 'ch40-circuit-complexity-and-it',
  41: 'ch41-collatz-dynamics',
  42: 'ch42-quantum-computing-connections',
  43: 'ch43-hott-connections',
};

// Extra questions indexed by chapter number; each entry is an array of 4 questions.
const EXTRA = {

// ── Ch 1: Real Analysis ───────────────────────────────────────────────────────
1: [
  { q: "Which of the following is the correct statement of the Heine-Borel theorem in ℝⁿ?",
    opts: ["Every bounded set is compact","Every closed set is compact","A subset of ℝⁿ is compact if and only if it is closed and bounded","Every open cover of a closed set has a finite subcover"],
    ans: 2,
    exp: "In ℝⁿ, the Heine-Borel theorem characterises compact sets precisely as those that are both closed and bounded. This fails in infinite-dimensional spaces." },
  { q: "The Arzelà-Ascoli theorem gives conditions for a family of functions to have a uniformly convergent subsequence. The key hypotheses are:",
    opts: ["Pointwise boundedness only","Equicontinuity and pointwise boundedness","Uniform continuity and compactness of domain","Lipschitz continuity and uniform boundedness"],
    ans: 1,
    exp: "Arzelà-Ascoli requires the family to be pointwise bounded and equicontinuous on a compact domain. Together these imply relative compactness in C(K)." },
  { q: "For a sequence of measurable functions fₙ → f pointwise a.e. on a finite measure space, Egorov's theorem guarantees:",
    opts: ["Uniform convergence everywhere","Convergence in L¹","Uniform convergence outside a set of arbitrarily small measure","Convergence in measure"],
    ans: 2,
    exp: "Egorov's theorem: on a finite measure space, pointwise a.e. convergence implies 'almost uniform' convergence—uniform convergence outside sets of measure ε for any ε > 0." },
  { q: "The Contraction Mapping Theorem (Banach Fixed-Point Theorem) requires the map T: X → X to satisfy:",
    opts: ["T is continuous","T is a bijection","There exists k < 1 such that d(Tx,Ty) ≤ k·d(x,y) for all x,y","T is an isometry"],
    ans: 2,
    exp: "A contraction requires a uniform Lipschitz constant k < 1. The theorem then guarantees a unique fixed point and gives an explicit convergence rate for iterates." },
],

// ── Ch 2: Measure Theory ─────────────────────────────────────────────────────
2: [
  { q: "The Radon-Nikodym theorem states that if ν ≪ μ (ν absolutely continuous w.r.t. μ), then:",
    opts: ["ν = μ","There exists a measurable f ≥ 0 such that ν(A) = ∫_A f dμ for all measurable A","ν and μ are mutually singular","ν is a finite measure"],
    ans: 1,
    exp: "Radon-Nikodym yields the density dν/dμ (the Radon-Nikodym derivative). It is fundamental in probability (conditional expectation) and ergodic theory (invariant measures)." },
  { q: "Lusin's theorem in measure theory states that for a measurable function f on a finite measure space:",
    opts: ["f is Riemann integrable","f equals a continuous function a.e.","For any ε > 0, there exists a closed set F with μ(Fᶜ) < ε on which f is continuous","f has at most countably many discontinuities"],
    ans: 2,
    exp: "Lusin's theorem: measurable functions are 'nearly continuous'—continuous when restricted to a large closed set. This justifies approximating measurable by continuous functions." },
  { q: "Which convergence theorem allows passing the limit inside the integral when |fₙ| ≤ g for an integrable function g?",
    opts: ["Monotone Convergence Theorem","Fatou's Lemma","Dominated Convergence Theorem","Uniform Convergence Theorem"],
    ans: 2,
    exp: "The Dominated Convergence Theorem requires an integrable dominating function. Monotone Convergence applies when fₙ is non-decreasing; Fatou's Lemma gives a lower bound." },
  { q: "A measure μ on (X, Σ) is called σ-finite if:",
    opts: ["μ(X) < ∞","X can be written as a countable union of sets with finite measure","Every measurable set has finite measure","μ is a probability measure"],
    ans: 1,
    exp: "σ-finiteness means X = ∪Xₙ with μ(Xₙ) < ∞. This weaker condition than finiteness still allows the Fubini theorem, Radon-Nikodym theorem, and most key results to hold." },
],

// ── Ch 3: Topology ──────────────────────────────────────────────────────────
3: [
  { q: "A topological space X is called normal (T₄) if:",
    opts: ["Every point is closed","Every open cover has a finite subcover","Any two disjoint closed sets can be separated by disjoint open sets","X is Hausdorff and compact"],
    ans: 2,
    exp: "Normality means disjoint closed sets have disjoint open neighborhoods. Urysohn's lemma then gives continuous functions separating them—key for extension theorems." },
  { q: "The Stone-Čech compactification βX of a completely regular space X is characterized by:",
    opts: ["It is the one-point compactification","Every bounded continuous f: X → ℝ extends uniquely to βX → ℝ","It is the smallest compactification","It preserves the topology of X"],
    ans: 1,
    exp: "βX is the universal compactification: every bounded continuous function on X extends uniquely to a continuous function on βX. This makes it the largest compactification." },
  { q: "In a metric space, a set is totally bounded if and only if:",
    opts: ["It is bounded","Every sequence has a Cauchy subsequence","For every ε > 0, it can be covered by finitely many ε-balls","It is compact"],
    ans: 2,
    exp: "Total boundedness means finite ε-nets exist for all ε > 0. Combined with completeness it characterises compactness: a complete metric space subset is compact iff totally bounded." },
  { q: "The fundamental group π₁(X, x₀) is trivial for which of the following spaces?",
    opts: ["The circle S¹","The torus T²","Euclidean space ℝⁿ","The figure-eight"],
    ans: 2,
    exp: "ℝⁿ is simply connected: every loop is contractible to a point, so π₁(ℝⁿ) = {e}. The circle has π₁ = ℤ, the torus ℤ², and the figure-eight the free group F₂." },
],

// ── Ch 4: Ordinary Differential Equations ────────────────────────────────────
4: [
  { q: "The method of Lyapunov functions proves asymptotic stability of an equilibrium x* if:",
    opts: ["A quadratic form V is positive definite and dV/dt ≤ 0","V is positive definite and dV/dt < 0 on a neighborhood of x*","V is negative definite along trajectories","The linearization has all eigenvalues with negative real part"],
    ans: 1,
    exp: "For asymptotic stability we need V > 0 and dV/dt < 0 (strictly negative definite) near x*. If only dV/dt ≤ 0, we get Lyapunov (not asymptotic) stability without LaSalle's invariance principle." },
  { q: "Floquet theory for periodic linear ODEs ẋ = A(t)x with A(t+T) = A(t) introduces the monodromy matrix M = Φ(T), where Φ is the fundamental matrix. Stability is determined by:",
    opts: ["Eigenvalues of A(0)","Trace of A(t)","Eigenvalues of M (Floquet multipliers)","The period T"],
    ans: 2,
    exp: "Floquet multipliers (eigenvalues of the monodromy matrix) determine stability: all |λ| < 1 → asymptotic stability; any |λ| > 1 → instability; on |λ| = 1 → Lyapunov stable or center." },
  { q: "Sturm-Liouville theory concerns the eigenvalue problem (p(x)y')' + (λw(x) - q(x))y = 0. Its eigenfunctions form:",
    opts: ["A finite orthogonal basis","A complete orthogonal basis in L²([a,b], w dx)","An orthonormal basis with w = 1 only","A basis only when p > 0 everywhere"],
    ans: 1,
    exp: "The Sturm-Liouville operator is self-adjoint in L²([a,b], w dx) with the weight function w. Its eigenfunctions are complete and orthogonal with respect to the weighted inner product." },
  { q: "Phase plane analysis of a 2D autonomous system finds that a critical point has Jacobian eigenvalues λ₁ = 2+3i, λ₂ = 2−3i. This point is:",
    opts: ["A stable spiral","A center","An unstable spiral","A saddle point"],
    ans: 2,
    exp: "Complex eigenvalues give spirals; the sign of the real part determines stability. Real part = 2 > 0 means trajectories spiral outward: unstable spiral (also called unstable focus)." },
],

// ── Ch 5: Linear Algebra ─────────────────────────────────────────────────────
5: [
  { q: "The singular value decomposition A = UΣVᵀ of an m×n matrix A relates to its eigendecomposition by the fact that the singular values are:",
    opts: ["Eigenvalues of A","Square roots of eigenvalues of AᵀA","Eigenvalues of AᵀA","Diagonal entries of A"],
    ans: 1,
    exp: "Singular values σᵢ = √λᵢ(AᵀA). The right singular vectors (columns of V) are eigenvectors of AᵀA; left singular vectors (U) are eigenvectors of AAᵀ." },
  { q: "The Cayley-Hamilton theorem states that for any n×n matrix A with characteristic polynomial p(λ) = det(λI - A):",
    opts: ["A has n distinct eigenvalues","p(A) = 0 (A satisfies its own characteristic equation)","Aⁿ = 0","The minimal polynomial equals p(λ)"],
    ans: 1,
    exp: "Every matrix satisfies its own characteristic equation p(A) = 0. This has computational uses (computing matrix inverses and powers) and theoretical uses (structure of the minimal polynomial)." },
  { q: "For a self-adjoint (Hermitian) linear operator T on a finite-dimensional inner product space, the spectral theorem guarantees:",
    opts: ["T has a unique eigenvalue","T is diagonalizable with real eigenvalues and orthonormal eigenvectors","T is invertible","All eigenvalues have absolute value 1"],
    ans: 1,
    exp: "The spectral theorem for Hermitian operators: all eigenvalues are real and eigenvectors for distinct eigenvalues are orthogonal, giving an orthonormal eigenbasis that diagonalizes T." },
  { q: "The Perron-Frobenius theorem applies to non-negative irreducible matrices and states that:",
    opts: ["All eigenvalues are positive","There is a unique largest real eigenvalue (Perron root) with a positive eigenvector","The matrix is diagonalizable","All eigenvalues have the same modulus"],
    ans: 1,
    exp: "Perron-Frobenius: a positive (irreducible non-negative) matrix has a simple largest positive eigenvalue ρ (Perron root) with a unique positive eigenvector. Critical in Markov chains and dynamical systems." },
],

// ── Ch 6: Topological Dynamics ───────────────────────────────────────────────
6: [
  { q: "A topological dynamical system (X, T) is called distal if:",
    opts: ["Every orbit is dense","inf_{n≥0} d(Tⁿx, Tⁿy) > 0 for all x ≠ y","T is an isometry","Every pair of points is proximal"],
    ans: 1,
    exp: "Distal means no two distinct points are proximal: their orbits never come arbitrarily close. Isometries are distal; the system has rich algebraic structure via the Ellis semigroup." },
  { q: "The Ellis semigroup E(X) of a compact topological dynamical system (X, T) is defined as:",
    opts: ["The group of homeomorphisms of X","The closure of {Tⁿ : n ∈ ℤ} in X^X with product topology","The group generated by T","The set of minimal idempotents"],
    ans: 1,
    exp: "E(X) is the closure of the orbit {Tⁿ} in the function space X^X under the product topology. It is a compact semigroup whose algebraic structure encodes the dynamics." },
  { q: "A point x in a topological dynamical system is called recurrent if:",
    opts: ["Its orbit is finite","It is a periodic point","x ∈ ω(x) (x is in its own omega-limit set)","T(x) = x"],
    ans: 2,
    exp: "Recurrent means x returns to any neighborhood infinitely often, equivalently x ∈ ω(x). Every point in a compact minimal system is recurrent (by the Birkhoff recurrence theorem)." },
  { q: "Auslander-Ellis theorem states that in any compact topological dynamical system (X, T):",
    opts: ["There exists a fixed point","There exists a minimal subsystem","T is uniquely ergodic","Every orbit is dense"],
    ans: 1,
    exp: "By Zorn's lemma, every compact dynamical system contains a minimal (T-invariant, closed, non-empty) subsystem. Every point in a minimal system is uniformly recurrent." },
],

// ── Ch 7: Ergodic Theory ─────────────────────────────────────────────────────
7: [
  { q: "The Mean Ergodic Theorem (von Neumann) states that for a unitary operator U on a Hilbert space H, the averages N⁻¹ Σ_{n=0}^{N-1} Uⁿf converge:",
    opts: ["Pointwise for all f ∈ H","In L² norm to the projection of f onto the fixed-point subspace","Only for f in a dense subspace","Uniformly in f on the unit ball"],
    ans: 1,
    exp: "Von Neumann's mean ergodic theorem: the ergodic averages converge in the Hilbert space norm to Pf, where P is the orthogonal projection onto {f : Uf = f}." },
  { q: "A measure-preserving system (X, μ, T) is ergodic if and only if the Koopman operator Uf = f∘T has:",
    opts: ["A dense set of eigenfunctions","Only constant functions as fixed points (eigenvalue 1 has multiplicity 1)","All eigenvalues on the unit circle","A spectral gap"],
    ans: 1,
    exp: "Ergodicity ↔ invariant functions are constant a.e. ↔ the eigenspace for eigenvalue 1 of the Koopman operator is one-dimensional (spanned by constants)." },
  { q: "The concept of mixing (strong mixing) for a measure-preserving system means:",
    opts: ["Time averages equal space averages","μ(T⁻ⁿA ∩ B) → μ(A)μ(B) for all measurable A, B","The system has positive entropy","Every orbit is dense"],
    ans: 1,
    exp: "Strong mixing: sets become asymptotically independent under iteration. This is strictly stronger than ergodicity (which only requires Cesàro convergence of μ(T⁻ⁿA ∩ B))." },
  { q: "Halmos-von Neumann theorem classifies ergodic systems with pure point spectrum. Such systems are:",
    opts: ["Isomorphic to a Bernoulli shift","Measure-theoretically isomorphic to a rotation on a compact abelian group","Always weakly mixing","Always strong mixing"],
    ans: 1,
    exp: "Pure point spectrum (all eigenfunctions span L²) characterizes isomorphism classes: these systems are exactly the compact group rotations (Kronecker systems), which are never mixing." },
],

// ── Ch 8: Stability Theory ───────────────────────────────────────────────────
8: [
  { q: "LaSalle's Invariance Principle extends Lyapunov stability to asymptotic stability when dV/dt ≤ 0. It concludes that trajectories converge to:",
    opts: ["The equilibrium directly","The largest invariant set contained in {x : dV/dt = 0}","The level set {V = c}","The boundary of the domain"],
    ans: 1,
    exp: "LaSalle: when V̇ ≤ 0 (not strictly negative), solutions converge to the largest T-invariant set in E = {V̇ = 0}. This handles cases like V̇ = 0 on a set rather than just at the equilibrium." },
  { q: "Hartman-Grobman theorem states that near a hyperbolic equilibrium x* of ẋ = f(x):",
    opts: ["The nonlinear system is globally topologically conjugate to its linearization","The flow is locally topologically conjugate to the linear flow ẋ = Df(x*)x","The system has a Lyapunov function equal to the quadratic form from Df","Stability is determined by the nonlinear terms"],
    ans: 1,
    exp: "Hartman-Grobman: near a hyperbolic fixed point (no eigenvalue with zero real part), the nonlinear flow is locally topologically conjugate (homeomorphic) to the linearization—the qualitative picture is the same." },
  { q: "Input-to-State Stability (ISS) of a control system ẋ = f(x,u) means:",
    opts: ["The system is stable with u = 0","The state x(t) is bounded by a KL function of x(0) plus a K function of sup|u|","The system has a quadratic Lyapunov function","All solutions converge to zero for any bounded input"],
    ans: 1,
    exp: "ISS: the state satisfies |x(t)| ≤ β(|x(0)|, t) + γ(||u||∞) with β a KL function and γ a class K function. This captures both stability (β → 0) and robustness to bounded disturbances." },
  { q: "A center manifold at a non-hyperbolic equilibrium captures dynamics corresponding to:",
    opts: ["Stable eigenvalues","Unstable eigenvalues","Eigenvalues with zero real part","All eigenvalues"],
    ans: 2,
    exp: "The center manifold is tangent to the center subspace (eigenvalues with Re(λ) = 0). Long-term dynamics of the full system are determined by the reduced dynamics on this manifold." },
],

// ── Ch 9: Hyperbolic Dynamics ────────────────────────────────────────────────
9: [
  { q: "The Shadowing Lemma for hyperbolic sets states that every δ-pseudo-orbit (with δ sufficiently small) is ε-shadowed by:",
    opts: ["A fixed point","A true orbit of the system","A periodic orbit","A dense orbit"],
    ans: 1,
    exp: "The shadowing lemma guarantees that any approximate orbit (pseudo-orbit) is uniformly tracked by a genuine orbit. This is crucial for the validity of numerical simulations in hyperbolic systems." },
  { q: "For an Anosov diffeomorphism T on a compact manifold, the stable and unstable foliations W^s, W^u are:",
    opts: ["Smooth foliations","Hölder continuous but not necessarily smooth","Only measurable","Defined only at periodic points"],
    ans: 1,
    exp: "Stable/unstable foliations of Anosov maps are Hölder continuous (in general) but typically not smooth, even though the individual leaves are smooth. This is a key subtlety in the theory." },
  { q: "The Bowen-Ruelle-Sinai (SRB) measure for a hyperbolic attractor is characterized by having:",
    opts: ["Zero Lyapunov exponents","Absolutely continuous conditional measures on unstable manifolds","Support on a smooth submanifold","Equal stable and unstable dimensions"],
    ans: 1,
    exp: "SRB measures have absolutely continuous conditional measures along unstable manifolds. They describe the statistics of typical orbits (w.r.t. Lebesgue measure) and satisfy Pesin's formula." },
  { q: "The spectral decomposition theorem for Axiom A diffeomorphisms decomposes the non-wandering set Ω into:",
    opts: ["A countable collection of fixed points","Finitely many disjoint T-invariant basic sets, each topologically transitive","A single transitive invariant set","The union of all periodic orbits"],
    ans: 1,
    exp: "Smale's spectral decomposition: Ω = Ω₁ ∪ … ∪ Ωₖ (finite, disjoint, invariant, locally maximal hyperbolic sets on each of which T is topologically transitive)." },
],

// ── Ch 10: Bifurcation Theory ────────────────────────────────────────────────
10: [
  { q: "In a saddle-node bifurcation (fold bifurcation), as the parameter crosses the bifurcation value:",
    opts: ["A stable and unstable equilibrium collide and disappear","A stable equilibrium splits into two","A limit cycle appears","The Jacobian eigenvalues cross the imaginary axis as complex pair"],
    ans: 0,
    exp: "Saddle-node: a stable and an unstable equilibrium approach each other as μ → μ_c, coalesce at μ = μ_c, and vanish for μ > μ_c (or vice versa). No equilibria exist on one side." },
  { q: "The Bogdanov-Takens bifurcation occurs when the Jacobian at equilibrium has:",
    opts: ["A pair of purely imaginary eigenvalues","A zero eigenvalue with algebraic multiplicity 1","A double zero eigenvalue (a Jordan block)","All eigenvalues with negative real parts"],
    ans: 2,
    exp: "Bogdanov-Takens: the Jacobian has eigenvalue 0 with algebraic multiplicity 2 (Jordan block 2×2). The unfolding generically contains saddle-node, Hopf, and homoclinic bifurcations." },
  { q: "A subcritical Hopf bifurcation differs from a supercritical one in that:",
    opts: ["The limit cycle exists after the bifurcation point","An unstable limit cycle shrinks to the equilibrium as the parameter reaches the critical value","The equilibrium remains stable after bifurcation","The bifurcation involves a zero eigenvalue"],
    ans: 1,
    exp: "Subcritical Hopf: an unstable limit cycle exists before bifurcation and shrinks onto the equilibrium at the critical parameter. After bifurcation, no small limit cycle exists—the system can jump to a distant attractor." },
  { q: "Period-doubling cascade to chaos (as studied by Feigenbaum) is a universal route with the convergence ratio of parameter intervals satisfying:",
    opts: ["δ = π","δ ≈ 4.669 (Feigenbaum constant)","δ = e","δ = 2"],
    ans: 1,
    exp: "Feigenbaum's constant δ ≈ 4.66920… is universal: consecutive period-doubling bifurcation parameter values satisfy (μₙ₊₁ − μₙ)/(μₙ₊₂ − μₙ₊₁) → δ for any smooth one-parameter family in this universality class." },
],

// ── Ch 11: Chaos Theory ──────────────────────────────────────────────────────
11: [
  { q: "Devaney's definition of chaos requires that a continuous map T: X → X be:",
    opts: ["Transitive, has dense periodic points, and depends sensitively on initial conditions","Topologically mixing and has positive topological entropy","Has positive Lyapunov exponents","Has a dense orbit and a fixed point"],
    ans: 0,
    exp: "Devaney chaos: (1) topological transitivity, (2) dense periodic points, (3) sensitive dependence. Banks et al. showed (3) follows from (1) and (2) for infinite spaces—sensitivity is redundant." },
  { q: "The Lorenz system ẋ = σ(y−x), ẏ = x(ρ−z)−y, ż = xy−βz has a strange attractor for σ=10, ρ=28, β=8/3. The attractor is:",
    opts: ["A fixed point","A periodic orbit","A fractal set with sensitive dependence","A 2-torus"],
    ans: 2,
    exp: "The Lorenz attractor is a strange attractor: a fractal invariant set on which dynamics are chaotic (sensitive dependence on initial conditions). It was the first rigorously studied strange attractor." },
  { q: "Melnikov's method detects transverse homoclinic intersections (and hence chaos via Smale-Birkhoff theorem) in near-integrable systems by computing:",
    opts: ["The Lyapunov exponent","An integral measuring the separation between stable and unstable manifolds","The topological entropy","The rotation number"],
    ans: 1,
    exp: "Melnikov's function M(t₀) = ∫ f ∧ g dt (wedge product of unperturbed and perturbation vector fields) measures the signed distance between the perturbed stable and unstable manifolds. A simple zero gives a transverse crossing." },
  { q: "In the logistic map xₙ₊₁ = rxₙ(1−xₙ), the value r = 4 produces dynamics with Lyapunov exponent:",
    opts: ["Negative, indicating stability","Zero, indicating neutral behavior","ln 2 ≈ 0.693 > 0, indicating chaos","Undefined"],
    ans: 2,
    exp: "At r = 4, the logistic map is conjugate to the angle-doubling map θ ↦ 2θ (mod 1), which has Lyapunov exponent ln 2. The map is fully chaotic on [0,1] with invariant measure μ = (π√(x(1-x)))⁻¹dx." },
],

// ── Ch 12: Symbolic Dynamics ─────────────────────────────────────────────────
12: [
  { q: "A subshift of finite type (SFT) is defined by forbidding a finite list of words. Its topological entropy equals:",
    opts: ["Zero always","The growth rate of the number of admissible words: log of the spectral radius of the adjacency matrix","The logarithm of the alphabet size","Infinity if the shift has fixed points"],
    ans: 1,
    exp: "For an SFT defined by a vertex or edge shift with adjacency matrix A, the topological entropy is log ρ(A), where ρ(A) is the spectral radius (Perron eigenvalue of A)." },
  { q: "The Zeta function of a subshift counts periodic orbits. For a subshift of finite type with adjacency matrix A:",
    opts: ["ζ(z) = exp(Σ (tr Aⁿ)/n · zⁿ)","ζ(z) = det(I − zA)","ζ(z) = 1/det(I − zA)","ζ(z) = log det(I + zA)"],
    ans: 2,
    exp: "The Artin-Mazur zeta function ζ(z) = exp(Σₙ |Fix Tⁿ| zⁿ/n). For SFTs, tr(Aⁿ) counts fixed points of Tⁿ, so ζ(z) = det(I − zA)⁻¹ (rational function)." },
  { q: "Two subshifts (X, σ) and (Y, σ) are conjugate (topologically isomorphic) if there exists a homeomorphism φ: X → Y such that:",
    opts: ["φ commutes with σ (φ ∘ σ = σ ∘ φ)","φ maps periodic orbits to periodic orbits","φ is a sliding block code","φ preserves entropy"],
    ans: 0,
    exp: "Conjugacy in symbolic dynamics: a bijective sliding block code φ with σ ∘ φ = φ ∘ σ. By Curtis-Lyndon-Hedlund theorem, every continuous shift-commuting map between subshifts is a sliding block code." },
  { q: "The Golden Mean shift is the subshift on {0,1}^ℤ that forbids the word '11'. Its entropy is:",
    opts: ["log 2","log φ where φ = (1+√5)/2 (the golden ratio)","0","1"],
    ans: 1,
    exp: "The Golden Mean shift has adjacency matrix [[1,1],[1,0]] with Perron eigenvalue φ = (1+√5)/2. Entropy = log φ ≈ 0.481. The number of admissible words of length n grows as φⁿ." },
],

// ── Ch 13: Complex Dynamics ──────────────────────────────────────────────────
13: [
  { q: "The Julia set J(f) of a rational map f: ℂ̂ → ℂ̂ is equivalently defined as the closure of the set of:",
    opts: ["Attracting periodic points","Repelling periodic points","Neutral periodic points","Critical points"],
    ans: 1,
    exp: "A fundamental theorem: J(f) equals the closure of the set of repelling periodic points. This characterization (due to Julia and Fatou) shows J(f) is non-empty for deg(f) ≥ 2." },
  { q: "For the quadratic family f_c(z) = z² + c, the Mandelbrot set M is defined as:",
    opts: ["The set of c for which |fₙ(0)| → ∞","The set of c for which the orbit of 0 is bounded","The set of c for which J(f_c) is connected","B and C are equivalent characterizations"],
    ans: 3,
    exp: "Both definitions coincide: c ∈ M ↔ the orbit of the critical point 0 is bounded ↔ J(f_c) is connected. This is the Böttcher-Fatou theorem connecting the Mandelbrot set to Julia set topology." },
  { q: "The Böttcher coordinate near an attracting fixed point 0 of f(z) = λz + … with |λ| < 1 linearizes f to:",
    opts: ["z ↦ λz","z ↦ z²","z ↦ z + 1","z ↦ e^z"],
    ans: 0,
    exp: "Koenigs linearization theorem: near an attracting fixed point with multiplier λ (0 < |λ| < 1), f is locally analytically conjugate to z ↦ λz. (Böttcher coordinates apply near superattracting fixed points.)" },
  { q: "Montel's theorem, which is fundamental in complex dynamics, states that a family of holomorphic functions is normal (has a locally uniformly convergent subsequence) if:",
    opts: ["The functions are uniformly bounded","The functions omit two distinct values in ℂ","The functions have uniformly bounded derivative","The functions are injective"],
    ans: 1,
    exp: "Montel's theorem (great Picard + normal families): a family omitting two fixed values in ℂ is normal. This is used to show the Fatou set is the maximal domain of normality of the family {fⁿ}." },
],

// ── Ch 14: Hamiltonian Systems ───────────────────────────────────────────────
14: [
  { q: "Noether's theorem in Hamiltonian mechanics states that every continuous symmetry of the action corresponds to:",
    opts: ["A conserved quantity (first integral)","A periodic orbit","An integrable subsystem","A Lyapunov stable equilibrium"],
    ans: 0,
    exp: "Noether's theorem: continuous symmetry ↔ conservation law. Time-translation symmetry → energy conservation; rotational symmetry → angular momentum conservation; etc." },
  { q: "The KAM (Kolmogorov-Arnold-Moser) theorem guarantees persistence of quasi-periodic invariant tori in near-integrable Hamiltonian systems when the frequency vector ω satisfies:",
    opts: ["ω is rational","ω satisfies a Diophantine condition |k·ω| ≥ γ|k|⁻τ for all k ∈ ℤⁿ\\{0}","ω has all components equal","ω is periodic"],
    ans: 1,
    exp: "KAM tori persist for Diophantine frequency vectors (small divisors controlled by γ and τ). Resonant (rational ω) and Liouville tori are destroyed. The measure of surviving tori is large for small perturbations." },
  { q: "The Arnold web in a multi-dimensional near-integrable Hamiltonian system refers to:",
    opts: ["The collection of all KAM tori","The network of resonance zones that can facilitate Arnold diffusion","The stable/unstable manifolds of hyperbolic tori","The Poincaré return map"],
    ans: 1,
    exp: "The Arnold web is the web of resonances in action space. Arnold diffusion is the slow drift of orbits along this web, which is the generic mechanism for global instability in systems with ≥ 2.5 degrees of freedom." },
  { q: "For a completely integrable Hamiltonian system with n degrees of freedom and n commuting first integrals, the Arnold-Liouville theorem states that compact connected level sets of the integrals are:",
    opts: ["Points","Circles","n-dimensional tori on which the motion is quasi-periodic","(2n-1)-dimensional hypersurfaces"],
    ans: 2,
    exp: "Arnold-Liouville: n commuting integrals in involution on a 2n-dimensional phase space, if the common level set is compact and connected, it is an n-torus carrying linear (quasi-periodic) flow." },
],

// ── Ch 15: Infinite-Dimensional Dynamics ────────────────────────────────────
15: [
  { q: "A global attractor for a dissipative PDE is characterized by being:",
    opts: ["A periodic orbit","The compact invariant set that attracts all bounded sets","An equilibrium solution","The set of all stationary solutions"],
    ans: 1,
    exp: "The global attractor is the unique compact, invariant, maximal attracting set. Its finite Hausdorff (and fractal) dimension reflects effective finite-dimensional reduction of the infinite-dimensional dynamics." },
  { q: "Inertial manifolds for dissipative PDEs are finite-dimensional invariant manifolds that:",
    opts: ["Contain only equilibria","Attract all solutions exponentially and contain the global attractor","Are spanned by unstable modes only","Have the same dimension as the phase space"],
    ans: 1,
    exp: "An inertial manifold M is finite-dimensional, invariant, and exponentially attracting: every solution approaches M at exponential rate. The global attractor lies in M, yielding a finite-dimensional ODE (the inertial form) governing long-time behavior." },
  { q: "The Kuramoto-Sivashinsky equation ut + uuₓ + uₓₓ + uₓₓₓₓ = 0 is important in infinite-dimensional dynamics because:",
    opts: ["It is completely integrable","It is a linearizable PDE","It has a finite-dimensional global attractor despite being an infinite-dimensional system","It has no bounded solutions"],
    ans: 2,
    exp: "The KS equation is a canonical example of a dissipative PDE with chaotic spatiotemporal dynamics. It has a finite-dimensional global attractor and is used to study turbulence, flame propagation, and spatiotemporal chaos." },
  { q: "The concept of a Lyapunov exponent generalizes to infinite-dimensional systems via the Oseledets multiplicative ergodic theorem, which guarantees:",
    opts: ["Finitely many Lyapunov exponents equal to the dimension of the attractor","A discrete spectrum of Lyapunov exponents for the linearized cocycle over an ergodic measure","Positive entropy for all PDEs","Uniform hyperbolicity of the global attractor"],
    ans: 1,
    exp: "Oseledets MET applies to measurable cocycles over ergodic systems, giving a splitting of the tangent space into Oseledets subspaces with well-defined exponential growth rates (Lyapunov exponents)." },
],

// ── Ch 16: Classical Information Theory ──────────────────────────────────────
16: [
  { q: "The channel capacity C of a discrete memoryless channel (DMC) is defined as:",
    opts: ["The maximum entropy of the output","C = max_{p(x)} I(X;Y) over all input distributions p(x)","The average mutual information","The entropy of the channel noise"],
    ans: 1,
    exp: "Shannon's channel capacity is the maximum mutual information over all input distributions. Shannon's channel coding theorem states reliable communication at rate R is possible iff R < C." },
  { q: "For a Gaussian channel Y = X + Z with Z ~ N(0, N) and power constraint E[X²] ≤ P, the capacity is:",
    opts: ["log(P/N)","½ log(1 + P/N)","log(1 + P/N)","½ log(P/N)"],
    ans: 1,
    exp: "Shannon's AWGN capacity formula: C = ½ log₂(1 + SNR) bits per channel use, where SNR = P/N. The ½ comes from the differential entropy formula h(X) = ½ log(2πeσ²) for Gaussian X." },
  { q: "The source coding theorem (Shannon's first theorem) states that a source with entropy H can be compressed to an average code length arbitrarily close to:",
    opts: ["0","H bits per symbol (and no less)","1 bit per symbol","log|A| bits per symbol where |A| is the alphabet size"],
    ans: 1,
    exp: "Shannon's source coding theorem: the minimum average description length per symbol approaches H(X) bits. Any lossless code requires average length ≥ H(X), and Huffman codes achieve lengths < H(X) + 1." },
  { q: "The entropy H(X) = −Σ p(x) log p(x) achieves its maximum value of log|A| when:",
    opts: ["p(x) = 1 for one x","X is concentrated on a small set","p(x) = 1/|A| for all x (uniform distribution)","The distribution is Gaussian"],
    ans: 2,
    exp: "Entropy is maximized by the uniform distribution: H(X) ≤ log|A| with equality iff p is uniform. This characterizes the uniform distribution as the maximum uncertainty distribution over a finite alphabet." },
],

// ── Ch 17: Entropy Generalizations ───────────────────────────────────────────
17: [
  { q: "The Rényi entropy of order α is defined as H_α(X) = (1−α)⁻¹ log Σ p(x)^α. As α → 1, this converges to:",
    opts: ["0","The min-entropy H_∞","The Shannon entropy H(X)","The max-entropy log|A|"],
    ans: 2,
    exp: "By L'Hôpital's rule, lim_{α→1} H_α(X) = −Σ p(x) log p(x) = H(X). So Shannon entropy is the special case α = 1. Rényi entropies form a monotone family: H_α ≥ H_β for α ≤ β." },
  { q: "The relative entropy (KL divergence) D(P||Q) = Σ p log(p/q) satisfies which fundamental inequality?",
    opts: ["D(P||Q) ≤ 0 always","D(P||Q) ≥ 0 with equality iff P = Q (Gibbs' inequality)","D(P||Q) = D(Q||P)","D(P||Q) ≤ H(P)"],
    ans: 1,
    exp: "Gibbs' inequality / non-negativity of KL: D(P||Q) ≥ 0 with equality iff P = Q a.e. This follows from the log-sum inequality and is the fundamental fact from which many information inequalities derive." },
  { q: "The Tsallis entropy S_q = (1 − Σ pᵢ^q)/(q−1) was introduced in statistical mechanics. As q → 1, it approaches:",
    opts: ["0","Boltzmann-Gibbs entropy −Σ pᵢ ln pᵢ","Max-entropy","Rényi entropy of order 2"],
    ans: 1,
    exp: "Tsallis entropy is a one-parameter family generalizing Boltzmann-Gibbs entropy, which it recovers in the limit q → 1. It is non-extensive and used in anomalous statistical systems." },
  { q: "The differential entropy h(X) = −∫ f(x) log f(x) dx for a continuous random variable differs from discrete entropy in that:",
    opts: ["It is always positive","It is invariant under invertible transformations","It can be negative and is not invariant under non-linear reparametrization (but changes by log|J| under linear maps)","It equals H(X) when X is quantized"],
    ans: 2,
    exp: "Differential entropy can be negative (e.g., Uniform[0, ε] for small ε). Under y = ax, h(Y) = h(X) + log|a|. It lacks the operational meaning of discrete entropy without conditioning on a resolution." },
],

// ── Ch 18: Algorithmic Information Theory ────────────────────────────────────
18: [
  { q: "The Kolmogorov complexity K(x) of a string x is defined as the length of the shortest program for a universal Turing machine that outputs x. K(x) is:",
    opts: ["Computable","Upper semi-computable (can be approximated from above)","Lower semi-computable (can be approximated from below)","Both computable and bounded by |x|"],
    ans: 1,
    exp: "K(x) is upper semi-computable: we can enumerate all programs and their outputs, so K(x) ≤ some d we discover. But K(x) is not computable—the minimal-length program cannot be found in general." },
  { q: "Martin-Löf randomness for an infinite sequence x ∈ {0,1}^ω is defined using effective null sets. Equivalently, x is Martin-Löf random iff:",
    opts: ["x has no computable subsequences","The prefix-free complexity K(xₙ) of the first n bits satisfies K(xₙ) ≥ n − O(1)","x is generated by a fair coin","The frequency of 1s converges to 1/2"],
    ans: 1,
    exp: "By the Schnorr-Levin theorem, Martin-Löf randomness ↔ K(xₙ) ≥ n − c for some constant c (all n). Sequences failing this have compressible initial segments and are non-random." },
  { q: "Solomonoff's universal prior m(x) = Σ_{U(p)=x} 2^{-|p|} (sum over programs p whose output starts with x) is important because:",
    opts: ["It is a computable probability distribution","It dominates every computable prior up to a multiplicative constant","It equals the Shannon measure on strings","It is the unique maximum entropy distribution"],
    ans: 1,
    exp: "Solomonoff's prior m is a semi-measure that dominates all computable semi-measures: for every computable semi-measure μ, m(x) ≥ c_μ · μ(x). This makes it the ideal Bayesian prior for induction." },
  { q: "The symmetry of information in Kolmogorov complexity states:",
    opts: ["K(x) = K(y) for all x, y of the same length","K(x, y) = K(x) + K(y|x) + O(log(|x|+|y|)) = K(y) + K(x|y) + O(log)","K(x|y) = K(y|x) always","K(xy) ≤ K(x) + K(y)"],
    ans: 1,
    exp: "Symmetry of information: K(x,y) = K(x) + K(y|x) + O(log n) = K(y) + K(x|y) + O(log n). This is an analogue of the chain rule for entropy, but with a logarithmic error term inherent to the theory." },
],

// ── Ch 19: Network Information Theory ────────────────────────────────────────
19: [
  { q: "In a multiple access channel (MAC) with two senders, the capacity region is:",
    opts: ["A single point","A triangle in (R₁, R₂) space","A pentagon characterized by conditions R₁ ≤ I(X₁;Y|X₂), R₂ ≤ I(X₂;Y|X₁), R₁+R₂ ≤ I(X₁,X₂;Y)","A square R₁ ≤ C₁, R₂ ≤ C₂"],
    ans: 2,
    exp: "The MAC capacity region is a convex pentagon bounded by three mutual information constraints. Superposition coding and successive cancellation decoding achieve the corner points of this region." },
  { q: "The broadcast channel capacity (one sender, multiple receivers) is in general:",
    opts: ["Completely solved by superposition coding","Not fully characterized; only special cases are known","Given by the min of individual channel capacities","Equal to the MAC capacity by duality"],
    ans: 1,
    exp: "The general broadcast channel capacity is a long-standing open problem. Only degraded, less noisy, and a few other special cases have complete capacity characterizations. Superposition coding is optimal for degraded broadcast channels." },
  { q: "The cut-set bound for a general relay network states that for any cut (S, Sᶜ) separating source from destination, the rate R satisfies:",
    opts: ["R ≤ max over cuts of I(X_S; Y_Sᶜ | X_Sᶜ)","R ≤ min over cuts of I(X_S; Y_Sᶜ | X_Sᶜ)","R ≤ Σ capacities of individual links","R ≤ H(Y_destination)"],
    ans: 1,
    exp: "The cut-set bound is the min over all cuts of the conditional mutual information across the cut. It is an upper bound on achievable rates and is tight for some network topologies (e.g., degraded relay channels)." },
  { q: "The capacity of a relay channel (source → relay → destination with direct link) under the decode-and-forward strategy is:",
    opts: ["min(I(X;Y_R), I(X,X_R;Y))","I(X;Y) with no relay","max(I(X;Y_R|X_R), I(X_R;Y))","I(X;Y) + I(X_R;Y)"],
    ans: 0,
    exp: "Decode-and-forward capacity: min(I(X;Y_R), I(X,X_R;Y))—the relay must decode the source message, then the source and relay cooperate. Cover and El Gamal proved this achieves capacity for degraded relay channels." },
],

// ── Ch 20: Information Geometry ───────────────────────────────────────────────
20: [
  { q: "The Fisher information metric g_{ij}(θ) = E[(∂ log p/∂θᵢ)(∂ log p/∂θⱼ)] is a Riemannian metric on the statistical manifold. It is important because:",
    opts: ["It gives the fastest algorithm","It is invariant under sufficient statistics (reparametrizations induced by sufficient statistics leave it invariant)","It equals the KL divergence","It is always flat"],
    ans: 1,
    exp: "The Fisher metric is the unique (up to scaling) Riemannian metric invariant under sufficient statistics (Chentsov's theorem). It is the natural intrinsic geometry on a statistical manifold." },
  { q: "In the dually flat geometry of an exponential family, the e-geodesics and m-geodesics are related to which pair of divergences?",
    opts: ["L² distance and KL divergence","KL divergence D(P||Q) and its reverse D(Q||P)","Shannon entropy and cross-entropy","Rényi divergence and Tsallis divergence"],
    ans: 1,
    exp: "In the Amari dual geometry: e-geodesics are projections with respect to D(·||Q) (KL), m-geodesics with respect to D(P||·). The Pythagorean theorem holds for orthogonal e/m projections." },
  { q: "The Cramér-Rao lower bound states that for any unbiased estimator θ̂ of θ:",
    opts: ["Var(θ̂) ≥ 1/n","Var(θ̂) ≥ 1/I(θ) where I(θ) is the Fisher information","Var(θ̂) ≥ H(θ)","Var(θ̂) ≥ E[θ²] − E[θ]²"],
    ans: 1,
    exp: "Cramér-Rao: Var(θ̂) ≥ I(θ)⁻¹ where I(θ) is the Fisher information (scalar case). For n i.i.d. samples, Var(θ̂) ≥ 1/(n·I(θ)). The MLE achieves this bound asymptotically." },
  { q: "Natural gradient descent, introduced by Amari, uses the update rule θ ← θ − η G⁻¹(θ) ∇L(θ), where G is the Fisher information matrix. Its advantage over standard gradient descent is:",
    opts: ["It always converges faster","It is parametrization invariant—the update direction is the steepest descent in the intrinsic geometry of the model","It requires fewer hyperparameters","It avoids saddle points"],
    ans: 1,
    exp: "Natural gradient descent is invariant under reparametrization of the model, unlike standard gradient descent. It follows the steepest descent direction in the Riemannian geometry defined by the Fisher metric." },
],

// ── Ch 21: Quantum Information Theory ────────────────────────────────────────
21: [
  { q: "The no-cloning theorem in quantum information states that:",
    opts: ["Quantum states cannot be teleported","There is no unitary operation that perfectly copies an arbitrary unknown quantum state","Quantum computation is slower than classical","Entanglement cannot be created"],
    ans: 1,
    exp: "No-cloning: there is no unitary U such that U|ψ⟩|0⟩ = |ψ⟩|ψ⟩ for all |ψ⟩. This distinguishes quantum from classical information and is why quantum cryptography can detect eavesdroppers." },
  { q: "The quantum channel capacity Q (for transmitting quantum information reliably) satisfies:",
    opts: ["Q = log₂(dim H)","Q is determined by the coherent information I_c(ρ, N) = S(N(ρ)) − S(N ⊗ I(|ψ⟩⟨ψ|))","Q equals the classical capacity C","Q is always greater than the entanglement-assisted capacity"],
    ans: 1,
    exp: "Quantum channel capacity is given by the regularized coherent information: Q = lim (1/n) max_ρ I_c(ρ, N^⊗n). Unlike the classical case, a single-letter formula is not always achievable due to superadditivity." },
  { q: "Bennett-Brassard-Wiesner dense coding allows transmission of 2 classical bits using:",
    opts: ["2 qubits and no entanglement","1 qubit and 1 pre-shared EPR pair","2 EPR pairs","1 qubit with no entanglement"],
    ans: 1,
    exp: "Superdense coding: Alice encodes 2 bits by applying one of 4 Pauli operations to her half of a shared EPR pair, then sends 1 qubit to Bob, who measures the pair. This doubles classical capacity via entanglement." },
  { q: "The quantum teleportation protocol transmits one qubit of quantum information using:",
    opts: ["2 classical bits and 1 EPR pair","1 qubit and 1 classical bit","3 EPR pairs","No classical communication"],
    ans: 0,
    exp: "Quantum teleportation: Alice shares an EPR pair with Bob, measures her qubit and her half of the EPR pair (2 bits outcome), sends 2 classical bits to Bob, who applies a correction. Net: 1 qubit teleported using 2 cbits + 1 ebit." },
],

// ── Ch 22: Entropy in Dynamical Systems ──────────────────────────────────────
22: [
  { q: "The Abramov formula relates the entropy of a flow to the entropy of its time-one map and the roof function. For a suspension flow over (X, T, μ) with constant roof function r:",
    opts: ["h(flow) = h(T) + r","h(flow) = h(T)/r","h(flow) = r·h(T)","h(flow) = h(T)"],
    ans: 1,
    exp: "Abramov's theorem: for a suspension flow with integrable roof function r, h(φ_t) = h(T) / ∫r dμ. For constant roof r, this gives h = h(T)/r—entropy scales inversely with the suspension height." },
  { q: "Entropy is an isomorphism invariant in ergodic theory. Two Bernoulli shifts with different entropies are:",
    opts: ["Always conjugate","Never conjugate as measure-preserving systems","Conjugate only if they have the same alphabet","Conjugate if they have the same period"],
    ans: 1,
    exp: "By Kolmogorov's theorem (and earlier observations), entropy is a measurable conjugacy invariant. Ornstein's theorem (1970) strengthened this: Bernoulli shifts are isomorphic if and only if they have the same entropy." },
  { q: "The Pesin entropy formula for a C¹⁺α diffeomorphism preserving a measure μ absolutely continuous w.r.t. Lebesgue states:",
    opts: ["h_μ(T) = 0","h_μ(T) = Σ max(λᵢ, 0) (sum of positive Lyapunov exponents)","h_μ(T) = |Σ λᵢ|","h_μ(T) = max λᵢ"],
    ans: 1,
    exp: "Pesin's formula: for SRB measures (absolutely continuous conditionals on unstable manifolds), h_μ(T) = ∫ Σ⁺ λᵢ dμ. Combined with Margulis-Ruelle inequality (h ≤ Σ⁺ λᵢ for any invariant μ), it characterizes SRB measures." },
  { q: "The variational principle for topological entropy states:",
    opts: ["h_top(T) = sup over all invariant measures of h_μ(T)","h_top(T) = inf over all invariant measures of h_μ(T)","h_top(T) = h_μ(T) for any ergodic μ","h_top(T) equals the Hausdorff dimension of X"],
    ans: 0,
    exp: "The variational principle: topological entropy equals the supremum of measure-theoretic entropies over all invariant probability measures. Measures achieving this supremum are called measures of maximal entropy." },
],

// ── Ch 23: Ergodic Information Theory ────────────────────────────────────────
23: [
  { q: "The Shannon-McMillan-Breiman (SMB) theorem states that for an ergodic stationary source with entropy rate H, the probability of a typical sequence xⁿ satisfies:",
    opts: ["P(xⁿ) → H","−(1/n) log P(xⁿ) → H almost surely","P(xⁿ) = 2^{−nH} exactly","All sequences have equal probability in the limit"],
    ans: 1,
    exp: "SMB (Asymptotic Equipartition Property for ergodic sources): −(1/n) log P(X₁…Xₙ) → H(X) a.s. The 'typical set' of ≈ 2^{nH} sequences accounts for nearly all probability." },
  { q: "The entropy rate of a stationary stochastic process {Xₙ} can be computed as:",
    opts: ["H(X₁)","lim_{n→∞} H(Xₙ|X₁,...,Xₙ₋₁) = lim H(X₁,...,Xₙ)/n","H(X₁,X₂,...) / lim n","lim sup H(Xₙ)"],
    ans: 1,
    exp: "For a stationary process, the entropy rate H̄ = lim_{n→∞} H(Xₙ|X₁,...,Xₙ₋₁). This limit exists by stationarity. Also H̄ = lim_{n→∞} H(X₁,...,Xₙ)/n (both limits exist and are equal)." },
  { q: "Ziv-Lempel complexity (used in LZ77/LZ78 compression) is related to entropy by the fact that:",
    opts: ["It equals H exactly for all sequences","The LZ complexity rate converges to H for stationary ergodic sources","LZ complexity equals Kolmogorov complexity","It is always less than H"],
    ans: 1,
    exp: "Ziv-Lempel theorem: for ergodic stationary sources, the compression ratio of the LZ algorithm converges a.s. to the entropy rate H. This makes LZ-based algorithms asymptotically optimal." },
  { q: "Predictive coding and the entropy rate are connected through the fact that the optimal predictor of Xₙ given X₁,...,Xₙ₋₁ achieves an average log-loss of:",
    opts: ["0","H(X₁)","H̄ (the entropy rate) in the limit","H(Xₙ) − H(Xₙ₋₁)"],
    ans: 2,
    exp: "The conditional entropy H(Xₙ|X₁,...,Xₙ₋₁) → H̄ for stationary ergodic processes. The optimal predictor's log-loss equals the conditional entropy, so long-run prediction difficulty equals the entropy rate." },
],

// ── Ch 24: Symbolic Dynamics and Information ──────────────────────────────────
24: [
  { q: "The topological entropy of the full shift on k symbols equals:",
    opts: ["0","k","log k","log₂ k bits (or ln k nats depending on log base)"],
    ans: 2,
    exp: "The full shift has exactly kⁿ words of length n, so h_top = lim (1/n) log kⁿ = log k. This is also the entropy of the i.i.d. uniform measure on the shift, which is the unique measure of maximal entropy." },
  { q: "A sofic shift is defined as the image of a subshift of finite type under a factor map (sliding block code). Every SFT is sofic, but sofic shifts can have:",
    opts: ["Higher entropy than any SFT","Non-integer topological entropy that equals log of an algebraic integer","Irrational topological entropy","Zero topological entropy only"],
    ans: 1,
    exp: "Sofic shifts have topological entropy = log of an algebraic integer (Perron eigenvalue of some non-negative integer matrix). Every SFT is sofic, but the class is strictly larger; sofic shifts include edge shifts of labeled graphs." },
  { q: "The Parry measure (measure of maximal entropy) for an irreducible SFT with adjacency matrix A assigns to each cylinder set a probability determined by:",
    opts: ["The uniform distribution on words","Left and right Perron eigenvectors of A","The unique stationary distribution of the Markov chain","The square root of each entry of A"],
    ans: 1,
    exp: "The Parry measure is the unique measure of maximal entropy for an irreducible SFT. It is the Markov measure with transition probabilities Pᵢⱼ = Aᵢⱼ vⱼ/(ρ vᵢ), where ρ = spectral radius and u, v are Perron eigenvectors." },
  { q: "The Morse sequence (0 1 1 0 1 0 0 1 …) generated by the substitution 0↦01, 1↦10 is a fixed point of the substitution and serves as an example of:",
    opts: ["A periodic sequence","A Bernoulli sequence","A minimal, almost periodic sequence that is not periodic","A Markov chain"],
    ans: 2,
    exp: "The Thue-Morse sequence (Morse sequence) is uniformly recurrent (almost periodic) and minimal but not periodic. Its complexity function p(n) = O(n), entropy 0, and it arises naturally in number theory and combinatorics on words." },
],

// ── Ch 25: Chaos, Randomness, Computation ────────────────────────────────────
25: [
  { q: "Pseudo-random number generators (PRNGs) based on chaotic maps use the property that chaotic maps:",
    opts: ["Have rational orbits","Are sensitive to initial conditions, mixing information quickly","Are linear","Have periodic orbits only"],
    ans: 1,
    exp: "Chaotic maps (logistic map, tent map, etc.) are sensitive to initial conditions and mix information rapidly. They can be used as PRNGs, though cryptographic security requires additional analysis of the unpredictability relative to polynomial-time adversaries." },
  { q: "The Chaitin-Kolmogorov notion of a random sequence is related to Lyapunov exponents by the observation that:",
    opts: ["Positive Lyapunov exponents imply Martin-Löf randomness of all orbits","The symbolic sequence generated by a uniformly hyperbolic system with positive entropy can be Martin-Löf random relative to the computable measure","Zero entropy implies computable orbits","Lyapunov exponents determine Kolmogorov complexity exactly"],
    ans: 1,
    exp: "For hyperbolic systems with positive entropy, the symbolic coding of a generic orbit is algorithmically random (relative to the natural invariant measure). This connects dynamical randomness to algorithmic randomness." },
  { q: "The notion of computational universality in cellular automata (e.g., Rule 110) relates to dynamical systems because:",
    opts: ["All cellular automata are universal","A CA that can simulate any Turing machine must exhibit complex dynamics (not periodic or eventually periodic)","Universal CAs are always chaotic in the topological sense","Universal CAs have zero entropy"],
    ans: 1,
    exp: "Computational universality implies undecidability of the halting problem for configurations, which requires complex (non-periodic, non-quiescent) orbits. Rule 110's universality (proven by Cook) makes many properties of its dynamics undecidable." },
  { q: "The Kolmogorov-Smirnov test for randomness checks whether a sample comes from a hypothesized distribution by comparing:",
    opts: ["The mean and variance to theoretical values","The empirical CDF to the theoretical CDF, bounding the supremum norm","The entropy of the sample to the theoretical entropy","The autocorrelation function"],
    ans: 1,
    exp: "The KS test uses the supremum norm ||F_n − F||_∞ between empirical and theoretical CDFs. By the Glivenko-Cantelli theorem, this converges to 0 a.s. for i.i.d. samples from F." },
],

// ── Ch 26: Information Methods in CS ─────────────────────────────────────────
26: [
  { q: "The information-theoretic lower bound for comparison-based sorting proves that any sorting algorithm requires at least:",
    opts: ["n comparisons","n log n comparisons asymptotically","n² comparisons","log(n!) = Θ(n log n) comparisons"],
    ans: 3,
    exp: "There are n! permutations to distinguish. Each comparison gives 1 bit, so at least log₂(n!) = Θ(n log n) comparisons are needed. This matches the upper bound of merge sort, proving it is optimal asymptotically." },
  { q: "Shannon entropy is used in decision tree learning (e.g., ID3 algorithm) to select features by maximizing:",
    opts: ["The gain in variance","Information gain = H(Y) − H(Y|X) (reduction in label entropy after observing feature X)","The mutual information I(X;X) between features","The conditional entropy H(X|Y)"],
    ans: 1,
    exp: "Information gain measures how much knowing feature X reduces uncertainty about label Y: IG(Y;X) = H(Y) − H(Y|X) = I(X;Y). ID3 greedily selects the feature with highest information gain at each node." },
  { q: "The min-entropy H_∞(X) = −log max_x P(X=x) is relevant in cryptography because:",
    opts: ["It equals the Shannon entropy for uniform distributions","It is an upper bound on the probability that an adversary correctly guesses X in one try","A distribution with high H_∞ is hard to predict: the best single-guess success probability is 2^{−H_∞}","All of the above"],
    ans: 3,
    exp: "All are correct: H_∞ = H_1 (Shannon entropy at uniform), and the optimal one-guess success probability is max P(X=x) = 2^{−H_∞}, so high min-entropy ↔ low guessing probability. Min-entropy is the right notion of randomness for cryptography." },
  { q: "The Chernoff bound provides exponential concentration for sums of independent random variables. For a sum S = X₁+…+Xₙ with E[S] = μ, it states P(S ≥ (1+δ)μ) ≤:",
    opts: ["1/(δ²n)","e^{−μδ²/3} for δ ∈ (0,1)","e^{−μδ}","1/√n"],
    ans: 1,
    exp: "The Chernoff bound: P(S ≥ (1+δ)μ) ≤ (e^δ/(1+δ)^{1+δ})^μ ≤ e^{−μδ²/3} for δ ∈ (0,1). This exponential decay (vs. polynomial for Chebyshev) makes Chernoff bounds much tighter for algorithms analysis." },
],

// ── Ch 27: Computability and Dynamics ────────────────────────────────────────
27: [
  { q: "The orbit problem for linear maps (given rational matrix A and rational vectors x, y, does Aⁿx = y for some n?) is:",
    opts: ["Decidable in polynomial time","Decidable but PSPACE-hard","Decidable for 2×2 matrices but open for higher dimensions","Undecidable in general"],
    ans: 2,
    exp: "The orbit problem for 2×2 matrices is decidable (Kannan-Lipton). For 3×3 it is open, and for sufficiently large matrices it is undecidable. This connects computational complexity to algebraic number theory." },
  { q: "The halting problem for cellular automata (does a given CA eventually reach an all-zero configuration from a given initial state?) is:",
    opts: ["Always decidable","Undecidable in general (for 2D or sufficiently complex 1D CAs)","Decidable for 1D CAs","Decidable if the CA is reversible"],
    ans: 1,
    exp: "The quiescence problem for cellular automata is undecidable by reduction from the halting problem of Turing machines, since CAs can simulate TMs. Even simple-looking CAs (like Rule 110) are computationally universal." },
  { q: "A computable real number x ∈ [0,1] is one for which:",
    opts: ["x is rational","There exists a Turing machine that outputs the n-th binary digit of x for each input n","x is algebraic","The binary expansion of x has a period"],
    ans: 1,
    exp: "Computable reals: x is computable if a TM can output any finite approximation to arbitrary precision—equivalently, the sequence of rational approximations is recursively enumerable and converges effectively." },
  { q: "Rice's theorem in computability theory states that for any non-trivial semantic property P of partial recursive functions:",
    opts: ["P is decidable","P is co-recursively enumerable","P is undecidable","P is NP-complete"],
    ans: 2,
    exp: "Rice's theorem: every non-trivial property of the function computed by a program (not the program itself) is undecidable. This is a sweeping undecidability result; almost everything you want to verify about program behavior is undecidable." },
],

// ── Ch 28: Category Theory and Dynamics ──────────────────────────────────────
28: [
  { q: "A coalgebra for an endofunctor F: C → C is a pair (X, α: X → F(X)). In dynamical systems, coalgebras model:",
    opts: ["Initial algebras","Systems with state-transition structure: X is the state space, α is the dynamics","Fixed points only","Invariant measures"],
    ans: 1,
    exp: "Coalgebras capture transition systems: the map α: X → FX describes how the state evolves. For F = (−)×A (A an action set), FX = X×A, and (X, α) is a labeled transition system. Terminal coalgebras represent bisimilarity." },
  { q: "The category of measure-preserving dynamical systems (X, μ, T) has morphisms given by:",
    opts: ["Continuous maps","Measurable maps φ: X → Y such that φ∘T = S∘φ and φ_*μ = ν (factor maps)","Isometries","Group homomorphisms"],
    ans: 1,
    exp: "Morphisms in the ergodic theory category are measure-theoretic factor maps: measurable maps that intertwine the dynamics and push forward the measure. Isomorphisms (invertible factor maps) are the measurable conjugacies." },
  { q: "The Giry monad in categorical probability associates to each measurable space X the space GX of probability measures on X. It models:",
    opts: ["Deterministic dynamical systems","Probabilistic transitions, making it the categorical foundation for stochastic processes","Topological dynamics","Sheaf-valued dynamics"],
    ans: 1,
    exp: "The Giry monad G is a monad on Meas: G(X) = {probability measures on X}. Kleisli morphisms X → G(Y) are Markov kernels (stochastic maps), and the monad structure captures composition of stochastic transitions." },
  { q: "An adjunction between two categories C and D (with F: C → D left adjoint to G: D → C) in the context of dynamical systems provides:",
    opts: ["An isomorphism of the categories","A natural bijection Hom_D(FX, Y) ≅ Hom_C(X, GY), often relating different representations of the same dynamics","A functor from flows to maps","A cohomology theory"],
    ans: 1,
    exp: "Adjunctions in dynamical systems often relate continuous-time flows to discrete-time maps (suspension/Poincaré section adjunction), or relate topological and measurable categories of systems via forgetful/free functors." },
],

// ── Ch 29: Thermodynamics and Information ────────────────────────────────────
29: [
  { q: "Landauer's principle states that erasure of one bit of information in a computation requires dissipating at least:",
    opts: ["0 energy","kT ln 2 of heat into the environment","kT of energy","1 eV"],
    ans: 1,
    exp: "Landauer (1961): logically irreversible operations (like bit erasure) must dissipate at least kT ln 2 ≈ 3×10⁻²¹ J at temperature T. This connects information theory and thermodynamics at a fundamental level." },
  { q: "Maxwell's demon thought experiment is resolved by showing that:",
    opts: ["The demon can violate the second law indefinitely","The demon's memory must be erased to complete the cycle, which requires kT ln 2 per bit and restores the second law","The demon's observation does not constitute a measurement","Quantum mechanics forbids Maxwell's demon"],
    ans: 1,
    exp: "Bennett's resolution (1982): the demon must record measurement outcomes. Resetting its memory to the initial state is a logically irreversible erasure costing kT ln 2 per bit (Landauer), which exactly compensates the apparent entropy decrease." },
  { q: "The partition function Z = Σ e^{−E_i/kT} in statistical mechanics relates to information theory through the free energy F = −kT ln Z, which equals:",
    opts: ["The entropy times T","−kT times the log-normalizer of the Gibbs distribution (Helmholtz free energy = negative log-sum-exp of energies)","The average energy E[E]","The KL divergence from the uniform distribution"],
    ans: 1,
    exp: "F = −kT ln Z is the Helmholtz free energy. From an information-theoretic view, F = E[E] − T·S where S = kH is the thermodynamic entropy. The Gibbs distribution minimizes free energy, equivalently maximizes entropy at fixed mean energy." },
  { q: "The Jarzynski equality relates the non-equilibrium work W done in a process to the equilibrium free energy difference ΔF by:",
    opts: ["⟨W⟩ = ΔF","⟨e^{−W/kT}⟩ = e^{−ΔF/kT}","W = ΔF for all paths","⟨W⟩ ≥ ΔF (second law only)"],
    ans: 1,
    exp: "Jarzynski equality (1997): ⟨e^{−βW}⟩ = e^{−βΔF} exactly, even far from equilibrium. By Jensen's inequality (e^x convex), ⟨W⟩ ≥ ΔF, recovering the second law as a special case." },
],

// ── Ch 30: Optimal Transport ──────────────────────────────────────────────────
30: [
  { q: "The Wasserstein-2 distance W₂(μ,ν) between two probability measures is defined as:",
    opts: ["sup_f ∫f dμ − ∫f dν over 1-Lipschitz f","(inf_γ ∫|x−y|² dγ(x,y))^{1/2} over couplings γ with marginals μ, ν","||μ−ν||₁ in total variation","D(μ||ν)^{1/2}"],
    ans: 1,
    exp: "W₂(μ,ν) = (min over couplings γ of ∫|x−y|² dγ)^{1/2}. This is the L² version of the Kantorovich-Wasserstein distance. The Kantorovich duality gives the dual formulation via (φ, ψ) with φ(x)+ψ(y) ≤ |x−y|²." },
  { q: "Brenier's theorem states that, for μ absolutely continuous, the optimal transport map from μ to ν with cost |x−y|² is:",
    opts: ["A rotation","The gradient of a convex function ∇φ (a Monge map)","A linear map","The identity map whenever μ = ν"],
    ans: 1,
    exp: "Brenier's theorem (1991): for absolutely continuous μ, the unique optimal transport map T for squared Euclidean cost is of the form T = ∇φ for a convex function φ. This is the polar factorization theorem for maps." },
  { q: "The HWI inequality in optimal transport connects entropy H, Wasserstein distance W, and Fisher information I via:",
    opts: ["H(ν) ≤ H(μ) + W₂(μ,ν)","H(ν|γ) ≤ W₂(μ,ν) · √I(μ|γ) − W₂(μ,ν)²/2 (where γ is a reference measure)","I(μ|γ) = W₂(μ,γ)²","H = W · I always"],
    ans: 1,
    exp: "The HWI inequality interpolates between the log-Sobolev inequality and the Talagrand inequality. It states H(ν|γ) ≤ W₂(ν,γ)√I(ν|γ) − W₂²/2 under appropriate curvature conditions (positive Ricci curvature)." },
  { q: "The Benamou-Brenier formula gives a dynamic (fluid mechanics) characterization of W₂²(μ₀,μ₁) as:",
    opts: ["The minimal total variation of the path","inf ∫₀¹ ∫|v(t,x)|² dμ_t(x) dt over paths (μ_t, v_t) satisfying the continuity equation ∂_t μ + ∇·(vμ) = 0","The geodesic length in KL geometry","The Fisher information along the path"],
    ans: 1,
    exp: "Benamou-Brenier: W₂²(μ₀,μ₁) = min ∫₀¹ ∫|v|² dμ_t dt subject to the continuity equation. This formulation links optimal transport to fluid mechanics and is the basis for numerical computation of Wasserstein distances." },
],

// ── Ch 31: Ergodic Number Theory ──────────────────────────────────────────────
31: [
  { q: "Weyl's equidistribution theorem states that the sequence {nα} (fractional parts) is equidistributed modulo 1 if and only if:",
    opts: ["α is rational","α is irrational","α is algebraic","α > 1"],
    ans: 1,
    exp: "Weyl's theorem: {nα} is equidistributed mod 1 (Cesàro averages of f({nα}) converge to ∫₀¹ f) iff α is irrational. This is equivalent to the ergodicity of the irrational rotation T_α: x ↦ x + α (mod 1)." },
  { q: "The continued fraction expansion of a real number α is connected to the Gauss map T: [0,1) → [0,1) by T(x) = {1/x}. The Gauss measure μ(A) = (1/ln 2) ∫_A dx/(1+x) is invariant under T, and the Birkhoff ergodic theorem implies:",
    opts: ["All continued fraction partial quotients are equal","The geometric mean of partial quotients converges to the Khinchin constant K ≈ 2.685 for μ-a.e. α","Rational numbers have periodic continued fractions","The Gauss map is conjugate to the doubling map"],
    ans: 1,
    exp: "By the ergodic theorem for the Gauss map with Gauss measure, the geometric mean (a₁a₂⋯aₙ)^{1/n} → K = Π_k (1 + 1/(k(k+2)))^{log₂ k} ≈ 2.685 for a.e. α. This is Khinchin's theorem." },
  { q: "Furstenberg's proof of Szemerédi's theorem (every set of integers with positive upper density contains arbitrarily long arithmetic progressions) uses:",
    opts: ["Analytic number theory and sieves","Multiple ergodic recurrence (ergodic Ramsey theory)","Random graph methods","The regularity lemma alone"],
    ans: 1,
    exp: "Furstenberg's correspondence principle translates the combinatorial problem to a measure-preserving system, then uses multiple recurrence (Furstenberg's ergodic theorem) to prove the result. This launched ergodic Ramsey theory." },
  { q: "Normal numbers (every block of digits appears with the correct frequency) are related to ergodic theory by the fact that x ∈ [0,1] is normal in base b iff:",
    opts: ["Its continued fraction expansion is bounded","The orbit of x under the ×b map (x ↦ bx mod 1) is equidistributed with respect to Lebesgue measure","x is a Liouville number","The ×b map is a contraction at x"],
    ans: 1,
    exp: "Normality in base b ↔ equidistribution of the orbit under T_b(x) = bx (mod 1) w.r.t. Lebesgue measure. By Birkhoff's theorem and ergodicity of T_b, Lebesgue-a.e. x is normal in base b (Borel's theorem)." },
],

// ── Ch 32: Descriptive Set Theory ─────────────────────────────────────────────
32: [
  { q: "A set A ⊆ ℝ is analytic (Σ¹₁) if it is:",
    opts: ["Borel","A continuous image of a Borel set (equivalently, of the Baire space ℕᴺ)","A countable union of closed sets","An open set"],
    ans: 1,
    exp: "Analytic sets are projections of Borel sets: A = {x : ∃y (x,y) ∈ B} for Borel B. Equivalently, A = f(ℕᴺ) for some continuous f. Not all analytic sets are Borel (Suslin's theorem characterizes Borel sets as those that are both analytic and co-analytic)." },
  { q: "The perfect set property (every uncountable set in the class contains a perfect set) is known to hold for:",
    opts: ["All subsets of ℝ (assuming ZFC)","Analytic sets (Suslin's theorem)","All projective sets (provable in ZFC)","Only Borel sets"],
    ans: 1,
    exp: "Suslin's theorem (1917): every uncountable analytic set contains a perfect set (hence has cardinality of the continuum). For projective sets beyond Σ¹₁, large cardinal axioms are needed." },
  { q: "The concept of Wadge reducibility (continuous reducibility) defines the Wadge hierarchy. In the Baire space, it is well-founded and almost linear, meaning:",
    opts: ["Every two sets are Wadge equivalent","Every two sets are Wadge comparable (A ≤_W B or B ≤_W Ā) by the Wadge-Martin theorem","The hierarchy has only countably many levels","All analytic sets have the same Wadge degree"],
    ans: 1,
    exp: "Wadge's lemma (using determinacy): for any A, B ⊆ ℕᴺ, either A ≤_W B or B ≤_W Ā (complement of A). The hierarchy is well-founded and almost linear, giving a fine classification of topological complexity." },
  { q: "A Polish space is a topological space that is:",
    opts: ["Compact and Hausdorff","Separable and completely metrizable","Locally compact","Second-countable and locally compact Hausdorff"],
    ans: 1,
    exp: "Polish spaces (separable completely metrizable) are the natural setting for descriptive set theory and standard Borel spaces in ergodic theory. Examples: ℝ, ℝⁿ, Baire space ℕᴺ, Cantor space {0,1}ᴺ." },
],

// ── Ch 33: Orbit Equivalence ──────────────────────────────────────────────────
33: [
  { q: "Two measure-preserving group actions Γ ↷ (X,μ) and Λ ↷ (Y,ν) are orbit equivalent if:",
    opts: ["Γ and Λ are isomorphic groups","There is a measure-space isomorphism φ: X → Y that maps Γ-orbits to Λ-orbits","The actions have the same entropy","The actions are topologically conjugate"],
    ans: 1,
    exp: "Orbit equivalence is a coarser equivalence than conjugacy: the groups and their actions may differ, but the orbit partition structures are isomorphic as measured equivalence relations. It ignores the individual group action." },
  { q: "The Connes-Feldman-Weiss theorem states that for a measure-preserving action of an amenable group:",
    opts: ["It is always free","It is orbit equivalent to a ℤ-action (i.e., an action of the integers)","It is orbit equivalent to every free action","It has zero entropy"],
    ans: 1,
    exp: "CFW theorem (1981): every essentially free, ergodic, measure-preserving action of a countable amenable group is orbit equivalent to an ergodic ℤ-action. This reduces the study of amenable group actions to single transformations." },
  { q: "Outer automorphisms of the orbit equivalence relation (the full group [T]) are relevant because Dye's reconstruction theorem states:",
    opts: ["The full group [T] determines the orbit structure only up to entropy","The orbit equivalence class of T is completely determined by the isomorphism class of [T] as an abstract group","Two systems are orbit equivalent iff they have the same entropy","The full group is always abelian"],
    ans: 1,
    exp: "Dye's reconstruction: the full group [T] = {S : S(x) ∈ Tx a.e.} as an abstract group completely determines the orbit equivalence class of T. Two free ergodic systems are OE iff their full groups are isomorphic." },
  { q: "Gaboriau's l²-Betti numbers are invariants of measure equivalence classes of groups. His theorem (2002) showed:",
    opts: ["All groups have the same l²-Betti numbers","Free groups Fₙ and Fₘ are not measure equivalent for n ≠ m (their l²-Betti numbers differ)","Amenable groups have non-zero l²-Betti numbers","l²-Betti numbers are orbit equivalence invariants"],
    ans: 1,
    exp: "Gaboriau proved that l²-Betti numbers are measure equivalence invariants. Since βₙ(Fₙ) = n−1, free groups Fₙ and Fₘ are not measure equivalent when n ≠ m, solving a long-standing open problem." },
],

// ── Ch 34: Sofic Entropy ───────────────────────────────────────────────────────
34: [
  { q: "Sofic groups are defined as groups that can be approximated by:",
    opts: ["Finite abelian groups","Finite symmetric groups (permutation groups) in a metric sense","Lie groups","Free groups"],
    ans: 1,
    exp: "A group G is sofic if it can be approximated by finite symmetric groups: for any finite F ⊆ G and ε > 0, there is a map to Sym(n) that is an almost-homomorphism on F with almost-free action. All amenable and all residually finite groups are sofic." },
  { q: "Lewis Bowen's sofic entropy (2010) extended measure-theoretic entropy to actions of sofic groups. For amenable groups, sofic entropy:",
    opts: ["Always equals 0","Coincides with the classical Kolmogorov-Sinai entropy","Is always larger than KS entropy","Is undefined"],
    ans: 1,
    exp: "Bowen's theorem: for actions of amenable groups (which are sofic), sofic entropy coincides with the classical KS entropy. This provides a unified framework extending to all sofic groups." },
  { q: "Sofic entropy is defined using approximating maps σᵢ: G → Sym(nᵢ). The entropy of a partition depends on counting good models; a key feature is that it can be:",
    opts: ["Always computable","−∞ (undefined/minus infinity) for some actions, unlike KS entropy which is always ≥ 0","Always positive","Invariant under all group automorphisms"],
    ans: 1,
    exp: "One subtlety of sofic entropy: it can equal −∞ (essentially undefined) for some actions of non-amenable groups. This indicates the action cannot be approximated in the sofic framework, a phenomenon absent in the amenable case." },
  { q: "The connection between sofic entropy and free energy in statistical mechanics is that:",
    opts: ["They are unrelated","The sofic entropy of a Gibbs measure equals the free energy of the corresponding interaction","Sofic entropy counts free energy configurations of the graph approximations","Sofic entropy and free energy are dual via the Legendre transform"],
    ans: 2,
    exp: "Sofic entropy of a Gibbs measure for a nearest-neighbor interaction on a Cayley graph can be computed via a variational principle counting the number of consistent configurations on the approximating graphs, mirroring the free energy computation." },
],

// ── Ch 35: Isomorphism Problem ────────────────────────────────────────────────
35: [
  { q: "Ornstein's isomorphism theorem (1970) states that two Bernoulli shifts with the same entropy are:",
    opts: ["Orbit equivalent","Measurably isomorphic (conjugate as measure-preserving systems)","Topologically conjugate","Only spectrally isomorphic"],
    ans: 1,
    exp: "Ornstein's theorem: entropy is a complete invariant for Bernoulli shifts. Any two Bernoulli shifts with the same entropy are measurably isomorphic. This was a landmark result—entropy had been shown to distinguish Bernoulli shifts (Kolmogorov), Ornstein showed it is the only obstruction." },
  { q: "The property 'very weak Bernoulli' (VWB) was introduced by Ornstein as a sufficient condition for a system to be:",
    opts: ["Weakly mixing","Isomorphic to a Bernoulli shift","Uniquely ergodic","An Anosov system"],
    ans: 1,
    exp: "VWB (very weak Bernoulli) is Ornstein's condition generalizing 'processes that approximate i.i.d.' Any VWB process is Bernoulli. Geodesic flows on compact surfaces of negative curvature are VWB (hence Bernoulli)." },
  { q: "Thouvenot's relative isomorphism theorem extends Ornstein's result to:",
    opts: ["Non-invertible systems","Joinings and factor maps between Bernoulli shifts","Extensions of Bernoulli shifts over a common factor","Group actions"],
    ans: 2,
    exp: "Thouvenot's relative Ornstein theorem: if two extensions of a common factor both have the relative VWB property, they are relatively isomorphic (isomorphic over the factor). This is the key tool in Ratner's early work on measure rigidity." },
  { q: "The Halmos-von Neumann theorem classifies ergodic systems with pure point spectrum as measurably isomorphic to:",
    opts: ["Bernoulli shifts","Rotations on compact abelian groups","Geodesic flows","Skew products"],
    ans: 1,
    exp: "Systems with pure point spectrum have all eigenfunctions dense in L², and are (by HvN) isomorphic to a Kronecker system—a group rotation on a compact abelian group. These are the simplest ergodic systems (zero entropy, not mixing)." },
],

// ── Ch 36: Zimmer Program ─────────────────────────────────────────────────────
36: [
  { q: "The Zimmer program concerns actions of lattices Γ in higher-rank semisimple Lie groups (e.g., SL(n,ℝ), n ≥ 3) on compact manifolds. The central conjecture is:",
    opts: ["Such actions are always trivial","Such actions are always algebraic—arising from representations of the group","The smallest manifold admitting a non-trivial action has dimension ≥ n−1","All such actions preserve a smooth volume form"],
    ans: 2,
    exp: "Zimmer's conjecture: lattices in higher-rank groups cannot act smoothly on low-dimensional manifolds. Brown-Fisher-Hurtado proved (2020) that SL(n,ℤ) cannot act on manifolds of dimension < n−1 by volume-preserving diffeomorphisms." },
  { q: "Cocycle superrigidity (Zimmer's theorem, 1980) states that a cocycle α: Γ × X → H over an ergodic action of a higher-rank lattice Γ into a real algebraic group H is:",
    opts: ["Always trivial","Cohomologous to a homomorphism Γ → H (up to compact noise)","Determined by the Lyapunov exponents","A Markov cocycle"],
    ans: 1,
    exp: "Zimmer's cocycle superrigidity theorem: any measurable cocycle over an ergodic action of a higher-rank lattice into a real algebraic group is cohomologous to a representation (homomorphism) up to a compact group factor. This is the dynamical analogue of Margulis superrigidity." },
  { q: "Margulis superrigidity theorem (1974), which inspired the Zimmer program, states that any homomorphism from a higher-rank lattice Γ to GL(n,ℝ):",
    opts: ["Has finite image","Extends to a representation of the ambient Lie group","Is always injective","Has image in a compact group"],
    ans: 1,
    exp: "Margulis superrigidity: any homomorphism Γ → GL(n,ℝ) from a lattice in a higher-rank semisimple group either has precompact image or extends (up to finite index) to an algebraic representation of the Lie group. It implies arithmeticity of lattices." },
  { q: "The Furstenberg boundary of a semisimple Lie group G is a G-space B(G) used in the Zimmer program because:",
    opts: ["It is the unique compact G-space","It is the unique measurable G-space with no invariant probability measure (non-amenable)","Every ergodic G-action has a G-equivariant map to B(G), enabling rigidity arguments","It classifies all G-representations"],
    ans: 2,
    exp: "Every ergodic G-action (and hence every lattice action that extends) factors onto the Furstenberg boundary via a measurable equivariant map (Furstenberg's boundary theory). This is the key to proving cocycle superrigidity and other rigidity phenomena." },
],

// ── Ch 37: Complex Dynamics Frontiers ────────────────────────────────────────
37: [
  { q: "Misiurewicz-Thurston classification of critically finite rational maps uses the concept of a Thurston map. A Thurston map has a topological obstruction to being realized as a rational map if:",
    opts: ["It has more than 2 critical values","There exists a Thurston obstruction: a multicurve with eigenvalue ≥ 1 of the associated linear operator","The degree is too high","The map is not postcritically finite"],
    ans: 1,
    exp: "Thurston's theorem (1982): a postcritically finite branched cover f: S² → S² is equivalent to a rational map iff it has no Thurston obstruction—no multicurve Γ with spectral radius of f_Γ ≥ 1. This solves the realization problem for such maps." },
  { q: "Local connectivity of the Mandelbrot set M is related to:",
    opts: ["The density of hyperbolic components being known to be false","The MLC conjecture (Mandelbrot set is locally connected), which if true would imply density of hyperbolicity","The set M being a fractal","The Julia set of every c ∈ M being locally connected"],
    ans: 1,
    exp: "MLC (Mandelbrot set is Locally Connected) is a central open conjecture. It would imply combinatorial description of M via external angles and would imply density of hyperbolic maps in the quadratic family—a major open problem." },
  { q: "Yoccoz puzzle pieces are used to study local connectivity of Julia sets. They are defined using:",
    opts: ["The Böttcher coordinate alone","Preimages of external rays landing at specific angles, creating a partition of the plane","The critical point orbit only","The immediate basin of attraction"],
    ans: 1,
    exp: "Yoccoz puzzles partition the plane into puzzle pieces using preimages of external rays and equipotentials. The tableaux of these pieces reveal whether the Julia set is locally connected at the critical point (Yoccoz's local connectivity theorem for non-renormalizable quadratics)." },
  { q: "Polynomial-like maps (Douady-Hubbard) generalize polynomials and are used to explain renormalization. A polynomial-like map of degree d is:",
    opts: ["A polynomial of degree d","A proper holomorphic map f: U' → U of degree d with U' ⊂⊂ U","A rational map of degree d on ℂ̂","An entire function with d critical points"],
    ans: 1,
    exp: "A polynomial-like map (Douady-Hubbard 1985) is a proper holomorphic map f: U' → U with U', U ⊂ ℂ open and U' ⊂⊂ U. Its filled Julia set K_f = ∩ f⁻ⁿ(U) mimics a polynomial. The straightening theorem shows it is hybrid equivalent to an actual polynomial." },
],

// ── Ch 38: Quantum Information Complexity ────────────────────────────────────
38: [
  { q: "The quantum communication complexity of a function f(x,y) can be exponentially smaller than classical communication complexity. The key example is:",
    opts: ["Integer multiplication","The equality function","The disjointness function (DISJ)","Matrix-vector multiplication"],
    ans: 1,
    exp: "Equality: classically requires Ω(n) bits (one-way), but quantumly O(1) qubits (quantum fingerprinting using random hashes). More dramatically, some relation problems show exponential quantum advantage in communication complexity." },
  { q: "The quantum PCP (Probabilistically Checkable Proofs) conjecture states:",
    opts: ["Every QMA problem has an efficient quantum verifier","Approximating the ground state energy of local Hamiltonians to constant precision is QMA-hard","Quantum proofs can be verified classically","QMA = PSPACE"],
    ans: 1,
    exp: "The quantum PCP conjecture: approximating the ground state energy of k-local Hamiltonians to constant relative error is QMA-hard. If true, it would imply constant-rate locally testable quantum codes and would have major complexity implications. It remains open." },
  { q: "The quantum complexity class QMA (Quantum Merlin-Arthur) is the quantum analogue of NP. The local Hamiltonian problem is QMA-complete, which means:",
    opts: ["Local Hamiltonians can be efficiently simulated","Determining whether the ground state energy is above or below a given threshold (with promise gap) is in QMA and every QMA problem reduces to it","All quantum algorithms are in QMA","Quantum computers can solve NP-complete problems efficiently"],
    ans: 1,
    exp: "The local Hamiltonian problem (Kitaev's theorem, 2002) is QMA-complete: it is in QMA and every QMA problem reduces to it. This is the quantum analogue of Cook-Levin (SAT is NP-complete) and launched quantum computational complexity theory." },
  { q: "The CHSH game demonstrates quantum advantage in non-local games. Using the shared EPR pair, Alice and Bob can win the CHSH game with probability:",
    opts: ["3/4 (same as classical)","cos²(π/8) ≈ 0.854 > 3/4","1","1/2"],
    ans: 1,
    exp: "The CHSH inequality: classically players win at most 3/4 of the time. With shared entanglement (EPR pair + optimal measurements), they achieve cos²(π/8) = (2+√2)/4 ≈ 0.854, violating the classical bound and demonstrating quantum non-locality." },
],

// ── Ch 39: One-Shot Information Theory ──────────────────────────────────────
39: [
  { q: "The smooth min-entropy H_min^ε(X|Y) in one-shot information theory represents:",
    opts: ["The average conditional entropy","The minimum number of bits extractable about X given Y with failure probability ≤ ε","The maximum entropy over all distributions ε-close to P_{XY}","The von Neumann entropy of the quantum state"],
    ans: 1,
    exp: "Smooth min-entropy H_min^ε(X|Y) characterizes one-shot privacy amplification: it is the maximum number of (nearly) uniform secret bits extractable given adversary's information Y, with failure ε. As n → ∞, it converges to the conditional entropy rate." },
  { q: "In the one-shot channel coding framework, the one-shot capacity with error ε is characterized by the hypothesis testing mutual information I_h^ε(X;Y). As block length n → ∞:",
    opts: ["It diverges","n⁻¹ · (one-shot capacity for Pⁿ) → I(X;Y) (Shannon capacity)","It converges to 0","It equals the Rényi mutual information of order 2"],
    ans: 1,
    exp: "The one-shot capacity recovers the Shannon capacity in the i.i.d. limit via the law of large numbers: 1/n times the ε-achievable rate for n channel uses → I(X;Y). Second-order analysis gives the normal approximation with √n dispersion corrections." },
  { q: "The quantum one-shot source compression theorem says that a quantum state ρ^A can be compressed to:",
    opts: ["S(ρ) qubits exactly","H_max^ε(ρ) qubits with error ε","log rank(ρ) qubits","H_min^ε(ρ) qubits with error ε"],
    ans: 1,
    exp: "One-shot quantum source coding: the minimum number of qubits to compress ρ with error ε is essentially H_max^ε(A)_ρ. In the i.i.d. limit (ρ^⊗n), this recovers the von Neumann entropy S(ρ) per copy." },
  { q: "The resource theory of coherence in one-shot quantum information identifies free states as:",
    opts: ["Maximally entangled states","Incoherent states (diagonal in the computational basis)","Pure states","States with maximum von Neumann entropy"],
    ans: 1,
    exp: "In the resource theory of coherence, free (resourceless) states are incoherent states—those diagonal in a fixed reference basis. Coherence is a resource and one-shot measures like robustness of coherence and one-shot coherence distillation/dilution quantify it." },
],

// ── Ch 40: Circuit Complexity and Information Theory ─────────────────────────
40: [
  { q: "The circuit complexity of a Boolean function f: {0,1}ⁿ → {0,1} is the size of the smallest Boolean circuit computing f. Shannon's counting argument shows:",
    opts: ["All functions have polynomial-size circuits","Most Boolean functions require exponential circuit size (Ω(2ⁿ/n))","No function requires more than n² gates","Circuit complexity equals formula complexity"],
    ans: 1,
    exp: "Shannon's counting argument (1949): there are 2^{2ⁿ} functions but only ≈ (nS)^S circuits of size S. For S = c·2ⁿ/n with small c, most functions cannot be computed. This shows explicit hard functions exist but doesn't exhibit them." },
  { q: "The Karchmer-Wigderson theorem relates circuit depth complexity to:",
    opts: ["The entropy of the function","The communication complexity of the Karchmer-Wigderson game for f","The number of satisfying assignments","The algebraic degree of f"],
    ans: 1,
    exp: "Karchmer-Wigderson: the depth of a Boolean circuit for f equals the communication complexity of the game where Alice has x ∈ f⁻¹(1), Bob has y ∈ f⁻¹(0), and they must find a coordinate i where x_i ≠ y_i. This reduces circuit lower bounds to communication lower bounds." },
  { q: "The entropy compression method (introduced in combinatorics) is an information-theoretic technique for proving existence results. It works by showing:",
    opts: ["The entropy of the output is maximized","If a random process terminates, then the entropy of the algorithm's execution must be bounded—forcing termination","Greedy algorithms achieve optimal entropy","Randomized algorithms have lower entropy than deterministic ones"],
    ans: 1,
    exp: "Entropy compression: if an algorithm can be 'compressed' (the random transcript can be reconstructed from a smaller encoding), then the information-theoretic bound forces the algorithm to terminate. Used by Moser-Tardos to prove the constructive Lovász Local Lemma." },
  { q: "AC⁰ circuits (constant depth, polynomial size, unbounded fan-in AND/OR) cannot compute the parity function (XOR of n bits). The lower bound proof uses:",
    opts: ["Diagonalization","Switching lemma (random restriction argument) — Håstad's theorem gives exponential lower bounds","Algebraization","Natural proofs"],
    ans: 1,
    exp: "Håstad's switching lemma (1986): under random restriction, constant-depth circuits simplify to decision trees. This gives exp(Ω(n^{1/d})) lower bounds for parity in depth-d circuits. Parity ∉ AC⁰ follows with exponential lower bounds on the size of constant-depth circuits." },
],

// ── Ch 41: Collatz Dynamics ───────────────────────────────────────────────────
41: [
  { q: "The 3n+1 problem (Collatz conjecture) asks whether the iteration n ↦ n/2 (n even) or n ↦ 3n+1 (n odd) always reaches 1. The best-known partial result (Tao, 2019) shows that for any ε > 0, the sequence reaches a value below ε·n for:",
    opts: ["All n","Almost all n (in the sense of logarithmic density)","Odd n only","n in a set of positive density"],
    ans: 1,
    exp: "Tao's result (2019): for almost all n (100% in logarithmic density), the Collatz orbit reaches a value ≤ f(n) for any f(n) → ∞. This is the best unconditional result toward the conjecture." },
  { q: "The 'Syracuse' representation of the Collatz map on odd numbers maps n → (3n+1)/2^{v₂(3n+1)}. The stochastic model for this map treats the 2-adic valuation as:",
    opts: ["Always equal to 1","Geometrically distributed with parameter 1/2 (by heuristic)","Always equal to log₂(3)","Uniformly distributed on {1,2,...,n}"],
    ans: 1,
    exp: "Heuristically, for a random odd n, the valuation v₂(3n+1) is approximately Geometric(1/2). This gives average multiplier 3/4 per step in log scale, explaining why the orbit should decrease on average—though proving this rigorously is the conjecture." },
  { q: "The Collatz map on the 2-adic integers ℤ₂ can be expressed as a continuous map. The conjecture is equivalent to:",
    opts: ["The 2-adic map has a unique fixed point","Every 2-adic integer has an orbit that passes through ℤ⁺ and eventually reaches 1","The 2-adic valuation of iterates grows","The map has no periodic orbits in ℤ₂"],
    ans: 1,
    exp: "Extending the Collatz map to ℤ₂ gives a continuous map. The conjecture is equivalent to every positive integer eventually reaching 1, i.e., every positive integer is in the basin of the fixed-point cycle {1,2} in ℤ₂." },
  { q: "The stopping time of the Collatz iteration for n is the first k with C^k(n) < n. Empirical and heuristic arguments suggest the stopping time for a typical n grows as:",
    opts: ["Linearly in n","O(log n)","O(log² n)","O(n)"],
    ans: 1,
    exp: "Heuristic analysis: the expected number of steps to reduce n to below n is O(log n) (since each step multiplies by ≈ 3/4 in expectation). Empirically, stopping times grow as O(log n) for almost all n." },
],

// ── Ch 42: Quantum Computing Connections ────────────────────────────────────
42: [
  { q: "The quantum threshold theorem for fault-tolerant quantum computation states that if physical error rates are below a threshold p_th, then:",
    opts: ["All quantum algorithms fail","Arbitrarily long quantum computations can be performed reliably by concatenating error-correcting codes with overhead poly(log n)","The computation must use O(n²) qubits","Fault-tolerance requires classical pre-computation"],
    ans: 1,
    exp: "Quantum threshold theorem: if per-gate error rate p < p_th (≈ 10⁻²–10⁻⁴ for various schemes), concatenating CSS or surface codes gives error rates that drop doubly exponentially with code distance, enabling scalable quantum computation." },
  { q: "The quantum Fourier transform (QFT) over ℤ_N can be implemented using O(log² N) quantum gates. Its speedup over the classical FFT (O(N log N)) is the basis for:",
    opts: ["Quantum error correction","Shor's factoring algorithm and the hidden subgroup problem","Grover's search algorithm","Quantum simulation"],
    ans: 1,
    exp: "The QFT provides exponential speedup for finding periodicity, which is the core of Shor's algorithm for factoring and discrete logarithm. Both reduce to the abelian hidden subgroup problem, which QFT solves efficiently." },
  { q: "The variational quantum eigensolver (VQE) is a hybrid classical-quantum algorithm for estimating ground state energies. It uses:",
    opts: ["Phase estimation","A parameterized quantum circuit (ansatz) optimized classically via minimizing ⟨ψ(θ)|H|ψ(θ)⟩","Quantum annealing","The quantum Zeno effect"],
    ans: 1,
    exp: "VQE: prepare a parameterized state |ψ(θ)⟩ on quantum hardware, estimate ⟨H⟩ = ⟨ψ(θ)|H|ψ(θ)⟩ via measurements, then optimize θ classically. The variational principle guarantees the energy estimate bounds the ground state energy from above." },
  { q: "Quantum advantage for sampling problems (like BosonSampling and random circuit sampling) is related to the hardness of computing:",
    opts: ["The trace of a unitary","The permanent of a matrix (BosonSampling) or amplitudes of random circuits","The eigenvalue gap","The entanglement entropy"],
    ans: 1,
    exp: "BosonSampling (Aaronson-Arkhipov): sampling from the output distribution of a boson interferometer is hard for classical computers unless the polynomial hierarchy collapses, based on the hardness of computing matrix permanents. Random circuit sampling has analogous hardness." },
],

// ── Ch 43: HoTT Connections ───────────────────────────────────────────────────
43: [
  { q: "In Homotopy Type Theory (HoTT), the univalence axiom (Voevodsky) states that for types A and B:",
    opts: ["A = B iff they are isomorphic sets","The type (A = B) is equivalent to the type of equivalences (A ≃ B)","A = B iff they have the same cardinality","Equivalent types are definitionally equal"],
    ans: 1,
    exp: "Univalence: (A =_U B) ≃ (A ≃ B). This means equivalence of types is the same as identity of types—formalizing the informal mathematical practice of treating isomorphic objects as identical. It implies function extensionality as a corollary." },
  { q: "In HoTT, the fundamental groupoid of a type X has as objects the terms of X and as morphisms:",
    opts: ["Functions X → X","The identity proofs (paths) p: x = y for x, y : X","The propositional truncations","The higher inductive constructors"],
    ans: 1,
    exp: "In HoTT, the type x =_X y of identity proofs behaves as a path space. The collection of all terms and all identity proofs forms the fundamental groupoid of X, and higher identities between paths give the ∞-groupoid structure (the homotopy type of X)." },
  { q: "Higher Inductive Types (HITs) in HoTT can define the circle S¹ with:",
    opts: ["One point constructor only","One point constructor base: S¹ and one path constructor loop: base = base","Two point constructors and one path","Infinitely many constructors"],
    ans: 1,
    exp: "S¹ as a HIT: base: S¹ (a point), loop: base = base (a non-trivial path). HoTT proves π₁(S¹) = ℤ—the fundamental group of the circle—purely type-theoretically. This demonstrates topology via HoTT without appeal to sets." },
  { q: "The Curry-Howard-Voevodsky correspondence extends Curry-Howard (propositions as types) by adding:",
    opts: ["The λ-calculus","Homotopy-theoretic meaning: types as spaces, terms as points, identities as paths, higher identities as homotopies","Classical logic into type theory","Set-theoretic foundations"],
    ans: 1,
    exp: "The ∞-groupoid interpretation: Curry-Howard identifies propositions ↔ types and proofs ↔ terms. Voevodsky's insight adds homotopy: types are ∞-groupoids (spaces), identity types are path spaces, and higher identity types are higher homotopies. HoTT is the resulting synthetic homotopy theory." },
],

}; // end EXTRA

// ── Write files ───────────────────────────────────────────────────────────────
const BASE = path.join(__dirname, 'questions');

let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);

  // Determine part
  let part = null;
  const partRanges = [
    [1, [1,2,3,4,5]],
    [2, [6,7,8,9,10,11,12,13,14,15]],
    [3, [16,17,18,19,20,21]],
    [4, [22,23,24,25,26]],
    [5, [27,28,29,30,31,32]],
    [6, [33,34,35,36,37,38,39,40]],
    [7, [41,42,43]],
  ];
  for (const [p, chs] of partRanges) {
    if (chs.includes(ch)) { part = p; break; }
  }

  // Read one existing file to get chTitle
  const dir = path.join(BASE, PART_DIRS[part], CH_DIRS[ch]);
  const existing = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir, existing[0]), 'utf8'));
  const chTitle = sample.chTitle;

  qs.forEach((q, i) => {
    const n = existing.length + i + 1;
    const filename = path.join(dir, `q${String(n).padStart(2, '0')}.json`);
    const record = { ch, part, chTitle, ...q };
    fs.writeFileSync(filename, JSON.stringify(record, null, 2) + '\n');
    console.log('wrote', path.relative(__dirname, filename));
    total++;
  });
}

console.log(`\nDone. ${total} new questions written.`);
console.log('Run `node build.js` to regenerate questions-bundle.js.');
