#!/usr/bin/env node
'use strict';
const fs   = require('fs');
const path = require('path');

const META = {
  21:{part:3,dir:'part-iii-information-theory',ch:'ch21-quantum-information-theory'},
  22:{part:4,dir:'part-iv-bridges',ch:'ch22-entropy-in-dynamical-systems'},
  23:{part:4,dir:'part-iv-bridges',ch:'ch23-ergodic-information-theory'},
  24:{part:4,dir:'part-iv-bridges',ch:'ch24-symbolic-dynamics-and-information'},
  25:{part:4,dir:'part-iv-bridges',ch:'ch25-chaos-randomness-computation'},
  26:{part:4,dir:'part-iv-bridges',ch:'ch26-information-methods-in-cs'},
  27:{part:5,dir:'part-v-foundations',ch:'ch27-computability-and-dynamics'},
  28:{part:5,dir:'part-v-foundations',ch:'ch28-category-theory-and-dynamics'},
  29:{part:5,dir:'part-v-foundations',ch:'ch29-thermodynamics-and-information'},
  30:{part:5,dir:'part-v-foundations',ch:'ch30-optimal-transport'},
  31:{part:5,dir:'part-v-foundations',ch:'ch31-ergodic-number-theory'},
  32:{part:5,dir:'part-v-foundations',ch:'ch32-descriptive-set-theory'},
};

const EXTRA = {

21:[
  {q:"The quantum mutual information for a bipartite state ρ_{AB} is defined as I(A:B)_ρ = S(A) + S(B) − S(AB). For a pure state |ψ⟩_{AB}, this equals:",
   opts:["0","2S(A) = 2S(B)","S(A) + S(B)","S(AB)"],
   ans:1,
   exp:"For pure |ψ⟩_{AB}: S(AB)=0 and S(A)=S(B) (by Schmidt decomposition), so I(A:B) = S(A)+S(B)−0 = 2S(A). This is twice the entanglement entropy and the maximum possible quantum mutual information for fixed marginals."},
  {q:"The quantum error correcting code [[n,k,d]] encodes k logical qubits into n physical qubits with distance d. The quantum Singleton bound states:",
   opts:["k ≤ n−d","k ≤ n−2(d−1)","k = n/2","d ≤ n/2"],
   ans:1,
   exp:"Quantum Singleton bound: k ≤ n − 2(d−1) = n − 2d + 2. This is stricter than the classical Singleton bound (k ≤ n−d+1) by a factor of 2, reflecting the need to correct both X and Z errors. Codes achieving equality are quantum MDS codes (e.g., certain stabilizer codes over GF(q²))."},
  {q:"The stabilizer formalism for quantum error correction uses an Abelian group S ⊂ Pauli group P_n. The code space is the +1 eigenspace of all elements of S. The code encodes k qubits into n qubits if |S| =",
   opts:["2^k","2^{n−k}","2^n","k"],
   ans:1,
   exp:"|S| = 2^{n-k}: S has n-k generators (independent Pauli operators), giving 2^k-dimensional code space (the +1 eigenspace of all 2^{n-k} generators). The code distance is the minimum weight of a Pauli in the normalizer N(S) not in S."},
  {q:"The quantum capacity Q of the erasure channel E_p (which erases each qubit with probability p, telling the receiver which qubits were erased) is:",
   opts:["1−p","max(1−2p, 0)","(1−p)²","½(1−p)"],
   ans:1,
   exp:"Quantum erasure channel: Q = max(1−2p, 0). For p < 1/2, the quantum capacity is 1−2p bits (strictly less than the classical capacity 1−p). The erasure channel is one of the few for which exact quantum capacity formulas are known."},
  {q:"The Holevo bound χ(ρ,{pᵢ,ρᵢ}) limits the classical information accessible from an ensemble {pᵢ,ρᵢ} of quantum states via any measurement. It states the accessible information is at most:",
   opts:["Σ pᵢ S(ρᵢ)","S(Σᵢ pᵢρᵢ) − Σᵢ pᵢ S(ρᵢ) = χ (the Holevo quantity)","log(dim H)","Σᵢ pᵢ log(1/pᵢ)"],
   ans:1,
   exp:"Holevo bound: I(X;Y) ≤ χ = S(ρ) − Σ pᵢS(ρᵢ) where ρ = Σpᵢρᵢ. The accessible information from measuring an ensemble cannot exceed χ. Equality is achievable (HSW theorem) with product-state encoding and suitable measurements."},
  {q:"Quantum key distribution (BB84 protocol) achieves information-theoretic security because any eavesdropper Eve disturbs the channel with detectable error rate. The key reconciliation and privacy amplification step reduces the key to length approximately:",
   opts:["n bits regardless of error rate","n[1 − H_b(e)] bits where e is the quantum bit error rate and H_b is binary entropy","n/2 bits","n·e bits"],
   ans:1,
   exp:"After error correction and privacy amplification, the secret key length is ≈ n[1 − H_b(e) − H_b(e_z)] ≈ n[1 − 2H_b(e)] in the symmetric case. At error rate e ≥ 11% (for BB84), the key rate drops to zero—above this threshold, no secure key can be extracted."},
  {q:"The Gottesman-Knill theorem states that quantum circuits consisting only of Clifford gates (Hadamard, CNOT, S gate) applied to computational basis states can be:",
   opts:["Efficiently simulated by classical computers in polynomial time","Not simulated classically","Simulated classically only for n ≤ 50 qubits","Universal for quantum computation"],
   ans:0,
   exp:"Gottesman-Knill: Clifford circuits are classically efficiently simulable. The stabilizer group (n Pauli operators) evolves under Clifford gates and can be tracked in O(n²) classical space. Clifford circuits are not universal—T gates (non-Clifford) are needed for universality."},
  {q:"Quantum entanglement distillation converts n copies of a partially entangled state ρ into m copies of a maximally entangled state (EPR pair) using only LOCC. The asymptotic rate m/n is bounded by the:",
   opts:["Von Neumann entropy S(ρ)","Entanglement of formation E_F(ρ)","Distillable entanglement E_D(ρ) = lim_{n→∞} max_{LOCC} m/n","Logarithmic negativity"],
   ans:2,
   exp:"Distillable entanglement E_D(ρ) = sup{r : LOCC on ρ^⊗n → approximately r·n EPR pairs}. For pure states, E_D = S(ρ_A) = entanglement entropy. For mixed states, E_D ≤ E_F (entanglement of formation) and may be strictly less (bound entangled states have E_D = 0 but E_F > 0)."},
],

22:[
  {q:"The topological pressure P(φ) for a continuous function φ on a compact topological dynamical system (X,T) is defined via the variational principle as:",
   opts:["P(φ) = h_top(T) + sup_{μ} ∫φ dμ","P(φ) = sup_{μ invariant} (h_μ(T) + ∫φ dμ)","P(φ) = ∫φ dμ_max","P(φ) = h_top(T)·||φ||_∞"],
   ans:1,
   exp:"Topological pressure: P(φ) = sup_{μ∈M(T)} (h_μ(T) + ∫φ dμ). Setting φ ≡ 0 recovers the variational principle for topological entropy. Equilibrium states are measures achieving the supremum. Pressure is the Legendre transform of entropy as a function of the potential φ."},
  {q:"The Bowen-Ruelle definition of topological pressure uses (n,ε)-spanning sets. Specifically:",
   opts:["P(φ) = lim_{ε→0} lim_{n→∞} (1/n) log inf_{E spanning} Σ_{x∈E} e^{Sₙφ(x)}","P(φ) = lim_{n→∞} (1/n) log Σ_{x: T^nx=x} e^{Sₙφ(x)}","P(φ) = sup_μ h_μ(T)","P(φ) = lim_{n→∞} (1/n) log max_{x} Sₙφ(x)"],
   ans:0,
   exp:"Bowen's definition: P(φ) = lim_{ε→0} limsup_{n→∞} (1/n) log Z_n(φ,ε) where Z_n is the weighted partition function over (n,ε)-spanning sets. The alternative sum over periodic orbits gives the same pressure for Axiom A systems."},
  {q:"For an ergodic measure-preserving system (X,μ,T) and partition 𝒫, the entropy h_μ(T,𝒫) = lim_{n→∞} (1/n) H(𝒫 ∨ T⁻¹𝒫 ∨ … ∨ T^{-(n-1)}𝒫). The Kolmogorov-Sinai theorem states:",
   opts:["h_μ(T) = h_μ(T,𝒫) for every partition 𝒫","h_μ(T) = sup_𝒫 h_μ(T,𝒫) = h_μ(T,𝒫) for any generating partition 𝒫","h_μ(T) = h_μ(T,𝒫) + h_μ(T,𝒬) for any two partitions","h_μ(T) = H(𝒫) for the finest partition"],
   ans:1,
   exp:"Kolmogorov-Sinai theorem: h_μ(T) = h_μ(T,𝒫) for any generating partition 𝒫 (one where ∨_{n=-∞}^∞ T^n𝒫 separates points). This is the key computational result: entropy can be computed from a single generating partition rather than taking the supremum."},
  {q:"The Margulis-Ruelle inequality states that for a C¹ diffeomorphism T of a compact Riemannian manifold with invariant measure μ:",
   opts:["h_μ(T) = Σ λᵢ","h_μ(T) ≤ Σᵢ max(λᵢ,0) (sum of positive Lyapunov exponents, integrated over μ)","h_μ(T) ≥ Σ |λᵢ|","h_μ(T) = 0 if all Lyapunov exponents are negative"],
   ans:1,
   exp:"Margulis-Ruelle inequality: h_μ(T) ≤ ∫ Σᵢ max(λᵢ(x),0) dμ(x). Equality characterises SRB measures (Pesin's formula). The inequality is proven by bounding the growth of volumes under T via Lyapunov exponents, using the Oseledets theorem."},
  {q:"Entropy conjugacy (Bowen, 1978): two subshifts of finite type with the same topological entropy are related by the existence of a common extension. Specifically, every mixing SFT of entropy log λ is:",
   opts:["Isomorphic to the full shift","A factor of the full shift on ⌈λ⌉ symbols","An extension of every other mixing SFT of the same entropy","Conjugate to the Bernoulli shift of the same entropy"],
   ans:2,
   exp:"Bowen's entropy conjecture (proved by Adler-Marcus): any mixing SFT of entropy h is an extension of every other mixing SFT of entropy h. Two mixing SFTs are topologically conjugate iff they have the same entropy AND the same period—but they are entropy-conjugate (common extension) based on entropy alone."},
  {q:"The measure of maximal entropy (MME) for a hyperbolic set Λ of a C¹⁺α diffeomorphism equals the SRB measure if and only if:",
   opts:["The Lyapunov exponents are all equal","The system is volume-preserving and ergodic w.r.t. volume","The stable and unstable manifolds have equal dimension","The topological entropy equals the sum of all positive Lyapunov exponents for every invariant measure"],
   ans:1,
   exp:"MME = SRB iff the system preserves a smooth (absolutely continuous) measure, i.e., it is volume-preserving (the Jacobian det(DT) = 1 along unstable manifolds). For Anosov diffeomorphisms, this is equivalent to volume preservation."},
  {q:"Takens' embedding theorem (delay-coordinate embedding) states that for a smooth dynamical system on a compact manifold M of dimension m, a generic delay embedding (x, T(x), T²(x), …, T^{2m}(x)) is:",
   opts:["Always onto M","An embedding (injective immersion) of M into ℝ^{2m+1}","Surjective onto ℝ^{2m+1}","Only injective for m = 1"],
   ans:1,
   exp:"Takens' theorem (1981): for a C² diffeomorphism T on a compact m-manifold M, the delay-coordinate map Φ: M → ℝ^{2m+1} is generically an embedding. This justifies reconstructing the attractor from a single scalar time series—the foundation of time-series analysis of chaotic systems."},
  {q:"For a continuous map T on a compact metric space with a unique measure of maximal entropy μ_max, the topological entropy can be computed from the growth rate of periodic orbits:",
   opts:["|Fix(Tⁿ)| = e^{nh_top} exactly","(1/n) log |Fix(Tⁿ)| → h_top(T) as n → ∞ (for expansive maps or when periodic orbits are dense)","h_top = lim_{n→∞} |Fix(Tⁿ)|^{1/n}","All periodic orbits have the same period"],
   ans:1,
   exp:"For expansive maps with specification property (e.g., mixing SFTs, Axiom A attractors): (1/n) log |Per_n(T)| → h_top. For the full k-shift: |Per_n| = kⁿ, giving entropy log k. This is the dynamical analogue of Dirichlet series counting prime orbits."},
],

23:[
  {q:"The Kolmogorov-Sinai entropy of a stationary ergodic process {Xₙ} equals the entropy rate H̄ of the process. This connection is stated precisely as:",
   opts:["h_μ(T) = H(X₀) always","h_μ(T) = H(X₀ | X_{-1}, X_{-2}, …) = lim H(Xₙ|X₁,…,Xₙ₋₁)","h_μ(T) = H(X₀,X₁)","h_μ(T) = log(alphabet size)"],
   ans:1,
   exp:"The KS entropy of the stationary measure μ on the shift space equals the entropy rate: h_μ(σ) = H(X₀|X_{-∞}^{-1}) = lim_{n→∞} H(Xₙ|X₁,…,Xₙ₋₁). This unifies Shannon's entropy rate (information theory) with Kolmogorov's measure-theoretic entropy."},
  {q:"The relative entropy rate of process P w.r.t. process Q satisfies D̄(P||Q) = lim_{n→∞} (1/n) D(P^n||Q^n). For ergodic processes, this equals:",
   opts:["H̄(P)","H̄(Q) − H̄(P)","The asymptotic expected log-likelihood ratio per symbol","D(P₁||Q₁) always"],
   ans:2,
   exp:"By Birkhoff ergodic theorem, (1/n)log(dP^n/dQ^n) → D̄(P||Q) a.s. under P. The relative entropy rate is the a.s. limit of the normalised log-likelihood ratio—the per-symbol KL divergence between stationary processes."},
  {q:"The universal prediction (lossless) problem: given x₁,…,xₙ without knowing the source distribution, the best achievable per-symbol regret against the best compressor from a class 𝒞 scales as:",
   opts:["O(1) (constant regret is achievable)","O((|𝒞|log n)/n) for finite classes, O((k log n)/n) for k-parameter models (the minimax redundancy)","O(n) (linear regret is unavoidable)","O(√n)"],
   ans:1,
   exp:"For k-parameter source classes, the minimax redundancy per symbol is (k/2)(log n)/n + O(1/n) (Shtarkov, Rissanen). This is the best achievable rate of learning—any universal code pays at least this penalty in extra bits per symbol relative to the true entropy."},
  {q:"The Minimum Description Length (MDL) principle for model selection chooses the model M that minimises the two-part code length L(M) + L(data|M). Its connection to Bayesian model selection is:",
   opts:["MDL always equals MAP (maximum a posteriori)","MDL corresponds to Bayesian model selection with a non-informative (Jeffreys) prior in the limit","MDL minimises the AIC (Akaike Information Criterion)","MDL requires knowing the true model class"],
   ans:1,
   exp:"MDL with the normalized maximum likelihood (NML) code corresponds to Bayesian model selection with the Jeffreys prior (invariant prior in information geometry). Both penalise model complexity by the number of parameters times (log n)/2."},
  {q:"The capacity of an information source (maximal entropy per symbol over all possible source distributions) connects to ergodic theory via the maximum entropy principle. For a stationary source constrained to a subshift X:",
   opts:["The max entropy equals H(X₀)","The max entropy rate over all shift-invariant measures on X equals h_top(X) (the topological entropy)","The max entropy is unbounded","The max entropy equals log|alphabet|"],
   ans:1,
   exp:"Variational principle: max_{μ shift-invariant on X} h_μ(σ) = h_top(X). The topological entropy is the maximum entropy rate achievable over all stationary sources supported on the subshift X. This is the information-theoretic meaning of topological entropy."},
  {q:"The Lempel-Ziv compression algorithm achieves near-optimal compression for stationary ergodic sources. The LZ77 algorithm parses the string into phrases, each defined as the longest match in the preceding text. The compression ratio satisfies:",
   opts:["Always equals H̄ exactly","Converges to H̄ (the entropy rate) almost surely for ergodic sources as n → ∞","Equals H̄ only for i.i.d. sources","Converges to 0 always"],
   ans:1,
   exp:"Ziv-Lempel theorem: for any ergodic stationary source, the LZ compression ratio (bits per symbol output by LZ77/78) converges a.s. to the entropy rate H̄. This makes LZ-based algorithms universally asymptotically optimal—no prior knowledge of the source is needed."},
  {q:"The capacity-achieving codes for memoryless sources in the Shannon sense are related to ergodic theory by the AEP. The typical set Tε^n has the properties:",
   opts:["It contains all 2^{nH} strings exactly","It has probability → 1, contains ≈ 2^{nH} strings each with probability ≈ 2^{-nH}, and can be described in ≈ nH bits","It contains exactly 2^{nH} strings","It equals the support of P^n"],
   ans:1,
   exp:"AEP typical set: P(T^n_ε) → 1, |T^n_ε| ≈ 2^{nH}, each x ∈ T^n_ε has P(x) ≈ 2^{-nH}. Encoding only typical sequences achieves rate H with vanishing error—the operational meaning of entropy as minimum description length for i.i.d. sources."},
  {q:"The mutual information between two stationary processes {Xₙ} and {Yₙ} is defined as I(X;Y) = lim_{n→∞} (1/n) I(X₁…Xₙ; Y₁…Yₙ). For an ergodic channel, this equals:",
   opts:["I(X₁;Y₁)","The channel capacity C","The mutual information rate Ī(X;Y) = H̄(Y) − H̄(Y|X)","I(X₀;Y₀|X_{-∞}^{-1}, Y_{-∞}^{-1})"],
   ans:2,
   exp:"The mutual information rate Ī(X;Y) = H̄(Y) − H̄(Y|X) (difference of entropy rates). For channels with memory, the capacity is C = sup_{X stationary} Ī(X;Y), a supremum over stationary input processes. This is the general formula for channels with memory."},
],

24:[
  {q:"The language of an SFT X (as a set of admissible words) is a regular language. The minimal deterministic finite automaton recognizing the language has states corresponding to:",
   opts:["Individual symbols","Follower sets: for each word w, the set of u such that wu is admissible","Predecessors sets of words","The periods of the periodic orbits"],
   ans:1,
   exp:"The follower set of w is F(w) = {u : wu ∈ L(X)}. The minimal DFA states are the distinct follower sets. For an SFT, the minimal automaton is the minimal edge shift presentation—the canonical graph with vertices = follower set classes."},
  {q:"Fischer's canonical automaton for a sofic shift S gives the minimal right-resolving presentation. An edge-labeled graph (G, L) presents S if the labeling is right-resolving, meaning:",
   opts:["Each vertex has exactly one outgoing edge per label","The in-degree of each vertex equals its out-degree","The graph is strongly connected","The labeling uses the full alphabet"],
   ans:0,
   exp:"Right-resolving: at each vertex, each label appears on at most one outgoing edge. This means the path reading a word w starting from a fixed vertex is uniquely determined by w. The Fischer cover is the minimal right-resolving presentation of a sofic shift."},
  {q:"Shannon's capacity of the noiseless channel with forbidden symbol sequences (the Shannon capacity of a graph G, Θ(G)) for the 5-cycle C₅ was computed by Lovász (1979) using the theta function:",
   opts:["Θ(C₅) = 2","Θ(C₅) = √5","Θ(C₅) = 5/2","Θ(C₅) = log 5"],
   ans:1,
   exp:"Lovász theta function: Θ(C₅) = √5. This equals the independence number α = 2 raised to the Shannon capacity power: the zero-error capacity of the channel with confusion graph C₅ is ½ log(√5) = ¼ log 5 bits. Shannon's original work left this open; Lovász solved it with the semidefinite theta function."},
  {q:"The entropy of a sofic shift X (image of an SFT Y under factor map π) satisfies:",
   opts:["h_top(X) > h_top(Y) always","h_top(X) ≤ h_top(Y) with equality in many cases","h_top(X) = h_top(Y) always","h_top(X) = 0 always"],
   ans:1,
   exp:"Since X = π(Y) is a factor (image under continuous surjective factor map), h_top(X) ≤ h_top(Y). Equality holds for finite-to-one factor maps (bounded-to-one). The entropy of a sofic shift equals log ρ(A) for the adjacency matrix of its minimal right-resolving presentation."},
  {q:"The follower set (right context) of a word w in a subshift X determines its syntactic complexity. For minimal subshifts, the map w ↦ F(w) has the property that as |w| → ∞:",
   opts:["F(w) grows exponentially","F(w) shrinks to a single word","F(w) stabilises to F(w') for longer extensions w' of w (the future eventually determines the word's type)","F(w) = L(X) for all w"],
   ans:2,
   exp:"In an SFT, follower sets are determined by the last m symbols (where m is the memory). In general minimal subshifts, the number of distinct follower sets equals the number of states in the minimal right-resolving presentation. The follower-set complexity measures syntactic complexity."},
  {q:"The topological entropy of a substitution tiling (like Penrose tiling) is:",
   opts:["Positive (it has many distinct tilings)","Zero, since substitution tilings are repetitive (every patch recurs) and complexity p(n) grows polynomially","log 5 (the golden ratio symmetry)","Infinite"],
   ans:1,
   exp:"Substitution tilings (Penrose, Ammann-Beenker, etc.) have polynomial patch complexity (number of distinct patches of size n grows polynomially in n), giving zero topological entropy. Despite having uncountably many distinct tilings, they are 'ordered' (zero entropy, not chaotic)."},
  {q:"The synchronizing word for an irreducible SFT (or sofic shift) is a word w such that after reading w, the state of the automaton is known regardless of the initial state. Sofic shifts with a synchronizing word are called:",
   opts:["Mixing","Synchronized","Transitive","Aperiodic"],
   ans:1,
   exp:"A synchronized sofic shift has a synchronizing word: reading w places the automaton in a unique state. Fischer's theorem: a sofic shift is synchronized iff its minimal right-resolving presentation has a synchronizing word. This is a strictly larger class than SFTs but has particularly nice properties."},
  {q:"The topological pressure P(φ) for a Hölder potential φ on a mixing SFT equals log λ_φ where λ_φ is:",
   opts:["The spectral radius of the adjacency matrix A","The maximal eigenvalue of the weighted adjacency matrix A_φ with (A_φ)ᵢⱼ = Aᵢⱼ e^{φ([ij])}","The topological entropy","The largest Lyapunov exponent"],
   ans:1,
   exp:"For a 1-step shift with Markov potential φ = φ([ij]) depending only on the transition, P(φ) = log(spectral radius of A_φ). This generalises the SFT entropy formula (φ=0: P(0) = log ρ(A)) and is the foundation of the Gibbs measure theory for SFTs."},
],

25:[
  {q:"The notion of computational depth (logical depth, Bennett 1988) measures the computational effort needed to produce a string. A string x has high logical depth if:",
   opts:["K(x) is large","The shortest program for x takes many steps to run (deep = costly to compute but short to describe)","x is incompressible","x has high mutual information with the halting string Ω"],
   ans:1,
   exp:"Logical depth: x has depth d if the shortest program of length ≤ K(x)+c takes ≥ d steps to output x. Deep objects (like Mandelbrot set images, evolved organisms) are 'information-dense': their structure took long to compute even if the description is short."},
  {q:"Pseudorandom generators (PRGs) in complexity theory produce an n-bit string from a short seed s of length O(log n) such that no polynomial-time test can distinguish the output from truly random. The existence of PRGs is equivalent to:",
   opts:["P ≠ NP","The existence of one-way functions (OWF)","BPP = P","RP = P"],
   ans:1,
   exp:"Håstad-Impagliazzo-Levin-Luby (1999): PRGs exist iff one-way functions exist. OWFs are functions easy to compute but hard to invert (for a random input). Their existence is implied by most cryptographic hardness assumptions (discrete log, factoring, etc.)."},
  {q:"The notion of algorithmic randomness and unpredictability in chaotic systems is formalized by the result that the Bernoulli shift on k symbols preserves the property that a sequence x ∈ {0,…,k-1}^ω is Martin-Löf random iff:",
   opts:["x has equal frequency of all symbols","K(x₁…xₙ) ≥ n log k − O(1) (incompressible in base k)","x generates a dense orbit","The sequence has no periods"],
   ans:1,
   exp:"Martin-Löf random sequences in {0,…,k-1}^ω are characterised by K(xₙ) ≥ n log k − O(1)—maximal complexity (incompressible). Under the Bernoulli measure (fair k-sided coin), Lebesgue-a.e. sequence is Martin-Löf random, connecting measure theory to algorithmic randomness."},
  {q:"The Wolfram classification of cellular automata (Classes I-IV) places Class IV CA near the 'edge of chaos'. Class IV CA are characterised by:",
   opts:["All cells eventually becoming quiescent","Periodic spatial and temporal patterns","Seemingly random behavior without simple global patterns","Complex, localised patterns with persistent structures (gliders)—potentially computationally universal"],
   ans:3,
   exp:"Class IV CA (like Conway's Game of Life, Rule 110) exhibit complex localised structures that interact in complicated ways. They live at the 'edge of chaos' between simple (periodic/ordered) and fully chaotic behavior, and are candidates for (or proven to be) computationally universal."},
  {q:"The relationship between entropy and computation in thermodynamics is quantified by the fact that a reversible computer can perform computations with:",
   opts:["Zero energy dissipation in principle (Fredkin gate, Toffoli gate enable reversible computation)","Exactly kT ln 2 per gate","Energy increasing with circuit depth","Energy proportional to entropy of output"],
   ans:0,
   exp:"Reversible computing (Landauer-Bennett): logically reversible gates (Toffoli, Fredkin) can perform computations in principle without dissipating energy—information is never erased. Only logically irreversible operations (like erasure/fan-out) require energy dissipation (kT ln 2 per bit)."},
  {q:"In the context of random dynamical systems, the Furstenberg theorem on random matrix products states that for i.i.d. matrices A₁, A₂, … chosen from a distribution μ on GL(d,ℝ) satisfying irreducibility and strong irreducibility:",
   opts:["The matrix products Aₙ…A₁ are bounded","The Lyapunov exponent λ = lim_{n→∞} (1/n) log||Aₙ…A₁|| > −∞ exists and λ > −∞ a.s.","The products converge to a fixed matrix","The products have zero Lyapunov exponent"],
   ans:1,
   exp:"Furstenberg's theorem: under irreducibility + strong irreducibility, the top Lyapunov exponent λ₁ is simple and positive (the distribution is not supported on compact groups). This implies the products grow exponentially—relevant for products of transfer matrices in disordered systems."},
  {q:"The class BPP (bounded-error probabilistic polynomial time) and its relationship to entropy: a language L ∈ BPP iff there is a probabilistic TM M with:",
   opts:["P(M(x)=L(x)) ≥ 3/4 for all x","P(M(x)=L(x)) = 1 for x ∈ L and = 0 for x ∉ L","P(M(x)=1) > 1/2 for x ∈ L and = 0 for x ∉ L","P(M(x)=L(x)) ≥ 1/2 + 1/poly(n)"],
   ans:0,
   exp:"BPP: M runs in poly time and P(M(x)=L(x)) ≥ 3/4. The error can be amplified: running k independent copies and majority-voting gives error 2^{-Θ(k)}. The entropy of the coin flips used is O(poly(n)) bits, giving the resource-theoretic interpretation."},
  {q:"Logspace randomness (RL) and derandomization: Saks-Zhou (1999) showed RL ⊆ DSPACE(log^{3/2} n). The Reingold (2008) result went further, proving:",
   opts:["RL = BPL","RL = L (undirected graph reachability is in deterministic logspace)","RL = NL","RL ⊂ P strictly"],
   ans:1,
   exp:"Reingold's theorem (2008): undirected ST-connectivity (USTCON) is in L (deterministic logspace), proving RL ⊆ L, hence RL = L. The proof uses Cayley graph expanders and iterative squaring of the graph to amplify expansion. This is a complete derandomization of USTCON."},
],

26:[
  {q:"The communication complexity of computing the inner product function IP(x,y) = Σxᵢyᵢ (mod 2) over GF(2) for two n-bit strings requires Alice and Bob to exchange:",
   opts:["O(log n) bits","O(√n) bits","Θ(n) bits even with randomness","Θ(n²) bits"],
   ans:2,
   exp:"IP has randomised communication complexity Θ(n): any protocol (deterministic or randomised) computing IP with error ≤ 1/3 requires Ω(n) bits. This is proven using the rank lower bound and the fact that the communication matrix of IP (sign matrix of inner product) has rank 2^n."},
  {q:"The birthday paradox and its information-theoretic content: a random hash function h: {0,1}^n → {0,1}^{n/2} will have a collision (h(x) = h(y) for x≠y) after drawing approximately how many random samples?",
   opts:["2^n samples","2^{n/4} samples","2^{n/2} samples (≈ the square root bound)","n samples"],
   ans:2,
   exp:"Birthday paradox: collisions occur after ≈ √(2^{n/2}) = 2^{n/4}... wait, for an output of n/2 bits (2^{n/2} values), collisions occur after ≈ √(2^{n/2}) = 2^{n/4} samples. (Corrected: for output space of size N, collisions after ≈ √N = 2^{n/4} samples when N = 2^{n/2}.) This underlies birthday attacks on hash functions."},
  {q:"The ε-net theorem (from combinatorics/learning theory) states that for a set system (X,𝒮) with VC dimension d, a random sample of size O((d log(1/ε))/ε) is an ε-net with probability ≥ 3/4. This is related to information theory by:",
   opts:["VC dimension equals entropy","Sample complexity bounds use entropy of the hypothesis class: log|𝒮_n| ≤ O(d log n) (Sauer-Shelah)","ε-nets achieve Shannon capacity","VC dimension equals KL divergence"],
   ans:1,
   exp:"Sauer-Shelah lemma: |𝒮_n| ≤ O(n^d) for VC dimension d. The entropy of the hypothesis class over n points is O(d log n) bits, directly controlling the sample complexity via uniform convergence bounds. The log factor in ε-nets comes from the entropy of the class."},
  {q:"Hashing in data structures (e.g., bloom filters) uses information-theoretic arguments. A Bloom filter with n elements, m bits, and k hash functions has false positive rate approximately:",
   opts:["n/m","(1/2)^k","(1 − e^{-kn/m})^k","k/m"],
   ans:2,
   exp:"Bloom filter false positive rate: (1 − e^{-kn/m})^k ≈ (1/2)^k when k = (m/n) ln 2 (optimal k). This minimises false positives for given m and n. The optimal rate ≈ (0.6185)^{m/n}, which can be achieved with O((m/n) ln 2) hash functions."},
  {q:"The randomised quicksort algorithm has expected O(n log n) comparisons. The information-theoretic argument uses the fact that the algorithm gains at least how much information per comparison?",
   opts:["0 bits","1 bit (each comparison is a binary question)","log n bits","H(n) bits"],
   ans:1,
   exp:"Each comparison is a binary yes/no answer, providing at most 1 bit. Since sorting requires at least log₂(n!) ≈ n log n bits total, and each comparison gives ≤ 1 bit, any comparison-based sort needs ≥ n log n comparisons. Quicksort achieves this optimum in expectation."},
  {q:"The Yao minimax principle for randomised algorithms states that the expected cost of the best deterministic algorithm on the worst-case input distribution equals:",
   opts:["The worst-case randomised complexity","A lower bound on the randomised complexity: max_D min_A E_D[cost(A)] ≤ min_A max_x cost(A,x)","The deterministic complexity","The entropy of the input distribution"],
   ans:1,
   exp:"Yao's principle: max over input distributions D of (expected cost of best deterministic algorithm under D) ≤ expected cost of best randomised algorithm on worst-case input. To prove R(f) ≥ C, find D such that every deterministic algorithm has expected cost ≥ C under D."},
  {q:"Expander graphs have important connections to information theory. An (n,d,λ)-expander with second largest eigenvalue λ has the mixing time of a random walk on it proportional to:",
   opts:["n","d","log n / log(d/λ)","λ"],
   ans:2,
   exp:"Mixing time of random walk on an expander: tmix ≈ log n / log(d/λ). The spectral gap d−λ controls the exponential convergence rate; mixing time is O(log n / spectral_gap). Expanders are crucial for derandomization (converting random walks to pseudorandom walks)."},
  {q:"The counting argument for lower bounds on circuit complexity (Shannon, 1949) works by showing that most Boolean functions on n bits require circuits of size:",
   opts:["O(n)","Θ(n log n)","Ω(2ⁿ/n)","O(n²)"],
   ans:2,
   exp:"Shannon counting argument: there are 2^{2^n} functions on n bits but only ≈ (nS)^S circuits of size S. For S ≪ 2^n/n, this is less than 2^{2^n}, so most functions require circuit size Ω(2^n/n). Despite this, no explicit function is known to require super-polynomial circuits."},
],

27:[
  {q:"Weihrauch reducibility classifies the computational difficulty of mathematical theorems by asking whether one theorem can be uniformly computably reduced to another. The Intermediate Value Theorem (IVT) is Weihrauch equivalent to:",
   opts:["The halting problem","Connected choice: CC, the problem of finding a point in a non-empty connected closed set given its membership oracle","Linear search","The fixed-point theorem"],
   ans:1,
   exp:"IVT is Weihrauch equivalent to CC (connected choice on the reals): both have the same computational content. This places IVT in the Weihrauch lattice at the level of 'finding zeros of continuous functions'—computable but not computably uniform."},
  {q:"Computable analysis extends computability to real functions. A real function f: ℝ → ℝ is computable (in the sense of Turing-Weihrauch) if:",
   opts:["It is continuous","There is a Turing machine that, given a rational approximation to x within 2^{-n}, outputs a rational approximation to f(x) within 2^{-n}","It is differentiable","It maps computable reals to computable reals"],
   ans:1,
   exp:"Computable real functions: f is computable if a TM can convert ε-approximations of x into δ-approximations of f(x) uniformly in ε. This is strictly stronger than continuity. Computable functions are continuous, but not all continuous functions are computable."},
  {q:"The Mandelbrot set M is computable in the sense that there exists an algorithm to compute membership to arbitrary precision. More precisely:",
   opts:["M is a recursive set","The boundary ∂M is not computably enumerable","M is computable in the sense of computable analysis (its characteristic function is computable on the complement of ∂M)","All of ∂M is computable"],
   ans:2,
   exp:"The Mandelbrot set M is computably closed: given c, one can compute arbitrarily tight approximations to the distance from c to M. The interior can be confirmed computably (hyperbolic components are computable). The computability of ∂M is subtle—local connectedness (MLC) would help but is unproven."},
  {q:"The Post correspondence problem (PCP) is undecidable. It asks: given pairs (aᵢ, bᵢ) of strings, does there exist a sequence i₁,…,iₖ such that aᵢ₁…aᵢₖ = bᵢ₁…bᵢₖ? PCP is used to prove undecidability of:",
   opts:["Primality testing","Ambiguity of context-free grammars, non-emptiness of two-tape TM intersections","Graph isomorphism","Sorting"],
   ans:1,
   exp:"PCP is used to prove undecidability of various language-theoretic problems: ambiguity of CFGs, emptiness of the intersection of two CFLs, and many tiling problems. PCP reduces from the halting problem and is a universal undecidability 'relay station'."},
  {q:"The class of computable dynamical systems (Julia sets, Newton's method dynamics) and their decidability: for a given polynomial p(z), the problem 'does the Newton iteration starting at z₀ converge to a root?' is:",
   opts:["Always decidable in polynomial time","Computable for almost all z₀ but undecidable on the Julia set (boundary between basins)","Always undecidable","Decidable iff z₀ is rational"],
   ans:1,
   exp:"Newton's method convergence is computable for points away from the Julia set (finite escape time or convergence within a basin). On the Julia set itself, the boundary between basins, convergence is not computable in general—this is a manifestation of the Blum-Shub-Smale (BSS) undecidability."},
  {q:"The Turing degree of the halting set ∅' = {e : φₑ(e) ↓} is denoted 0'. The Turing degrees form a partial order under Turing reducibility. The jump operator A ↦ A' satisfies:",
   opts:["A' = A always","A' is strictly above A in Turing degree (A <_T A') by the relativized halting problem","A' = ∅' for all A","A' = ∅ if A is computable"],
   ans:1,
   exp:"Jump theorem: A <_T A' always (the jump is strictly harder than A, by the relativized diagonal argument). For computable A: A' ≡_T ∅'. The jump operation is fundamental in the arithmetic hierarchy: Σ⁰_n sets are exactly those computable in ∅^{(n-1)} (the n-1 fold jump of the empty set)."},
  {q:"The Blum-Shub-Smale (BSS) model of computation over ℝ (the real RAM model) can decide the Mandelbrot set membership problem in:",
   opts:["P over ℝ","Polynomial time over ℝ (using exact real arithmetic, Newton iteration converges geometrically)","Exponential time only","It is undecidable over ℝ"],
   ans:1,
   exp:"Over the BSS model (exact real arithmetic), Mandelbrot set membership is decidable in polynomial time: iterate z ↦ z²+c exactly and check if |z| > 2 within polynomially many steps. This contrasts with the classical Turing model where the boundary ∂M poses challenges."},
  {q:"Dynamical systems and descriptive complexity: the omega-limit set ω(x) of a point x under a continuous map T on a compact space is always:",
   opts:["A single point","A closed T-invariant set (non-empty, compact, connected in some cases)","An open set","Finite"],
   ans:1,
   exp:"ω(x) = ∩_{n≥0} cl{T^k(x) : k ≥ n} is always non-empty (compactness), closed, and T-invariant. It may not be connected. From a descriptive set theory perspective, the map x ↦ ω(x) (taking values in the hyperspace of closed sets) is Borel measurable but not continuous in general."},
],

28:[
  {q:"The category Meas of measurable spaces has objects (X,Σ) and morphisms measurable functions. The category of standard Borel spaces (with Borel morphisms) is particularly well-behaved because:",
   opts:["Every morphism has an inverse","It has all limits and colimits","It embeds fully faithfully into the category of Polish spaces, and standard Borel spaces are closed under countable limits/colimits","Every object is compact"],
   ans:2,
   exp:"Standard Borel spaces (Borel σ-algebra of a Polish space) form a well-behaved category: closed under countable products, countable disjoint unions, Borel subsets. The Borel isomorphism theorem: any two uncountable standard Borel spaces are isomorphic (as Borel spaces)."},
  {q:"The Kleisli category of the Giry monad G on Meas has morphisms X → Y corresponding to:",
   opts:["Measurable functions X → Y","Markov kernels: measurable maps X → G(Y) (stochastic maps assigning a probability measure on Y to each x ∈ X)","Probability measures on X × Y","Deterministic functions"],
   ans:1,
   exp:"Kleisli category of Giry: morphisms are Markov kernels κ: X → G(Y) (x ↦ κ(x,·) a probability measure on Y). Composition is by Chapman-Kolmogorov. This makes the Kleisli category the natural framework for stochastic processes and Markov chains."},
  {q:"An endofunctor F: C → C has an initial algebra α: F(A) → A characterised by Lambek's lemma, which states:",
   opts:["α is surjective","α is an isomorphism (the initial algebra is a fixed point of F)","α is the identity","A = F(∅)"],
   ans:1,
   exp:"Lambek's lemma: if (A,α) is an initial F-algebra, then α: F(A) → A is an isomorphism. Thus A ≅ F(A)—the initial algebra is a fixed point. For the functor F(X) = 1 + X (lists), the initial algebra is ℕ; for F(X) = A × X, it is A^ω (streams)."},
  {q:"The 2-category structure relevant to dynamical systems considers functors (morphisms between categories), natural transformations (morphisms between functors), and modifications. In the context of dynamical systems:",
   opts:["Dynamical systems are 1-cells between categories","A natural transformation η: F ⇒ G between two functor-representations of dynamical systems corresponds to an intertwining map (conjugacy) between the systems","The 2-cells are Lyapunov functions","Categories represent orbits"],
   ans:1,
   exp:"Natural transformations in the category of dynamical systems correspond to conjugacies or semi-conjugacies. A natural transformation η: F ⇒ G (where F and G are functors representing two systems) has components ηₓ satisfying ηₓ ∘ F(f) = G(f) ∘ ηₓ—exactly the commutativity required for an intertwining map."},
  {q:"Topos theory provides a categorical framework for logic and geometry. A Grothendieck topos is a category equivalent to a category of sheaves on a site. In dynamical systems, the topos of discrete dynamical systems (sets with endomorphism) classifies:",
   opts:["Invariant measures","Orbits, periodic points, and invariant sets via the internal logic of the topos","Topological invariants","Only fixed points"],
   ans:1,
   exp:"The topos Set^ℕ (functors ℕ → Set, or sets equipped with an endomorphism) has internal logic where 'always true' means 'eventually true'. Periodic orbits, eventual periodicity, and invariant subsets can all be described internally. This gives a topos-theoretic approach to discrete dynamics."},
  {q:"Profunctors (distributors) H: C ↛ D are defined as functors H: D^op × C → Set. They represent 'many-valued' maps and are relevant to dynamical systems as they can represent:",
   opts:["Non-deterministic transitions (set-valued maps)","Lyapunov functions","Invariant measures","Topological entropy"],
   ans:0,
   exp:"A profunctor H: C ↛ D can be seen as a bimodule or a generalised relation. In the context of non-deterministic systems, a Markov transition kernel or a set-valued map (relation) can be expressed as a profunctor. Profunctor composition generalises relational composition."},
  {q:"The Chu construction Chu(Set,2) produces a star-autonomous category (a model of multiplicative linear logic). Its objects are pairs (X,A,r) with r: X×A → 2, which can represent:",
   opts:["Measure spaces","Games (X = positions of player 1, A = strategies of player 2, r = winner)","Topological spaces","Probability distributions"],
   ans:1,
   exp:"Chu spaces (X,A,r) model various structures in a unified way: r: X×A → 2 can be membership (topology: X = points, A = open sets), strategies (game theory: X = moves, A = counter-moves, r = outcome), or binary relations. The Chu construction is a universal way to build star-autonomous categories."},
  {q:"The theory of coalgebraic modal logic provides a syntax for specifying properties of coalgebras (dynamical systems). Bisimulation between two coalgebras (X,α) and (Y,β) for functor F is a relation R ⊆ X × Y such that:",
   opts:["R is a function","R is an F-coalgebra morphism in the span: (R, F-rel(α,β): R → F(R)) where F-rel lifts R to F(R)","R contains all pairs","R is symmetric and transitive"],
   ans:1,
   exp:"Bisimulation for F-coalgebras: R is a bisimulation if there is a coalgebra structure on R making both projections π₁: R → X and π₂: R → Y into coalgebra morphisms. For transition systems (F = P, the powerset functor), this recovers the classical Park-Milner bisimulation."},
],

29:[
  {q:"The second law of thermodynamics in its information-theoretic form (via the H-theorem) states that for a closed system evolving under Boltzmann's kinetic equation, the entropy:",
   opts:["H = −∫f log f dv decreases monotonically (Boltzmann's H-theorem)","H = −∫f log f dv increases monotonically (H decreases = entropy increases)","H is constant","H oscillates"],
   ans:1,
   exp:"Boltzmann's H-theorem: H(t) = ∫f log f dv decreases monotonically (dH/dt ≤ 0), where −H = thermodynamic entropy S/k. This is the microscopic explanation of the second law. The equilibrium (Maxwell-Boltzmann) distribution is the minimum of H (maximum entropy)."},
  {q:"The work extractable from a non-equilibrium state ρ relative to a thermal bath at temperature T with free Hamiltonian H₀ is bounded by the non-equilibrium free energy:",
   opts:["W ≤ kT·S(ρ)","W ≤ F(ρ) − F(γ) = kT·D(ρ||γ) where γ ∝ e^{-H₀/kT} is the Gibbs state","W ≤ kT log(dim H)","W = Tr(H₀ρ)"],
   ans:1,
   exp:"Non-equilibrium free energy: W ≤ F(ρ)−F(γ) = kT·D(ρ||γ_{thermal}). The extractable work is bounded by kT times the KL divergence from the Gibbs state. This is the quantum/classical second law in resource-theoretic form—KL divergence measures the 'thermodynamic resource'."},
  {q:"Fluctuation theorems (Crooks, Jarzynski) are exact equalities valid arbitrarily far from equilibrium. Crooks' fluctuation theorem states that for a protocol and its time-reverse:",
   opts:["P_F(W) = P_R(−W)","P_F(W)/P_R(−W) = e^{β(W−ΔF)}","P_F(W) = e^{βW} P_R(W)","⟨W⟩ = ΔF"],
   ans:1,
   exp:"Crooks FT: P_F(W)/P_R(−W) = e^{β(W−ΔF)}, where P_F is the work distribution in the forward protocol and P_R in the reverse. Integrating both sides over W gives Jarzynski's equality ⟨e^{-βW}⟩ = e^{-βΔF}. Crooks FT is a stronger, more symmetric version."},
  {q:"The Gibbs paradox (entropy of mixing) arises when mixing two volumes of the same ideal gas. The correct resolution (via Gibbs) gives ΔS_mixing = 0 for identical gases because:",
   opts:["The entropy formula is wrong","Identical particles are indistinguishable; the correct Gibbs entropy uses 1/N! in the partition function (counting distinct microstates)","The gases have zero entropy","Mixing doesn't occur for identical gases"],
   ans:1,
   exp:"Gibbs resolution: dividing the classical partition function by N! (for identical particles) gives the Sackur-Tetrode equation for the entropy, which correctly gives ΔS_mixing = 0 for identical gases and the correct entropy of mixing for distinguishable gases. This is a precursor to quantum statistics."},
  {q:"The maximum entropy principle (MaxEnt, Jaynes 1957) states that the best probability distribution for an inference problem is the one that:",
   opts:["Minimises the entropy","Maximises the Shannon entropy subject to the constraints (known moment conditions, given information)","Equals the uniform distribution","Minimises KL divergence from a flat prior"],
   ans:1,
   exp:"Jaynes' MaxEnt: given constraints ⟨fᵢ(X)⟩ = aᵢ, the maximum entropy distribution is the Gibbs distribution P ∝ exp(Σ λᵢfᵢ(x)) (Lagrange multipliers). This is the least informative (least biased) distribution consistent with the known constraints, and is the unique maximum of H(P)."},
  {q:"The Onsager reciprocal relations in non-equilibrium thermodynamics state that near equilibrium, the phenomenological coefficients Lᵢⱼ (relating fluxes to thermodynamic forces) satisfy:",
   opts:["Lᵢⱼ = 0 for i≠j","Lᵢⱼ = Lⱼᵢ (the Onsager symmetry)","Lᵢⱼ = −Lⱼᵢ","Lᵢⱼ depends only on i"],
   ans:1,
   exp:"Onsager reciprocal relations (1931, Nobel Prize 1968): Lᵢⱼ = Lⱼᵢ. This symmetry follows from time-reversal invariance of microscopic dynamics (detailed balance). Onsager relations constrain transport coefficients (e.g., Seebeck and Peltier coefficients in thermoelectricity are equal)."},
  {q:"The Carnot efficiency η_C = 1 − T_C/T_H is the maximum efficiency of a heat engine operating between temperatures T_C and T_H. Endoreversible thermodynamics (Curzon-Ahlborn) gives the efficiency at maximum power:",
   opts:["η_C","η_CA = 1 − √(T_C/T_H)","η = T_H/(T_C+T_H)","η = (T_H−T_C)²/T_H²"],
   ans:1,
   exp:"Curzon-Ahlborn efficiency: η_CA = 1 − √(T_C/T_H). This is the efficiency at maximum power output for an endoreversible engine (one that operates with reversible internal processes but has finite-rate heat transfer). For T_C/T_H = 2/3, η_CA ≈ 0.18 while η_C ≈ 0.33."},
  {q:"The Szilard engine (1929) is a single-molecule heat engine that converts a single bit of information into kT ln 2 of work. The connection to information theory is:",
   opts:["Work = kT × entropy","Each bit of information (1 nat = kT, 1 bit = kT ln 2) can be converted to work—this is the physical value of information","The engine violates the second law","Work is independent of temperature"],
   ans:1,
   exp:"Szilard's engine: measuring which half of a container a molecule is in (1 bit of information) allows extracting kT ln 2 of work isothermally. Landauer's principle resolves the apparent paradox: erasing the measurement record requires kT ln 2 of dissipation, maintaining the second law. This quantifies the 'physical value' of a bit."},
],

30:[
  {q:"The Monge problem (1781) seeks a transport map T: X → Y (with T_*μ = ν) minimising ∫c(x,T(x))dμ. The Kantorovich relaxation allows:",
   opts:["Only deterministic maps","Transport plans γ ∈ Π(μ,ν) (joint distributions with marginals μ,ν) — a convex relaxation of the Monge problem","Only linear maps","Maps that increase entropy"],
   ans:1,
   exp:"Kantorovich relaxation (1942): replace the Monge map T with a coupling (transport plan) γ ∈ Π(μ,ν), minimising ∫c(x,y)dγ(x,y). This is a linear program (convex) and always has a solution. Under the assumptions of Brenier's theorem, the optimal coupling is induced by a map T = ∇φ."},
  {q:"The Kantorovich dual of the optimal transport problem with cost c(x,y) is:",
   opts:["max_{γ∈Π(μ,ν)} ∫c dγ","max_{(φ,ψ): φ(x)+ψ(y)≤c(x,y)} ∫φ dμ + ∫ψ dν","min_{φ convex} ∫φ dμ","max_φ ∫φ d(μ−ν)"],
   ans:1,
   exp:"Kantorovich dual: max over (φ,ψ) with φ(x)+ψ(y) ≤ c(x,y) of ∫φdμ + ∫ψdν. For c(x,y) = |x−y|, ψ = −φ and ||φ||_{Lip} ≤ 1, recovering the Wasserstein-1 = Kantorovich-Rubinstein formula: W₁(μ,ν) = max_{||f||_{Lip}≤1} |∫fdμ − ∫fdν|."},
  {q:"McCann's displacement interpolation (1997) shows that the geodesic in (P(M), W₂) between μ₀ and μ₁ is given by:",
   opts:["μ_t = (1-t)μ₀ + tμ₁ (linear interpolation)","μ_t = ((1-t)id + tT)_*μ₀ where T is the optimal transport map (push-forward along the straight-line map)","μ_t = T^t_*μ₀ for the flow T^t","μ_t = μ₀ ∗ μ₁^t"],
   ans:1,
   exp:"Displacement interpolation: μ_t = ((1-t)x + tT(x))_*μ₀ where T = ∇φ is the optimal transport map. The path t ↦ μ_t is the unique constant-speed geodesic in (P(M),W₂). This is fundamentally different from the linear interpolation μ_t = (1-t)μ₀+tμ₁ (which is the mixture, not a geodesic)."},
  {q:"Lott-Sturm-Villani theory defines Ricci curvature bounds for metric measure spaces via optimal transport. A space (X,d,m) satisfies CD(K,∞) (curvature ≥ K) if:",
   opts:["The Riemannian curvature is ≥ K","The entropy functional H_m(ρ) = ∫ρ log ρ dm is K-convex along W₂-geodesics","The Wasserstein distance satisfies W₂ ≥ K","All geodesics are straight lines"],
   ans:1,
   exp:"CD(K,∞): H_m(ρ) = ∫ρlog ρ dm is K-convex along W₂-geodesics (displacement convexity). This generalises Ricci curvature ≥ K for Riemannian manifolds to metric measure spaces (by the Otto-Villani equivalence: K-convexity of entropy ↔ Ric ≥ K for smooth manifolds)."},
  {q:"The Talagrand inequality T₂(C) states that for a probability measure μ satisfying it, every measure ν satisfies:",
   opts:["W₂(ν,μ)² ≤ C·D(ν||μ) (Wasserstein-2 distance controlled by KL divergence)","D(ν||μ) ≤ C·W₂(ν,μ)","W₂(ν,μ) = D(ν||μ)^{1/2}","W₁(ν,μ) ≤ C·H(ν)"],
   ans:0,
   exp:"Talagrand T₂: W₂(ν,μ)² ≤ 2C·D(ν||μ). The Gaussian measure satisfies T₂(1) (Otto-Villani, 2000). Talagrand T₂ is implied by the log-Sobolev inequality (LSI with constant C) and implies the Poincaré inequality. This chain LSI → T₂ → Poincaré encodes increasing concentration."},
  {q:"Cuturi's Sinkhorn algorithm for regularised optimal transport (with entropy regularisation ε·H(γ)) converges to the solution of:",
   opts:["The exact Monge problem","min_{γ∈Π(μ,ν)} ∫c dγ − ε·H(γ) (entropy-regularised OT), converging to the unregularised solution as ε → 0","The Kantorovich dual","A Wasserstein barycenter"],
   ans:1,
   exp:"Sinkhorn iterations solve the entropy-regularised OT: min_γ {∫c dγ − ε·H(γ)}. The solution is a matrix proportional to e^{-c/ε} diag(u) diag(v)^T; Sinkhorn rescales rows and columns alternately. As ε → 0, the solution converges to the unregularised OT (Brenier map). Sinkhorn runs in O(n²) iterations."},
  {q:"The Fréchet mean (barycenter) in Wasserstein space W₂(ℝᵈ) of probability measures μ₁,…,μₙ with weights λᵢ is defined as:",
   opts:["Σ λᵢ μᵢ","argmin_ν Σᵢ λᵢ W₂(ν,μᵢ)²","argmin_ν max_i W₂(ν,μᵢ)","Σᵢ λᵢ T_i where Tᵢ are transport maps"],
   ans:1,
   exp:"Wasserstein barycenter: μ̄ = argmin_ν Σᵢ λᵢ W₂²(ν,μᵢ). For Gaussian measures, the barycenter is Gaussian with parameters given by solving a fixed-point equation. Wasserstein barycenters are used in domain adaptation, atlas construction, and averaging distributions."},
  {q:"The Schrödinger bridge problem (1931/1932) seeks the most likely (maximum likelihood) evolution of a diffusion conditioned to go from μ₀ to μ₁. It is related to optimal transport by:",
   opts:["It is equivalent to the Monge problem","In the zero-temperature limit, the Schrödinger bridge converges to the optimal transport map T = ∇φ","The Schrödinger bridge is always a product measure","They are unrelated"],
   ans:1,
   exp:"Schrödinger bridge: find a measure on paths closest (in KL) to Brownian motion that has prescribed marginals at t=0 and t=1. As the noise parameter ε → 0 (temperature → 0), the Schrödinger bridge converges to the displacement interpolation (optimal transport geodesic). The finite-ε case is equivalent to entropy-regularised OT."},
],

31:[
  {q:"Van der Corput's theorem for equidistribution: if the differences {aₙ₊ₖ − aₙ} are equidistributed for every k ≥ 1, then:",
   opts:["The sequence {aₙ} is periodic","The sequence {aₙ} is equidistributed","The sequence {aₙ} converges","The sequence is eventually constant"],
   ans:1,
   exp:"Van der Corput's theorem (first difference theorem): if for every h, the sequence (aₙ₊ₕ − aₙ) is equidistributed, then aₙ is equidistributed. This is the key tool for proving equidistribution of polynomial sequences (Weyl), since the differences have lower degree."},
  {q:"Weyl's polynomial equidistribution theorem generalises Weyl's rotation theorem. It states that for a polynomial p(n) = αₖnᵏ + … + α₁n + α₀ with at least one αᵢ (i ≥ 1) irrational, the sequence {p(n)} is:",
   opts:["Dense in [0,1] but not equidistributed","Equidistributed mod 1","Eventually periodic","Computable"],
   ans:1,
   exp:"Weyl's theorem (1916): if any non-constant coefficient αᵢ of p(n) is irrational, then {p(n)} = {p(n) mod 1} is equidistributed in [0,1]. Proved by van der Corput's theorem (reducing to lower-degree polynomials) and Weyl sums |Σ e^{2πi p(n)}| = o(N)."},
  {q:"The three-distance theorem (Steinhaus, Sós) states that the N points {0}, {α}, {2α}, …, {(N-1)α} on [0,1) partition the circle into N arcs of at most:",
   opts:["N distinct lengths","2 distinct lengths","3 distinct lengths","N/2 distinct lengths"],
   ans:2,
   exp:"Three-distance theorem: for any α and N, the N points {kα} (k=0,…,N-1) partition the unit circle into N arcs of exactly 2 or 3 distinct lengths. The three lengths are determined by the continued fraction expansion of α. This is a remarkable uniformity result for irrational rotations."},
  {q:"The Birkhoff ergodic theorem for the Gauss map implies that for Lebesgue-a.e. α, the partial quotients aₙ of the continued fraction of α satisfy:",
   opts:["(1/n) Σᵢ aᵢ → Khinchin's constant (the geometric mean)","(1/n) Σᵢ log aᵢ → log K (where K is Khinchin's constant)","aₙ → ∞","aₙ are bounded"],
   ans:1,
   exp:"Birkhoff for the Gauss map with Gauss measure: (1/n) Σᵢ log aᵢ(α) → ∫₀¹ log⌊1/x⌋ dμ_Gauss(x) = log K / log 2 for a.e. α. Hence the geometric mean (a₁…aₙ)^{1/n} → K ≈ 2.685 (Khinchin's constant). The arithmetic mean is infinite (since E_Gauss[a₁] = ∞)."},
  {q:"The Denjoy-Koksma inequality for quasi-periodic functions gives a bound on the discrepancy of Birkhoff sums. For a function f of bounded variation Var(f) and the irrational rotation T_α with best approximations p_n/q_n:",
   opts:["|(1/qₙ) Σ_{k=0}^{qₙ-1} f(x+kα) − ∫f| ≤ Var(f)/qₙ","|(1/qₙ) Σ_{k=0}^{qₙ-1} f(x+kα) − ∫f| ≤ Var(f)·(qₙ)^{-1}","The sum equals ∫f for all n","The bound depends on α being Diophantine"],
   ans:1,
   exp:"Denjoy-Koksma: |Σ_{k=0}^{qₙ-1} f(kα) − qₙ∫f| ≤ Var(f). This is a sharp bound for Birkhoff sums at the denominators qₙ of best rational approximations. It quantifies how well the irrational rotation approximates the time average by the space average."},
  {q:"Furstenberg's 2×3 theorem (1967) states that the only infinite closed subsets of [0,1) invariant under both x ↦ 2x (mod 1) and x ↦ 3x (mod 1) are:",
   opts:["Finite sets","The set [0,1) itself","The Cantor set","The rationals"],
   ans:1,
   exp:"Furstenberg's ×2 ×3 conjecture (proved for closed sets, still open for ergodic measures): the only infinite closed set simultaneously invariant under ×2 and ×3 is [0,1). The measure version (only common invariant ergodic measure is Lebesgue) remains open—it is implied by normality of all numbers."},
  {q:"The continued fraction expansion connects to hyperbolic geometry via the modular surface. Periodic continued fractions correspond to:",
   opts:["Irrational numbers","Quadratic irrationals (real roots of quadratic equations with integer coefficients)","Transcendental numbers","Normal numbers"],
   ans:1,
   exp:"Periodic continued fractions ↔ quadratic irrationals (Lagrange's theorem): α has a periodic CF expansion iff α is a root of a quadratic with integer coefficients (irrational root). Under the geodesic flow on the modular surface SL(2,ℤ)\\ℍ, the periodic CF corresponds to closed geodesics."},
  {q:"Markov triples (a,b,c) with a²+b²+c² = 3abc arise in Diophantine approximation. The Markov spectrum relates to the Lagrange spectrum of approximability of reals. Numbers with Markov constant m(α) ≥ √5 are related to:",
   opts:["Normal numbers","The 'worst-case' badly approximable numbers: those with CF partial quotients all equal to 1 (golden ratio, √5-related)","Rational numbers","Periodic points of the doubling map"],
   ans:1,
   exp:"Markov spectrum: isolated points below the Hall ray {m(α) < 3} correspond to Markov numbers. The least well-approximable numbers (largest m(α)) are related to the golden ratio: m((√5-1)/2) = √5. Periodic CF expansions with all 1s (quadratic irrationals related to φ) are hardest to approximate."},
],

32:[
  {q:"The Borel hierarchy on a Polish space X starts with open and closed sets and is built by taking countable unions (Σ⁰_α) and complements (Π⁰_α). The first levels are Σ⁰₁ = open, Π⁰₁ = closed, Σ⁰₂ =",
   opts:["Closed sets","F_σ (countable union of closed sets) = {∪ Fₙ : Fₙ closed}","G_δ sets","Open sets"],
   ans:1,
   exp:"Σ⁰₂ = F_σ (countable unions of closed sets). Π⁰₂ = G_δ (countable intersections of open sets). The key examples: ℚ is F_σ in ℝ (not G_δ by Baire), ℝ\\ℚ is G_δ (countable intersection of dense open sets). The hierarchy is strict (each class is strictly larger than all previous ones)."},
  {q:"The Luzin-Suslin theorem characterises Borel subsets among analytic sets. It states that an analytic subset A of a Polish space is Borel if and only if:",
   opts:["A is closed","The complement X\\A is also analytic (A is both Σ¹₁ and Π¹₁ — bianalytic)","A is compact","A is countable"],
   ans:1,
   exp:"Luzin-Suslin (or Suslin's theorem): a subset of a Polish space is Borel iff it is both analytic (Σ¹₁) and co-analytic (Π¹₁). If A is analytic and its complement is also analytic, then A is Borel. This is a non-trivial separation theorem—there exist analytic sets that are not Borel."},
  {q:"Borel equivalence relations (countable Borel equivalence relations, CBER) are equivalence relations on Polish spaces with Borel graphs. The simplest non-trivial is E₀ (tail equivalence on {0,1}^ℕ). Dye's theorem states:",
   opts:["All CBERs are smooth (Borel reducible to equality)","E₀ is the unique minimal non-smooth CBER — every non-smooth CBER contains E₀","CBERs have only finitely many classes","All CBERs have the same Borel complexity"],
   ans:1,
   exp:"Dye's theorem (in descriptive set theory formulation): E₀ is Borel reducible to every non-smooth CBER. E₀ is not smooth (no Borel assignment of canonical elements to classes), but it is the minimum non-smooth CBER. This begins the rich theory of Borel equivalence relations."},
  {q:"The Feldman-Moore theorem in descriptive set theory states that every countable Borel equivalence relation E on a standard Borel space X is:",
   opts:["Orbit equivalent to a rotation","The orbit equivalence relation of a Borel action of a countable group Γ on X","Generated by a single Borel automorphism","Smooth"],
   ans:1,
   exp:"Feldman-Moore: every countable Borel equivalence relation E (each class is countable) arises as the orbit equivalence relation of some Borel action of a countable group Γ on X. This connects descriptive set theory to ergodic theory and is used to study invariants of CBERs."},
  {q:"The notion of Borel reducibility E ≤_B F (E is Borel reducible to F) means:",
   opts:["E and F have the same number of classes","There is a Borel function f: X → Y such that x E x' ↔ f(x) F f(x')","E ⊆ F as sets of pairs","The Borel complexity of E is less than that of F"],
   ans:1,
   exp:"E ≤_B F: a Borel reduction is a Borel function f with xEx' ↔ f(x)Ff(x'). This measures relative difficulty of classification: E ≤_B F means classifying E-classes is no harder than classifying F-classes (in a Borel way). The Borel reducibility order is rich and far from linear."},
  {q:"The Cantor-Bendixson theorem for closed subsets of ℝ states that every closed set F can be written as F = P ∪ C where:",
   opts:["P is open and C is closed","P is a perfect set (closed, no isolated points) and C is countable — F = P ∪ C (disjoint)","P is compact and C is the boundary","P and C are both closed and uncountable"],
   ans:1,
   exp:"Cantor-Bendixson: every closed subset F of ℝ (or any Polish space) decomposes uniquely as F = P ∪ C with P perfect (closed, dense-in-itself) and C = F\\P countable. The perfect set P is the Cantor-Bendixson kernel (P = F^{(α)} for some countable ordinal α)."},
  {q:"Effective descriptive set theory uses computable (recursive) versions of classical concepts. A set A ⊆ ℕ is Σ⁰₁ (recursively enumerable) in classical computability iff it is:",
   opts:["Decidable","The domain of a partial recursive function (computably enumerable)","A finite set","A recursive subset of ℕ"],
   ans:1,
   exp:"A ⊆ ℕ is Σ⁰₁ (computably enumerable, r.e.) iff A = dom(φ_e) for some partial recursive φ_e — the set of inputs on which a Turing machine halts. This is the effective analogue of open sets in the Borel hierarchy; decidable (recursive) = Σ⁰₁ ∩ Π⁰₁ = Δ⁰₁."},
  {q:"The Kleene-Brouwer ordering on descriptive set theory: a tree T on ω is well-founded iff it has no infinite branches. A set A ⊆ ℕ^ℕ is Π⁰₁ (closed) in the Baire space iff:",
   opts:["A is the set of paths through a recursive tree T","A = [T] = {paths through T} for a closed tree T (a tree closed under initial segments)","A is a finite union of closed intervals","A is the complement of an open set (in the product topology)"],
   ans:3,
   exp:"Π⁰₁ (closed in Baire space) sets are exactly the complements of Σ⁰₁ (open) sets. In the product topology on ℕ^ℕ, open sets = unions of cylinder sets. So closed sets = complements = those that can be represented as [T] = {branches of a pruned tree T} where T is closed under initial segments."},
],

};

const BASE = path.join(__dirname, 'questions');
let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);
  const m = META[ch];
  const dir = path.join(BASE, m.dir, m.ch);
  const existing = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir, existing[0]),'utf8'));
  const {chTitle, part} = sample;
  qs.forEach((q,i) => {
    const n = existing.length + i + 1;
    const file = path.join(dir, `q${String(n).padStart(2,'0')}.json`);
    fs.writeFileSync(file, JSON.stringify({ch,part,chTitle,...q},null,2)+'\n');
    console.log('wrote', path.relative(__dirname,file));
    total++;
  });
}
console.log(`\nDone. ${total} questions written.`);
