#!/usr/bin/env node
'use strict';
const fs   = require('fs');
const path = require('path');

const META = {
  33:{part:6,dir:'part-vi-frontiers',ch:'ch33-orbit-equivalence'},
  34:{part:6,dir:'part-vi-frontiers',ch:'ch34-sofic-entropy'},
  35:{part:6,dir:'part-vi-frontiers',ch:'ch35-isomorphism-problem'},
  36:{part:6,dir:'part-vi-frontiers',ch:'ch36-zimmer-program'},
  37:{part:6,dir:'part-vi-frontiers',ch:'ch37-complex-dynamics-frontiers'},
  38:{part:6,dir:'part-vi-frontiers',ch:'ch38-quantum-information-complexity'},
  39:{part:6,dir:'part-vi-frontiers',ch:'ch39-one-shot-information-theory'},
  40:{part:6,dir:'part-vi-frontiers',ch:'ch40-circuit-complexity-and-it'},
  41:{part:7,dir:'part-vii-connections',ch:'ch41-collatz-dynamics'},
  42:{part:7,dir:'part-vii-connections',ch:'ch42-quantum-computing-connections'},
  43:{part:7,dir:'part-vii-connections',ch:'ch43-hott-connections'},
};

const EXTRA = {

33:[
  {q:"Dye's theorem (1959) on orbit equivalence states that all ergodic measure-preserving transformations of a Lebesgue space that are:",
   opts:["Bernoulli shifts","Aperiodic (every point has infinite orbit)","Volume-preserving","Weakly mixing"],
   ans:1,
   exp:"Dye's theorem: any two aperiodic, ergodic, measure-preserving transformations of a standard probability space are orbit equivalent. This is the foundational result: the orbit structure (ignoring the specific transformation) is unique for aperiodic ergodic systems."},
  {q:"The full group [T] of a measure-preserving transformation T consists of all MPT S such that S(x) ∈ {T^n(x) : n ∈ ℤ} a.e. The group [T] completely determines the orbit equivalence class because:",
   opts:["[T] determines h(T)","Dye's reconstruction theorem: T and T' are OE iff [T] and [T'] are isomorphic as abstract groups","[T] = [T'] iff T = T'","[T] determines the spectrum of T"],
   ans:1,
   exp:"Dye's reconstruction: [T] as an abstract group (without its action) completely encodes the orbit equivalence class. Two ergodic MPTs are OE iff their full groups are isomorphic as abstract groups. This 'algebraisation' of OE is a profound result."},
  {q:"The cost of a countable standard equivalence relation E on (X,μ) is defined (Levitt, Gaboriau) as:",
   opts:["The number of orbits","inf{μ(Φ) : Φ generates E} = inf over graphings (measurable generating subsets of E) of their measure","The rank of the associated von Neumann algebra","The topological entropy of E"],
   ans:1,
   exp:"Cost of E: C(E) = inf{μ(graphing)} over all graphings (Borel subsets of E\\ diagonal that generate E). For a free action of Γ, C(E_Γ) = β₁^{(2)}(Γ) − χ(Γ) for many groups (Gaboriau's formula connecting cost to l²-Betti numbers)."},
  {q:"The treeable equivalence relations (those having a graphing that is a treeing, i.e., a.e. the graph is a tree) are important because:",
   opts:["They are all smooth","They include free group actions and are exactly the hyperfinite relations","They have zero cost","Free groups produce treeings, and treeability is preserved under stable orbit equivalence — connecting free group actions to the cost invariant"],
   ans:3,
   exp:"A relation is treeable if it has an a.e. acyclic graphing. Free actions of free groups Fₙ are treeable with cost n. Gaboriau showed cost is a stable OE invariant, and treeability is preserved under stable OE. This is key to distinguishing OE classes of free group actions."},
  {q:"Popa's cocycle superrigidity theorem (2007) extends Zimmer's to non-linear targets. It states that for a Bernoulli action Γ ↷ (X^Γ,μ^Γ) of a group Γ with property (T) or a product group, any measurable cocycle α: Γ×X → Λ (target group Λ):",
   opts:["Is always trivial","Is cohomologous to a group homomorphism Γ → Λ (a 'virtual homomorphism')","Depends only on the group structure of Λ","Is bounded"],
   ans:1,
   exp:"Popa's cocycle superrigidity: for Bernoulli actions of groups with property (T), every cocycle into a countable group (or an algebraic group) is cohomologous to a group homomorphism. This implies orbit equivalence implies conjugacy for many groups—a vast strengthening of Zimmer's theorem."},
  {q:"Property (T) (Kazhdan's property, 1967) for a group Γ means every unitary representation with almost-invariant vectors has invariant vectors. For orbit equivalence, property (T) groups have the rigidity property that:",
   opts:["All their actions are free","They cannot be orbit equivalent to amenable group actions","Their Bernoulli actions are not OE to each other for different entropies","Property (T) groups have cost 1"],
   ans:1,
   exp:"Groups with property (T) are not OE-equivalent to amenable group actions (by CFW theorem, all amenable actions are OE to ℤ-actions). Property (T) prevents the 'softness' of amenable OE classes. Popa's work shows property (T) implies very strong rigidity for OE."},
  {q:"Measure equivalence (ME) of groups Γ and Λ (Gromov's notion): they are ME if they have commuting, measure-preserving, free actions on a standard measure space Σ with finite-measure fundamental domains. This is related to OE by:",
   opts:["ME implies OE","OE of free ergodic actions implies ME: if Γ ↷ X and Λ ↷ X are OE free ergodic, then Γ and Λ are ME","ME and OE are unrelated","ME implies isomorphism of groups"],
   ans:1,
   exp:"Furman's theorem: if two free ergodic actions Γ ↷ X and Λ ↷ X are orbit equivalent, then Γ and Λ are measure equivalent (as abstract groups). This reduces orbit equivalence questions to group-theoretic (ME) questions. Gaboriau's l²-Betti number theorems then give ME invariants."},
  {q:"The von Neumann algebra M = L∞(X) ⋊ Γ (crossed product) associated to an ergodic free action Γ ↷ (X,μ) is a complete invariant of:",
   opts:["The measure-theoretic conjugacy class","Not a complete OE invariant in general — Murray-von Neumann showed there are non-conjugate systems with isomorphic crossed products","The topological conjugacy class","The entropy of the action"],
   ans:1,
   exp:"The crossed product L∞(X) ⋊ Γ is an OE invariant (if Γ ↷ X and Λ ↷ Y are OE, the crossed products are isomorphic). But it is not a complete invariant: non-OE actions can give isomorphic von Neumann algebras (the free group problem). Popa's deformation/rigidity theory separates many cases."},
],

34:[
  {q:"The graph entropy h_{Σ,G}(μ,T) for a sofic approximation Σ = (σᵢ: G → Sym(dᵢ)) and a partition P (finite measurable) is defined as:",
   opts:["The topological entropy of the shift","(1/dᵢ) log |Hom_μ(P, σᵢ, ε)| in the limit as i → ∞ and ε → 0","The KS entropy of the partition","The Hausdorff dimension of the orbit closure"],
   ans:1,
   exp:"Bowen's sofic entropy: hΣ(μ,T,P) = lim_{ε→0} limsup_{i→∞} (1/dᵢ) log |good models|, where good models are maps from dᵢ into the partition P that approximately reproduce the distributions of words under T. This limits to the KS entropy for amenable G."},
  {q:"The sofic entropy of a Bernoulli action G ↷ (K^G, μ^G) (with K a finite set, μ uniform) equals:",
   opts:["0","log |K|","h_KS(G-action on K^G)","The topological entropy of K^G"],
   ans:1,
   exp:"For Bernoulli actions of sofic groups, Bowen computed the sofic entropy as log|K| (for the uniform measure on K)—matching the classical formula for amenable groups. This was the first major result establishing that sofic entropy extends KS entropy beyond the amenable setting."},
  {q:"Hayes' theorem on the sofic entropy of algebraic actions (automorphisms of compact abelian groups) connected sofic entropy to:",
   opts:["Hausdorff dimension","Fuglede-Kadison determinants of elements of the group ring ℤ[G]","Lyapunov exponents","The number of fixed points"],
   ans:1,
   exp:"Hayes (building on work of Li-Thom, Deninger, Lück): the sofic entropy of the algebraic action G ↷ Ĝ_f (dual of G/f for f ∈ ℤ[G]) equals the Fuglede-Kadison logarithmic determinant log det_{L(G)}(f) when positive. This connects sofic entropy to L²-invariants (Fuglede-Kadison determinants)."},
  {q:"The independence at infinity (f-independence) condition for sofic entropy: two partitions P and Q are f-independent (for some function f) if their joint distribution approaches the product of marginals at large scales in the sofic approximation. This is related to:",
   opts:["Strong mixing","The relative sofic entropy hΣ(T,P|Q) equalling hΣ(T,P) — Q gives no additional entropy","The orbit equivalence class","The spectral gap"],
   ans:1,
   exp:"Relative sofic entropy: if P and Q are asymptotically independent in the sofic approximation, hΣ(T, P∨Q) = hΣ(T,P) + hΣ(T,Q) (additivity). This mirrors the classical KS entropy property. Independence conditions are key to the classification of Bernoulli actions via sofic entropy."},
  {q:"The measure-theoretic sofic entropy and the topological sofic entropy are related by a variational principle (under appropriate conditions). For a sofic group G and G-action on a compact space X:",
   opts:["htop_Σ(X) = sup_μ h_Σ(μ) always","htop_Σ(X) ≥ sup_μ h_Σ(μ,T) with equality for actions with a unique measure of maximal sofic entropy","htop_Σ(X) = 0 for non-amenable G","The variational principle fails for all non-amenable groups"],
   ans:1,
   exp:"The sofic variational principle: htop_Σ(X) ≥ sup_μ h_Σ(μ). Equality holds for many actions (e.g., subshifts with the specification property relative to the sofic approximation). This extends the classical variational principle to the sofic setting."},
  {q:"Austin's theorem on multiple recurrence for amenable groups and its relation to sofic entropy: the multiple Birkhoff average (1/|Φₙ|) Σ_{g∈Φₙ} T^g f₁ · T^{g²} f₂ converges in L². The connection to sofic entropy is that:",
   opts:["Multiple recurrence requires positive sofic entropy","The non-conventional ergodic averages (Host-Kra theory) use structured extensions that can be viewed as systems of bounded sofic entropy","All convergence results require amenability","Sofic entropy is irrelevant to multiple recurrence"],
   ans:1,
   exp:"Host-Kra theory of characteristic factors for multiple convergence uses nilpotent extensions (nilsystems). These are algebraic actions whose entropy structure (sofic or classical) is well-controlled. The connection is indirect but deep: nilsystems have bounded entropy and control multiple averages."},
  {q:"The f-invariant of Bowen (2010) is a more refined invariant for free group actions that takes into account the tree structure. It equals sofic entropy when computed with a specific sofic approximation coming from random homomorphisms into:",
   opts:["Symmetric groups","The free group itself via Schreier coset graphs","Alternating groups","Finite quotients"],
   ans:1,
   exp:"Bowen's f-invariant uses Schreier graphs (coset graphs) of finite-index subgroups of the free group as the sofic approximation. The f-invariant can be strictly different from hΣ for other sofic approximations, showing sofic entropy depends on the choice of Σ for non-amenable groups."},
  {q:"The stability of sofic entropy under extensions and factors: if π: (X,μ,G) → (Y,ν,G) is a G-equivariant factor map, then:",
   opts:["hΣ(μ) = hΣ(ν) always","hΣ(μ) ≥ hΣ(ν) (factors cannot have greater entropy)","hΣ(μ) ≤ hΣ(ν)","Entropy is not preserved under factors for non-amenable groups"],
   ans:1,
   exp:"For sofic entropy: factors cannot have greater entropy. hΣ(factor) ≤ hΣ(base action). This is the monotonicity of sofic entropy under factor maps, extending the classical fact h(factor) ≤ h(T) for KS entropy. Extensions can only increase entropy."},
],

35:[
  {q:"The Rokhlin-Sinai theorem states that any ergodic MPT of positive entropy has a Bernoulli factor. More precisely:",
   opts:["Every positive-entropy system is Bernoulli","For any h' < h(T), there exists a Bernoulli factor of entropy h'","Every Bernoulli factor has the same entropy as T","Every ergodic system has a Bernoulli factor of entropy 0"],
   ans:1,
   exp:"Rokhlin-Sinai theorem: for any ergodic T with h(T) > 0 and any 0 < h' ≤ h(T), T has a Bernoulli factor of entropy h'. In particular, T has Bernoulli factors of all entropies up to h(T). This builds the 'Bernoulli part' of any positive-entropy system."},
  {q:"Thouvenot's relative isomorphism theorem extends Ornstein's result. Two extensions T̃ of T and S̃ of S over isomorphic base (T ≅ S) are relatively isomorphic if they both have the relative:",
   opts:["Same entropy","VWB property (very weak Bernoulli relative to the factor)","Same spectrum","Same orbit equivalence class"],
   ans:1,
   exp:"Thouvenot's relative Ornstein: if T and S are isomorphic and T̃, S̃ are extensions satisfying the relative VWB property with the same relative entropy, then T̃ ≅ S̃ over the common factor. This is the main tool for proving isomorphism of geodesic flows and other systems."},
  {q:"The Pinsker algebra Π(T) of an ergodic MPT T is the largest T-invariant sub-σ-algebra with zero entropy. The factor T/Π(T) is the Pinsker factor, and T is a:",
   opts:["Kronecker system if Π(T) is the whole algebra","Bernoulli system if Π(T) is trivial (the zero-entropy factor is trivial, and T has completely positive entropy)","Mixing system if Π(T) = {∅,X}","Weakly mixing system if Π(T) contains the invariant sets"],
   ans:1,
   exp:"Completely positive entropy (CPE) means Π(T) is trivial: no non-trivial sub-σ-algebra has zero entropy. Bernoulli systems have CPE (Thouvenot). The Pinsker factor is the 'zero-entropy part'; factoring it out leaves a CPE system, which by Thouvenot's theorem on factors is Bernoulli up to a zero-entropy extension."},
  {q:"Ratner's theorems on orbit closures and equidistribution for unipotent flows on homogeneous spaces include the measure classification theorem, which states that every ergodic U-invariant probability measure on Γ\\G (G Lie, Γ lattice, U unipotent) is:",
   opts:["The Haar measure","An algebraic measure: the U-invariant measure on a closed orbit Γ\\ΓgH for some closed subgroup H ≤ G","A product measure","Zero"],
   ans:1,
   exp:"Ratner's measure classification (1991): every ergodic U-invariant (U = unipotent one-parameter subgroup) probability measure μ on Γ\\G is the L-invariant measure on a closed orbit xL for some closed connected subgroup L ≥ U. This is the 'algebraicity' of limits of translates by unipotent flows."},
  {q:"The entropy method in ergodic theory (Sinai, Ornstein) uses the notion of 'finitely determined' (or VWB) processes. A process {Xₙ} is finitely determined if:",
   opts:["It is determined by finitely many variables","For any ε > 0 there exists δ > 0 and N such that processes matching the joint distribution of X₁,…,X_N within δ are within ε of the original in the d̄-metric","It is periodic","It is a Markov chain"],
   ans:1,
   exp:"Finitely determined (Ornstein): the process can be 'approximated' by finite windows with respect to the d̄-metric (the Ornstein metric). Bernoulli processes are finitely determined. VWB implies FD, and FD implies the process is Bernoulli—this was Ornstein's key technical lemma in proving his isomorphism theorem."},
  {q:"Goodman's theorem extends the variational principle by showing that for expansive homeomorphisms T of compact metric spaces:",
   opts:["h_top(T) = sup_μ h_μ(T) with the supremum achieved","h_top(T) = max_μ h_μ(T) — the supremum is always achieved (maximum entropy measures exist)","h_top(T) > sup_μ h_μ(T)","h_top(T) = h_μ(T) for every ergodic μ"],
   ans:1,
   exp:"Goodman: for expansive homeomorphisms, the variational principle gives a maximum (not just supremum). The maximum entropy measure exists for expansive systems. This includes SFTs (where the Parry measure achieves the maximum) and Axiom A attractors."},
  {q:"The Isomorphism Problem for ergodic flows (continuous-time measure-preserving flows) was resolved by Ornstein-Rudolph for Bernoulli flows. Two Bernoulli flows {T^t}_{t∈ℝ} and {S^t}_{t∈ℝ} are measurably isomorphic iff:",
   opts:["They have the same topological entropy","They have the same entropy (the entropy of the time-1 map determines the flow up to isomorphism)","They have the same spectrum","They have the same Lyapunov exponents"],
   ans:1,
   exp:"Ornstein-Rudolph: the entropy of a Bernoulli flow (defined as the entropy of the time-1 map) is a complete invariant — two Bernoulli flows are measurably isomorphic iff their entropies are equal. This is the continuous-time analogue of Ornstein's theorem for Bernoulli shifts."},
  {q:"The Jewett-Krieger theorem constructs a uniquely ergodic minimal topological model for any ergodic MPT. The relevance to the isomorphism problem is that:",
   opts:["Topological conjugacy implies measure-theoretic isomorphism","Topological models are not unique: different Jewett-Krieger models of the same abstract ergodic system can be topologically inequivalent — measure-theoretic isomorphism is coarser than topological conjugacy","Unique ergodicity implies the system is Bernoulli","All models have the same topological entropy"],
   ans:1,
   exp:"The Jewett-Krieger theorem shows every abstract ergodic system has a uniquely ergodic minimal topological model, but this model is far from unique (many topologically inequivalent models exist). Topological conjugacy is strictly finer than measure-theoretic isomorphism: the latter is the 'right' notion for ergodic theory."},
],

36:[
  {q:"The Zimmer program's central question asks: what are the actions of lattices Γ in higher-rank Lie groups (like SL(n,ℝ)) on compact manifolds M? The most basic question is: what is the minimum dimension of M for a non-trivial action?",
   opts:["1 (on S¹)","n−1 (for SL(n,ℝ)-lattices, the conjecture is that actions on manifolds of dimension < n−1 are finite image)","2","log n"],
   ans:1,
   exp:"Brown-Fisher-Hurtado (2020): SL(n,ℤ) cannot act on compact manifolds of dimension < n−1 by smooth volume-preserving diffeomorphisms (the action must have finite image). This resolves the main case of the Zimmer conjecture in these dimensions."},
  {q:"The Margulis normal subgroup theorem states that for an irreducible lattice Γ in a higher-rank semisimple Lie group G, any normal subgroup N ⊲ Γ is either:",
   opts:["Trivial","Finite or of finite index in Γ","All of Γ","A lattice itself"],
   ans:1,
   exp:"Margulis's normal subgroup theorem: for lattices in higher-rank groups (ℝ-rank ≥ 2), every normal subgroup is either finite or has finite index. This 'simplicity modulo finite' shows lattices are highly rigid—far from having rich normal subgroup structure like free groups."},
  {q:"The Furstenberg-Poisson boundary of a random walk (Γ,μ) on a group Γ is the unique μ-stationary measure space (B,ν) to which the random walk converges. For lattices in semisimple Lie groups, the Poisson boundary is:",
   opts:["Trivial","The Furstenberg boundary G/P (P = minimal parabolic subgroup)","A torus","A compact group"],
   ans:1,
   exp:"Furstenberg showed that for a lattice Γ ≤ G in a semisimple Lie group, with appropriate measure μ on Γ, the Poisson boundary is G/P (the Furstenberg boundary = real flag variety). This boundary characterises the 'ideal boundary' of the random walk and is the key tool in Margulis's proof of superrigidity."},
  {q:"The Lyapunov exponents of a measurable cocycle over an ergodic action of a lattice Γ are controlled by superrigidity. Zimmer's cocycle superrigidity implies that for a representation-like cocycle, the Lyapunov exponents:",
   opts:["Are all equal","Are all zero","Are the Lyapunov exponents of a homomorphism Γ → GL(n,ℝ), since the cocycle is cohomologous to a representation","Depend on the base dynamics"],
   ans:2,
   exp:"By Zimmer's cocycle superrigidity, the cocycle α: Γ×X → GL(n,ℝ) is cohomologous to a group homomorphism ρ: Γ → GL(n,ℝ). The Lyapunov exponents of α therefore equal those of the constant cocycle x ↦ ρ(g), which are log|eigenvalues of ρ(g)| — purely algebraic quantities."},
  {q:"Stuck-Zimmer theorem (1994) concerns invariant random subgroups (IRS) of higher-rank lattices. An IRS of G is a conjugation-invariant probability measure on the space of closed subgroups Sub(G). Stuck-Zimmer showed that for higher-rank lattices Γ:",
   opts:["Every IRS is trivial","Every ergodic IRS is either a fixed subgroup (Dirac mass on a normal subgroup) or the Haar measure on Γ\\G (counting measure on conjugates of the trivial subgroup)","IRSs classify all subgroups of Γ","Every IRS is supported on amenable subgroups"],
   ans:1,
   exp:"Stuck-Zimmer: for lattices in higher-rank simple Lie groups, every ergodic IRS (invariant random subgroup) is either supported on a fixed normal subgroup of finite index, or is the uniform measure on an orbit Γ/Λ for a lattice Λ. This 'classification of IRSs' is a far-reaching generalisation of Margulis's normal subgroup theorem."},
  {q:"The Borel density theorem (for lattices) states that if Γ is a lattice in a connected semisimple Lie group G with no compact factors, then for any representation ρ: G → GL(n,ℝ):",
   opts:["ρ(Γ) is a lattice in ρ(G)","ρ(Γ) is Zariski-dense in ρ(G) — the closure of ρ(Γ) in the Zariski topology is all of ρ(G)","ρ(Γ) is finite","ρ restricted to Γ is trivial"],
   ans:1,
   exp:"Borel density theorem: Γ is Zariski dense in G (when G has no compact factors). This means there are no algebraic subgroups of G strictly between Γ and G. It is used in Margulis's proof to force a homomorphism Γ → H to extend to G."},
  {q:"The Ghys theorem on actions of higher-rank lattices on the circle S¹: for any action Γ → Homeo(S¹) of a lattice Γ in a higher-rank semisimple Lie group:",
   opts:["The action is always by isometries","The action factors through a finite group (has finite image)","The action is conjugate to a rotation action","The action is always free"],
   ans:1,
   exp:"Ghys (1999) and Burger-Monod (2002) proved (by different methods) that any action of a higher-rank lattice on S¹ factors through a finite group. This is the Zimmer conjecture in dimension 1, confirming that higher-rank lattices cannot act faithfully on S¹."},
  {q:"Super-rigidity for products: if Γ = Γ₁ × Γ₂ is a product of lattices, Margulis's theorem on 'commensurating superrigidity' shows that homomorphisms from Γ to GL(n,ℝ) that are:",
   opts:["Non-trivial on both factors must extend to G₁ × G₂","Non-trivial on exactly one factor must factor through the projection to that factor (Margulis's factor theorem)","Always trivial","Determined by their restriction to the center"],
   ans:1,
   exp:"Margulis's factor theorem for irreducible lattices Γ ≤ G₁×G₂: any irreducible lattice is algebraically 'indivisible' — homomorphisms from Γ to other groups cannot factor through either projection alone. This is a form of 'algebraic irreducibility' and is the basis for arithmeticity proofs."},
],

37:[
  {q:"The straightening theorem (Douady-Hubbard) for polynomial-like maps states that any polynomial-like map f: U' → U of degree d is hybrid equivalent to a polynomial pₐ of degree d. Hybrid equivalence means:",
   opts:["Topological conjugacy","A quasiconformal conjugacy on a neighborhood of the filled Julia set, with ∂̄φ = 0 a.e. on the filled Julia set K_f","Holomorphic conjugacy","Conformal conjugacy on the basin of infinity"],
   ans:1,
   exp:"Hybrid equivalence: φ is quasiconformal (bounded dilatation) on a neighborhood of K_f, with φ ∘ f = pₐ ∘ φ, and the Beltrami coefficient μ_φ = 0 a.e. on K_f (holomorphic on K_f). This 'mostly conformal' conjugacy is the right notion for polynomial-like maps."},
  {q:"Renormalization in complex dynamics studies polynomial-like maps appearing as iterates of a polynomial. A quadratic polynomial f(z) = z²+c is renormalizable if:",
   opts:["J(f) is connected","There exist k ≥ 2 and open sets U' ⊂⊂ U such that f^k: U' → U is a degree-2 polynomial-like map with connected filled Julia set","The critical point is periodic","c is in the Mandelbrot set"],
   ans:1,
   exp:"f is renormalizable if f^k is polynomial-like of degree 2 with connected Julia set (so that the small Julia set 'copies' the big one). Infinitely renormalizable polynomials have Cantor-like Julia sets. Renormalization is the key to understanding the Mandelbrot set's self-similarity."},
  {q:"The Fatou-Shishikura inequality bounds the number of non-repelling cycles of a rational map f of degree d. It states that the number of non-repelling periodic cycles (attracting, neutral) is at most:",
   opts:["d−1","2d−2","d","d²"],
   ans:1,
   exp:"Fatou-Shishikura inequality: #{non-repelling cycles} ≤ 2d−2 = #{critical points} (by the Riemann-Hurwitz formula). Each non-repelling cycle 'absorbs' at least one critical orbit. This is the correct bound for rational maps; for polynomials, the bound is d−1."},
  {q:"The Multibrot set M_d (the analogue of the Mandelbrot set for f_c(z) = z^d + c) satisfies: c ∈ M_d iff the orbit of the critical point 0 is bounded. For d even, M_d is:",
   opts:["Simply connected","Has d−1 'buds' around the main cardioid","Connected but not locally connected","Has the same shape as M₂"],
   ans:0,
   exp:"The Multibrot set M_d is connected (as the Mandelbrot set M₂), homeomorphic to M₂ for d ≥ 2. For d odd, the boundary consists of d-1 main components. For all d, M_d is simply connected. The self-similarity and topology of M_d parallel those of M₂."},
  {q:"Lyubich's theorem on the density of hyperbolicity in the real quadratic family fᵣ(x) = rx(1−x) states that:",
   opts:["The Mandelbrot set has positive measure","Hyperbolicity is dense in parameter space (for the real family): for almost every r ∈ [0,4], fᵣ has an attracting periodic orbit","Every r ∈ [0,4] gives a hyperbolic map","The chaotic parameters form a set of positive measure"],
   ans:1,
   exp:"Lyubich (1997): hyperbolic parameters are dense in [0,4] for the real logistic family. Moreover, the set of non-hyperbolic parameters has measure zero (Lyubich, following Graczyk-Swiatek). This is a major result toward the 'density of hyperbolicity' conjecture in the complex setting (still open)."},
  {q:"The quadratic recurrence formula for the Mandelbrot set's boundary relates external angles via the angle-doubling map. The Douady-Hubbard theorem on the Böttcher coordinate ΦM outside M states that ΦM conjugates:",
   opts:["f_c to the squaring map z ↦ z²","The map c ↦ c²+c to the squaring map on the complement of M (the Riemann mapping of ℂ̂\\M)","f_c to a rotation","The Mandelbrot set to the unit disk"],
   ans:1,
   exp:"The Böttcher coordinate ΦM: ℂ̂\\M → ℂ̂\\𝔻 is the Riemann mapping of the complement of M, conjugating the map c ↦ f_c(0)...complex. More precisely, ΦM(c) = φ_c(c) where φ_c is the Böttcher coordinate of f_c near ∞. External rays in M-complement are preimages of radii under angle doubling."},
  {q:"The Branner-Hubbard work on cubic polynomials (non-connected Julia sets) introduced tableaux and the 'wringing' deformation. Tableaux track the orbit of the critical points in the puzzle structure. When all tableau entries are:",
   opts:["Periodic","'Escaping' (mapped outside all puzzle pieces after finitely many steps), the corresponding cubic has a Cantor Julia set","'Bounded', the Julia set is connected","Preperiodic, the critical point is eventually periodic"],
   ans:1,
   exp:"In Branner-Hubbard theory: if all critical point orbits eventually escape the puzzle pieces (the tableau is 'escaping'), the Julia set is a Cantor set (totally disconnected). This generalizes Mandelbrot/Douady-Hubbard: connected Julia set ↔ bounded critical orbit, but for cubics there are two critical points."},
  {q:"The Thurston-Douady-Hubbard classification via Hubbard trees: for a postcritically finite polynomial f (all critical orbits are finite), the combinatorial type is captured by:",
   opts:["The Mandelbrot set","The Hubbard tree: a finite invariant tree containing the postcritical set, on which f acts as a graph map with specific topological properties","The Julia set topology","The rotation number of the Siegel disk"],
   ans:1,
   exp:"Hubbard tree: for a postcritically finite polynomial, the convex hull of the postcritical set in the filled Julia set K(f) is a finite invariant tree (the Hubbard tree). The restriction of f to the tree encodes the combinatorics of the polynomial up to topological conjugacy. Thurston's algorithm reconstructs f from the Hubbard tree."},
],

38:[
  {q:"The quantum chromatic number χ_q(G) of a graph G satisfies χ_q(G) ≤ χ(G) (classical chromatic number). The separation between the two is related to:",
   opts:["Graph planarity","Non-local games and quantum entanglement: there exist graphs where χ_q(G) < χ(G) (quantum players can properly color with fewer colors using entanglement)","The clique number","Degree of vertices"],
   ans:1,
   exp:"The quantum chromatic number uses entangled quantum strategies in the graph coloring game. Cameron-Montanaro-Newman-Severini-Winter showed ∃ graphs with χ_q < χ. This connects graph theory to quantum information and the study of entanglement."},
  {q:"The complexity class MIP* (multiprover interactive proofs with entangled provers) was shown by Ji-Natarajan-Vidick-Wright-Yuen (2020, MIP*=RE) to satisfy:",
   opts:["MIP* = PSPACE","MIP* = RE (recursively enumerable) — the class of all computably enumerable languages","MIP* = NP","MIP* ⊆ EXPTIME"],
   ans:1,
   exp:"MIP*=RE (JNVWY, 2020): the power of multiprover interactive proofs with quantum-entangled provers is exactly RE — all computably enumerable problems! This refuted Tsirelson's conjecture (C*-algebra), resolved Connes' embedding conjecture (negatively), and showed quantum entanglement between provers is enormously powerful."},
  {q:"Quantum money (Wiesner, 1969/1983) proposes bank notes with quantum states that cannot be counterfeited due to the no-cloning theorem. The challenge for public-key quantum money is:",
   opts:["Constructing such money is impossible","The bank must verify the note, which requires a way to check the quantum state without revealing it — this is the 'collision resistance' requirement for a quantum one-way function","The no-cloning theorem allows verification","Quantum money is equivalent to classical money"],
   ans:1,
   exp:"Public quantum money requires a verification algorithm that can test validity without revealing the state (so that counterfeiters cannot learn it from multiple verification queries). Constructing secure public quantum money under standard cryptographic assumptions is an open problem."},
  {q:"The quantum Merlin-Arthur (QMA) class and its relationship to 2-QMA (two-prover QMA): it is known that:",
   opts:["2-QMA = QMA","2-QMA = NEXP (nondeterministic exponential time)","2-QMA ⊆ QMA","2-QMA = PSPACE"],
   ans:1,
   exp:"Kobayashi-Matsumoto (2003): 2-QMA = NEXP. Having two separate quantum provers (who cannot communicate) dramatically increases power compared to one quantum prover (QMA ⊆ PSPACE). This is the quantum analogue of the classical MIP = NEXP result."},
  {q:"Random circuit sampling (as implemented in Google's quantum supremacy experiment, 2019) aims to sample from the output distribution of a random quantum circuit. The classical hardness of this task is based on:",
   opts:["Proven lower bounds on circuit depth","The conjectural hardness of computing output probabilities of random circuits (anticoncentration and average-case hardness of computing amplitudes)","P ≠ NP","The no-cloning theorem"],
   ans:1,
   exp:"The hardness of classical simulation of random circuit sampling is not proven but based on: (1) anticoncentration of output probabilities (distributed like Porter-Thomas), (2) average-case hardness of computing amplitudes (related to #P-hardness), and (3) the assumption that worst-case and average-case hardness are equivalent for this problem."},
  {q:"The Harrow-Hassidim-Lloyd (HHL) algorithm solves linear systems Ax = b with exponential speedup (under specific conditions). The quantum speedup over classical methods (like Gaussian elimination) assumes:",
   opts:["A is a dense matrix","A is sparse and well-conditioned (condition number κ = O(poly(n))), b is given as a quantum state, and the solution is accessed via expectation values of observables","All entries of A are known classically","The solution x has polynomial many non-zero entries"],
   ans:1,
   exp:"HHL: solves Ax = b in O(log(n) κ² / ε) time for sparse A with condition number κ. Assumptions: (1) efficient quantum access to A (quantum RAM or sparse oracle), (2) |b⟩ can be prepared efficiently, (3) the output is a quantum state |x⟩ from which expectation values (not all of x) are extracted. 'Quantum speed limit' caveats make classical speedup rare in practice."},
  {q:"Quantum expanders are quantum channels (completely positive trace-preserving maps) that rapidly mix quantum states. Their spectral gap λ (second largest singular value of the channel's Kraus representation) determines the mixing time as:",
   opts:["O(1/λ)","O(log(d) / (1−λ)) where d is the Hilbert space dimension — identical to classical expanders","O(d/λ)","O(λ²)"],
   ans:1,
   exp:"Quantum expander mixing: the trace-norm distance to the maximally mixed state decays as (1−λ)^t after t applications. Mixing time ≈ log(d)/(1−λ), identical in form to classical random-walk mixing. Quantum expanders are used in quantum error correction, quantum pseudorandom unitaries, and quantum complexity."},
  {q:"The quantum-classical gap in query complexity: the decision tree complexity D(f) and quantum query complexity Q(f) are related by the polynomial method. The polynomial method (Beals-Buhrman-Cleve-Mosca-de Wolf) shows:",
   opts:["Q(f) = D(f) always","D(f) = O(Q(f)^6) — any quantum algorithm can be 'dequantized' with at most polynomial overhead","Q(f) = O(D(f)^{1/2}) always","Q(f) = 0 for all constant functions"],
   ans:1,
   exp:"BBCMW polynomial method: Q(f) ≥ deg(f)/2, where deg(f) is the degree of the unique real multilinear polynomial representing f. Also D(f) ≤ Q(f)^6 (Nisan-Szegedy). The gap between Q and D can be at most polynomial, even though constant factors can show exponential quantum speedup."},
],

39:[
  {q:"The ε-hypothesis testing relative entropy D_h^ε(ρ||σ) is defined as the minimum of −log β over type-II error β, subject to type-I error α ≤ ε. Its relationship to the quantum relative entropy D(ρ||σ) in the i.i.d. limit is:",
   opts:["D_h^ε(ρ^⊗n||σ^⊗n)/n → 0","D_h^ε(ρ^⊗n||σ^⊗n)/n → D(ρ||σ) (the quantum Stein's lemma)","D_h^ε(ρ^⊗n||σ^⊗n) = nε·D(ρ||σ)","D_h^ε(ρ^⊗n||σ^⊗n)/n → H(ρ)"],
   ans:1,
   exp:"Quantum Stein's lemma (Hiai-Petz 1991, Ogawa-Nagaoka 2000): D_h^ε(ρ^⊗n||σ^⊗n)/n → D(ρ||σ) for any fixed 0 < ε < 1. This gives an operational meaning to quantum relative entropy as the optimal error exponent in quantum hypothesis testing."},
  {q:"The second-order term in optimal channel coding (normal approximation) at rate R below capacity C is characterised by the channel dispersion V. The probability of error at block length n is approximately:",
   opts:["exp(−n(C−R)²/V)","Q((C−R)√(n/V)) where Q is the Q-function (tail of the standard normal)","1 − (C−R)·n^{-1/2}","e^{-nC}"],
   ans:1,
   exp:"Polyanskiy-Poor-Verdú (2010): the optimal rate at block length n and error ε satisfies R* ≈ C − √(V/n)·Q⁻¹(ε) + O(log n / n), where V = E[(log P(Y|X)/P(Y))²] − C² is the channel dispersion. The Q-function correction gives the √n second-order term."},
  {q:"The resource theory of thermodynamics in one-shot quantum information uses 'thermal operations' (interactions with a heat bath at temperature T). The second law in this framework says a state ρ can be converted to σ by thermal operations iff:",
   opts:["S(ρ) ≤ S(σ)","The free energies satisfy F(ρ) ≥ F(σ): F = Tr[Hρ] − TS(ρ)","The Rényi divergences D_α(ρ||γ) ≥ D_α(σ||γ) for all α ≥ 0 (where γ is the Gibbs state)","ρ and σ commute with H"],
   ans:2,
   exp:"In the one-shot resource theory (Brandão-Horodecki-Oppenheim-Streltsov-Wehner 2015): ρ → σ by thermal operations iff D_α(ρ||γ) ≥ D_α(σ||γ) for all α ≥ 0 (the 'thermomajorization' condition in terms of Rényi divergences). This is an infinite family of constraints — the single free energy F(ρ) ≥ F(σ) is only the first-order (i.i.d.) condition."},
  {q:"The position-based quantum cryptography (Malaney, Chandran-Fehr-Garg-Ostrovsky 2009) proposes using location as a cryptographic credential. Its security in the quantum setting:",
   opts:["Is unconditionally secure","Can be broken by adversaries using quantum entanglement (port-based teleportation allows attacks)","Requires no quantum entanglement to attack","Is equivalent to quantum key distribution"],
   ans:1,
   exp:"Position-based quantum cryptography is insecure against quantum adversaries who pre-share entangled states. Using port-based teleportation (Ishizaka-Hiroshima), the adversary can simulate the honest prover's actions. The attack uses O(d^4) EPR pairs for d-dimensional systems."},
  {q:"Quantum reverse Shannon theorem (Bennett-Harrow-Morgan-Smolin, Winter) states that a quantum channel N can be simulated using:",
   opts:["Entanglement only","Classical communication at rate C(N) (the classical capacity) and shared entanglement at rate E(N)","Quantum communication at rate Q(N) only","Forward classical communication at rate C_→(N)"],
   ans:1,
   exp:"Quantum reverse Shannon theorem: any channel N can be simulated using E_{EA}(N) ebits of entanglement and C(N) classical bits, where E_{EA} is the entanglement-assisted classical capacity / 2. This is the 'reverse' of the classical Shannon theorem: any channel is as good as classical + entanglement of the same rates."},
  {q:"The spectrum of the one-shot channel coding problem is captured by the information spectrum (Han-Verdú). The ε-capacity is defined via the limsup and liminf of the empirical mutual information. For ergodic channels:",
   opts:["The ε-capacity equals 0 for all ε < 1","The ε-capacity equals C (the ergodic channel capacity) for all 0 < ε < 1","The ε-capacity varies with ε","The ε-capacity equals the entropy rate of the channel output"],
   ans:1,
   exp:"Information spectrum approach (Han-Verdú 1993): the ε-capacity C_ε = liminf_{n} (1/n) log M*(n,ε) equals the spectral inf-mutual information rate for stationary ergodic channels—which equals the ergodic capacity C for all ε ∈ (0,1). The power of the information spectrum method is treating non-ergodic channels."},
  {q:"The quantum information spectrum approach defines the spectral inf-entropy rate of a sequence of states {ρ_n} as:",
   opts:["lim_{n→∞} S(ρ_n)/n","H̄(ρ) = liminf_{n→∞} inf{R : Tr[ρ_n{ρ_n ≥ 2^{nR}}] → 0}","lim_{n→∞} log rank(ρ_n)/n","The von Neumann entropy of the limit state"],
   ans:1,
   exp:"Spectral inf-entropy: H̄(ρ) = sup{R : Tr[ρ_n · 1_{ρ_n ≥ 2^{nR}}] → 1}. This is the operational minimum compression rate for the state sequence {ρ_n} in the one-shot/non-i.i.d. framework. For i.i.d. states ρ^⊗n, H̄ = S(ρ) (the von Neumann entropy)."},
  {q:"The entanglement of purification E_p(ρ_{AB}) is defined as the minimum entanglement of a purification |ψ⟩_{ABB'A'} of ρ_{AB}: E_p(ρ) = min_{|ψ⟩ purification} S(AA'). It satisfies:",
   opts:["E_p ≤ S(A) always","E_p(ρ) ≤ min(S(A), S(B)) and E_p(ρ) ≥ I(A:B)/2","E_p = S(A) − S(AB)","E_p = 0 for all separable states"],
   ans:1,
   exp:"Entanglement of purification satisfies E_p(ρ) ≥ S(A)/2 and E_p ≥ I(A:B)/2. For pure states, E_p = S(A). For separable states, E_p ≥ 0 but may be positive (unlike entanglement measures). E_p appears in the AdS/CFT holographic dictionary as the minimal entanglement wedge cross-section."},
],

40:[
  {q:"The formula for circuit depth complexity via communication complexity (Karchmer-Wigderson) gives a lower bound of depth Ω(log n) for explicit functions because:",
   opts:["Every Boolean circuit has depth ≥ log n","The communication complexity of the corresponding KW game is Ω(log n) for functions with O(1)-ary trees","The KW game for iterated set disjointness requires Ω(log n) rounds and O(1) bits per round","Functions with n inputs need at least n gates"],
   ans:2,
   exp:"KW lower bounds: h(f) ≥ CC(KW_f). The KW game for the universal relation has communication complexity Θ(log n) (Alice sends a coordinate, Bob responds). For specific functions like the majority function, the KW game requires Θ(log n) bits, matching known depth lower bounds."},
  {q:"Natural proofs (Razborov-Rudich, 1994) are a framework for proving circuit lower bounds. A lower bound proof is 'natural' if it uses a property P of Boolean functions that is:",
   opts:["Random","Useful (functions outside circuit class C satisfy P), large (P holds for 2^{Ω(n)} functions), and constructive (P is computable in polynomial time)","Algebraic","Topological"],
   ans:1,
   exp:"Razborov-Rudich: a natural proof against P/poly would break pseudorandom generators (which exist if OWFs exist). Most known lower bound techniques (switching lemma, random restrictions) are natural, suggesting they cannot prove P ≠ NP. This 'natural proofs barrier' explains why circuit lower bounds are hard."},
  {q:"Monotone circuit complexity: a monotone Boolean circuit uses only AND and OR gates (no negation). Razborov (1985) proved exponential lower bounds on monotone circuit size for:",
   opts:["All monotone functions","The CLIQUE function: detecting if a graph on n vertices has a k-clique requires monotone circuits of size exp(Ω(n^{1/4}))","All functions with more than n/2 satisfying inputs","The majority function"],
   ans:1,
   exp:"Razborov's breakthrough (1985): the clique function CLIQUE_{n,k} (k = n^{1/3}) requires monotone circuit size exp(Ω(n^{1/4})). This used the approximation method (sunflower lemma). The result was strengthened by Alon-Boppana and later Rossman (2008) to size n^{Ω(k)} for k-clique."},
  {q:"The ACC⁰ class consists of constant-depth circuits with AND, OR, NOT, and MOD-m gates for arbitrary m. Williams (2011) showed:",
   opts:["ACC⁰ = P","NEXP ⊄ ACC⁰ — NEXP is not contained in ACC⁰","ACC⁰ = NC¹","ACC⁰ ⊂ TC⁰ strictly"],
   ans:1,
   exp:"Williams (2011): NEXP ⊄ ACC⁰. The proof used a clever algorithm-based approach: efficient simulation of ACC⁰ circuits yields a non-trivial NTIME(n^{polylog}) algorithm for NEXP (via satisfiability), contradicting NTIME hierarchy theorems. This is the strongest known explicit lower bound for ACC⁰."},
  {q:"The polynomial method in circuit complexity (Razborov-Smolensky) uses the fact that any depth-d AC⁰[p] circuit (with MOD-p for prime p) computing a function f can be approximated by a polynomial of degree:",
   opts:["O(log n)","O(n^{1/d}) with probability 1−1/n over random restrictions","O(log²n)","O(n)"],
   ans:0,
   exp:"Razborov-Smolensky: AC⁰[p] circuits of size S and depth d have degree O(log S · log(1/ε))^d approximating polynomials over GF(p). For constant d and S = poly(n), the approximating polynomial has degree O(log^d n). This shows MOD_q (q≠p prime) requires exponential-size AC⁰[p] circuits."},
  {q:"The connection between information complexity and communication complexity: the information complexity IC(f) is defined as the minimum information that must be revealed about the inputs during a communication protocol. It satisfies:",
   opts:["IC(f) = CC(f) always","IC(f) ≤ CC(f) and IC(f) = lim_{n→∞} CC(f^n)/n (amortised communication complexity equals information complexity)","IC(f) ≥ CC(f)","IC(f) = 0 for all f"],
   ans:1,
   exp:"Information complexity IC(f) is the amortised communication complexity: CC(f^n)/n → IC(f) as n → ∞. Always IC(f) ≤ CC(f) ≤ O(IC(f) · log n). Braverman's theorem (2012): the amortised complexity equals the information complexity. This gives a direct connection between entropy and communication."},
  {q:"The Log-rank conjecture in communication complexity states that the deterministic communication complexity D(f) is polynomially related to the log of the rank of the communication matrix M_f:",
   opts:["D(f) = log rank(M_f) always","D(f) = O(log rank(M_f)^c) for some constant c (conjectured; best known is D(f) = O(rank(M_f))","D(f) = rank(M_f)","D(f) ≥ 2^{log rank(M_f)}"],
   ans:1,
   exp:"Log-rank conjecture: D(f) = O(log^c rank(M_f)). Lower bound: D(f) ≥ log rank(M_f) (Mehlhorn-Schmidt). Upper bound: D(f) ≤ rank(M_f) (trivial). The conjecture is that D and log rank are polynomially related. Best known: D(f) = O(√rank · log rank) (Lovett 2016)."},
  {q:"Parity decision trees and their connection to Fourier analysis: the XOR lemma (Yao, Blum-Luby-Rubinfeld) states that for a function f which is hard on average for small circuits:",
   opts:["f^⊕n (the XOR of n copies) is easier","f^⊕n = f(x₁) ⊕ ... ⊕ f(xₙ) is exponentially harder — hardness amplification","Hardness is preserved exactly (not amplified)","The XOR of n copies is always hard for n ≥ 2"],
   ans:1,
   exp:"XOR lemma (direct product / hardness amplification): if f is δ-hard (best circuit succeeds with probability ≤ 1/2 + δ), then f^⊕n (XOR of n copies on separate inputs) is 2^{-Ω(n)}-hard. This amplifies weak hardness to strong hardness. The proof uses the Fourier representation of Boolean functions on the hypercube."},
],

41:[
  {q:"The 2-adic representation of the Collatz map on odd integers n is: T(n) = (3n+1)/2^{v₂(3n+1)}. In terms of the 2-adic norm |·|₂ (where |2^k m|₂ = 2^{-k} for odd m), T is:",
   opts:["An isometry","A contraction: |T(n)|₂ < |n|₂ on average (heuristically)","An expansion","Measure-preserving on ℤ₂"],
   ans:1,
   exp:"In 2-adic terms: T multiplies n by 3/2^{v₂(3n+1)}. The 2-adic valuation v₂ is geometrically distributed (heuristically), so |T(n)|₂ = 2^{-v₂(3n+1)}|n|₂ · 3 ≈ (3/4)|n|₂ on average (since E[2^{-v₂}] = 1/2). Average contraction by 3/4 < 1 explains why iterates should go to 0 (which is 1 → fixed point in ℤ₂)."},
  {q:"The Syracuse function Syr: 2ℤ+1 → 2ℤ+1 maps odd n ↦ (3n+1)/2^{v₂(3n+1)}. Its connection to the 2-adic integers ℤ₂ = lim_{←} ℤ/2^nℤ: the Collatz conjecture is equivalent to stating that for every odd n ∈ ℤ⁺, the sequence Syr^k(n):",
   opts:["Converges in ℤ₂ to 0","Eventually reaches 1 (the unique positive integer fixed point)","Is dense in ℤ₂","Is periodic in ℤ₂"],
   ans:1,
   exp:"Collatz conjecture ↔ every positive odd integer eventually maps to 1 under Syr. In ℤ₂, there are other fixed points and cycles (e.g., the negative integers give cycles like −1 → −1). The conjecture concerns the orbit of positive integers specifically."},
  {q:"Terras (1976) and others studied the distribution of the stopping time σ(n) = min{k : Syr^k(n) < n}. For most n, σ(n) behaves statistically like:",
   opts:["σ(n) ≈ n","σ(n) ≈ log n / log(4/3) (approximately geometric in log n)","σ(n) = 0 for all n","σ(n) ≈ √n"],
   ans:1,
   exp:"Heuristically, each step of Syr multiplies by 3/2^{ν} where ν is geometric(1/2), giving average factor 3/4 per step. The stopping time σ(n) ≈ log(n) / log(4/3) ≈ 2.4 log₂(n) steps on average. Empirically σ(n) = O(log n) for all n tested."},
  {q:"The Collatz graph G = (ℕ, →) where n → Syr(n) is a directed graph. The Collatz conjecture states that G has a specific tree structure. Specifically:",
   opts:["G is a tree rooted at 1","G has a unique infinite connected component but may have multiple fixed points","G is a forest with one root per cycle","G would be a tree rooted at 1 iff the conjecture holds — every positive integer eventually maps to 1"],
   ans:3,
   exp:"If the Collatz conjecture holds, every positive integer eventually reaches 1, making G a directed tree rooted at 1 (every node has exactly one outgoing edge, and all paths lead to 1). The conjecture fails iff some orbit never reaches 1 — either diverging or cycling at a different value."},
],

42:[
  {q:"Quantum error correction and topological quantum codes: the toric code (Kitaev, 1997) is a [[2n², n², d]] code on an n×n torus with:",
   opts:["d = n (distance equal to system size)","d = n (the minimum weight logical operator has weight n — going around the torus)","d = O(log n)","d = 2"],
   ans:1,
   exp:"Toric code: encodes 2 logical qubits, has distance d = n (on n×n lattice). Logical operators are non-contractible loops on the torus, which have minimum weight n. Physical error rate below threshold (≈ 1%) allows scalable fault tolerance with growing distance d = n."},
  {q:"Shor's algorithm factoring an n-bit integer N runs in time O(n² log n log log n) on a quantum computer. The key quantum step uses the quantum Fourier transform to find the period r of the function f(x) = a^x mod N for random a. The classical reduction reduces factoring to:",
   opts:["Computing gcd(a, N)","Finding the period r of f(x) = aˣ mod N: if r is even and a^{r/2} ≢ −1 mod N, then gcd(a^{r/2}±1, N) gives a non-trivial factor","Computing the Euler totient φ(N)","Finding a prime factorisation of N−1"],
   ans:1,
   exp:"Shor's classical reduction: pick random a, find period r of aˣ (mod N). If r is even and a^{r/2} ≢ ±1 (mod N), then gcd(a^{r/2}±1, N) is a non-trivial factor. The QFT finds r in O(n²) quantum gates, exponentially faster than classical period-finding (best known: sub-exponential)."},
  {q:"Quantum simulation of chemistry (the electronic structure problem): the N-electron molecule problem is QMA-complete in general, but variational methods (VQE) approximate ground states. The main challenge is that the Hilbert space dimension grows as:",
   opts:["O(N)","O(N²)","Exponentially: O(2^N) (the full Hilbert space of N two-level systems)","O(N log N)"],
   ans:2,
   exp:"The N-electron Hilbert space (with M spin-orbitals) has dimension C(M,N) ≈ 2^{M} — exponentially large. Classical methods (FCI = full configuration interaction) are exact but exponentially expensive. Quantum computers can represent the N-electron state in O(M) qubits, potentially giving exponential speedup."},
  {q:"Adiabatic quantum computation (AQC) and its relation to the circuit model: Aharonov-van Dam-Kempe-Landau-Lloyd-Regev (2007) showed that AQC and the quantum circuit model are:",
   opts:["AQC is strictly weaker (cannot solve all BQP problems)","Polynomially equivalent — each can simulate the other with at most polynomial overhead","AQC is strictly stronger (solves NP-complete problems efficiently)","AQC is equivalent to classical computation"],
   ans:1,
   exp:"ADKLLR theorem: AQC and BQP are polynomially equivalent. Any quantum circuit can be simulated by adiabatic evolution (with spectral gap Ω(1/poly(n))), and any AQC can be simulated by a quantum circuit. This means AQC is a universal quantum computing model."},
  {q:"Quantum approximate optimization algorithm (QAOA) for MaxCut uses p layers of alternating phase and mixing unitaries. At p = 1, the achievable approximation ratio for MaxCut on 3-regular graphs is:",
   opts:["1 (exact solution)","0.6924... (Farhi-Goldstone-Gutmann theoretical bound)","0.878... (Goemans-Williamson SDP bound)","0.5"],
   ans:1,
   exp:"QAOA at depth p=1: Farhi-Goldstone-Gutmann computed the expected cut value for 3-regular graphs as 0.6924... of the optimal MaxCut. This is below the Goemans-Williamson SDP bound of 0.878... (assuming Unique Games Conjecture is optimal). Higher p gives better approximations but the advantage over classical is unclear."},
  {q:"The Grover algorithm for unstructured search (finding a marked element in N items) achieves a quadratic speedup with O(√N) queries. The lower bound matching this is:",
   opts:["Ω(N) queries","Ω(√N) queries — no quantum algorithm can do better (Bennett-Bernstein-Brassard-Vazirani)","Ω(N/log N) queries","Ω(log N) queries"],
   ans:1,
   exp:"BBBV lower bound (1997): any quantum algorithm requires Ω(√N) queries to find a marked element in an unstructured database of N items. Grover's algorithm is optimal. The quadratic speedup (√N vs N classically) is the maximum possible for unstructured search."},
  {q:"Clifford+T circuits are universal for quantum computation. The T gate (π/8 phase gate) requires fault-tolerant implementation via 'magic state distillation'. The overhead of T gate implementation in a fault-tolerant architecture is approximately:",
   opts:["O(1) physical qubits per T gate","O(log²(1/ε)) T gates to implement one T gate to accuracy ε (Solovay-Kitaev), or O(log(1/ε)) with optimal decomposition (Ross-Selinger)","O(1/ε) physical qubits","Linear in the circuit depth"],
   ans:1,
   exp:"Solovay-Kitaev: any single-qubit gate can be approximated within ε using O(log^c(1/ε)) gates from a universal set (c ≈ 3.97). For T gates specifically, optimal decompositions (Ross-Selinger) achieve O(log(1/ε)) T gates. Magic state distillation adds space overhead to produce accurate T gate magic states."},
  {q:"The quantum volume (IBM metric for quantum computer quality) combines the number of qubits and the circuit depth achievable with low error. A device with quantum volume V = 2^n can reliably execute circuits of:",
   opts:["n qubits, depth n, with error below a threshold","Any circuit of n qubits","Depth n²","All Clifford circuits on n qubits"],
   ans:0,
   exp:"Quantum volume QV = 2^n means the device can reliably (with ≥ 2/3 heavy output probability) execute random square circuits of n qubits and depth n. It is a single number capturing the effective quality (combining T₂ time, gate fidelity, connectivity, and cross-talk). Doubling QV requires ~halving the error rate."},
],

43:[
  {q:"In HoTT, the Encode-Decode method proves a path space calculation. For the circle S¹, to prove π₁(S¹) = ℤ, one defines a 'code' Cover: S¹ → U by Cover(base) = ℤ and Cover(loop) =",
   opts:["refl","the successor function equiv succ: ℤ ≃ ℤ","the identity","a constant path"],
   ans:1,
   exp:"The universal cover of S¹ is the path space. In HoTT: Cover: S¹ → U with Cover(base) = ℤ and Cover(loop) = (ℤ ≃ ℤ) via succ. The encode map sends p: base = x to transport^Cover(p, 0) ∈ Cover(x). The decode map sends n ∈ ℤ to loop^n. Together they give π₁(S¹) ≅ ℤ."},
  {q:"The Seifert-van Kampen theorem in HoTT (pushout of fundamental groups) computes π₁ of a pushout A ←f B →g C as:",
   opts:["π₁(A) × π₁(C)","The pushout (amalgamated free product) of π₁(A) and π₁(C) over π₁(B) — the HoTT proof uses the recursion principle of the pushout HIT","π₁(A) + π₁(C)","A free group on |A| + |C| generators"],
   ans:1,
   exp:"HoTT van Kampen: given a pushout of spaces (represented as HITs), π₁ of the pushout is the pushout (amalgamated free product) of the fundamental groups. The proof uses the universal property of the pushout HIT and the recursion principle for π₁ (loop induction)."},
  {q:"Synthetic homotopy theory in HoTT proves theorems about homotopy groups πₙ(Sⁿ) using only type-theoretic reasoning. The Freudenthal suspension theorem states:",
   opts:["πₙ(Sⁿ) = ℤ for all n","The suspension homomorphism E: πₙ(X) → πₙ₊₁(ΣX) is an isomorphism if X is (n−1)-connected and n ≥ 2·(connectivity of X)","πₙ(Sⁿ) = 0 for n ≥ 2","All suspension maps are trivial"],
   ans:1,
   exp:"Freudenthal's theorem: if X is (k-1)-connected, the suspension E: πₙ(X) → πₙ₊₁(ΣX) is an isomorphism for n < 2k and surjection for n = 2k. In HoTT, this is proved using the 'join construction' and is one of the deepest results in synthetic homotopy theory."},
  {q:"Univalent foundations (Voevodsky) provides a set-level foundation via setoids or types with decidable equality. A 'set' in HoTT is a type A with:",
   opts:["A = B for all B","IsSet(A): all identity proofs in A are equal — (p q: a = b) → p = q (h-proposition level 1)","A has at least one element","A is decidable"],
   ans:1,
   exp:"Sets in HoTT (h-sets or 0-types): A is a set if for any a, b: A, the type a =_A b is a mere proposition (h-Prop) — any two proofs of a = b are equal. This means A has no non-trivial homotopy (no higher structure). Classical mathematics lives in sets; HoTT adds higher types above them."},
  {q:"The law of excluded middle (LEM) and axiom of choice (AC) in HoTT: both are consistent with HoTT (they hold in the set-theoretic model) but not provable. LEM for mere propositions states: for any P: Prop, ‖P‖ + ‖¬P‖. In HoTT without LEM:",
   opts:["All propositions are decidable","There exist propositions P that are neither provably true nor provably false — HoTT is constructive by default","All types are sets","AC is equivalent to LEM"],
   ans:1,
   exp:"HoTT is constructive: LEM is not provable from the type-theoretic axioms alone (it is consistent but not derivable). Adding LEM gives a 'classical' version of HoTT. Without LEM, existence proofs must be constructive (providing actual witnesses), and the propositional truncation ‖P‖ separates existence from explicit witnesses."},
  {q:"Cubical type theory (Bezem-Coquand-Huber, CCHM) provides a computational interpretation of HoTT where:",
   opts:["The univalence axiom has no computational content","The univalence axiom is provable from cubical primitives (faces, degeneracies, connections in the n-cube) and has a reduction rule (is definitionally true)","Cubical types are just simplicial types","Higher inductive types are not definable"],
   ans:1,
   exp:"Cubical type theory (CTT): introduces an interval type I with endpoints 0, 1 and face maps. Paths are functions I → A; the composition/filling operations give a constructive proof of univalence (as a theorem, not an axiom). This resolves the 'non-constructive' nature of the original HoTT book."},
  {q:"The Brunerie number β (Brunerie 2016) is an integer defined as the value of a specific HoTT-definable element β: ℤ, computed by a homotopy-theoretic argument involving π₄(S³). Its value was computed to be:",
   opts:["0","1","2","±1"],
   ans:2,
   exp:"Brunerie proved in HoTT that β ∈ {±1, ±2}, and later verified computationally (in a cubical proof assistant) that β = 2. This corresponds to the classical result π₄(S³) = ℤ/2ℤ, with the generator having Hopf invariant 2. The computation required years of work in the Agda proof assistant."},
  {q:"The cohomology of BG (classifying space of a group G) in HoTT corresponds to:",
   opts:["The group homology of G","The type K(G,1) (the Eilenberg-MacLane space), defined as the connected 1-type with π₁ = G, and the cohomology H*(K(G,1)) = group cohomology H*(G)","The homotopy groups of G","The free group on |G| generators"],
   ans:1,
   exp:"BG = K(G,1) in HoTT is defined as the groupoid quotient (or delooping) of G: a type with a point ⋆ and π₁(BG) = G. The cohomology H*(BG) computes the group cohomology H*(G). In HoTT, this is constructed via the 'delooping' using HITs or the quotient type."},
],

};

const BASE = path.join(__dirname, 'questions');
let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);
  const m = META[ch];
  const dir = path.join(BASE, m.dir, m.ch);
  const existing = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir, existing[0]),'utf8'));
  const {chTitle, part} = sample;
  qs.forEach((q,i) => {
    const n = existing.length + i + 1;
    const file = path.join(dir, `q${String(n).padStart(2,'0')}.json`);
    fs.writeFileSync(file, JSON.stringify({ch,part,chTitle,...q},null,2)+'\n');
    console.log('wrote', path.relative(__dirname,file));
    total++;
  });
}
console.log(`\nDone. ${total} questions written.`);
