#!/usr/bin/env node
'use strict';
const fs = require('fs'), path = require('path');

const META = {
  1:{part:1,dir:'part-i-foundations',ch:'ch01-real-analysis'},
  2:{part:1,dir:'part-i-foundations',ch:'ch02-measure-theory'},
  3:{part:1,dir:'part-i-foundations',ch:'ch03-topology'},
  4:{part:1,dir:'part-i-foundations',ch:'ch04-ordinary-differential-equations'},
  5:{part:1,dir:'part-i-foundations',ch:'ch05-linear-algebra'},
  6:{part:2,dir:'part-ii-dynamical-systems',ch:'ch06-topological-dynamics'},
  7:{part:2,dir:'part-ii-dynamical-systems',ch:'ch07-ergodic-theory'},
  8:{part:2,dir:'part-ii-dynamical-systems',ch:'ch08-stability-theory'},
  9:{part:2,dir:'part-ii-dynamical-systems',ch:'ch09-hyperbolic-dynamics'},
  10:{part:2,dir:'part-ii-dynamical-systems',ch:'ch10-bifurcation-theory'},
};

const EXTRA = {
1:[
  {q:"The Banach-Alaoglu theorem states that the closed unit ball of the dual space X* is compact in the weak-* topology. This is used in analysis to:",
   opts:["Prove every bounded sequence has a norm-convergent subsequence","Extract weak-* convergent subsequences from bounded sequences in X*, enabling compactness arguments in function spaces","Show X* is reflexive","Prove X is finite-dimensional"],
   ans:1,exp:"Banach-Alaoglu: B_{X*} is weak-* compact. This is the main compactness tool in functional analysis: bounded sequences in L^∞, measures, etc. have weak-* convergent subsequences. It is the foundation of many existence proofs (e.g., invariant measures via Markov-Kakutani fixed point theorem)."},
  {q:"The Sobolev embedding theorem relates Sobolev spaces W^{k,p}(Ω) to continuous function spaces. For p > n (dimension of domain), the embedding W^{1,p}(Ω) ↪ C^{0,α}(Ω) holds with α =",
   opts:["1 − n/p","n/p","p/n","1/p"],
   ans:0,exp:"Morrey's inequality: for p > n, W^{1,p}(Ω) ↪ C^{0,1−n/p}(Ω) (Hölder continuous with exponent α = 1−n/p). This allows Sobolev functions to be represented pointwise (not just a.e.) when p > n, which is crucial for regularity theory of PDEs."},
  {q:"The Fourier transform on L²(ℝ) is a unitary isometry (Parseval's theorem). For f, g ∈ L²(ℝ):",
   opts:["∫|f|² dx = ∫|f̂|² dξ (Plancherel)","||f||₂ = ||f̂||₁","f̂ ∈ L¹ for all f ∈ L²","f * g = f̂ · ĝ pointwise"],
   ans:0,exp:"Plancherel theorem: ||f̂||₂ = ||f||₂ (with appropriate normalization). The Fourier transform extends to a unitary operator on L²(ℝ). The L² theory requires extension from L¹ ∩ L² by density, unlike the L¹ case where the Fourier transform is defined directly."},
  {q:"Interpolation of operators: the Riesz-Thorin theorem states that if a linear operator T is bounded from L^{p₀} → L^{q₀} with norm M₀ and from L^{p₁} → L^{q₁} with norm M₁, then for θ ∈ (0,1), T is bounded from L^p → L^q (1/p = (1-θ)/p₀ + θ/p₁, 1/q = (1-θ)/q₀ + θ/q₁) with norm:",
   opts:["M₀ + M₁","M₀^{1-θ} M₁^θ","max(M₀,M₁)","M₀ · M₁"],
   ans:1,exp:"Riesz-Thorin interpolation: the norm in L^p→L^q is ≤ M₀^{1-θ}M₁^θ. This log-convex norm estimate is proven via the three-lines lemma for analytic functions. It is the foundation of the Calderón-Mityagin real interpolation and applies to Fourier multipliers, convolution operators, etc."},
  {q:"The Lax-Milgram theorem guarantees existence and uniqueness of weak solutions to elliptic PDEs. It states: if a(u,v) is a bilinear form on a Hilbert space H that is continuous and coercive (a(u,u) ≥ α||u||²), then for any f ∈ H*, there exists unique u ∈ H with:",
   opts:["u = f","a(u,v) = f(v) for all v ∈ H","a(u,u) = ||f||","u = α f"],
   ans:1,exp:"Lax-Milgram: under continuity |a(u,v)| ≤ M||u||||v|| and coercivity a(u,u) ≥ α||u||², the variational problem a(u,v) = f(v) ∀v has a unique solution u with ||u|| ≤ ||f||/α. This underlies existence of weak solutions to Poisson, elliptic, and parabolic PDE problems."},
  {q:"The spectral theorem for compact self-adjoint operators T: H → H on an infinite-dimensional Hilbert space states the eigenvalues {λₙ} satisfy:",
   opts:["Countably many eigenvalues, all positive","Finitely many nonzero eigenvalues","Eigenvalues accumulate only at 0, and there is an orthonormal basis of eigenvectors (possibly infinite)","No eigenvalues"],
   ans:2,exp:"Compact self-adjoint operators: the nonzero eigenvalues form a sequence λₙ → 0 (accumulating only at 0), each of finite multiplicity, and the eigenvectors form a complete orthonormal system. This is the Hilbert-Schmidt theorem — the infinite-dimensional analogue of eigendecomposition."},
  {q:"The open mapping theorem states that a surjective bounded linear operator T: X → Y between Banach spaces maps open sets to open sets. A corollary is:",
   opts:["T must be injective","If T is bijective and bounded, then T⁻¹ is also bounded (bounded inverse theorem)","T must be an isometry","Y must be finite-dimensional"],
   ans:1,exp:"Bounded inverse theorem (corollary of open mapping): if T: X → Y is a bounded bijection between Banach spaces, T⁻¹ is automatically bounded. This is used constantly: e.g., if a Banach space has two complete norms, and one is finer, they must be equivalent."},
  {q:"The Fredholm alternative for compact operators K: H → H states that for any λ ≠ 0, exactly one of the following holds:",
   opts:["(I − λK)u = 0 has a non-trivial solution","(I − λK)u = f has a unique solution for every f, or the homogeneous equation (I−λK)u = 0 has a non-trivial solution (but not both)","I − λK is always invertible","The equation has no solutions"],
   ans:1,exp:"Fredholm alternative: either (I−λK)u = f has a unique solution for all f (when 1/λ is not an eigenvalue of K), or the homogeneous equation has a non-trivial solution (1/λ is an eigenvalue). This dichotomy—analogous to linear algebra—is fundamental to integral equations and spectral theory."},
],
2:[
  {q:"The co-area formula relates integrals of functions on ℝⁿ to integrals over level sets. For a Lipschitz function u: ℝⁿ → ℝ and non-negative measurable g:",
   opts:["∫g dx = ∫_{-∞}^∞ (∫_{u=t} g/|∇u| dσ) dt","∫g|∇u| dx = ∫_{-∞}^∞ (∫_{u=t} g dσ) dt","∫g dx = ∫|∇u| dt","∫|∇u| dx = ∫ℋ^{n-1}({u=t}) dt"],
   ans:1,exp:"Co-area formula: ∫_ℝⁿ g|∇u|dx = ∫_{-∞}^∞ (∫_{u⁻¹(t)} g dℋ^{n-1}) dt. Setting g=1: ∫|∇u|dx = ∫ℋ^{n-1}({u=t})dt — the L¹ norm of the gradient equals the integral of perimeters of level sets. This is a fundamental tool in geometric measure theory and the BV space theory."},
  {q:"A function f ∈ BV([a,b]) (bounded variation) can be decomposed (Lebesgue decomposition) into:",
   opts:["Absolutely continuous and Cantor parts only","Absolutely continuous part f_{ac}, jump part f_j (step function), and Cantor part f_c (continuous, but derivative = 0 a.e.)","Continuous and discontinuous parts","Measurable and non-measurable parts"],
   ans:1,exp:"Lebesgue decomposition of BV functions: f = f_{ac} + f_j + f_c (three parts). The Cantor part is the subtle component: it is continuous, singular (derivative 0 a.e.), and carries mass on a set of measure zero (like the Cantor function). All three parts are BV."},
  {q:"The Vitali-Carathéodory theorem states that every integrable function f can be approximated by functions of the form l ≤ f ≤ u where l is upper semi-continuous and u is lower semi-continuous with:",
   opts:["∫(u−l) dx = 0","∫(u−l) dx < ε for any ε > 0","u = l everywhere","u − l is constant"],
   ans:1,exp:"Vitali-Carathéodory: for f ∈ L¹, and any ε > 0, ∃ upper semi-continuous l ≤ f and lower semi-continuous u ≥ f with ∫(u−l)dx < ε. This gives 'semi-continuous envelopes' approximating f, used in capacity theory and potential analysis."},
  {q:"The Lebesgue differentiation theorem states that for f ∈ L¹_{loc}(ℝⁿ), at Lebesgue-almost every x:",
   opts:["f is differentiable","(1/|B_r(x)|)∫_{B_r(x)} f(y) dy → f(x) as r → 0","f is continuous","The Fourier series of f converges at x"],
   ans:1,exp:"Lebesgue differentiation theorem: for a.e. x, the balls-average of f converges to f(x). x is a 'Lebesgue point' of f. The proof uses the Hardy-Littlewood maximal function. This makes the 'almost everywhere pointwise value' of an L¹ function well-defined."},
  {q:"The Borel-Cantelli lemma (first): if Σ μ(Eₙ) < ∞, then μ(lim sup Eₙ) = 0 (almost every point is in at most finitely many Eₙ). The second Borel-Cantelli lemma requires independence and states:",
   opts:["Σ μ(Eₙ) = ∞ implies μ(lim sup Eₙ) = 0","If the Eₙ are independent and Σ μ(Eₙ) = ∞, then μ(lim sup Eₙ) = 1 (a.e. point is in infinitely many Eₙ)","If Eₙ are disjoint, μ(lim sup Eₙ) = 1","Σ μ(Eₙ) < ∞ implies independence"],
   ans:1,exp:"Second Borel-Cantelli: independence + Σ μ(Eₙ) = ∞ → μ(lim sup Eₙ) = 1. This is the 'converse' under independence. Without independence, the conclusion fails (e.g., Eₙ = E for all n and μ(E) = 1 gives Σ μ(Eₙ) = ∞ but lim sup Eₙ = E — fine, but correlated)."},
  {q:"The Nikodym boundedness theorem states that if {μₙ} is a sequence of signed measures on (X,Σ) that is pointwise bounded (supₙ |μₙ(A)| < ∞ for each A ∈ Σ), then the sequence is uniformly bounded:",
   opts:["sup_{n,A} |μₙ(A)| < ∞","sup_A |μₙ(A)| → 0","Each μₙ is absolutely continuous","The sequence converges weakly"],
   ans:0,exp:"Nikodym's theorem (an instance of the uniform boundedness principle for measures): pointwise boundedness implies uniform boundedness: sup_{n,A} |μₙ(A)| < ∞. This is the 'Banach-Steinhaus theorem for measures' and is used in the theory of weak convergence of measures."},
  {q:"The Daniell integral extends the Lebesgue integral by starting from a lattice of functions and a positive linear functional. Its advantage over the Lebesgue approach is:",
   opts:["It requires fewer axioms","It allows construction of integrals on spaces without a pre-existing σ-algebra — the σ-algebra is derived from the integral","It gives a different result than Lebesgue for L¹ functions","It handles only bounded functions"],
   ans:1,exp:"Daniell's approach: start with (X, L, I) where L is a vector lattice of functions and I is a positive linear functional. Extend by monotone convergence. The measure is recovered a posteriori: μ(A) = I(1_A). This is basis for integration on locally compact spaces (Riesz representation) without first specifying a σ-algebra."},
  {q:"Prokhorov's theorem characterises relative compactness of families of probability measures on a Polish space (X,d). A family Π of probability measures is relatively compact in the weak topology if and only if it is:",
   opts:["Uniformly absolutely continuous","Tight: for every ε > 0, there exists a compact K ⊂ X with μ(K) > 1 − ε for all μ ∈ Π","Uniformly bounded in total variation","Supported on a common compact set"],
   ans:1,exp:"Prokhorov's theorem: on a Polish space, weak relative compactness ↔ tightness. Tightness means the probability mass can be concentrated in compact sets uniformly. This is the main tool for proving existence of weak limits of sequences of probability measures (e.g., invariant measures of dynamical systems)."},
],
3:[
  {q:"The long exact sequence of a pair (X, A) in singular homology reads: … → Hₙ(A) → Hₙ(X) → Hₙ(X,A) → H_{n-1}(A) → … The connecting homomorphism ∂: Hₙ(X,A) → H_{n-1}(A) is defined by:",
   opts:["∂[σ] = [∂σ] (the boundary of the cycle σ)","∂[c] = [∂c|_A] — represent a relative cycle c by its boundary (which lies in A), giving a class in H_{n-1}(A)","∂ is the zero map","∂ = inclusion-induced map"],
   ans:1,exp:"The connecting homomorphism: given a relative cycle c ∈ Cₙ(X,A) (∂c ∈ Cₙ₋₁(A)), ∂[c] = [∂c] ∈ H_{n-1}(A). This is well-defined and gives the long exact sequence. It measures how cycles in X 'rel A' bound in A — capturing the topology of the pair."},
  {q:"The universal coefficient theorem for cohomology relates H^n(X; G) to homology via:",
   opts:["H^n(X;G) = Hom(Hₙ(X), G)","0 → Ext¹(H_{n-1}(X), G) → H^n(X;G) → Hom(Hₙ(X), G) → 0 (split, not naturally)","H^n(X;G) = H_n(X) ⊗ G","H^n(X;G) = G for all n"],
   ans:1,exp:"Universal coefficient theorem: H^n(X;G) fits in a split short exact sequence 0 → Ext¹(H_{n-1}(X),G) → H^n(X;G) → Hom(H_n(X),G) → 0. The Ext term captures the 'torsion' correction. For G = ℤ, the Ext term picks up torsion in H_{n-1}(X)."},
  {q:"The Künneth formula for the homology of a product space X × Y (over a field k) gives:",
   opts:["Hₙ(X×Y;k) = ⊕_{p+q=n} Hₚ(X;k) ⊗ H_q(Y;k)","Hₙ(X×Y;k) = Hₙ(X;k) ⊕ Hₙ(Y;k)","H_*(X×Y;k) = H_*(X;k) ∧ H_*(Y;k) (smash product)","Hₙ(X×Y;k) = Hₙ(X;k) for all n"],
   ans:0,exp:"Künneth over a field: Hₙ(X×Y;k) = ⊕_{p+q=n} Hₚ(X;k) ⊗ H_q(Y;k). Over ℤ there is a correction term Tor(H_{p-1}(X), H_q(Y)). Over a field, the graded homology is the tensor product of graded homologies — a clean multiplicative structure."},
  {q:"The de Rham cohomology H^k_{dR}(M) of a smooth manifold M is defined using differential forms. The de Rham theorem states:",
   opts:["H^k_{dR}(M) = 0 for k > dim M","H^k_{dR}(M) ≅ H^k_{sing}(M; ℝ) (de Rham cohomology equals singular cohomology with real coefficients)","H^k_{dR}(M) is always ℝ","Every closed form is exact"],
   ans:1,exp:"de Rham's theorem: H^k_{dR}(M) ≅ H^k_{sing}(M;ℝ) via integration of k-forms over k-cycles. This profound theorem connects differential geometry (forms) to algebraic topology (singular cohomology), proved using the Mayer-Vietoris sequence and the Poincaré lemma."},
  {q:"Poincaré duality for a closed oriented n-manifold M gives a natural isomorphism:",
   opts:["H^k(M;ℤ) ≅ H^k(M;ℤ)","H^k(M;ℤ) ≅ H_{n-k}(M;ℤ) (cohomology in degree k ↔ homology in degree n-k)","H^k(M) ≅ H^{n-k}(M)","Hₖ(M) ≅ Hₖ(M)"],
   ans:1,exp:"Poincaré duality: for a closed oriented n-manifold, [M] ∩ ·: H^k(M) → H_{n-k}(M) is an isomorphism (cap product with the fundamental class). Over ℤ, one must account for Ext/Tor corrections. Over a field, H^k(M;k) ≅ H_{n-k}(M;k)."},
  {q:"The Seifert fibration of a 3-manifold decomposes it into circles. The Euler class of the fibration is an obstruction to:",
   opts:["The fibration being a product","The existence of a section (global cross-section of the S¹ bundle) — the fibration is trivial iff Euler class = 0","The manifold being orientable","The base being simply connected"],
   ans:1,exp:"Euler class e(E) ∈ H²(B;ℤ) for an oriented S¹ bundle E → B measures the twisting. A section exists iff e = 0. For the Hopf fibration S³ → S², e is the generator of H²(S²) = ℤ, so no section exists. Seifert fibrations generalise this to orbifold bases."},
  {q:"The Leray-Hirsch theorem gives conditions for the cohomology of a fiber bundle E → B with fiber F to split as H*(E) ≅ H*(B) ⊗ H*(F). The conditions are:",
   opts:["The fiber is contractible","The inclusion of each fiber F → E_b induces a surjection H*(E) → H*(F), and H*(F) is a free module","The base is simply connected","The bundle is trivial"],
   ans:1,exp:"Leray-Hirsch: if i*: H*(E) → H*(F) is surjective (equivalently, there exist global cohomology classes on E restricting to a basis for each fiber), then H*(E) ≅ H*(B) ⊗ H*(F) as H*(B)-modules. This applies to sphere bundles, flag bundles, etc."},
  {q:"A CW-complex is built by attaching cells. The cellular chain complex C_n = H_n(X^n, X^{n-1}) (relative homology of skeleta) has boundary maps d_n: C_n → C_{n-1} given by the degrees of attaching maps. The homology of this chain complex:",
   opts:["Is always the same as singular homology","Equals singular homology H_*(X) (cellular homology theorem)","Depends on the CW structure chosen","Is isomorphic to cohomology"],
   ans:1,exp:"Cellular homology theorem: the homology of the cellular chain complex equals the singular homology of X. This gives a practical computational tool: the cellular boundary map has matrix entries given by degrees of compositions of attaching and projection maps, often computable from geometric data."},
],
4:[
  {q:"Gronwall's inequality: if u(t) ≤ α(t) + ∫₀ᵗ β(s)u(s)ds with β ≥ 0, then:",
   opts:["u(t) ≤ α(t) + ∫₀ᵗ β(s)α(s)ds","u(t) ≤ α(t) · exp(∫₀ᵗ β(s)ds)","u(t) ≤ max α + t · max β","u(t) ≤ α(t)"],
   ans:1,exp:"Gronwall's inequality: u(t) ≤ α(t)exp(∫₀ᵗ β(s)ds). This is the fundamental comparison principle for differential inequalities. It is used ubiquitously to prove uniqueness and continuous dependence on parameters for ODEs, and to bound solutions of perturbed systems."},
  {q:"The Picard-Lindelöf theorem guarantees unique local solutions to ẋ = f(x,t), x(t₀) = x₀ when f is:",
   opts:["Measurable in t","Locally Lipschitz in x and continuous in t","Differentiable in x","Bounded and measurable"],
   ans:1,exp:"Picard-Lindelöf: local Lipschitz in x + continuity in t → unique local solution. The proof uses the Banach contraction on the space of continuous functions. The condition is sharp: without Lipschitz (e.g., f = |x|^{1/2}), uniqueness fails."},
  {q:"For a 2D Hamiltonian system with H(x,y) as a conserved quantity, the phase portrait near an elliptic fixed point (center) consists of:",
   opts:["Spiraling orbits converging to the fixed point","Closed orbits (level curves of H) surrounding the fixed point","Straight-line orbits","Heteroclinic orbits"],
   ans:1,exp:"Near an elliptic fixed point (purely imaginary eigenvalues), H is locally a positive definite quadratic, so level sets are closed curves. The orbits are these level curves — closed trajectories (periodic orbits). Nonlinear corrections may break this picture (only Lyapunov stability, not asymptotic), but the orbits remain closed to all orders in the integrable case."},
  {q:"The method of characteristics for a first-order PDE uₜ + c(x,t)uₓ = 0 gives the solution along characteristic curves x = x(t) defined by dx/dt = c(x,t). The solution satisfies:",
   opts:["u is constant along characteristics: du/dt = 0","u increases linearly along characteristics","u(x(t),t) = u(x(0),0) for each characteristic","Characteristics are always straight lines"],
   ans:2,exp:"Along the characteristic curve x(t) (with dx/dt = c): du/dt = uₜ + ẋuₓ = uₜ + c·uₓ = 0. So u is constant along each characteristic: u(x(t),t) = u(x₀,0). This reduces the PDE to a family of ODEs. Characteristics may cross (causing shocks) when c depends on u."},
  {q:"The Hopf-Rinow theorem in Riemannian geometry states that a connected Riemannian manifold is geodesically complete (all geodesics extend indefinitely) if and only if it is:",
   opts:["Simply connected","Complete as a metric space (every Cauchy sequence converges)","Compact","Flat (zero curvature)"],
   ans:1,exp:"Hopf-Rinow: geodesic completeness ↔ metric completeness ↔ 'every closed bounded set is compact' (Heine-Borel property). Additionally, geodesic completeness implies any two points can be joined by a length-minimizing geodesic."},
  {q:"The Hamiltonian formulation of classical mechanics uses the Legendre transform to pass from Lagrangian L(q,q̇,t) to Hamiltonian H(q,p,t). The canonical equations are:",
   opts:["q̇ = ∂H/∂q, ṗ = −∂H/∂p","q̇ = ∂H/∂p, ṗ = −∂H/∂q","q̈ = −∂H/∂q","q̇ = p, ṗ = −∂H/∂q"],
   ans:1,exp:"Hamilton's equations: q̇ = ∂H/∂p (velocity from momentum), ṗ = −∂H/∂q (force = negative gradient of H). These are first-order equations on phase space (q,p) ∈ T*M. They preserve the symplectic form dq∧dp and (when H has no explicit t-dependence) the total energy H."},
  {q:"The Euler-Lagrange equation for a functional J[y] = ∫ₐᵇ F(x,y,y')dx is:",
   opts:["∂F/∂y = 0","∂F/∂y − d/dx(∂F/∂y') = 0","d/dx(∂F/∂y') = 0","∂F/∂x = 0"],
   ans:1,exp:"Euler-Lagrange equation: ∂F/∂y − d/dx(∂F/∂y') = 0. This is the necessary condition for y to be an extremum of J[y] with fixed endpoints. Derived by setting the first variation δJ = 0 and using integration by parts. It is a second-order ODE for y(x)."},
  {q:"Sturm comparison theorem: if p(x) > q(x) on [a,b] and u'' + p(x)u = 0, v'' + q(x)v = 0, then between any two consecutive zeros of v, u has at least:",
   opts:["No zeros","Exactly one zero","One zero (u oscillates faster than v when p > q)","Two zeros"],
   ans:2,exp:"Sturm comparison: if p ≥ q (with p > q somewhere), solutions of the equation with larger coefficient oscillate at least as fast. Between any two consecutive zeros of v (satisfying q-equation), u (satisfying p-equation) must have at least one zero. This is the basis for oscillation theory of Sturm-Liouville problems."},
],
5:[
  {q:"The matrix exponential e^A is defined by the power series Σ Aⁿ/n!. For commuting matrices A, B (AB = BA):",
   opts:["e^{A+B} = e^A · e^B","e^{A+B} ≠ e^A · e^B in general","e^{A+B} = e^A + e^B","e^{A+B} = max(e^A, e^B)"],
   ans:0,exp:"For commuting A, B: e^{A+B} = e^A·e^B. Without commutativity, the Baker-Campbell-Hausdorff formula applies: e^A·e^B = e^{A+B+[A,B]/2+...}. The matrix exponential maps the Lie algebra to the Lie group and is fundamental in solving linear ODEs ẋ = Ax with solution x(t) = e^{At}x₀."},
  {q:"A matrix A is diagonalizable over ℂ if and only if the minimal polynomial m_A has:",
   opts:["Degree equal to the algebraic multiplicity of each eigenvalue","No repeated roots (each eigenvalue appears with multiplicity 1 in m_A)","All roots of absolute value 1","All roots real"],
   ans:1,exp:"Diagonalizability ↔ m_A has no repeated roots ↔ the Jordan form has no Jordan blocks of size > 1 ↔ the algebraic and geometric multiplicities of each eigenvalue coincide. This is equivalent to the eigenspace decomposition spanning the full space."},
  {q:"The condition number κ(A) = ||A||·||A⁻¹|| (in any consistent matrix norm) measures numerical sensitivity. For a linear system Ax = b, a perturbation δb in b causes a relative error in x bounded by:",
   opts:["||δx||/||x|| ≤ κ(A) · ||δb||/||b||","||δx|| = κ(A)||δb||","||δx||/||x|| ≤ ||δb||/||b||","||δx|| ≤ ||δb||"],
   ans:0,exp:"Condition number bound: ||δx||/||x|| ≤ κ(A)||δb||/||b||. A large κ(A) means the system is ill-conditioned: small relative errors in b can cause large relative errors in x. For Gaussian elimination, rounding errors of magnitude ε_machine produce x errors of order κ(A)·ε_machine."},
  {q:"The Gram-Schmidt process orthogonalises a linearly independent set {v₁,...,vₙ} to produce {u₁,...,uₙ}. In terms of matrix factorisations, this is equivalent to the:",
   opts:["LU factorisation of A","QR factorisation: A = QR with Q orthogonal and R upper triangular","Cholesky factorisation: A = LLᵀ","SVD of A"],
   ans:1,exp:"Gram-Schmidt gives the QR factorisation: if A = [v₁|…|vₙ], then A = QR where Q = [u₁|…|uₙ] (orthonormal columns) and R is upper triangular with positive diagonal (encoding the projection coefficients). QR factorisation is numerically more stable than normal equations for least squares."},
  {q:"A Hermitian positive semidefinite (PSD) matrix A satisfies x*Ax ≥ 0 for all x. It is PSD if and only if:",
   opts:["All eigenvalues are non-negative","det(A) ≥ 0","All diagonal entries are non-negative","All principal submatrices have non-negative determinant"],
   ans:0,exp:"PSD ↔ all eigenvalues ≥ 0 ↔ A = B*B for some matrix B ↔ all leading principal minors ≥ 0 (Sylvester's criterion for PSD). Note: all eigenvalues ≥ 0 is the correct characterization; checking all principal minors (not just leading ones) may be needed for PSD vs PD."},
  {q:"The Schur decomposition states that any matrix A ∈ Mₙ(ℂ) is unitarily similar to an upper triangular matrix:",
   opts:["A = UDU* with D diagonal","A = QTQ* with Q unitary and T upper triangular (Schur form)","A = LU with L lower triangular","A = QRQ* with R symmetric"],
   ans:1,exp:"Schur decomposition: every complex matrix A is unitarily similar to an upper triangular T (Schur form): A = QTQ*. The diagonal of T gives the eigenvalues (in any order). Unlike eigendecomposition, Schur form always exists. It is the basis for the QR algorithm for eigenvalue computation."},
  {q:"For symmetric positive definite A, the conjugate gradient (CG) method for solving Ax = b converges in at most n steps (exactly) and in practice converges faster. The convergence rate is determined by:",
   opts:["The condition number κ(A) = λ_max/λ_min","The spectral radius of A − I","The rank of A","The dimension n"],
   ans:0,exp:"CG convergence: the error after k steps satisfies ||e_k||_A ≤ 2((√κ−1)/(√κ+1))^k ||e₀||_A. The rate (√κ−1)/(√κ+1) → 1 as κ → ∞ (slow) and → 0 as κ → 1 (fast). Preconditioning reduces κ, dramatically accelerating convergence."},
  {q:"The Weyl chamber and root system of a Lie algebra g partition the weight space. For sl(2,ℂ) (the simplest non-abelian Lie algebra), the representation with highest weight n has dimension:",
   opts:["n","n+1","2n+1","n²"],
   ans:1,exp:"For sl(2,ℂ): the irreducible representation V(n) with highest weight n has dimension n+1. It is spanned by basis vectors v₀,...,vₙ with H·vₖ = (n−2k)vₖ. For n=0: dim=1 (trivial), n=1: dim=2 (standard), n=2: dim=3 (adjoint representation of so(3))."},
],
6:[
  {q:"The Furstenberg correspondence principle in combinatorics: for a set A ⊆ ℕ of positive upper density d*(A) > 0, the correspondence provides a measure-preserving system (X,μ,T) and a set Ã with μ(Ã) = d*(A) such that d*(A ∩ (A-n₁) ∩ ... ∩ (A-nₖ)) ≥ μ(Ã ∩ T^{-n₁}Ã ∩ ... ∩ T^{-nₖ}Ã). This is used to prove:",
   opts:["A is periodic","Szemerédi's theorem: A contains arbitrarily long arithmetic progressions (via ergodic multiple recurrence)","A is a Sidon set","A contains all pairs"],
   ans:1,exp:"Furstenberg's correspondence + multiple recurrence theorem: since μ(Ã ∩ T^{-n}Ã ∩ T^{-2n}Ã ∩ ...) > 0 for some n > 0 (by multiple recurrence), the set A ∩ (A-n) ∩ (A-2n) ∩ ... is non-empty, giving arithmetic progressions in A. This is Furstenberg's ergodic proof of Szemerédi's theorem (1977)."},
  {q:"The concept of a Toeplitz sequence in topological dynamics: a sequence x ∈ A^ℤ is Toeplitz if for every position n ∈ ℤ, there exists a period p > 0 such that x(n) = x(n+kp) for all k ∈ ℤ (each position is 'periodic', but with different periods). Toeplitz subshifts are:",
   opts:["Always SFTs","Minimal and almost 1-to-1 extensions of their maximal equicontinuous factor (an odometer)","Always Bernoulli","Always of positive entropy"],
   ans:1,exp:"Toeplitz subshifts are minimal (the orbit closure of a Toeplitz sequence) and almost 1-to-1 extensions of an odometer (an inverse limit of cyclic groups). They have zero entropy and serve as examples of minimal but non-uniquely ergodic systems (in some cases)."},
  {q:"The Veech dichotomy for translation surfaces (flat surfaces with conical singularities) states that for a Veech surface, every direction θ is either:",
   opts:["Completely ergodic and minimal in direction θ, or has all flow lines closed (periodic direction)","Ergodic or mixing","Minimal or periodic","Dense or nowhere dense"],
   ans:0,exp:"Veech dichotomy: for a Veech surface (one with a large group of affine symmetries, the Veech group), every direction is either (1) a saddle connection direction (all trajectories periodic, i.e., the surface decomposes into cylinders) or (2) ergodic and minimal (the directional flow is minimal and uniquely ergodic)."},
  {q:"Uniform recurrence (almost periodicity in the sense of Bohr-Birkhoff) for a point x in a topological dynamical system means: for every ε > 0, the set of return times {n : d(T^nx,x) < ε} is:",
   opts:["Finite","A syndetic set (has bounded gaps)","Dense","A set of positive density"],
   ans:1,exp:"Uniform recurrence = syndetic return times: {n : T^nx ∈ U} has bounded gaps for every open U ∋ x. This is equivalent to x being a minimal point (its orbit closure is minimal). Syndetic return times imply the system is 'almost periodic' in the topological sense."},
  {q:"The maximal equicontinuous factor of a minimal topological dynamical system (X,T) is the quotient by the proximal relation P and the regionally proximal relation RP. For a distal system:",
   opts:["The system IS its own maximal equicontinuous factor","P = {(x,x)} (no non-trivial proximal pairs), and the maximal equicontinuous factor equals the system if it is equicontinuous","All points are proximal","The system has no equicontinuous factor"],
   ans:1,exp:"For a distal system (no non-trivial proximal pairs), P = Δ (diagonal). The maximal equicontinuous factor of an equicontinuous distal system is the system itself — a group rotation. For general distal systems, the equicontinuous structure relation (= RP) determines the maximal equicontinuous factor."},
  {q:"Glasner's theorem on the structure of minimal flows: every minimal equicontinuous flow is (topologically conjugate to) a rotation on a compact abelian group. The group is:",
   opts:["Always ℤ_p for some prime p","The Ellis group of the system, which equals the enveloping semigroup (which is a group for equicontinuous systems)","The fundamental group of X","The automorphism group of X"],
   ans:1,exp:"Minimal equicontinuous flows: the enveloping semigroup (Ellis semigroup) E(X) is a compact abelian group, and the flow is conjugate to left-multiplication on E(X). This group is compact, metrizable when X is metrizable, and encodes all the equicontinuous dynamics."},
  {q:"Mean equicontinuity (m.e.c.) is a weakening of equicontinuity using Cesàro averages. A minimal system is mean equicontinuous if and only if it is:",
   opts:["Equicontinuous","Weakly almost periodic (the family {T^n} is relatively weakly compact in C(X))","Uniquely ergodic and has discrete spectrum","Positively expansive"],
   ans:2,exp:"Mean equicontinuity (Li-Tu-Ye): a minimal system is m.e.c. iff it is uniquely ergodic with discrete (pure point) spectrum — all eigenvalues of the Koopman operator. This connects topological mean equicontinuity to the measure-theoretic pure point spectrum condition."},
  {q:"The Jewett-Krieger-Weiss theorem refines Jewett-Krieger: every aperiodic ergodic measure-preserving system is measurably isomorphic to a strictly ergodic (uniquely ergodic minimal) topological system. Moreover, the topological system can be chosen to be:",
   opts:["A subshift of finite type","A subshift (closed shift-invariant subset of A^ℤ for a finite alphabet A)","A rotation on a compact group","A minimal homeomorphism of the Cantor set only"],
   ans:1,exp:"Weiss's theorem: every aperiodic ergodic MPT is isomorphic to a strictly ergodic subshift. The topological model is a subshift on a finite alphabet, with the unique invariant measure being the given measure. This gives measure-theoretic ergodic theory a natural symbolic topological model."},
],
7:[
  {q:"The Mackey-Zimmer theorem classifies extensions of ergodic systems. An ergodic extension T̃ of an ergodic T (both systems on standard probability spaces) is a:",
   opts:["Bernoulli extension","Compact group extension: X̃ = X × G/H for a compact group G and closed subgroup H, with T̃(x,gH) = (Tx, α(x)·gH)","Direct product extension","Skew product over a Kronecker system"],
   ans:1,exp:"Mackey-Zimmer structure theorem: any ergodic extension is (up to isomorphism) a compact group extension (also called a homogeneous extension or induced extension). The cocycle α: X → G encodes the fibering. This is the key tool in the structure theory of ergodic systems (Host-Kra theory uses it for characteristic factors)."},
  {q:"The Host-Kra seminorms ||f||_{U^k} (Gowers-Host-Kra norms in ergodic theory) are defined by the recurrence ||f||_{U^{k+1}}^{2^{k+1}} = lim_{N→∞} (1/N) Σ_{n=1}^N ||f · T^n f||_{U^k}^{2^k}. These seminorms control the convergence of multiple ergodic averages because:",
   opts:["||f||_{U^k} = 0 implies f = 0","||f||_{U^2} = 0 if and only if f is 'anti-correlated' with all degree-1 polynomial phases — any f with ||f||_{U^{k+1}} = 0 is orthogonal to all (k+1)-step nilsystems","They measure the L² norm of f","They are multiplicative norms"],
   ans:1,exp:"Host-Kra: f has ||f||_{U^{k+1}} = 0 iff f is orthogonal (in L²) to all (k+1)-step nilsystems. The characteristic factor for k-term arithmetic progression averages is the (k-1)-step nilfactor (generated by nilsystems). These seminorms are the ergodic-theoretic analogues of Gowers norms in combinatorics."},
  {q:"For an ergodic measure-preserving system (X,μ,T) and a partition 𝒫 = {P₁,...,Pₖ}, the process {Xₙ = i : T^n x ∈ Pᵢ} is a stationary stochastic process. The KS entropy h_μ(T) equals the process entropy rate, and for Bernoulli systems the process is:",
   opts:["A Markov chain of finite order","An i.i.d. process (the partition generates an independent sequence iff the system is Bernoulli w.r.t. 𝒫)","Always periodic","Gaussian"],
   ans:1,exp:"A Bernoulli system is by definition measurably isomorphic to a Bernoulli shift. For the 'canonical' generating partition of a Bernoulli shift, the process {Xₙ} is i.i.d. (independent and identically distributed). The entropy is H(𝒫) = −Σ μ(Pᵢ)log μ(Pᵢ). Ornstein's theorem: the entropy determines the Bernoulli system up to isomorphism."},
  {q:"The spectral measure of a unitary operator U on a Hilbert space is a projection-valued measure E on the unit circle S¹. For the Koopman operator U_T and f ∈ L²(μ), the spectral measure ν_f is the measure on S¹ satisfying:",
   opts:["∫ λ^n dν_f(λ) = ⟨U^n f, f⟩ = ∫ f(T^nx) f(x) dμ(x)","ν_f = μ for all f","ν_f is always Lebesgue measure","ν_f has atoms only at roots of unity"],
   ans:0,exp:"Spectral measure: ⟨U^n f,f⟩ = ∫_{S¹} λ^n dν_f(λ). The spectral type of (X,T,μ) is classified by whether ν_f is purely atomic (pure point spectrum ↔ eigenfunctions dense ↔ Kronecker system), absolutely continuous, or singular continuous. These determine mixing properties."},
  {q:"Rokhlin's cocycle theorem: for an ergodic measure-preserving transformation T and a measurable function φ: X → ℝ (a cocycle), the Birkhoff sums Sₙφ(x) = Σ_{k=0}^{n-1} φ(T^k x) are centered if ∫φ dμ = 0. The CLT (central limit theorem) for Birkhoff sums holds (with √n normalization) when:",
   opts:["φ is bounded","φ is Lipschitz","φ satisfies a mixing condition and is sufficiently regular (e.g., Hölder for hyperbolic systems via the spectral gap of the transfer operator)","∫φ dμ = 1"],
   ans:2,exp:"CLT for Birkhoff sums: (1/√n) Sₙφ → N(0,σ²) (in distribution) when the system is mixing and φ is regular enough (Hölder). The proof uses the spectral gap of the Ruelle-Perron-Frobenius operator. For hyperbolic systems, this gives statistical laws for chaotic trajectories."},
  {q:"Oseledets' multiplicative ergodic theorem (1968) for a measurable cocycle A: X → GL(d,ℝ) over an ergodic MPT T asserts the existence of a T-invariant measurable splitting ℝ^d = E₁(x) ⊕ ... ⊕ Eₖ(x) and numbers λ₁ > ... > λₖ such that for vectors v ∈ Eᵢ(x):",
   opts:["||A^n(x)v|| → 0 for all i","(1/n) log ||A^n(x)v|| → λᵢ almost surely","||A^n(x)v|| = e^{nλᵢ} exactly","The splitting is constant in x"],
   ans:1,exp:"Oseledets MET: for a.e. x, the Lyapunov exponent lim (1/n)log||A^n(x)v|| = λᵢ for all v ∈ Eᵢ(x)\\{0}. This is the ergodic theorem for matrix products. The splitting Eᵢ(x) is measurable, T-equivariant, and the exponents are deterministic constants (Lyapunov exponents)."},
  {q:"An ergodic MPT T is called a K-automorphism (Kolmogorov automorphism) if there exists a sub-σ-algebra 𝒦 such that T⁻¹𝒦 ⊂ 𝒦, ∨ₙ T^n𝒦 = ℬ (full σ-algebra), and ∩ₙ T^{-n}𝒦 = {∅, X} (trivial tail). K-automorphisms satisfy:",
   opts:["Zero entropy","Completely positive entropy (h(T,𝒫) > 0 for every non-trivial 𝒫) and strong mixing","Periodicity","Discrete spectrum"],
   ans:1,exp:"K-systems (K-automorphisms): any K-system has completely positive entropy and is strongly mixing. The K-property lies between positive entropy and Bernoulli: all Bernoulli shifts are K, but not all K-systems are Bernoulli. K-systems are characterized by the 0-1 law for the tail field."},
  {q:"The Rohlin entropy of a countable Borel equivalence relation E generated by a free ergodic action of a countable amenable group Γ equals:",
   opts:["The topological entropy of the Cayley graph","h(E) = inf{H(𝒫) : 𝒫 is an E-generating partition} — the minimum entropy of a generating partition, which equals the KS entropy of the action","The number of orbits","0 for all amenable actions"],
   ans:1,exp:"Rohlin entropy: h(E) = inf{H(𝒫) : 𝒫 generates E}. Tucker-Drob and Seward proved that for free actions of countable amenable groups, Rohlin entropy equals KS entropy. For non-amenable groups, Rohlin entropy provides an extension of KS entropy."},
],
8:[
  {q:"The circle criterion for absolute stability of a feedback system with nonlinearity φ ∈ [k₁, k₂] (sector condition) states that stability holds if the Nyquist plot of G(jω) does not intersect or encircle the disk D(k₁,k₂) centered at (−(k₁+k₂)/(2k₁k₂), 0). This is equivalent to:",
   opts:["||G(jω)||∞ < 1","The loop transfer function G(s) maps the boundary of D(k₁,k₂) into the left half-plane (Nyquist criterion on the modified plant)","G being strictly positive real (SPR)","The eigenvalues of G(0) being negative"],
   ans:1,exp:"Circle criterion: system is absolutely stable for φ ∈ [k₁,k₂] iff the Nyquist plot of G(jω) lies entirely outside (or entirely inside) the critical disk D(k₁,k₂). This is a graphical criterion generalizing the Nyquist criterion for linear stability. It is implied by the Popov criterion in many cases."},
  {q:"The passivity theorem for interconnected systems: a feedback connection of a passive system H₁ and a strictly passive system H₂ (satisfying ⟨y,u⟩ ≥ δ||u||² for some δ > 0) is:",
   opts:["Passive but not necessarily stable","L²-stable (input-output stable)","Always unstable","Neutral (energy-preserving)"],
   ans:1,exp:"Passivity theorem: if H₁ is passive (∫y·u dt ≥ −γ for all T > 0 and some γ) and H₂ is strictly passive, the feedback connection is L²-stable. Passivity is preserved under parallel and positive feedback connections; strict passivity provides the dissipation needed for stability."},
  {q:"Lyapunov's second method for discrete-time systems: the system xₙ₊₁ = f(xₙ) is asymptotically stable at x* = 0 if there exists V with V(0) = 0, V(x) > 0 for x ≠ 0, and:",
   opts:["V(f(x)) − V(x) ≤ 0","V(f(x)) − V(x) < 0 for x ≠ 0 (ΔV < 0 — the discrete Lyapunov decrease condition)","V(f(x)) = V(x)","V(f(x)) > V(x)"],
   ans:1,exp:"Discrete Lyapunov: ΔV(x) = V(f(x)) − V(x) < 0 for x ≠ 0 implies asymptotic stability. The discrete version is analogous to V̇ < 0 in continuous time, but care must be taken: ΔV < 0 is sufficient for A.S. but not strictly necessary in the same way as continuous time."},
  {q:"The notion of incremental stability (δ-ISS or incremental input-output stability) strengthens stability by requiring the system to be stable with respect to differences between trajectories. A system is incrementally stable if:",
   opts:["All solutions converge to 0","Any two solutions x(t,x₀,u) and x(t,x₀',u') satisfy |x(t,x₀,u) − x(t,x₀',u')| ≤ β(|x₀−x₀'|,t) + γ(||u−u'||)","The system is linear","The system has a unique equilibrium"],
   ans:1,exp:"Incremental stability: δ-ISS means the difference between any two solutions satisfies a KL+K gain bound in the differences of initial conditions and inputs. This is stronger than ordinary stability and ensures uniqueness of steady states and convergence of trajectories to each other — crucial for observer design and synchronization."},
  {q:"Barbalat's lemma: if a uniformly continuous function f: [0,∞) → ℝ satisfies ∫₀^∞ f(t) dt < ∞, then:",
   opts:["f(t) → 0 as t → ∞","f is bounded","∫₀^∞ |f(t)| dt < ∞","f is periodic"],
   ans:0,exp:"Barbalat's lemma: uniform continuity + square integrability (or absolute integrability) → f(t) → 0. This is used in adaptive control and Lyapunov stability analysis when V̇ ≤ 0 only (not strict): Barbalat gives convergence of V̇ to 0 even when V̇ < 0 fails, via the integrated bound on V̇."},
  {q:"The Kalman decomposition for a linear system (A,B,C) decomposes the state space into four subspaces based on reachability and observability. The transfer function G(s) = C(sI−A)⁻¹B is determined entirely by:",
   opts:["The full state space","Only the reachable AND observable subspace (the 'good' part of the decomposition)","The unobservable subspace","The unreachable subspace"],
   ans:1,exp:"Kalman decomposition: the transfer function G(s) depends only on the states that are both reachable and observable. Unreachable and/or unobservable modes are 'hidden' from the input-output description. A minimal realization (least-order state space representation) consists exactly of the reachable+observable subspace."},
  {q:"Stein's equation A*PA − P = −Q for discrete-time systems (where A is stable: all eigenvalues inside unit disk) has a unique positive definite solution P when Q > 0. This P is the infinite-horizon LQR cost:",
   opts:["The controllability Gramian","The discrete-time observability Gramian W_o = Σ_{k=0}^∞ (A*)^k Q A^k","The closed-loop covariance","The reachability Gramian"],
   ans:1,exp:"Discrete Stein equation A*PA − P = −Q has unique solution P = Σ_{k=0}^∞ (A*)^k Q A^k (discrete observability Gramian). For A stable, the series converges. P is the cost matrix for the discrete LQR problem with stage cost x*Qx. The dual equation APA* − P = −Q gives the reachability Gramian."},
  {q:"Input-to-state stability (ISS) of ẋ = f(x,u) can be characterized by the existence of an ISS-Lyapunov function V satisfying:",
   opts:["V̇ ≤ −α(|x|) whenever |u| ≤ σ(|x|) for some class K functions α, σ","α₁(|x|) ≤ V(x) ≤ α₂(|x|) and V̇ ≤ −α(|x|) + γ(|u|) for class K∞ functions α₁,α₂,α and class K function γ","V(x) = ||x||² and V̇ = 0","V is bounded"],
   ans:1,exp:"ISS Lyapunov function: (1) α₁(|x|) ≤ V ≤ α₂(|x|) (positive definite, radially unbounded), (2) V̇ ≤ −α(|x|) + γ(|u|). Condition (2) means: if |x| is large relative to |u| (|x| ≥ σ(|u|)), then V̇ ≤ −α'(|x|) < 0. The Sontag-Teel theorem: ISS ↔ existence of smooth ISS-Lyapunov function."},
],
9:[
  {q:"The Anosov closing lemma states that near a recurrent point of an Anosov diffeomorphism, there is a periodic orbit. More precisely: for any recurrent point x and ε > 0, there is a periodic point y with d(Tⁿy,Tⁿx) < ε for 0 ≤ n ≤ period(y). This follows from the shadowing lemma because:",
   opts:["All orbits are periodic","A recurrent orbit is a pseudo-orbit (it returns near itself), and the shadowing lemma provides a true periodic orbit that shadows it","The system is uniformly hyperbolic","The Markov partition gives the closing directly"],
   ans:1,exp:"Closing lemma for Anosov maps: a recurrent point gives a pseudo-orbit (the orbit eventually returns near its start), and the hyperbolic shadowing lemma says this pseudo-orbit is shadowed by a true orbit that must be periodic (since it shadows a nearly-periodic sequence). This gives the density of periodic points in Ω(T)."},
  {q:"The Hadamard-Perron method proves the stable manifold theorem using a fixed-point argument. The stable manifold near a hyperbolic fixed point is constructed as a graph over E^s of a Lipschitz function h: E^s → E^u. The map h is a fixed point of the:",
   opts:["Stable manifold map","Graph transform operator Γ, which sends a graph h to the graph of a new function computed by one step of the dynamics and projection","Poincaré return map","Transfer matrix"],
   ans:1,exp:"Graph transform: Γ sends a Lipschitz graph h: E^s → E^u to the graph of T∘h∘(T|_{E^s})⁻¹ (apply T, project back). The hyperbolicity ensures Γ is a contraction on the space of Lipschitz graphs, giving a unique fixed point h that is the stable manifold. This is the Perron-Irwin method."},
  {q:"The concept of 'thickness' (or Newhouse thickness) of a Cantor set C ⊂ ℝ is defined using the gaps (complementary intervals). A Cantor set C has thickness τ(C) > 0 if the ratio of any 'bridge' (part of C between two gaps at the same level) to the adjacent gap is ≥ τ. Two Cantor sets C₁, C₂ with τ(C₁)·τ(C₂) > 1 must:",
   opts:["Be disjoint","Intersect (Newhouse's gap lemma)","Be equal","Have equal thickness"],
   ans:1,exp:"Newhouse's gap lemma: if τ(C₁)·τ(C₂) > 1, then C₁ ∩ C₂ ≠ ∅ for any positioning where they interleave. This is used to prove the Newhouse phenomenon: near any diffeomorphism with a homoclinic tangency, there are diffeomorphisms with persistent tangencies (infinitely many attractors)."},
  {q:"The Hirsch-Pugh-Shub theorem on normally hyperbolic invariant manifolds (NHIMs) states that if M is invariant under T and the normal bundle expansion/contraction dominates the tangential, then M persists under C¹ perturbations. The persistence means:",
   opts:["M is unchanged by perturbations","There exists M' close to M that is invariant for the perturbed map T' = T+ε","T restricted to M is unchanged","The normal bundle vanishes"],
   ans:1,exp:"NHIM persistence theorem: if M is compact invariant with normal hyperbolicity (normal rates dominate tangential rates), then for any C¹ perturbation T' of T, there exists M' (homeomorphic to M, C^r close) that is invariant for T'. This generalizes the hyperbolic fixed-point theory to higher-dimensional invariant manifolds."},
  {q:"Pesin's Lyapunov stable manifold theorem extends stable manifold theory to non-uniformly hyperbolic systems. For a.e. x w.r.t. an ergodic measure with negative Lyapunov exponent λ_s < 0 < λ_u, the stable manifold W^s(x) satisfies:",
   opts:["W^s(x) is a C¹ submanifold tangent to the Oseledets stable space at x, with exponential contraction rate approaching λ_s","W^s(x) is a linear subspace","W^s(x) is the entire manifold","W^s(x) = {x}"],
   ans:0,exp:"Pesin's theorem: for a.e. x (w.r.t. ergodic measure with nonzero Lyapunov exponents), W^s(x) is a C¹⁺ᵅ injectively immersed submanifold tangent to the Oseledets stable space E^s(x) and satisfying d(T^nx, T^ny) ≤ C(x) e^{n(λ_s+ε)} d(x,y) for y ∈ W^s(x)."},
  {q:"The Mañé-Sad-Sullivan theorem on holomorphic families: for a holomorphic family {f_λ} of rational maps (λ ∈ D), the Julia set J(f_λ) moves continuously (holomorphically) for λ outside the bifurcation locus. More precisely:",
   opts:["J(f_λ) is always the same set","In the stable set {λ : f_λ is stable (J moves analytically)}, there is a holomorphic motion h: D × J(f₀) → ℂ with h(λ,·) a conjugacy on J","J(f_λ) is compact for all λ","The bifurcation locus is empty"],
   ans:1,exp:"Mañé-Sad-Sullivan (MSS) theorem: stable maps form an open dense set in 1-parameter families (Sullivan, and separately MSS). In the stable component, J moves by a holomorphic motion — a quasiconformal map h_λ: J₀ → J_λ depending holomorphically on λ. The λ-lemma extends this to a quasiconformal conjugacy."},
  {q:"The C¹-generic theory of diffeomorphisms (Pugh-Shub, Bonatti-Díaz-Viana): C¹-generically (for a residual set of diffeomorphisms in Diff¹(M)), every diffeomorphism satisfies:",
   opts:["All Lyapunov exponents are negative","Periodic orbits are dense in the chain-recurrent set (Pugh's closing lemma for C¹ maps), and stable/unstable manifolds of periodic orbits are dense","Every orbit is periodic","The system is Anosov"],
   ans:1,exp:"C¹ generic properties: (1) Pugh's closing lemma: recurrent orbits are approximated by periodic orbits (C¹-generically, periodic orbits are dense in the chain-recurrent set). (2) Kupka-Smale theorem: generically, all periodic orbits are hyperbolic and their stable/unstable manifolds intersect transversely."},
  {q:"The Oseledets decomposition ℝ^d = E₁(x) ⊕ ... ⊕ Eₖ(x) is measurable but typically not continuous. The obstruction to continuity is related to:",
   opts:["Lack of differentiability","Non-uniform hyperbolicity: the Oseledets spaces can vary wildly with x in the C⁰ topology, even for smooth systems, due to resonances and slow hyperbolic behavior","The dimension of M","The measure μ being non-ergodic"],
   ans:1,exp:"The Oseledets decomposition is only measurable (a.e. defined) and can fail to be continuous anywhere. Near points where two Lyapunov exponents are equal (a resonance), the corresponding Oseledets subspaces may rotate rapidly. This is a fundamental difference between uniform hyperbolicity (where subspaces vary continuously) and non-uniform hyperbolicity."},
],
10:[
  {q:"Takens' theorem (1981) on delay embeddings: for a smooth dynamical system on a compact manifold M of dimension d, the delay-coordinate map using 2d+1 time delays is generically an embedding. The proof uses Sard's theorem to show that:",
   opts:["The map is always a diffeomorphism","The set of 'bad' observation functions (those for which the delay map is not an embedding) has measure zero in the space of smooth functions","The manifold M must be a sphere","Only 2 delays are needed"],
   ans:1,exp:"Takens' proof: the 'bad' set of functions h: M → ℝ for which (h(x), h(Tx),..., h(T^{2d}x)) fails to be an embedding has measure zero by Sard's theorem and Whitney's embedding theorem. So generically 2d+1 delays suffice. Extensions (Sauer-Yorke-Casdagli) handle fractal attractors: 2·dim_H(A)+1 delays suffice."},
  {q:"The Neimark-Sacker bifurcation (discrete-time Hopf bifurcation) occurs when a fixed point of a map f: ℝ² → ℝ² has eigenvalues e^{±iθ} crossing the unit circle. The bifurcation produces:",
   opts:["A period-2 orbit","An invariant closed curve (invariant circle) surrounding the fixed point","A fixed point with different stability","A Cantor set"],
   ans:1,exp:"Neimark-Sacker bifurcation: when the multipliers e^{±iθ} cross the unit circle (|multiplier| passes through 1 as complex conjugate pair), an invariant closed curve is born (discrete-time analogue of the limit cycle in Hopf). For irrational θ/2π, the dynamics on the invariant curve is quasi-periodic."},
  {q:"Catastrophe theory (Thom) classifies generic singularities of smooth functions. The canonical forms of the 7 elementary catastrophes (in terms of the potential function V(x;u) where u are control parameters) include the fold (V = x³+ux) and the cusp (V = x⁴+ux²+vx). The cusp catastrophe models:",
   opts:["Irrational rotations","Bistable systems with hysteresis (two stable equilibria can coexist for a range of parameters, with sudden jumps at the fold curves)","Limit cycles","Homoclinic connections"],
   ans:1,exp:"The cusp catastrophe: ∂V/∂x = 0 gives the equilibrium surface, which folds over itself in parameter space, creating a region of bistability. As parameters cross the fold curves, the system jumps discontinuously between equilibria — hysteresis. Applications: buckling, phase transitions, opinion dynamics."},
  {q:"Homoclinic bifurcation (orbit flip/inclination flip) occurs when a homoclinic orbit to a hyperbolic fixed point satisfies a non-generic tangency condition. Near such a bifurcation, the Shilnikov phenomenon predicts:",
   opts:["A Hopf bifurcation","Infinitely many periodic orbits and horseshoes if the saddle quantity σ = λ_u − |λ_s| > 0 (Shilnikov condition)","A saddle-node bifurcation","Global stability"],
   ans:1,exp:"Shilnikov homoclinic bifurcation (in 3D): if the fixed point is a saddle-focus with real eigenvalue λ_u > 0 and complex eigenvalues −ρ ± iω (ρ > 0), and the saddle quantity λ_u > ρ, then near the homoclinic orbit there are infinitely many periodic orbits of all periods — Shilnikov chaos. The Shilnikov condition λ_u > ρ is the key."},
  {q:"In 2D maps, the twist condition for a Birkhoff annulus map (r, θ) ↦ (r + f(r,θ), θ + g(r,θ)) requires ∂g/∂r ≠ 0. This condition ensures the Poincaré-Birkhoff theorem applies, giving:",
   opts:["No fixed points","At least two fixed points of the map for every rational rotation number","Dense orbits","A global attractor"],
   ans:1,exp:"Poincaré-Birkhoff theorem: an area-preserving twist map of an annulus has at least two fixed points (for any period-p/q approximation). The twist condition (rotation number varies monotonically with r) is essential. This is a cornerstone of KAM theory for 2D maps."},
  {q:"The Ruelle-Takens route to turbulence (1971) proposes that turbulence arises via a sequence of bifurcations: fixed point → periodic → 2-torus → (potentially chaotic) strange attractor. The key insight was that:",
   opts:["Three-frequency quasi-periodicity is robust","After two Hopf bifurcations (creating a 2-torus), a third bifurcation generically leads to strange attractors (unlike the Landau-Hopf route via infinite Hopf bifurcations)","Turbulence requires infinitely many degrees of freedom","The route always goes through period-doubling"],
   ans:1,exp:"Ruelle-Takens: generically, a 3-torus T³ (three incommensurate frequencies) supports strange attractors for arbitrary small perturbations — 3-frequency quasi-periodicity is not robust. This suggested turbulence can arise after few bifurcations, contrasting Landau's infinite-cascade hypothesis. Newhouse-Ruelle-Takens formalized this."},
  {q:"In the unfolding of a codimension-2 singularity (like a Takens-Bogdanov point with double-zero eigenvalue), the bifurcation diagram contains a curve of homoclinic orbits. This curve ends at:",
   opts:["The Hopf bifurcation curve","A point where the homoclinic orbit becomes a heteroclinic cycle or a degenerate homoclinic (e.g., the orbit returns tangentially — a homoclinic tangency)","The saddle-node curve","The center manifold"],
   ans:3,exp:"In the Bogdanov-Takens unfolding, the homoclinic curve (where a homoclinic orbit to the saddle exists) ends at the saddle-node curve. At the endpoint, the saddle and node merge (saddle-node on the invariant cycle), and the homoclinic orbit becomes a heteroclinic connection from the saddle-node to itself in the limit."},
  {q:"The blue sky catastrophe (Shilnikov-Turaev) is a bifurcation where a stable periodic orbit disappears as its period goes to infinity. It occurs when the periodic orbit approaches:",
   opts:["A fixed point","A saddle-node periodic orbit on an invariant torus (the orbit approaches another periodic orbit)","A heteroclinic cycle","A Shilnikov saddle-focus"],
   ans:2,exp:"Blue sky catastrophe (Turaev-Shilnikov 1995): a stable periodic orbit disappears as it approaches a saddle periodic orbit (creating a heteroclinic connection), with the period T → ∞ and amplitude remaining bounded (unlike homoclinic bifurcations where amplitude → 0). The orbit 'disappears into the blue sky'."},
],
};

const BASE = path.join(__dirname, 'questions');
let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);
  const m = META[ch];
  const dir = path.join(BASE, m.dir, m.ch);
  const existing = fs.readdirSync(dir).filter(f=>f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir,existing[0]),'utf8'));
  const {chTitle,part} = sample;
  qs.forEach((q,i)=>{
    const n = existing.length+i+1;
    const file = path.join(dir,`q${String(n).padStart(2,'0')}.json`);
    fs.writeFileSync(file, JSON.stringify({ch,part,chTitle,...q},null,2)+'\n');
    console.log('wrote', path.relative(__dirname,file));
    total++;
  });
}
console.log(`\nDone. ${total} questions written.`);
