#!/usr/bin/env node
'use strict';
const fs   = require('fs');
const path = require('path');

const PART_DIRS = {
  1:'part-i-foundations',2:'part-i-foundations',3:'part-i-foundations',
  4:'part-i-foundations',5:'part-i-foundations',
  6:'part-ii-dynamical-systems',7:'part-ii-dynamical-systems',8:'part-ii-dynamical-systems',
  9:'part-ii-dynamical-systems',10:'part-ii-dynamical-systems',
};
const CH_DIRS = {
  1:'ch01-real-analysis',2:'ch02-measure-theory',3:'ch03-topology',
  4:'ch04-ordinary-differential-equations',5:'ch05-linear-algebra',
  6:'ch06-topological-dynamics',7:'ch07-ergodic-theory',8:'ch08-stability-theory',
  9:'ch09-hyperbolic-dynamics',10:'ch10-bifurcation-theory',
};
const PART_OF = {1:1,2:1,3:1,4:1,5:1,6:2,7:2,8:2,9:2,10:2};

const EXTRA = {

1:[
  {q:"The Stone-Weierstrass theorem generalises the Weierstrass approximation theorem. It states that a subalgebra A of C(K,ℝ) that separates points and contains constants is:",
   opts:["Dense in C(K,ℝ) in the sup-norm","Closed in C(K,ℝ)","Equal to C(K,ℝ)","Dense only if K is compact and metrizable"],
   ans:0,
   exp:"Stone-Weierstrass: if A ⊂ C(K,ℝ) is a subalgebra that separates points and contains a nonzero constant, then Ā = C(K,ℝ) in the uniform norm. The complex version requires additionally that A is closed under conjugation."},
  {q:"The Riemann-Lebesgue lemma states that for any f ∈ L¹(ℝ):",
   opts:["The Fourier transform f̂ is in L¹(ℝ)","f̂(ξ) → 0 as |ξ| → ∞","f̂ is uniformly continuous","f̂ is in L²(ℝ)"],
   ans:1,
   exp:"Riemann-Lebesgue: f̂(ξ) = ∫ f(x)e^{-2πiξx}dx → 0 as |ξ| → ∞ for any f ∈ L¹. Intuitively, rapid oscillations of e^{-2πiξx} cancel; formally, approximate f by step functions and use that f̂ of a step function decays."},
  {q:"A function f: ℝ → ℝ has the Luzin N-property if:",
   opts:["f maps null sets to null sets","f maps null sets to sets of positive measure","f is absolutely continuous","f is Lipschitz"],
   ans:0,
   exp:"Luzin N: f maps every Lebesgue-null set to a null set. Absolutely continuous functions satisfy Luzin N (this is key to the fundamental theorem of calculus for Lebesgue integrals), but the converse fails."},
  {q:"The Vitali covering theorem states: given a collection 𝒱 of balls covering a set E ⊂ ℝⁿ in the Vitali sense, there exists a countable disjoint subcollection {Bₖ} ⊂ 𝒱 such that:",
   opts:["The Bₖ cover E exactly","E ⊂ ∪ 5Bₖ (the 5× dilations cover E)","The Bₖ partition E","The subcollection is finite"],
   ans:1,
   exp:"Vitali's covering theorem: from a Vitali cover (every point is in arbitrarily small balls of 𝒱) one extracts a disjoint subcollection whose 5-fold dilates cover the whole set. This is the foundation of Lebesgue differentiation theorem."},
  {q:"The Tietze extension theorem states that if X is a normal topological space, A ⊆ X is closed, and f: A → [a,b] is continuous, then f:",
   opts:["Cannot be extended","Extends to a continuous F: X → [a,b]","Extends only if X is compact","Extends to a Lipschitz function on X"],
   ans:1,
   exp:"Tietze extension: on a normal space, every continuous real-valued function on a closed subset extends continuously to the whole space (preserving bounds). This follows from Urysohn's lemma and is a basic tool in topology and functional analysis."},
  {q:"For a sequence fₙ in L^p([0,1]) (1 < p < ∞) that is bounded and converges pointwise a.e. to f, weak convergence fₙ ⇀ f in L^p is guaranteed because:",
   opts:["Pointwise a.e. convergence implies strong convergence","Boundedness + pointwise a.e. convergence implies weak convergence (by Dunford-Pettis and reflexivity)","Strong and weak convergence coincide in L^p","Every L^p-bounded sequence has a weakly convergent subsequence by reflexivity, and the limit must be f"],
   ans:3,
   exp:"L^p for p ∈ (1,∞) is reflexive, so bounded sequences have weakly convergent subsequences. If fₙ → f a.e. and fₙ is bounded in L^p, any weak cluster point must equal f a.e. (by testing against indicators), so fₙ ⇀ f."},
  {q:"The Hausdorff dimension of the middle-thirds Cantor set is:",
   opts:["0","log 2 / log 3","1/2","1"],
   ans:1,
   exp:"The Cantor set is self-similar: it consists of 2 copies scaled by factor 1/3, so dim_H = log 2 / log 3 ≈ 0.631. It has measure zero (it's a null set) but uncountably many points—a hallmark example for fractal geometry."},
  {q:"The closed graph theorem states that a linear map T: X → Y between Banach spaces is bounded (continuous) if and only if:",
   opts:["T is surjective","T has a closed kernel","The graph {(x,Tx)} is closed in X×Y","T is an isometry"],
   ans:2,
   exp:"Closed graph theorem (consequence of the open mapping theorem): if X, Y are Banach spaces and T is linear with closed graph, then T is continuous. This is frequently used to prove that a naturally defined linear operator is bounded."},
],

2:[
  {q:"The Hahn decomposition theorem states that for a signed measure ν on (X,Σ), X can be decomposed as X = P ∪ N with P ∩ N = ∅ where:",
   opts:["P and N are both positive sets","P is a positive set (ν(A) ≥ 0 for all A ⊆ P) and N is a negative set (ν(A) ≤ 0 for all A ⊆ N)","P = supp(ν⁺) and N = supp(ν⁻)","P and N are disjoint open sets"],
   ans:1,
   exp:"Hahn decomposition: every signed measure admits a partition into a positive set P and negative set N. The Jordan decomposition ν = ν⁺ − ν⁻ then gives ν⁺(A) = ν(A∩P) and ν⁻(A) = −ν(A∩N)."},
  {q:"The Fubini-Tonelli theorem allows switching the order of integration. Tonelli's version (for non-negative functions) requires:",
   opts:["Both measures to be finite","Both measures to be σ-finite (and the function to be non-negative measurable)","The function to be continuous","The product space to be compact"],
   ans:1,
   exp:"Tonelli's theorem: for σ-finite measures and a non-negative measurable f, ∫∫ f d(μ×ν) = ∫(∫f dμ) dν = ∫(∫f dν) dμ with all integrals equal (possibly infinite). Fubini then extends this to integrable functions."},
  {q:"The Riesz representation theorem for C(K) (K compact Hausdorff) identifies the dual space C(K)* with:",
   opts:["L¹(K)","The space of regular Borel signed measures on K, via Λ(f) = ∫ f dμ","The space of Borel probability measures","L²(K)"],
   ans:1,
   exp:"Riesz-Markov-Kakutani: every bounded linear functional Λ on C(K) is represented by a unique regular Borel signed measure μ. For positive functionals, μ is a positive measure. This is foundational for weak-* topology on measure spaces."},
  {q:"The Carathéodory extension theorem says that a premeasure μ₀ on an algebra 𝒜 extends to a measure on the σ-algebra σ(𝒜). The extension is unique when:",
   opts:["𝒜 is a σ-algebra","μ₀ is σ-finite on 𝒜","X is a compact space","𝒜 contains all open sets"],
   ans:1,
   exp:"Carathéodory extension is always possible, and uniqueness holds when μ₀ is σ-finite (X = ∪Xₙ with μ₀(Xₙ) < ∞). Without σ-finiteness, multiple extensions can exist."},
  {q:"Disintegration of measure: if π: (X,μ) → (Y,ν) is a measurable map with π_*μ = ν, then μ disintegrates as μ = ∫ μ_y dν(y) where each μ_y is:",
   opts:["A measure on Y","A probability measure on the fiber π⁻¹(y)","A measure on X equal to μ","A signed measure"],
   ans:1,
   exp:"Disintegration: under mild regularity (e.g., standard Borel spaces), μ = ∫_Y μ_y dν(y) with μ_y supported on π⁻¹(y) and ∫ f dμ = ∫_Y (∫ f dμ_y) dν(y). This is the measure-theoretic analogue of conditional distributions."},
  {q:"Hausdorff measure ℋˢ is an outer measure on ℝⁿ. Its key property relating to Lebesgue measure is:",
   opts:["ℋⁿ = Lebesgue measure on ℝⁿ (up to a constant)","ℋˢ = 0 for all s < n","ℋˢ = ∞ for all s > 0","ℋˢ is not σ-finite for any s"],
   ans:0,
   exp:"ℋⁿ equals the n-dimensional Lebesgue measure up to the constant ω_n/2^n (where ω_n is the volume of the unit ball). Hausdorff dimension of a set is the critical exponent where ℋˢ jumps from ∞ to 0."},
  {q:"A measure μ on a topological space X is called regular if:",
   opts:["μ(X) = 1","μ is inner regular (μ(A) = sup{μ(K) : K⊆A, K compact}) and outer regular (μ(A) = inf{μ(U) : U⊇A, U open})","μ is absolutely continuous w.r.t. Lebesgue measure","μ is a product measure"],
   ans:1,
   exp:"Regularity means Borel sets can be approximated from inside by compact sets and from outside by open sets. Radon measures (locally finite regular Borel measures) are the natural class for analysis on locally compact spaces."},
  {q:"The Hardy-Littlewood maximal function Mf(x) = sup_{r>0} (1/|B(x,r)|) ∫_{B(x,r)} |f| is weak-type (1,1), meaning:",
   opts:["Mf ∈ L¹ whenever f ∈ L¹","μ({Mf > λ}) ≤ C||f||₁/λ for all λ > 0","Mf ≤ f pointwise","Mf ∈ L^p for p > 1"],
   ans:1,
   exp:"The maximal function is not in L¹ generally (Mf(x) ≥ c/|x|ⁿ for f = 1_{B(0,1)}), but satisfies the weak-type bound. This implies the Lebesgue differentiation theorem: (1/|B(x,r)|)∫_{B(x,r)} f → f(x) a.e."},
],

3:[
  {q:"The van Kampen theorem computes the fundamental group of a space X = U ∪ V (U,V open, path-connected, with U∩V path-connected) as:",
   opts:["π₁(U) × π₁(V)","The free product π₁(U) * π₁(V) modulo the normal subgroup generated by i_U(γ)i_V(γ)⁻¹ for γ ∈ π₁(U∩V)","π₁(U) ∩ π₁(V)","π₁(U) / π₁(V)"],
   ans:1,
   exp:"Seifert-van Kampen theorem: π₁(X) is the pushout of π₁(U) and π₁(V) over π₁(U∩V)—the amalgamated free product. This is the main computational tool for fundamental groups: e.g. π₁(S¹) = ℤ, π₁(figure-eight) = F₂."},
  {q:"A covering space p: (X̃, x̃₀) → (X, x₀) corresponds (via the monodromy action) to:",
   opts:["A normal subgroup of π₁(X, x₀)","A subgroup H ≤ π₁(X, x₀) (namely p_*(π₁(X̃, x̃₀)))","A quotient group of π₁(X)","An element of H¹(X, ℤ)"],
   ans:1,
   exp:"Covering space theory: connected covering spaces of X correspond (up to isomorphism) to conjugacy classes of subgroups of π₁(X). The subgroup is the image p_*(π₁(X̃)). The universal cover corresponds to the trivial subgroup."},
  {q:"A topological space is called paracompact if:",
   opts:["It is compact","Every open cover has a locally finite open refinement","Every open cover is finite","It is a countable union of compact sets"],
   ans:1,
   exp:"Paracompactness: every open cover has a locally finite open refinement. All metric spaces and CW-complexes are paracompact. Paracompactness implies the existence of partitions of unity, crucial for differential topology and sheaf theory."},
  {q:"The compact-open topology on the function space C(X,Y) (continuous maps from X to Y) is generated by the sub-basic sets K(K,U) = {f : f(K) ⊆ U} for K compact in X and U open in Y. When X is locally compact Hausdorff, the evaluation map:",
   opts:["Is always discontinuous","ev: C(X,Y) × X → Y is continuous with the compact-open topology","ev is only continuous when Y = ℝ","ev is a homeomorphism"],
   ans:1,
   exp:"The compact-open topology makes evaluation continuous (when X is locally compact Hausdorff). This makes it the natural topology for function spaces; for example, C(X,ℝ) with compact-open topology is a locally convex topological vector space."},
  {q:"Čech cohomology H̃ⁿ(X; G) agrees with singular cohomology for 'nice' spaces (CW-complexes). Its main advantage is that:",
   opts:["It is easier to compute","It is defined for all topological spaces (not just CW-complexes) and is functorial and exact","It agrees with de Rham cohomology on manifolds","It is finitely generated always"],
   ans:1,
   exp:"Čech cohomology is defined for any topological space via good covers (or the nerve of covers). It agrees with singular and de Rham cohomology for manifolds/CW-complexes, but extends to more singular spaces where singular cohomology may misbehave."},
  {q:"A topological space X is locally compact if and only if every point x ∈ X has:",
   opts:["A compact neighborhood","A finite neighborhood","A neighborhood homeomorphic to ℝⁿ","A neighborhood that is a manifold"],
   ans:0,
   exp:"Local compactness: every point has a compact neighborhood (equivalently: every point has a neighborhood basis of compact sets). ℝⁿ is locally compact but not compact. Local compactness is preserved by open and closed subspaces."},
  {q:"The Whitehead theorem states that a map f: X → Y between CW-complexes that induces isomorphisms on all homotopy groups πₙ for all n:",
   opts:["Is a homeomorphism","Is a homotopy equivalence","Is a covering map","Is null-homotopic"],
   ans:1,
   exp:"Whitehead's theorem: a weak homotopy equivalence between CW-complexes is a genuine homotopy equivalence. This fails for general spaces (e.g., the Warsaw circle). It is the main reason CW-complexes are the 'right' category for homotopy theory."},
  {q:"The Hopf invariant of a map f: S³ → S² classifies elements of π₃(S²). The Hopf fibration η: S³ → S² has Hopf invariant:",
   opts:["0","1","2","-1"],
   ans:1,
   exp:"The Hopf fibration η: S³ → S² (fibers are great circles S¹) has Hopf invariant 1, generating π₃(S²) ≅ ℤ. The Hopf invariant-1 problem (Adams, 1960) showed the only maps with Hopf invariant 1 occur in dimensions 1, 2, 4, 8 (related to division algebras)."},
],

4:[
  {q:"Poincaré-Bendixson theorem classifies limit sets of trajectories in the plane. For a bounded trajectory in ℝ² with no equilibria in its omega-limit set:",
   opts:["The trajectory converges to a fixed point","The omega-limit set is a periodic orbit","The trajectory is dense in ℝ²","The trajectory is eventually periodic"],
   ans:1,
   exp:"Poincaré-Bendixson: in ℝ² (or S²), if the omega-limit set ω(x) is compact, connected, and contains no equilibrium, it must be a periodic orbit. This limits complexity of 2D ODEs—chaos is impossible in the plane."},
  {q:"Bendixson's criterion for ruling out closed orbits states: if div(f) = ∂f₁/∂x + ∂f₂/∂y is not identically zero and does not change sign in a simply connected region D, then ẋ = f(x):",
   opts:["Has a fixed point in D","Has no closed orbit entirely contained in D","Is globally asymptotically stable","Has exactly one periodic orbit"],
   ans:1,
   exp:"Bendixson's criterion: by Green's theorem, ∮_γ f·n ds = ∬_D div(f) dA. If div(f) doesn't change sign, the right-hand side is nonzero, contradicting ∮ = 0 for a closed trajectory. This rules out limit cycles in D."},
  {q:"The method of variation of parameters solves the inhomogeneous system ẋ = A(t)x + g(t) by seeking a solution of the form x(t) = Φ(t)c(t), where Φ is the fundamental matrix. The result is:",
   opts:["x(t) = Φ(t)x₀","x(t) = Φ(t)x₀ + Φ(t)∫₀ᵗ Φ⁻¹(s)g(s)ds","x(t) = ∫₀ᵗ Φ(t-s)g(s)ds","x(t) = e^{At}x₀ + g(t)"],
   ans:1,
   exp:"Variation of parameters: differentiating x = Φc and substituting gives Φċ = g, so c(t) = x₀ + ∫₀ᵗ Φ⁻¹(s)g(s)ds. This gives the variation of constants formula—exact solution for any continuous g."},
  {q:"For a gradient system ẋ = −∇V(x) on ℝⁿ, the function V serves as a Lyapunov function. The dynamics has the property that:",
   opts:["V is constant along orbits","dV/dt = −|∇V|² ≤ 0 along orbits, with equality only at equilibria","Orbits spiral around minima of V","The system is Hamiltonian"],
   ans:1,
   exp:"Along solutions of ẋ = −∇V: dV/dt = ∇V · ẋ = −|∇V|² ≤ 0. By LaSalle, orbits converge to equilibria (where ∇V = 0). Gradient systems have no periodic orbits—all energy is dissipated monotonically."},
  {q:"The index of a vector field at an isolated equilibrium is a topological invariant. For a stable node or spiral, the index equals:",
   opts:["-1","0","1","2"],
   ans:2,
   exp:"The Poincaré index of a stable/unstable node, star, or spiral is +1. Saddle points have index −1. The Poincaré-Hopf theorem: the sum of indices over all equilibria on a compact surface equals the Euler characteristic χ(S)."},
  {q:"Singular perturbation problems (fast-slow systems) with ẋ = f(x,y), εẏ = g(x,y) (ε → 0) are analysed by Fenichel's geometric singular perturbation theory. The slow manifold is:",
   opts:["The set where f = 0","An O(ε) perturbation of the critical manifold {g(x,y) = 0} that is invariant for small ε > 0","The set where both f = 0 and g = 0","An invariant torus for the fast system"],
   ans:1,
   exp:"Fenichel's theorem: near a normally hyperbolic compact piece of the critical manifold S₀ = {g = 0}, there exists a slow invariant manifold S_ε = S₀ + O(ε) on which dynamics reduces to a slower system. This formalises Tikhonov's theorem geometrically."},
  {q:"The Melnikov function for a periodically forced planar system ẋ = f(x) + εg(x,t) measures the distance between stable and unstable manifolds. When M(t₀) has a simple zero:",
   opts:["The system has a periodic orbit","The manifolds intersect transversally, implying chaotic dynamics by Smale-Birkhoff","The equilibrium is stable","The perturbation is conservative"],
   ans:1,
   exp:"A simple zero of the Melnikov function implies transverse homoclinic intersection of stable and unstable manifolds. By Smale-Birkhoff, transverse homoclinic points imply a horseshoe, hence topological chaos (positive entropy, sensitive dependence)."},
  {q:"The Cauchy-Kovalevskaya theorem guarantees local analytic solutions to PDE initial value problems when the data and coefficients are analytic. Its main limitation is:",
   opts:["It requires the domain to be compact","It only applies to linear PDEs","It says nothing about well-posedness in Sobolev spaces (the solution may not be stable in L²)","It only works in one spatial dimension"],
   ans:2,
   exp:"Cauchy-Kovalevskaya gives local analytic solutions but not stability: small analytic perturbations can lead to wildly different solutions in non-hyperbolic directions (Hadamard's example). Well-posedness in Sobolev spaces requires separate analysis."},
],

5:[
  {q:"The Jordan normal form theorem states that every matrix A over ℂ is similar to a block diagonal matrix with Jordan blocks. A Jordan block J_k(λ) is a k×k matrix with λ on the diagonal and:",
   opts:["0 everywhere off diagonal","1 on the superdiagonal and 0 elsewhere off diagonal","λ on the superdiagonal","−1 on the subdiagonal"],
   ans:1,
   exp:"A Jordan block J_k(λ) has λ on the diagonal, 1 on the superdiagonal, 0 elsewhere. The number and sizes of Jordan blocks for each eigenvalue λ are uniquely determined by the dimensions of ker(A−λI)^k (the invariant factor structure)."},
  {q:"The spectral radius ρ(A) = max{|λ| : λ eigenvalue of A} is related to the operator norm by:",
   opts:["ρ(A) = ||A||","ρ(A) ≤ ||A|| for any matrix norm, with equality for normal matrices in the 2-norm","ρ(A) ≥ ||A||","ρ(A) = ||A||₂/√n"],
   ans:1,
   exp:"Gelfand's formula: ρ(A) = lim_{n→∞} ||Aⁿ||^{1/n} for any matrix norm, and ρ(A) ≤ ||A||. For normal matrices (AA* = A*A), the 2-norm equals the spectral radius. Aⁿ → 0 iff ρ(A) < 1."},
  {q:"The min-max (Courant-Fischer) theorem characterises eigenvalues of a Hermitian matrix A. The k-th largest eigenvalue is:",
   opts:["min_{dim V=k} max_{x∈V, ||x||=1} ⟨Ax,x⟩","max_{dim V=k} min_{x∈V, ||x||=1} ⟨Ax,x⟩","max_{||x||=1} ⟨Ax,x⟩","min_{||x||=1} ⟨Ax,x⟩"],
   ans:1,
   exp:"Courant-Fischer: λ_k = max_{dim V=k} min_{x∈V,||x||=1} x*Ax = min_{dim W=n-k+1} max_{x∈W,||x||=1} x*Ax. This variational characterisation is fundamental for eigenvalue perturbation theory, Weyl's inequalities, and interlacing theorems."},
  {q:"The Moore-Penrose pseudoinverse A⁺ of a matrix A with SVD A = UΣVᵀ is given by:",
   opts:["A⁺ = Vᵀ Σ⁺ U where Σ⁺ replaces each nonzero σᵢ by 1/σᵢ","A⁺ = (AᵀA)⁻¹Aᵀ when A is full column rank (otherwise undefined)","A⁺ = Aᵀ(AAᵀ)⁻¹ always","A⁺ = U Σ⁺ Vᵀ where Σ⁺ replaces each nonzero σᵢ by 1/σᵢ"],
   ans:3,
   exp:"A⁺ = V Σ⁺ Uᵀ where Σ⁺ inverts each nonzero singular value. This satisfies the four Moore-Penrose conditions: AA⁺A = A, A⁺AA⁺ = A⁺, (AA⁺)* = AA⁺, (A⁺A)* = A⁺A. It gives the minimum-norm least-squares solution to Ax = b."},
  {q:"Weyl's inequalities for the singular values of A + B where A, B are m×n matrices state:",
   opts:["σᵢ(A+B) = σᵢ(A) + σᵢ(B)","σᵢ₊ⱼ₋₁(A+B) ≤ σᵢ(A) + σⱼ(B)","σ₁(A+B) ≤ σ₁(A) · σ₁(B)","Singular values of A+B are independent of those of A and B"],
   ans:1,
   exp:"Weyl's inequality: σᵢ₊ⱼ₋₁(A+B) ≤ σᵢ(A) + σⱼ(B). In particular σ₁(A+B) ≤ σ₁(A) + σ₁(B) (triangle inequality for operator norm). These inequalities are fundamental in matrix perturbation theory and random matrix theory."},
  {q:"A matrix A is called positive definite if for all nonzero x: xᵀAx > 0. Equivalently, for symmetric A, this holds iff:",
   opts:["All diagonal entries are positive","A = BᵀB for some invertible B (Cholesky decomposition exists)","The trace is positive","All minors are nonnegative"],
   ans:1,
   exp:"Symmetric A is positive definite iff all eigenvalues are positive, iff A = LLᵀ for invertible lower-triangular L (Cholesky), iff all leading principal minors are positive (Sylvester's criterion). PD matrices define inner products and arise naturally in optimisation."},
  {q:"The tensor product V ⊗ W of vector spaces V and W over a field k has dimension:",
   opts:["dim V + dim W","dim V · dim W","max(dim V, dim W)","dim V^{dim W}"],
   ans:1,
   exp:"dim(V ⊗ W) = dim V · dim W. The tensor product is characterised by the universal property: bilinear maps V × W → Z correspond bijectively to linear maps V ⊗ W → Z. Tensor products of representations, modules, and Hilbert spaces are central in algebra and physics."},
  {q:"For a linear map T: V → V on a finite-dimensional space, the Cayley-Hamilton theorem can be used to show the minimal polynomial m_T divides the characteristic polynomial p_T. This means the minimal polynomial:",
   opts:["Equals p_T always","Has the same roots as p_T but possibly smaller degree","Has strictly smaller degree than p_T","Is unrelated to p_T"],
   ans:1,
   exp:"The minimal polynomial m_T has the same roots (eigenvalues) as p_T but each may appear with smaller multiplicity. m_T | p_T by CH. A matrix is diagonalizable iff m_T has no repeated roots (all eigenvalues appear with multiplicity 1 in m_T)."},
],

6:[
  {q:"A topological dynamical system (X,T) is called minimal if X has no proper closed T-invariant subsets. Equivalently, every orbit is:",
   opts:["Finite","Periodic","Dense in X","Eventually periodic"],
   ans:2,
   exp:"Minimality: every orbit is dense. Minimal systems are the 'atoms' of topological dynamics—they cannot be decomposed further. Irrational rotations on the circle are minimal; every system contains a minimal subsystem (Auslander-Ellis theorem)."},
  {q:"The topological entropy of a continuous map T: X → X (X compact metric) via spanning sets is: h_top(T) = lim_{ε→0} lim sup_{n→∞} (1/n) log s(n,ε), where s(n,ε) is:",
   opts:["The number of periodic orbits of period n","The minimum number of (n,ε)-spanning orbits","The minimum number of balls of radius ε needed to cover X","The number of (n,ε)-separated points"],
   ans:3,
   exp:"Both definitions (spanning and separating sets) give the same entropy. s(n,ε) = maximum number of (n,ε)-separated points (no two within ε in the first n iterates). Equivalently use r(n,ε) = min spanning set; both give h_top via the same limit."},
  {q:"The proximal relation P in a topological dynamical system: x P y if inf_{n≥0} d(Tⁿx, Tⁿy) = 0. In a distal system (no two distinct proximal points), the Ellis semigroup E(X) is:",
   opts:["A group (every element is invertible)","A semigroup with a zero element","Trivial (one element)","Isomorphic to ℤ"],
   ans:0,
   exp:"Distal systems: E(X) is a group. This is because in a distal system, every element of E(X) is bijective (invertible). The structure theorem for distal systems (Furstenberg) builds them as towers of isometric extensions."},
  {q:"An almost periodic function f: ℝ → ℂ (Bohr) has the property that for every ε > 0 there exists L > 0 such that every interval of length L contains an ε-period. This is equivalent to:",
   opts:["f being periodic","f being the uniform limit of trigonometric polynomials","f being bounded","f being integrable"],
   ans:1,
   exp:"Bohr's theorem: almost periodic functions are exactly the uniform limits of trigonometric polynomials (finite sums Σcₖe^{iλₖt}). They are the continuous functions on the Bohr compactification ℝ̂ of ℝ."},
  {q:"The Furstenberg structure theorem for distal systems states that every minimal distal system is:",
   opts:["An isometric extension of a point","A transfinite tower of isometric extensions (each stage is an isometric extension of the previous)","A group rotation","A Bernoulli system"],
   ans:1,
   exp:"Furstenberg (1963): every minimal distal flow is built as a (possibly transfinite) tower of isometric extensions, starting from a point. Each isometric extension adds a compact group fiber with isometric action. This completely characterises distal systems."},
  {q:"A topological dynamical system (X,T) is topologically mixing if for any two nonempty open sets U, V:",
   opts:["T(U) ∩ V ≠ ∅","There exists N such that Tⁿ(U) ∩ V ≠ ∅ for all n ≥ N","The orbit of every point is dense","Every closed set is T-invariant"],
   ans:1,
   exp:"Topological mixing: eventually, every pair of open sets U, V has Tⁿ(U)∩V ≠ ∅ for all large n (not just some n, as in transitivity). Mixing implies transitivity; Bernoulli shifts are mixing but irrational rotations are transitive but not mixing."},
  {q:"The rotation number of an orientation-preserving homeomorphism f of the circle S¹ = ℝ/ℤ is defined via a lift F: ℝ → ℝ as:",
   opts:["F(0)","lim_{n→∞} Fⁿ(0)/n (mod 1)","F(1) − F(0)","F'(0)"],
   ans:1,
   exp:"Rotation number ρ(f) = lim Fⁿ(0)/n (mod 1), independent of initial point and of the lift (up to integer). f is conjugate to the rotation R_ρ iff ρ is irrational; if ρ is rational p/q, f has a periodic orbit of period q (Poincaré classification)."},
  {q:"Jewett-Krieger theorem states that every ergodic measure-preserving system (X,μ,T) is:",
   opts:["Isomorphic to a Bernoulli shift","Measurably isomorphic to a uniquely ergodic minimal topological system","Orbit equivalent to an irrational rotation","Conjugate to a group rotation"],
   ans:1,
   exp:"Jewett-Krieger: every ergodic system can be realised as a uniquely ergodic minimal homeomorphism of a compact metric space. This shows the abstract measure-theoretic category contains all topological systems—and topological systems can realise any abstract ergodic system."},
],

7:[
  {q:"The ergodic decomposition theorem states that every invariant probability measure μ for a measurable transformation T can be decomposed as:",
   opts:["μ = μ_ergodic uniquely","μ = ∫ μ_x dμ(x) where μ_x is ergodic for μ-a.e. x","μ = Σ cₙμₙ for finitely many ergodic measures","μ is always ergodic for a generic T"],
   ans:1,
   exp:"Ergodic decomposition: the space of invariant measures is a Choquet simplex with extreme points being the ergodic measures. Every invariant measure decomposes as a (possibly uncountable) integral/mixture of ergodic measures, unique for standard Borel systems."},
  {q:"The spectrum of the Koopman operator U_T on L²(μ) determines dynamical properties. Weak mixing is equivalent to U_T having:",
   opts:["Purely absolutely continuous spectrum","No eigenvalues other than 1 (continuous spectrum)","Purely discrete (point) spectrum","A spectral gap"],
   ans:1,
   exp:"Weak mixing ↔ Koopman operator has no eigenvalues other than λ = 1 (of multiplicity 1). Equivalently, for all f ∈ L²: (1/N)Σ |⟨U_T^n f, f⟩|² → |⟨f,1⟩|². Weak mixing is strictly between ergodicity (Cesàro) and strong mixing (convergence)."},
  {q:"The natural extension of a non-invertible measure-preserving system (X,μ,T) is the invertible system (X̃,μ̃,T̃) where X̃ is:",
   opts:["The product space X×X","The inverse limit: {(x₀,x₁,...) : T(xₙ₊₁) = xₙ for all n}","The suspension of X over T","The one-sided shift on X^ℕ"],
   ans:1,
   exp:"The natural extension X̃ = {(xₙ)_{n≤0} : T(xₙ) = xₙ₊₁} is the 'smallest' invertible extension. T̃ is the left-shift. The natural extension of the Gauss map is the two-sided continued fraction map, central in the metric theory of continued fractions."},
  {q:"Rokhlin's lemma states that for any aperiodic measure-preserving transformation T and ε > 0, there exists a measurable set F such that F, TF, …, T^{n-1}F are disjoint and:",
   opts:["Their union has measure 1","Their union has measure > 1 − ε","F has measure 1/n exactly","T^n F = F"],
   ans:1,
   exp:"Rokhlin (Halmos-Rokhlin) lemma: for every aperiodic T and any n,ε, there exists F with F, TF, …, T^{n-1}F disjoint and μ(∪T^kF) > 1−ε. This is the key approximation lemma used in entropy theory and the proof of Ornstein's theorem."},
  {q:"The entropy of a factor of an ergodic system satisfies:",
   opts:["h(factor) ≥ h(T)","h(factor) ≤ h(T), with equality iff the factor is isomorphic to T","h(factor) = h(T) always","h(factor) = 0 always"],
   ans:1,
   exp:"Factors have smaller or equal entropy: if π: (X,T) → (Y,S) is a factor map, then h(S) ≤ h(T). Equality h(S) = h(T) holds iff π is an isomorphism (in the Bernoulli case—Ornstein's theorem implies this for Bernoulli shifts)."},
  {q:"Furstenberg's correspondence principle (1977) translates combinatorial density results to ergodic theory. It states that for a set A ⊆ ℤ with upper density d̄(A) > 0, there exists a measure-preserving system (X,μ,T) and a set Ã ⊆ X with μ(Ã) = d̄(A) such that:",
   opts:["A contains arbitrarily long arithmetic progressions iff Ã has the same property","d̄(A ∩ (A-n) ∩ (A-2n) ∩ …) = μ(Ã ∩ T⁻ⁿÃ ∩ T⁻²ⁿÃ ∩ …)","A is syndetic iff Ã is T-invariant","d̄(A ∩ (A-n)) ≥ μ(Ã)² − ε"],
   ans:3,
   exp:"Furstenberg's principle: d̄(A∩(A-n)∩…∩(A-kn)) ≥ μ(Ã∩T⁻ⁿÃ∩…∩T⁻ᵏⁿÃ) − ε for most n. Multiple recurrence (positivity of the right side for some n) translates back to arithmetic progressions in A—this is the ergodic proof of Szemerédi's theorem."},
  {q:"The Abramov-Rokhlin formula expresses the entropy of a skew product T̃(x,y) = (Tx, φ(x,y)) over (X,μ,T) with fiber maps φ(x,·) preserving measures ν_x as:",
   opts:["h(T̃) = h(T) + h(fiber)","h(T̃) = h(T) + ∫ h(φ(x,·)) dμ(x)","h(T̃) = max(h(T), h(fiber))","h(T̃) = h(T)·h(fiber)"],
   ans:1,
   exp:"Abramov-Rokhlin: h(T̃) = h(T) + ∫_X h(φ(x,·)) dμ(x). The entropy of a skew product is the base entropy plus the fiberwise entropy (averaged over the base). This generalises the product formula h(T×S) = h(T) + h(S)."},
  {q:"Krieger's generator theorem states that an ergodic measure-preserving system (X,μ,T) has a generating partition of size k (a finite partition 𝒫 with ∨_{n=-∞}^∞ T^n𝒫 = ℬ) if:",
   opts:["h(T) = 0","h(T) < log k","h(T) = log k","k ≥ 2"],
   ans:1,
   exp:"Krieger's theorem: an ergodic aperiodic system with entropy h(T) < log k has a generator of size k. In particular, any system with finite entropy has a finite generator. The minimum generator size is ⌈e^{h(T)}⌉ (Rokhlin-Sinai theorem)."},
],

8:[
  {q:"The Linearisation theorem of Sternberg (smooth conjugacy near a hyperbolic fixed point) strengthens Hartman-Grobman by providing a smooth (C^∞) conjugacy when:",
   opts:["The system is analytic","The eigenvalues satisfy non-resonance conditions: no eigenvalue λⱼ equals a monomial λ₁^{m₁}…λₙ^{mₙ} with Σmᵢ ≥ 2","The fixed point is asymptotically stable","The linearization has real eigenvalues"],
   ans:1,
   exp:"Sternberg's theorem: if the eigenvalues of Df(0) satisfy non-resonance conditions (no resonances among them), then f is C^∞ (even C^ω)-conjugate to its linear part. Resonances obstruct smooth linearisation and lead to normal forms (Dulac, Poincaré normal form theory)."},
  {q:"Conley's fundamental theorem of dynamical systems states that any flow on a compact space decomposes into:",
   opts:["Fixed points and limit cycles","Chain-recurrent set (attractor-free dynamics) and gradient-like part flowing between chain-recurrent pieces","Stable and unstable manifolds","Invariant tori"],
   ans:1,
   exp:"Conley decomposition: X = CR(T) ∪ {points flowing between chain-recurrent pieces}. There exists a Lyapunov function (Conley-Lyapunov function) that is constant on chain-recurrent pieces and strictly decreasing on connecting orbits. This is the 'fundamental theorem of dynamical systems'."},
  {q:"The stable manifold theorem for a hyperbolic fixed point guarantees the existence of W^s(x*) as an injectively immersed submanifold of the same dimension as the stable subspace. Near x*, W^s is:",
   opts:["A linear subspace","Tangent to E^s at x* and an exact graph over E^s (via the Perron-Irwin method)","Equal to E^s","An analytic submanifold always"],
   ans:1,
   exp:"The stable manifold is tangent to E^s (the stable eigenspace) at x*, and locally is a graph over E^s. It is as smooth as the vector field (C^r if f ∈ C^r). The Hadamard-Perron proof constructs it as a fixed point of a graph-transform operator."},
  {q:"Global asymptotic stability of ẋ = f(x) can be established by finding a Lyapunov function V: ℝⁿ → ℝ that is positive definite, radially unbounded (V(x) → ∞ as |x| → ∞), and satisfies V̇ < 0 for x ≠ 0. Radial unboundedness ensures:",
   opts:["V has a unique minimum","All sublevel sets {V ≤ c} are compact, so trajectories cannot escape to infinity","V is convex","V is a norm"],
   ans:1,
   exp:"Radially unbounded (V → ∞) Lyapunov functions ensure that all level sets are compact, so trajectories are bounded for all time. Combined with V̇ < 0, this gives global (not just local) asymptotic stability."},
  {q:"Input-output stability (BIBO: bounded input bounded output) for a linear system with transfer function G(s) holds if and only if:",
   opts:["G(s) has no poles","All poles of G(s) are in the open left half-plane (OLHP) and G(s) is proper","G(s) is a polynomial","G(s) has no zeros"],
   ans:1,
   exp:"BIBO stability ↔ the impulse response g(t) is absolutely integrable (∫₀^∞ |g(t)| dt < ∞) ↔ all poles of G(s) are in the open left half-plane. This is the standard condition for stability of linear time-invariant systems."},
  {q:"The Popov criterion for absolute stability of a feedback system with a sector nonlinearity φ (0 ≤ φ(y)/y ≤ K) requires the existence of a constant q ≥ 0 such that:",
   opts:["Re[G(iω)] ≥ −1/K for all ω","Re[(1+iqω)G(iω)] + 1/K ≥ 0 for all ω ≥ 0","The Nyquist plot of G lies to the right of −1/K","Im[G(iω)] = 0"],
   ans:1,
   exp:"Popov's criterion (1961): absolute stability holds if (1+iqω)G(iω) + 1/K has nonnegative real part for some q ≥ 0. The Popov line in the Nyquist diagram separates stable from unstable. Stronger than the circle criterion, Popov's condition is less conservative."},
  {q:"The Lyapunov equation AᵀP + PA = −Q for a given positive definite Q has a unique positive definite solution P if and only if:",
   opts:["A is symmetric","A is Hurwitz stable (all eigenvalues in the open left half-plane)","A is orthogonal","A is nilpotent"],
   ans:1,
   exp:"Lyapunov's algebraic equation: the unique solution P = ∫₀^∞ e^{Aᵀt}Qe^{At}dt is positive definite iff A is Hurwitz. This links the algebraic Lyapunov equation to stability analysis and is used to compute quadratic Lyapunov functions algorithmically."},
  {q:"Zubov's method constructs the exact domain of attraction D(0) of an asymptotically stable equilibrium as the sublevel set {V < 1} of a function V satisfying a specific PDE. The PDE is:",
   opts:["∇V · f = −V","∇V · f = −(1−V)h(x) for some positive h","∇V · f = −|x|²","∇V · f = 1 − V²"],
   ans:1,
   exp:"Zubov's PDE: ∇V(x)·f(x) = −h(x)(1−V(x)) with boundary condition V → 1 as x → ∂D. The solution V ∈ [0,1) in D, V = 1 on ∂D, giving the exact boundary of the domain of attraction. Unlike standard Lyapunov functions, Zubov's gives the exact (not merely an estimate of) the domain."},
],

9:[
  {q:"The closing lemma (Pugh, 1967) states that for a C¹ vector field, any recurrent orbit can be:",
   opts:["Proved to be periodic by structural stability","Closed (made periodic) by an arbitrarily small C¹ perturbation of the vector field","Ergodic","Hyperbolic after perturbation"],
   ans:1,
   exp:"Pugh's C¹ closing lemma: if x is a nonwandering point (equivalently, a recurrent point in many settings) of a C¹ flow, there is a C¹-small perturbation making x periodic. This connects the nonwandering set to periodic orbits but fails for C² (Gutierrez counterexample)."},
  {q:"The λ-lemma (inclination lemma) for a hyperbolic fixed point states that any disk transverse to W^s eventually:",
   opts:["Converges to the fixed point","Has iterates that are C¹-close to the unstable manifold W^u on compact subsets","Lies in W^u","Is mapped to a fixed disk"],
   ans:1,
   exp:"λ-lemma (Palis): if a disk D is transverse to W^s at a point p ∈ W^u, then the images T^n(D) approach (in C¹) a disk in W^u as n → ∞. This is used to prove the stable manifold theorem and analyse homoclinic tangencies."},
  {q:"For an Anosov diffeomorphism, the measure of maximal entropy (Parry measure) is distinct from the SRB measure unless the system is:",
   opts:["Bernoulli","Conjugate to a linear toral automorphism","A conformal Anosov flow","Volume-preserving"],
   ans:3,
   exp:"The SRB measure is absolutely continuous along unstable manifolds and equal to the Riemannian volume iff the Lyapunov exponents satisfy the Pesin formula for volume. The Parry (maximal entropy) measure equals volume iff the system is volume-preserving and ergodic—coinciding with the SRB measure."},
  {q:"Structural stability of a diffeomorphism T means that all diffeomorphisms C¹-close to T are:",
   opts:["Isomorphic in the measure-theoretic sense","Topologically conjugate to T","Measure-conjugate to T","Periodic"],
   ans:1,
   exp:"Structural stability: there is a C¹ neighborhood U of T such that every S ∈ U is topologically conjugate to T. Peixoto's theorem characterises structurally stable vector fields on compact surfaces; in higher dimensions, Axiom A + strong transversality condition (Smale) is sufficient."},
  {q:"The non-wandering set Ω(T) of a diffeomorphism T consists of points x such that for every neighborhood U of x:",
   opts:["T(x) ∈ U","T^n U ∩ U ≠ ∅ for some n > 0","U is T-invariant","The orbit of x is periodic"],
   ans:1,
   exp:"Non-wandering: x ∈ Ω(T) iff every neighborhood U returns: ∃n > 0 with T^n(U)∩U ≠ ∅. Ω(T) is closed and T-invariant. For Axiom A systems, Ω(T) is hyperbolic and equals the closure of periodic orbits—the spectral decomposition theorem applies."},
  {q:"Markov partitions for Anosov diffeomorphisms enable symbolic coding. A Markov partition {R₁,…,Rₖ} of a basic set satisfies the Markov property:",
   opts:["T(Rᵢ) = Rⱼ for some j","T(int(Rᵢ)) ∩ int(Rⱼ) ≠ ∅ implies T(W^u(Rᵢ)) ⊇ W^u(Rⱼ) and T(W^s(Rᵢ)) ⊆ W^s(Rⱼ)","The rectangles tile X exactly","T maps each Rᵢ onto a single Rⱼ"],
   ans:1,
   exp:"Markov property: when T(Rᵢ)∩Rⱼ ≠ ∅, the unstable boundary of Rᵢ maps across Rⱼ (Markov in the u-direction) and the stable boundary maps inside (s-direction). This gives a well-defined symbolic dynamics via the transition matrix Aᵢⱼ = 1[T(Rᵢ)∩Rⱼ ≠ ∅]."},
  {q:"The Bowen-Manning formula expresses the Hausdorff dimension of the basic set Λ of a conformal Anosov diffeomorphism in terms of the pressure function P(·). Specifically:",
   opts:["dim_H(Λ) = dim(W^s) + dim(W^u)","dim_H(Λ) = t_s + t_u where P(−t_s φ^s) = 0 and P(−t_u φ^u) = 0 (t_s and t_u are solutions to Bowen equations)","dim_H(Λ) = topological entropy / Lyapunov exponent","dim_H(Λ) = n (the ambient dimension)"],
   ans:1,
   exp:"For conformal Anosov maps, dim_H(Λ) = t_s + t_u where t_s (resp. t_u) solves the Bowen equation P(−t_s log|DT|_{E^s}|) = 0 (P = topological pressure). The formula decouples into stable and unstable contributions in the conformal case."},
  {q:"The concept of a dominated splitting generalises hyperbolicity. A T-invariant splitting TM|_Λ = E ⊕ F is dominated if there exists C > 0, λ < 1 such that for all x and all unit vectors u ∈ Eₓ, v ∈ Fₓ:",
   opts:["||DTⁿu|| < ||DTⁿv||","||DTⁿu|| ≤ Cλⁿ||DTⁿv||","||DTⁿu|| / ||DTⁿv|| → 0","F is contracting and E is expanding"],
   ans:1,
   exp:"Dominated splitting: ||DT^n|_E(x)|| · ||DT^{-n}|_F(T^nx)|| ≤ Cλ^n (equivalently, E is uniformly dominated by F). Dominated splittings are C¹-robust and persist under perturbations, unlike hyperbolicity which requires both expansion and contraction."},
],

10:[
  {q:"At a pitchfork bifurcation (common in symmetric systems), as the parameter passes through the critical value:",
   opts:["One equilibrium disappears","One stable equilibrium becomes unstable and two new stable equilibria are born (supercritical) or vice versa (subcritical)","Two equilibria merge and annihilate","A limit cycle appears"],
   ans:1,
   exp:"Supercritical pitchfork: single stable equilibrium loses stability and two symmetric stable equilibria are born. Subcritical: two unstable equilibria merge with the main equilibrium, which then loses stability. Occurs in systems with ℤ₂ symmetry (x ↦ −x)."},
  {q:"Normal form theory reduces a vector field near a bifurcation to its simplest equivalent form. The normal form for the Hopf bifurcation (in polar coordinates) is:",
   opts:["ṙ = μr + r³, θ̇ = ω","ṙ = μr − r³, θ̇ = ω + br² (supercritical)","ṙ = μr, θ̇ = ω","ṙ = r², θ̇ = ω"],
   ans:1,
   exp:"Supercritical Hopf normal form: ṙ = μr − r³, θ̇ = ω + br². For μ < 0: stable focus at origin; for μ > 0: unstable focus and stable limit cycle of radius √μ. The cubic term (first Lyapunov coefficient) determines super- vs. subcritical."},
  {q:"Center manifold reduction at a non-hyperbolic equilibrium works because the center manifold W^c is attracting and carries the essential bifurcation dynamics. Specifically, after the reduction to ẋ_c = f_c(x_c) on W^c:",
   opts:["The full system is linear","Bifurcations in the full system correspond bijectively to bifurcations in the reduced system on W^c","The reduced system has more equilibria","The reduced system is Hamiltonian"],
   ans:1,
   exp:"Center manifold theorem: the qualitative dynamics (number and stability of equilibria, limit cycles) near the bifurcation is captured by the reduced equation on W^c. The center manifold is computed as a formal power series in x_c."},
  {q:"The Shilnikov condition for a homoclinic orbit to a saddle-focus equilibrium in ℝ³ (eigenvalues −ρ ± iω, λ with ρ,ω,λ > 0) leads to chaos if:",
   opts:["λ > ρ (the Shilnikov condition)","ρ > λ","ω > λ","The orbit is asymmetric"],
   ans:0,
   exp:"Shilnikov's theorem: if λ > ρ (the real positive eigenvalue exceeds the magnitude of the real part of the complex eigenvalues), then near the homoclinic orbit there are infinitely many periodic orbits with horseshoe dynamics—Shilnikov chaos."},
  {q:"The Lyapunov-Schmidt reduction is used to study bifurcation from a known solution u₀ of F(u,λ) = 0 when the Fréchet derivative D_uF(u₀,λ₀) has a nontrivial kernel. It splits the equation into:",
   opts:["Two separate ODEs","An equation in the image of D_uF (solvable by implicit function theorem) and a finite-dimensional bifurcation equation in the kernel","A PDE and an ODE","A Hamiltonian system"],
   ans:1,
   exp:"Lyapunov-Schmidt: project onto Im(L) and Ker(L*). The Im(L) component is solved by IFT (giving u as a function of the kernel component v and λ); the Ker(L*) component gives the bifurcation equation G(v,λ) = 0, which is finite-dimensional."},
  {q:"Global bifurcations (homoclinic/heteroclinic connections) cannot be detected by local normal forms. The most important tool is:",
   opts:["The implicit function theorem","The Melnikov function or Lin's method (for computing distances between stable/unstable manifolds)","The center manifold theorem","Floquet theory"],
   ans:1,
   exp:"Global bifurcations involving homoclinic/heteroclinic orbits require measurement of manifold separations globally. Melnikov's method (for near-integrable systems) and Lin's method (general) provide these measurements and predict the bifurcation values."},
  {q:"The period of the limit cycle born in a Hopf bifurcation at ω = ω₀ is approximately:",
   opts:["2π/ω₀ (the period of the linear oscillation)","2π/ω₀ + O(μ) for small bifurcation parameter μ","1/μ","2π"],
   ans:1,
   exp:"The limit cycle period near a Hopf bifurcation is 2π/ω₀ + O(μ), where ω₀ is the imaginary part of the critical eigenvalue. The frequency correction O(μ) comes from the nonlinear terms (the b in the normal form θ̇ = ω₀ + b·r²)."},
  {q:"In the context of continuation methods (numerical bifurcation analysis), pseudo-arclength continuation is used to follow solution branches past:",
   opts:["All bifurcation points","Fold (saddle-node) points where the standard parameter-continuation fails (vertical tangent)","Hopf bifurcation points","Fixed points only"],
   ans:1,
   exp:"Pseudo-arclength continuation parameterises the solution branch by arclength (in solution × parameter space) rather than by the parameter alone. This handles fold points (turning points) where the branch turns back, allowing continuation past the fold."},
],

};

const BASE = path.join(__dirname, 'questions');
const PART_DIRS_MAP = {
  1:'part-i-foundations',2:'part-i-foundations',3:'part-i-foundations',
  4:'part-i-foundations',5:'part-i-foundations',
  6:'part-ii-dynamical-systems',7:'part-ii-dynamical-systems',8:'part-ii-dynamical-systems',
  9:'part-ii-dynamical-systems',10:'part-ii-dynamical-systems',
};
const CH_DIRS_MAP = {
  1:'ch01-real-analysis',2:'ch02-measure-theory',3:'ch03-topology',
  4:'ch04-ordinary-differential-equations',5:'ch05-linear-algebra',
  6:'ch06-topological-dynamics',7:'ch07-ergodic-theory',8:'ch08-stability-theory',
  9:'ch09-hyperbolic-dynamics',10:'ch10-bifurcation-theory',
};

let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);
  const dir = path.join(BASE, PART_DIRS_MAP[ch], CH_DIRS_MAP[ch]);
  const existing = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir, existing[0]),'utf8'));
  const {chTitle, part} = sample;
  qs.forEach((q,i) => {
    const n = existing.length + i + 1;
    const file = path.join(dir, `q${String(n).padStart(2,'0')}.json`);
    fs.writeFileSync(file, JSON.stringify({ch,part,chTitle,...q},null,2)+'\n');
    console.log('wrote', path.relative(__dirname,file));
    total++;
  });
}
console.log(`\nDone. ${total} questions written.`);
