#!/usr/bin/env node
'use strict';
const fs   = require('fs');
const path = require('path');

const META = {
  11:{part:2,dir:'part-ii-dynamical-systems',ch:'ch11-chaos-theory'},
  12:{part:2,dir:'part-ii-dynamical-systems',ch:'ch12-symbolic-dynamics'},
  13:{part:2,dir:'part-ii-dynamical-systems',ch:'ch13-complex-dynamics'},
  14:{part:2,dir:'part-ii-dynamical-systems',ch:'ch14-hamiltonian-systems'},
  15:{part:2,dir:'part-ii-dynamical-systems',ch:'ch15-infinite-dimensional-dynamics'},
  16:{part:3,dir:'part-iii-information-theory',ch:'ch16-classical-information-theory'},
  17:{part:3,dir:'part-iii-information-theory',ch:'ch17-entropy-generalizations'},
  18:{part:3,dir:'part-iii-information-theory',ch:'ch18-algorithmic-information-theory'},
  19:{part:3,dir:'part-iii-information-theory',ch:'ch19-network-information-theory'},
  20:{part:3,dir:'part-iii-information-theory',ch:'ch20-information-geometry'},
};

const EXTRA = {

11:[
  {q:"The Smale horseshoe map on the square D demonstrates chaos by showing the existence of an invariant Cantor set on which the dynamics is conjugate to:",
   opts:["A rotation","The full 2-shift (Bernoulli shift on 2 symbols)","A Markov chain","An irrational rotation"],
   ans:1,
   exp:"Smale's horseshoe: the intersection ∩_{n=-∞}^∞ T^n(D) is a Cantor set on which T is conjugate to the 2-sided shift on {0,1}. This gives uncountably many distinct orbits, dense periodic orbits, and sensitive dependence—the prototypical example of deterministic chaos."},
  {q:"The Hénon map (x,y) ↦ (1 − ax² + y, bx) is a benchmark chaotic map. For the parameter values a=1.4, b=0.3 it has a strange attractor with Hausdorff dimension approximately:",
   opts:["1","1.26","2","0.63"],
   ans:1,
   exp:"The Hénon attractor for a=1.4, b=0.3 has Hausdorff dimension ≈ 1.261 (estimated numerically). The attractor is 'thin' in one direction (contracting, b=0.3 gives |Jac|=b<1) and has fractal structure in the other, giving dimension between 1 and 2."},
  {q:"The Birkhoff ergodic theorem for a topological dynamical system implies that time averages along orbits converge for μ-almost every starting point. For a fully chaotic map like the doubling map Tx = 2x (mod 1):",
   opts:["Time averages equal space averages for all x","Time averages equal space averages for Lebesgue-a.e. x (but not all x, since periodic points give rational averages)","Time averages never converge","Time averages equal the maximum of f"],
   ans:1,
   exp:"Ergodicity of the doubling map w.r.t. Lebesgue measure: for a.e. x (in the Lebesgue sense), (1/n)Σ_{k=0}^{n-1} f(T^kx) → ∫f dx. Periodic points (countable set) give rational averages that typically differ from the space average."},
  {q:"The topological conjugacy class of the tent map Tₐ (slope ±a) and the logistic map f_r are related by:",
   opts:["They are always conjugate","For r = 4, the logistic map is conjugate to the full tent map T₂ via x = sin²(πθ/2)","They are conjugate only for r = 4 and a = 2","They have the same entropy but different dynamics"],
   ans:1,
   exp:"At r = 4, fᵣ(x) = 4x(1-x) is topologically conjugate to the full tent map T₂ (slope ±2) via the semi-conjugacy θ ↦ sin²(πθ/2). Both have topological entropy log 2 and support the same ergodic measure (arcsine law for the logistic map)."},
  {q:"The correlation function C(n) = ∫ f ∘ Tⁿ · g dμ − ∫f dμ ∫g dμ for a mixing system satisfies C(n) → 0. For Anosov diffeomorphisms with SRB measure, this decay is:",
   opts:["Polynomial","Exponential in n","Zero for all n > 1","Oscillatory"],
   ans:1,
   exp:"For contact Anosov flows and Anosov diffeomorphisms with Hölder observables, Ruelle (1976) and later Liverani (1995) proved exponential decay of correlations: |C(n)| ≤ Cρⁿ for some ρ < 1. This is related to the spectral gap of the Ruelle-Perron-Frobenius operator."},
  {q:"Chaos in the sense of positive topological entropy is implied by the existence of a transverse homoclinic point. The Smale-Birkhoff theorem states:",
   opts:["Transverse homoclinic points imply a periodic orbit","A transverse homoclinic point implies a hyperbolic invariant set homeomorphic to the full shift (a horseshoe)","Homoclinic points imply mixing","Homoclinic tangencies always lead to chaos"],
   ans:1,
   exp:"Smale-Birkhoff: near a transverse homoclinic point (stable and unstable manifolds of a hyperbolic periodic orbit meet transversally), there is a horseshoe—an invariant set conjugate to the shift. This gives positive topological entropy and countably many periodic orbits."},
  {q:"The Yorke-Li theorem ('Period Three Implies Chaos', 1975) states that for a continuous map f: [a,b] → [a,b]:",
   opts:["Existence of a fixed point implies chaos","If f has a period-3 orbit, then f has periodic orbits of all periods and uncountably many irregular (non-periodic) points","Period-3 implies the map is topologically conjugate to the tent map","Chaos implies period-3"],
   ans:1,
   exp:"Li-Yorke theorem: period-3 → all periods. More precisely, the theorem produces a 'scrambled set' of uncountably many points with irregular orbits (pairs asymptotically independent but not asymptotically separate). This is the Li-Yorke definition of chaos."},
  {q:"The Ruelle-Perron-Frobenius (transfer) operator L_φ acting on continuous functions by (L_φ f)(x) = Σ_{Ty=x} e^{φ(y)} f(y) has a spectral gap for:",
   opts:["Any continuous φ","Hölder continuous φ on a topologically mixing SFT (or hyperbolic system)","Analytic φ only","φ ≡ 0 only"],
   ans:1,
   exp:"For Hölder φ on a mixing SFT, L_φ has a simple maximal eigenvalue e^{P(φ)} (topological pressure) with a positive eigenfunction, and the rest of the spectrum lies in a strictly smaller disk. This spectral gap implies exponential decay of correlations for Gibbs measures."},
],

12:[
  {q:"The two-sided full shift (Σ_k, σ) on k symbols and the one-sided shift (Σ_k^+, σ^+) have the same topological entropy (log k) but differ in that:",
   opts:["They are topologically conjugate","The two-sided shift is invertible (homeomorphism) while the one-sided shift is not invertible","The one-sided shift has more invariant measures","The two-sided shift has fewer periodic points"],
   ans:1,
   exp:"The two-sided shift is a homeomorphism (σ⁻¹ is the left shift). The one-sided shift σ^+ is not invertible: σ^+(x) = (x₁,x₂,...) drops x₀ and cannot be inverted. The natural extension of the one-sided shift is the two-sided shift."},
  {q:"The Perron-Frobenius theorem applied to the adjacency matrix A of an irreducible SFT gives the topological entropy as log ρ(A). The unique measure of maximal entropy (Parry measure) is the Markov measure with transition matrix:",
   opts:["Aᵢⱼ / Σⱼ Aᵢⱼ","Aᵢⱼ uⱼ / (ρ uᵢ) where u is the right Perron eigenvector","Aᵢⱼ / ρ","(AᵀA)ᵢⱼ / ρ²"],
   ans:1,
   exp:"Parry measure: transition probability Pᵢⱼ = Aᵢⱼ vⱼ / (ρ vᵢ) using the right Perron eigenvector v. The initial distribution π is given by the left eigenvector (πᵢ = uᵢvᵢ / Σⱼ uⱼvⱼ). This is the unique shift-invariant measure of maximal entropy."},
  {q:"The complexity function p(n) of a minimal subshift counts the number of distinct words of length n. Morse-Hedlund theorem characterises periodic sequences by:",
   opts:["p(n) = 1 for all n","p(n) ≤ n for all n implies the sequence is eventually periodic; p(n) < n+1 for some n implies periodic","p(n) is eventually constant iff the sequence is eventually periodic","p(n) ≥ n+1 for all n iff the sequence is not periodic"],
   ans:3,
   exp:"Morse-Hedlund theorem: a sequence x ∈ A^ℤ is periodic iff p(n) ≤ n for some n (since p(n) ≤ n implies p(n) is eventually constant). Equivalently, x is not periodic iff p(n) ≥ n+1 for all n. The minimal complexity for non-periodic sequences is the Sturmian case p(n) = n+1."},
  {q:"Sturmian sequences are the aperiodic sequences with minimal complexity p(n) = n+1. They are in bijection with:",
   opts:["Periodic orbits of the shift","Irrational rotations: the orbit of 0 under T_α(x)=x+α (mod 1) coded by the partition [0,α)∪[α,1)","Bernoulli sequences","SFTs of minimal entropy"],
   ans:1,
   exp:"Every Sturmian sequence arises as a coding of an irrational rotation by a two-interval partition. The rotation number α ∈ (0,1)\\ℚ parameterises the Sturmian sequence. Sturmian sequences have zero entropy and appear in combinatorics on words and quasicrystal theory."},
  {q:"Williams' classification of SFTs by strong shift equivalence states that two SFTs (with adjacency matrices A, B) are conjugate iff:",
   opts:["A and B have the same determinant","A and B are strongly shift equivalent (related by a chain of elementary equivalences R, S with RS=A, SR=B)","A and B have the same spectrum","A and B have the same size"],
   ans:1,
   exp:"Williams' theorem (1973): SFTs defined by non-negative integer matrices A, B are topologically conjugate iff A and B are strongly shift equivalent (SSE). Checking SSE is algorithmically undecidable in general; shift equivalence (a weaker algebraic relation) is decidable but not equivalent to SSE."},
  {q:"The notion of a sofic shift (image of an SFT under a factor map) is strictly more general than SFT. The key example showing the difference is:",
   opts:["The golden mean shift","The even shift (sequences where between any two 1s there are an even number of 0s), which is sofic but not an SFT","The full shift","Any mixing SFT"],
   ans:1,
   exp:"The even shift: S = {x ∈ {0,1}^ℤ : every run of 0s between 1s has even length}. It is sofic (factor of an SFT via a 2-symbol labeling) but not an SFT—no finite list of forbidden words characterises it (arbitrarily long 'even run' conditions are needed)."},
  {q:"The dimension group of an SFT with adjacency matrix A is the inductive limit group:",
   opts:["ℤ[A] = ℤ[x]/(det(xI-A))","(ℤ^n, A): the group ℤ^n with the automorphism induced by A, forming the direct limit under multiplication by A","det(A)·ℤ","The group of invariant measures"],
   ans:1,
   exp:"The dimension group (Krieger, 1980) is the direct limit G(A) = lim_{→} (ℤ^n →^A ℤ^n), with the automorphism induced by A. It is a complete invariant for eventual conjugacy (flow equivalence) of SFTs and connects symbolic dynamics to K-theory."},
  {q:"Substitution systems generate sequences by iterating a substitution σ: A → A^* (each symbol maps to a finite word). The topological entropy of a substitution shift equals:",
   opts:["log|A|","0 (substitution shifts have zero entropy)","The growth rate of the substitution","log(spectral radius of the substitution matrix)"],
   ans:1,
   exp:"Substitution shifts are minimal (under primitivity of the substitution) and have entropy 0: p(n) grows polynomially (often linearly), far slower than exponential. This contrasts with SFTs; substitution shifts are the main source of zero-entropy, non-periodic, minimal systems."},
],

13:[
  {q:"The Riemann mapping theorem states that any simply connected proper open subset U ⊊ ℂ is:",
   opts:["Conformally equivalent to the upper half-plane only","Conformally equivalent to the unit disk 𝔻 (by a biholomorphic map)","Conformally equivalent to ℂ","A Fatou component"],
   ans:1,
   exp:"Riemann mapping theorem: any simply connected U ⊊ ℂ is biholomorphic to 𝔻. The map is unique up to Möbius transformations of 𝔻. This is a cornerstone of complex analysis and is used in complex dynamics to study basins of attraction."},
  {q:"Sullivan's no-wandering-domains theorem (1985) states that for a rational map f: ℂ̂ → ℂ̂:",
   opts:["All Fatou components are eventually periodic","Every wandering domain maps to a periodic cycle of Fatou components (no proper wandering domains exist)","The Fatou set is always connected","Every Fatou component is simply connected"],
   ans:1,
   exp:"Sullivan's theorem (using quasiconformal surgery): rational maps have no wandering Fatou components—every Fatou component eventually maps into a periodic cycle. Before Sullivan, wandering domains were only ruled out for specific classes. This was a landmark application of quasiconformal deformations."},
  {q:"The Böttcher coordinate near a superattracting fixed point 0 (f(z) = cz^d + …, d ≥ 2) is a biholomorphism φ: (U,0) → (𝔻,0) such that:",
   opts:["φ(f(z)) = φ(z)²","φ(f(z)) = φ(z)^d","φ(f(z)) = d·φ(z)","φ(f(z)) = φ(z) + 1"],
   ans:1,
   exp:"Böttcher coordinate: φ linearises f to z ↦ z^d. It satisfies φ(f(z)) = φ(z)^d, conjugating f to the power map. This is used to define the Green's function and external rays for polynomials, which are the level sets and gradient lines of log|φ|."},
  {q:"Parabolic fixed points (multiplier λ = e^{2πip/q}) have associated Leau-Fatou petals. The number of attracting petals is:",
   opts:["1","p","q","p+q"],
   ans:2,
   exp:"At a parabolic fixed point with multiplier e^{2πip/q}, the local dynamics has q attracting petals and q repelling petals alternating around the fixed point (Leau-Fatou flower theorem). Orbits in each attracting petal converge to the fixed point along specific directions."},
  {q:"The degree of a rational map f: ℂ̂ → ℂ̂ is the number of preimages of a generic point. The Riemann-Hurwitz formula for a degree-d map with ramification gives:",
   opts:["2 − 2·deg(f) = χ(ℂ̂) − Σ(eₚ − 1) with eₚ the local degree at each ramification point","Σ(eₚ − 1) = 2(d−1)","The number of critical points equals d","deg(f) = Σ eₚ"],
   ans:1,
   exp:"Riemann-Hurwitz: 2−2g' = d(2−2g) − Σ(eₚ−1). For f: ℂ̂ → ℂ̂ (g = g' = 0): 0 = d·0 − Σ(eₚ−1), so Σ(eₚ−1) = 2(d−1). A degree-d rational map has exactly 2d−2 critical points counted with multiplicity."},
  {q:"Carathéodory's theorem extends the Riemann mapping φ: 𝔻 → U to the boundary when:",
   opts:["U is convex","U is a Jordan domain (bounded by a Jordan curve), in which case φ extends to a homeomorphism 𝔻̄ → Ū","U is a half-plane","U has finitely many boundary components"],
   ans:1,
   exp:"Carathéodory extension theorem: if U is a Jordan domain, the Riemann map φ: 𝔻 → U extends continuously to a homeomorphism of the closed disk 𝔻̄ → Ū. This fails for domains with fractal boundaries (e.g., the complement of a Julia set may not be a Jordan domain)."},
  {q:"The measurable dynamics of a rational map f is governed by the conformal measure μ supported on the Julia set J(f). For a polynomial of degree d, the natural conformal measure has exponent:",
   opts:["1","d","log d","dim_H(J(f))"],
   ans:3,
   exp:"The natural conformal measure (Patterson-Sullivan measure) has exponent δ = dim_H(J(f)): μ(f(A)) = ∫_A |f'|^δ dμ. For hyperbolic polynomials, δ = dim_H(J) and μ is ergodic, giving the 'canonical' measure on the Julia set."},
  {q:"The Douady-Hubbard theorem on the connectedness of the Julia set for a polynomial states that J(f) is connected iff:",
   opts:["The critical points have bounded orbits","The leading coefficient is positive","The polynomial is monic","deg(f) is even"],
   ans:0,
   exp:"For a polynomial, J(f) is connected iff all critical points have bounded orbits (equivalently, all critical points are in the filled Julia set K(f)). If any critical point escapes to ∞, J(f) is a Cantor set (totally disconnected). For z²+c this gives c ∈ Mandelbrot set ↔ J(f) connected."},
],

14:[
  {q:"The Liouville-Arnold theorem on integrability requires the first integrals F₁,…,Fₙ to be in involution. This means:",
   opts:["{Fᵢ, Fⱼ} = δᵢⱼ (Kronecker delta) for the Poisson bracket","{Fᵢ, Fⱼ} = 0 for all i,j (pairwise vanishing Poisson brackets)","∇Fᵢ · ∇Fⱼ = 0","The Hamiltonian flows of Fᵢ and Fⱼ commute only at t=0"],
   ans:1,
   exp:"In involution means {Fᵢ,Fⱼ} = 0 for all i,j. This ensures the Hamiltonian flows of each Fᵢ commute, allowing simultaneous canonical coordinates (action-angle). It is the condition for Liouville integrability."},
  {q:"Action-angle variables (I,θ) for an integrable system reduce the Hamiltonian to H = H(I) (function of actions only). The dynamics in these coordinates is:",
   opts:["İ = ω(I), θ̇ = 0","Ι̇ = 0, θ̇ = ω(I) where ωᵢ = ∂H/∂Iᵢ","İ = θ, θ̇ = −I","θ̇ = I·ω(I)"],
   ans:1,
   exp:"In action-angle coordinates: İ = −∂H/∂θ = 0 (H is θ-independent), θ̇ = ∂H/∂I = ω(I). Actions are constants of motion; angles increase linearly in time. Motion is quasi-periodic on invariant tori with frequencies ω(I)."},
  {q:"The generating function approach to canonical transformations uses a function S(q,P) such that the old and new canonical coordinates are related by:",
   opts:["p = ∂S/∂q, Q = ∂S/∂P","Q = ∂S/∂q, P = ∂S/∂p","p = S·Q, P = S·q","q = ∂S/∂p, P = ∂S/∂Q"],
   ans:0,
   exp:"For a generating function of type-2, S(q,P): old momenta p = ∂S/∂q and new coordinates Q = ∂S/∂P. The transformation is canonical (symplectic) iff these relations hold, and the new Hamiltonian is K(Q,P) = H(q(Q,P),p(Q,P)) + ∂S/∂t."},
  {q:"The Nekhoroshev theorem (1977) on near-integrable Hamiltonian systems provides stability over exponentially long time scales. For perturbation size ε, actions I(t) stay within O(ε^b) of I(0) for time:",
   opts:["O(1/ε)","O(exp(1/ε^a)) for some exponents a,b > 0 depending on the number of degrees of freedom","O(1/ε²)","All time (KAM stability)"],
   ans:1,
   exp:"Nekhoroshev stability: under convexity conditions on H₀(I), the actions satisfy |I(t)−I(0)| ≤ Cε^b for |t| ≤ T₀ exp((ε₀/ε)^a). This super-exponential time scale bridges KAM (infinite time for Diophantine tori) and Chirikov diffusion (polynomial time for resonant zones)."},
  {q:"The Birkhoff normal form near an elliptic fixed point of a symplectic map T reduces T (to any order) to a map of the form (Iₖ = |zₖ|²):",
   opts:["zₖ ↦ e^{iωₖ}zₖ (pure rotation)","zₖ ↦ e^{i(ωₖ + Σⱼ aₖⱼIⱼ)}zₖ (twist map in each action)","zₖ ↦ zₖ + ωₖ (translation)","zₖ ↦ λₖzₖ with |λₖ| < 1"],
   ans:1,
   exp:"Birkhoff normal form: the symplectic map near a non-resonant elliptic fixed point is formally conjugate to zₖ ↦ exp(i(ωₖ + Σⱼ aₖⱼ|zⱼ|²))zₖ — a nonlinear twist. The coefficients aₖⱼ are the Birkhoff constants, which determine the KAM condition and Arnold diffusion."},
  {q:"Gromov's non-squeezing theorem (1985) states that a symplectic map cannot embed a ball B(r) into a cylinder Z(R) = {z : |z₁|² + |z₂|² < R²} × ℝ^{2n-2} if:",
   opts:["r > R","r < R","r = R","n > 2"],
   ans:0,
   exp:"Non-squeezing: a symplectic embedding of B(r) into Z(R) requires r ≤ R. Despite the cylinder having infinite volume, symplectic rigidity prevents compressing in the symplectic directions. This shows symplectic maps are far more rigid than volume-preserving maps."},
  {q:"The Maslov index of a Lagrangian path (path in the Lagrangian Grassmannian Λ(n)) is an integer that counts signed intersections with the Maslov cycle. In physics and semiclassical analysis, it appears in the:",
   opts:["Hamiltonian equations of motion","WKB quantisation condition: ∮ p dq = (n + μ/4)h where μ is the Maslov index","Poisson bracket formula","Definition of canonical transformations"],
   ans:1,
   exp:"The Maslov index μ appears in the semiclassical (WKB/Bohr-Sommerfeld) quantisation condition ∮ p dq = (n + μ/4)h, correcting the naive quantisation by counting caustic crossings. It is a topological invariant of Lagrangian submanifolds."},
  {q:"The Toda lattice is a completely integrable Hamiltonian system of n particles with exponential nearest-neighbor interactions. Its integrability is established via a Lax pair (L, B) satisfying:",
   opts:["L̇ = LB","L̇ = LB − BL = [L,B]","L̇ = 0","L̇ = B²"],
   ans:1,
   exp:"Lax pair: L̇ = [L,B] implies that eigenvalues of L are conserved quantities (since d/dt eig(L) = 0 follows from L̇ = [L,B]). This generates enough integrals of motion for complete integrability. The Toda lattice was the first non-trivial system shown completely integrable via the Lax method."},
],

15:[
  {q:"The Navier-Stokes equations on a 2D torus have a global attractor 𝒜 of finite Hausdorff dimension. The dimension estimate (Lieb-Thirring inequality approach) gives dim_H(𝒜) ≤ C·G^{2/3} where G is:",
   opts:["The Reynolds number","The Grashof number (ratio of forcing to viscosity: G = ||f||/ν²)","The Lyapunov exponent","The topological entropy"],
   ans:1,
   exp:"The Grashof number G = ||f||/(ν²) controls the attractor dimension. The estimate dim_H(𝒜) ≤ C·G^{2/3} (or similar bounds via trace formula) uses the Lieb-Thirring inequality to bound the sum of Lyapunov exponents. This is the best known bound for 2D Navier-Stokes."},
  {q:"A dissipative evolution equation generates a semigroup {S(t)}_{t≥0} on a Banach space X. The global attractor 𝒜 is the omega-limit set of any bounded absorbing set B:",
   opts:["𝒜 = {x : S(t)x ∈ B for all t}","𝒜 = ω(B) = ∩_{s≥0} cl(∪_{t≥s} S(t)B)","𝒜 = ∪_{t≥0} S(t)B","𝒜 = S(1)B"],
   ans:1,
   exp:"The global attractor is the omega-limit set of any absorbing set B: 𝒜 = ∩_{s≥0} cl(∪_{t≥s} S(t)B). This is compact, invariant (S(t)𝒜 = 𝒜), and attracts all bounded sets. Existence requires a compact absorbing set (obtained from energy estimates for dissipative PDEs)."},
  {q:"The reaction-diffusion equation uₜ = DΔu + f(u) (D > 0, f satisfies a dissipativity condition) on a bounded domain has a global attractor 𝒜 in H¹₀(Ω). The key step in proving compactness of 𝒜 uses:",
   opts:["The maximum principle only","Compact Sobolev embeddings: H¹ ↪ L² is compact (Rellich-Kondrachov), which converts H¹-boundedness to L²-precompactness","Fourier analysis","The Poincaré inequality alone"],
   ans:1,
   exp:"The compact embedding H¹(Ω) ↪ L²(Ω) (Rellich-Kondrachov) is the key: solutions bounded in H¹ (from energy estimates) form a precompact set in L². This gives the compact absorbing set needed for the global attractor theorem."},
  {q:"The Squire transformation for linearised Navier-Stokes shows that 3D instabilities can be reduced to 2D instabilities. More precisely:",
   opts:["All 3D instabilities are equivalent to 2D instabilities","Any 3D normal mode (k_x, k_y, k_z) instability corresponds to a 2D instability at the same Reynolds number (Squire's theorem)","3D flows are more stable than 2D","The Orr-Sommerfeld equation is 3D"],
   ans:1,
   exp:"Squire's theorem: for any unstable 3D oblique mode at Reynolds number Re, there is a more unstable 2D mode at a lower Re'. Therefore the critical Reynolds number for instability is determined by 2D disturbances (the Orr-Sommerfeld equation)."},
  {q:"Temam's notion of the universal attractor for the Navier-Stokes equations has finite fractal dimension d_f (Mandelbrot). The physical interpretation is that:",
   opts:["The flow has only d_f degrees of freedom for all time","Asymptotically, the flow is effectively finite-dimensional: only d_f modes are active on the attractor","d_f equals the spatial dimension","The flow is always laminar for d_f < 3"],
   ans:1,
   exp:"Finite fractal dimension of the attractor means turbulent flow has finite effective degrees of freedom (the number of active modes on the attractor). This justifies dimensional reduction and the use of finite-dimensional models (like reduced-order models) for turbulence."},
  {q:"The Cahn-Hilliard equation uₜ = −Δ(Δu − f(u)) models phase separation. It differs from the Allen-Cahn equation (uₜ = Δu − f(u)) in that the Cahn-Hilliard is:",
   opts:["Parabolic and dissipates energy","A conservation law (∫u dx is preserved) while Allen-Cahn is not mass-conserving","Second order in space","Always globally well-posed in L²"],
   ans:1,
   exp:"Cahn-Hilliard conserves mass: ∫_Ω u dx = const (it's in conservation form uₜ = −∇·J). Allen-Cahn does not conserve mass (∫u changes in time). Both decrease the free energy ∫(½|∇u|² + F(u))dx, but via different mechanisms (H^{-1} vs L² gradient flow)."},
  {q:"The concept of determining modes for the Navier-Stokes equations says that the long-time behavior is determined by a finite number of Fourier modes N_d. The estimate for N_d is:",
   opts:["N_d ∼ Re","N_d ∼ Re³/² or G^{2/3} (depending on dimension and norm)","N_d ∼ Re²","N_d = dim(𝒜)"],
   ans:1,
   exp:"Foias-Prodi-Ladyzhenskaya theorem: if two solutions agree on the first N Fourier modes for all t, they are asymptotically identical, for N above a threshold N_d ∼ G^{2/3}. This is the number of 'determining modes' and relates to the attractor dimension."},
  {q:"The Lapidus-Pang-Man result on wave maps and the Klainerman null condition: nonlinear wave equations □u = N(u,∂u) have global small-data solutions when N satisfies the null condition. The null condition means:",
   opts:["N vanishes at u = 0","N(u,∂u) contains only products of derivatives with a factor that vanishes on the light cone (null cone)","N is linear in ∂u","N has no quadratic terms"],
   ans:1,
   exp:"Klainerman's null condition: the nonlinearity N involves contractions of derivatives with respect to the Minkowski metric that vanish on the null cone |ξ| = |τ| in Fourier space. This prevents resonant interactions on the light cone and allows global existence for small data, crucial for the stability of Minkowski space."},
],

16:[
  {q:"The prefix-free (Shannon) code length for a symbol x with probability p(x) is optimally −log₂ p(x) bits. The Kraft inequality states that a prefix-free code with lengths {lᵢ} exists if and only if:",
   opts:["Σ lᵢ ≤ n","Σ 2^{−lᵢ} ≤ 1","Σ lᵢ·pᵢ = H(X)","All lᵢ are positive integers"],
   ans:1,
   exp:"Kraft inequality: Σ 2^{-lᵢ} ≤ 1 is necessary and sufficient for prefix-free codes. Conversely, for any lengths satisfying Kraft's inequality, a prefix-free code exists. Combined with H(X) ≤ ∑ pᵢlᵢ < H(X)+1, this bounds the overhead of Huffman coding."},
  {q:"The data processing inequality states that for a Markov chain X → Y → Z:",
   opts:["I(X;Z) ≥ I(X;Y)","I(X;Z) ≤ I(X;Y) (processing data cannot increase mutual information)","H(Z|Y) ≥ H(Z|X)","I(Y;Z) = I(X;Z)"],
   ans:1,
   exp:"Data processing inequality: if X → Y → Z is Markov, then I(X;Z) ≤ I(X;Y). Processing (applying a channel to Y) cannot increase the information about X. This fundamental inequality underpins the channel coding theorem and source-channel separation."},
  {q:"The mutual information I(X;Y) can be written as a KL divergence:",
   opts:["I(X;Y) = D(P_{XY} || P_X ⊗ P_Y)","I(X;Y) = D(P_X || P_Y)","I(X;Y) = H(X) + H(Y)","I(X;Y) = D(P_Y || P_{Y|X})"],
   ans:0,
   exp:"I(X;Y) = D(P_{XY} || P_X ⊗ P_Y) = Σ p(x,y) log[p(x,y)/(p(x)p(y))]. This expresses mutual information as the KL divergence between the joint distribution and the product of marginals, measuring the deviation from independence."},
  {q:"Slepian-Wolf theorem for distributed source coding allows two correlated sources X,Y to be compressed separately (without seeing each other) and decoded jointly at rates:",
   opts:["R_X ≥ H(X), R_Y ≥ H(Y) always","R_X ≥ H(X|Y), R_Y ≥ H(Y|X), and R_X+R_Y ≥ H(X,Y)","R_X + R_Y ≥ H(X) + H(Y)","R_X = R_Y = H(X,Y)/2"],
   ans:1,
   exp:"Slepian-Wolf: the achievable rate region for separate encoding, joint decoding of (X,Y) is R_X ≥ H(X|Y), R_Y ≥ H(Y|X), R_X+R_Y ≥ H(X,Y). Remarkably, this matches the rate for joint encoding—correlation can be exploited even without communication between encoders."},
  {q:"The error exponent for binary hypothesis testing (Stein's lemma): for H₀: P vs H₁: Q with type-I error α ≤ ε < 1, the optimal type-II error satisfies:",
   opts:["β → 0 at rate 2^{-nH(P)}","log β / n → −D(P||Q) (the error exponent is the KL divergence)","β = ε always","log β / n → −H(P,Q)"],
   ans:1,
   exp:"Stein's lemma: for fixed type-I error α < 1, the optimal type-II error satisfies lim (1/n) log β_n = −D(P||Q). The KL divergence is the optimal error exponent for hypothesis testing—a fundamental result connecting information theory and statistics."},
  {q:"The Blahut-Arimoto algorithm computes channel capacity by alternately optimising the input distribution and the channel's backward probabilities. Its convergence is guaranteed because it:",
   opts:["Is a gradient descent","Is an EM algorithm (expectation-maximization), converging to the capacity achieving distribution","Solves a linear program","Uses Newton's method"],
   ans:1,
   exp:"Blahut-Arimoto is an instance of the EM algorithm: it alternates between computing the backward channel (E-step) and optimising the input distribution (M-step). Each iteration increases the mutual information, and convergence to capacity is guaranteed (though rate may be slow near capacity)."},
  {q:"Turbo codes and LDPC codes are practical capacity-approaching codes. LDPC codes (Gallager, 1962) are characterised by:",
   opts:["A dense parity-check matrix","A sparse parity-check matrix H with density O(1/n) — most entries are 0","A circulant parity-check matrix","A parity-check matrix with all entries 1"],
   ans:1,
   exp:"LDPC (Low-Density Parity-Check) codes have sparse H: each row and column has O(1) ones. This allows efficient belief-propagation (sum-product) decoding on the Tanner graph. LDPC codes asymptotically achieve Shannon capacity on the BEC and approach it on other channels."},
  {q:"The capacity of the binary symmetric channel (BSC) with crossover probability p is:",
   opts:["1−p","p·log(1/p)","1 − H_b(p) where H_b(p) = −p log p − (1-p)log(1-p)","log(1/(2p))"],
   ans:2,
   exp:"BSC capacity: C = 1 − H_b(p) bits. At p = 0 or p = 1, C = 1 bit (perfect channel); at p = 1/2, C = 0 (pure noise). The capacity-achieving input is uniform Bernoulli, and H_b(p) is the binary entropy of the noise."},
],

17:[
  {q:"Rényi's entropy H_α(X) → H_∞(X) = −log max_x p(x) as α → ∞. This min-entropy equals:",
   opts:["−log E[p(X)]","The negative log of the largest probability (the most likely outcome's surprisal)","H(X)/α","0"],
   ans:1,
   exp:"Min-entropy H_∞(X) = −log max_x p(x) is the entropy of the best single-guess predictor. It is the most conservative (smallest) Rényi entropy and equals 0 for a deterministic X. In cryptography it measures the one-query distinguishing advantage."},
  {q:"The quantum Rényi entropy of order α for a density matrix ρ is defined as S_α(ρ) = (1/(1−α)) log tr(ρ^α). As α → 1, this converges to:",
   opts:["0","The von Neumann entropy S(ρ) = −tr(ρ log ρ)","log(rank ρ)","tr(ρ²)"],
   ans:1,
   exp:"By L'Hôpital applied to tr(ρ^α)/(1−α): lim_{α→1} S_α(ρ) = −tr(ρ log ρ) = S(ρ). The quantum Rényi entropies form a family parameterised by α, with S₁ = von Neumann entropy as the special case."},
  {q:"The f-divergence D_f(P||Q) = Σ q(x) f(p(x)/q(x)) (for a convex f with f(1)=0) unifies many divergences. The total variation distance TV(P,Q) = (1/2)Σ|p(x)−q(x)| corresponds to f(t) =",
   opts:["(t−1)²","t log t","½|t−1|","(√t − 1)²"],
   ans:2,
   exp:"TV distance: f(t) = ½|t−1|. For KL divergence: f(t) = t log t. For Hellinger distance: f(t) = (√t−1)². For χ²-divergence: f(t) = (t−1)². The common f-divergence framework allows unified proofs of data-processing inequalities."},
  {q:"Pinsker's inequality relates total variation to KL divergence by:",
   opts:["TV(P,Q) ≤ D(P||Q)","TV(P,Q)² ≤ ½ D(P||Q)","TV(P,Q) = D(P||Q)^{1/2}","D(P||Q) ≤ TV(P,Q)"],
   ans:1,
   exp:"Pinsker's inequality: TV(P,Q) ≤ √(D(P||Q)/2), or equivalently TV(P,Q)² ≤ D(P||Q)/2. This gives a quantitative relationship between KL divergence and total variation, used in hypothesis testing and statistics to bound the probability of error."},
  {q:"The Gibbs variational principle states that the Boltzmann-Gibbs distribution P_β(x) ∝ e^{−βH(x)} minimises the free energy F(P) = E_P[H] − (1/β)H(P). Equivalently, P_β is the unique distribution satisfying:",
   opts:["H(P_β) = 0","D(P || P_β) ≥ 0 for all P (P_β minimises free energy by non-negativity of KL)","E_{P_β}[H] = 0","F(P_β) = H(P_β)"],
   ans:1,
   exp:"The Gibbs distribution is the unique minimiser of the free energy E_P[H] − H(P)/β. This follows from F(P) − F(P_β) = D(P||P_β)/β ≥ 0. Equivalently, P_β is the maximum entropy distribution subject to the constraint E_P[H] = E_{P_β}[H]."},
  {q:"Conditional entropy H(X|Y) satisfies the chain rule H(X,Y) = H(X) + H(Y|X). The non-negativity of mutual information I(X;Y) = H(X) − H(X|Y) ≥ 0 means:",
   opts:["Conditioning always increases entropy","Conditioning never increases entropy: H(X|Y) ≤ H(X)","Conditioning on Y makes X deterministic","H(X|Y) = H(Y|X)"],
   ans:1,
   exp:"H(X|Y) ≤ H(X): knowledge of Y can only decrease (or maintain) uncertainty about X. Equality holds iff X ⊥ Y (independent). This is equivalent to I(X;Y) ≥ 0 (non-negativity of mutual information, which follows from non-negativity of KL divergence)."},
  {q:"The log-sum inequality states that for non-negative aᵢ, bᵢ:",
   opts:["Σaᵢ log(aᵢ/bᵢ) ≤ (Σaᵢ) log(Σaᵢ/Σbᵢ)","Σaᵢ log(aᵢ/bᵢ) ≥ (Σaᵢ) log(Σaᵢ/Σbᵢ)","Σaᵢ log(aᵢ/bᵢ) = Σaᵢ·Σlog(aᵢ/bᵢ)","Σaᵢ log(aᵢ/bᵢ) = 0"],
   ans:1,
   exp:"Log-sum inequality: Σᵢ aᵢ log(aᵢ/bᵢ) ≥ (Σaᵢ) log(Σaᵢ/Σbᵢ). This follows from Jensen's inequality applied to the convex function t log t. It is used to prove non-negativity of KL divergence, convexity of mutual information, and many other information inequalities."},
  {q:"Rényi's characterisation theorem shows that Shannon entropy is the unique measure satisfying certain axioms. The key distinguishing axiom is:",
   opts:["Continuity in probabilities","The chain rule (decomposability): H(p₁,…,pₙ) = H(p₁+p₂, p₃,…,pₙ) + (p₁+p₂)H(p₁/(p₁+p₂), p₂/(p₁+p₂))","Symmetry","Maximum at uniform distribution"],
   ans:1,
   exp:"The chain rule (decomposability) axiom is the key distinguishing property. Shannon (1948) and Khinchin characterised entropy as the unique function satisfying continuity, symmetry, normalization, and this chain rule. Rényi entropies satisfy the others but not this chain rule (which is specific to α = 1)."},
],

18:[
  {q:"Chaitin's Ω = Σ_{p: U(p) halts} 2^{-|p|} is a specific example of an algorithmic-random real. It is notable because:",
   opts:["It is computable to arbitrary precision","It is left-computable (its binary expansion can be approximated from below) but not computable, and every bit encodes a halting problem","It equals 1/2 exactly","Its digits are eventually periodic"],
   ans:1,
   exp:"Ω (halting probability) is Martin-Löf random, left-computable (Σ over terminating programs ≤ 1 by Kraft), but not computable. Knowing finitely many bits of Ω answers finitely many halting problems. It is the canonical example of an 'unknowable' real number."},
  {q:"The incompressibility method in combinatorics uses the fact that K(x) ≥ |x| − c for 'most' strings x (incompressible strings). To prove a combinatorial statement about strings of length n, one:",
   opts:["Assumes K(x) = 0 and derives a contradiction","Assumes x is incompressible (K(x) ≥ n − c) and shows that any algorithm compressing x would require K(x) < n − c, reaching a contradiction","Uses the existence of one compressible string","Applies K(x) to the empty string"],
   ans:1,
   exp:"The incompressibility method: fix a shortest program for x. Since x is incompressible, any description of x (using any structure x might have) has length ≥ n − O(1). This forces the structure to be absent. Used to prove lower bounds in combinatorics and sorting."},
  {q:"The Algorithmic Sufficient Statistic of a string x is a set S ∋ x (a hypothesis) such that:",
   opts:["S has minimum description length K(S)","K(x) = K(S) + log|S| + O(log n) — the two-part description S (model) then x's rank in S is as short as any description","S = {x}","S has maximum cardinality"],
   ans:1,
   exp:"Algorithmic sufficient statistic: S is sufficient for x if K(x|S) ≈ log|S| (random within S) and K(S) + log|S| ≈ K(x) (S captures all meaningful structure). This formalises the distinction between random and structural components of x."},
  {q:"Levin's notion of 'universal distribution' assigns to each finite string x the probability m(x) = Σ_{p: U(p)=x} 2^{-|p|}. This is a semi-measure (Σ m(x) ≤ 1) because:",
   opts:["Some programs output infinitely many x","Programs can loop indefinitely (not outputting anything), contributing probability mass that doesn't correspond to any output","The universal TM is non-deterministic","The alphabet is infinite"],
   ans:1,
   exp:"Σ_x m(x) = P(U halts and outputs x for some x) = P(U halts) ≤ 1 (not necessarily =1 since U may not halt). This is the 'halting probability' Ω. The universal semi-measure m dominates all computable semi-measures, making it the prior of choice for induction."},
  {q:"The Kolmogorov structure function h_x(α) measures, for a string x of length n, the minimum description length K(S) of a model S ∋ x such that K(x|S) ≤ α (x appears random in S). The graph of h_x is:",
   opts:["Constant","A non-increasing staircase from K(x) (at α=0) to K({x}) ≈ n (at α=K(x))","An increasing function","Linear in α"],
   ans:1,
   exp:"The structure function h_x(α) = min{K(S) : x∈S, log|S| ≤ α} is non-increasing in α: more allowance for randomness within S allows more structured (shorter description) models. The 'meaningful information' of x is the initial steep decrease of h_x before it flattens."},
  {q:"Time-bounded Kolmogorov complexity K^t(x) (Ct-complexity) restricts to programs running in ≤ t(|x|) steps. Its relationship to circuit complexity is:",
   opts:["K^t(x) = circuit complexity of x always","K^t(x) ≈ the size of the smallest circuit computing x in the given time bound (up to logarithmic factors)","K^t(x) is always greater than K(x)","K^t(x) is computable for any t"],
   ans:1,
   exp:"Time-bounded Kolmogorov complexity is closely related to circuit complexity: K^{poly}(x) ≈ the minimum circuit size computing x (Sipser, Schnorr). This connection links descriptional complexity to computational complexity, and is related to the P vs NP question."},
  {q:"The Coding Theorem (Levin's theorem) for the universal semi-measure m states that for any computable semi-measure P:",
   opts:["P(x) = m(x) for all x","m(x) ≥ c_P · P(x) for some constant c_P > 0 independent of x (m dominates all computable semi-measures)","m(x) ≤ P(x)","m = P for the natural measure"],
   ans:1,
   exp:"Levin's coding theorem: m(x) = 2^{-K(x)} up to constants, and m dominates every computable (semi-)measure: m(x) ≥ c_P · P(x). This makes m the 'universal a priori probability': it assigns at least as much probability as any computable model, up to a constant factor."},
  {q:"Fortnow-Kummer (and others) proved results on the random-regular sequence in terms of Kolmogorov complexity. An infinite sequence X = x₁x₂… is computably random (Schnorr random) if:",
   opts:["K(xₙ) ≥ n − O(1)","Every computable martingale fails to succeed on X (makes no unbounded profit betting on X)","X is Martin-Löf random","X passes all computable statistical tests"],
   ans:1,
   exp:"Schnorr randomness: X is Schnorr random iff no computable martingale succeeds (wins unboundedly) on X. This is strictly weaker than Martin-Löf randomness (which uses effective null sets / prefix complexity). The three main notions form a strict hierarchy: Schnorr ⊂ computable ⊂ Martin-Löf."},
],

19:[
  {q:"The Wyner-Ziv theorem addresses lossy source coding with decoder side information Y. The rate-distortion function with side information is:",
   opts:["R(D) = I(X;X̂) as in the standard case","R(D) = min_{p(x̂|x,y): E[d(X,X̂)]≤D} I(X;X̂|Y), achievable without encoding Y","R(D) = H(X|Y) for any D","R(D) = I(X;Y) − D"],
   ans:1,
   exp:"Wyner-Ziv: R_{X|Y}(D) = min_{p(x̂|x,y): E[d]≤D} I(X;X̂|Y). Remarkably, despite the encoder not having Y, the rate-distortion function equals the case where the encoder has Y (side-information at encoder gives no benefit for Gaussian sources)—the 'Wyner-Ziv theorem'."},
  {q:"The Costa dirty-paper coding (DPC) result states that for the channel Y = X + S + Z (S is interference known to encoder, Z ~ N(0,N), power constraint P on X):",
   opts:["The capacity is log(1 + P/(N + σ²_S))","The capacity is the same as if S were absent: C = ½ log(1 + P/N)","DPC achieves zero rate","The capacity is reduced by the interference"],
   ans:1,
   exp:"Costa (1983): if the encoder knows S non-causally, the channel capacity is ½ log(1+P/N)—as if S were absent! The encoder pre-cancels the known interference using a version of Gel'fand-Pinsker coding (auxiliary variable U = X + αS). This underlies precoding in MIMO communications."},
  {q:"The capacity region of the interference channel (two sender-receiver pairs sharing a channel) is known completely only for:",
   opts:["All interference levels","The strong interference regime (|a₁₂|² ≥ 1 and |a₂₁|² ≥ 1 in the Gaussian case) where treating interference as noise is optimal","The weak interference regime","The Gaussian case generally"],
   ans:1,
   exp:"The interference channel capacity is open in general. For strong interference (each receiver's interference is stronger than its desired signal), the capacity region is known and equals that of a compound multiple access channel. For Gaussian weak interference, the Han-Kobayashi inner bound is not tight in general."},
  {q:"The network coding theorem (Ahlswede-Cai-Li-Yeung, 2000) for multicast networks states that the max-flow min-cut bound is:",
   opts:["Only achievable with uncoded routing","Achievable using linear network coding over a sufficiently large finite field","Never achievable in practice","Only an upper bound, not achievable"],
   ans:1,
   exp:"Ahlswede et al. proved the revolutionary result that for multicast (single source, multiple sinks), the max-flow min-cut capacity is achievable by allowing intermediate nodes to encode (mix) their received packets—linear network coding over GF(q) suffices for large enough q."},
  {q:"The Gaussian multiple access channel with K users, each with power P, has a sum-rate capacity of:",
   opts:["K · ½ log(1 + P/N)","½ log(1 + KP/N)","½ log(1 + P/N)","K · C₁ where C₁ is the single-user capacity"],
   ans:1,
   exp:"MAC sum-rate capacity: C_sum = ½ log(1 + KP/N). All K users share the channel coherently (superimposed signals), so the total power is KP relative to noise N. This can exceed K times the single-user capacity ½ log(1+P/N) achieved by TDMA."},
  {q:"The decode-forward (DF) strategy for the relay channel achieves rates up to min(I(X;Y_R|X_R), I(X,X_R;Y)). A key limitation is:",
   opts:["The relay must know the channel","The relay must fully decode the source message, which requires I(X;Y_R) ≥ R (bottleneck at weak relay-destination link)","DF requires full-duplex relay","DF never outperforms direct transmission"],
   ans:1,
   exp:"DF's bottleneck: the relay must reliably decode the source message, requiring R ≤ I(X;Y_R). If the source-relay link is weak, DF may not be better than direct transmission. Compress-forward (CF) does not require decoding and can outperform DF when the relay-destination link is strong."},
  {q:"The degrees of freedom (DoF) of the K-user interference channel gives the pre-log factor of capacity at high SNR. The surprising result by Cadambe-Jafar (2008) showed that the total DoF is:",
   opts:["1 (as if there were only one user)","K/2 — each user gets half a degree of freedom on average via interference alignment","K — each user gets full DoF","log K"],
   ans:1,
   exp:"Cadambe-Jafar (2008): the K-user Gaussian interference channel has K/2 total degrees of freedom via interference alignment—each user achieves ½ DoF. This result showed that interference is not the fundamental bottleneck it was believed to be, revolutionising the understanding of interference."},
  {q:"The Gelfand-Pinsker theorem addresses channel coding with non-causal side information S at the encoder. The capacity is:",
   opts:["max_{p(x|s)} I(X;Y|S)","max_{p(u|s),x(u,s)} I(U;Y) − I(U;S) where U is an auxiliary RV","max_{p(x)} I(X;Y)","I(X;Y) − I(X;S)"],
   ans:1,
   exp:"Gelfand-Pinsker capacity: C = max_{p(u,x|s)} [I(U;Y) − I(U;S)]. The auxiliary variable U encodes the message plus the known interference S. Costa's DPC is the Gaussian special case where the maximum equals ½ log(1+P/N), independent of the interference power."},
],

20:[
  {q:"The exponential family of distributions p(x;θ) = exp(θ·T(x) − A(θ) + B(x)) has the remarkable property that the Fisher information matrix equals:",
   opts:["The covariance matrix of T(x)","The Hessian of the log-partition function: G(θ) = ∇²A(θ)","The identity matrix","The inverse covariance of T(x)"],
   ans:1,
   exp:"For exponential families, the Fisher information G(θ) = ∇²A(θ) = Cov_θ(T(X)). The log-partition function A(θ) is strictly convex (positive definite Fisher metric), and its Legendre transform gives the dual (m-flat) coordinate system η = E_θ[T(X)]."},
  {q:"In information geometry, the e-flat submanifold (exponential submanifold) through p has the property that its tangent space at p is:",
   opts:["Orthogonal to the Fisher metric","The set of score functions ∂ log p/∂θ (tangent vectors in the θ-coordinate","A linear subspace of probability distributions","The m-flat submanifold through p"],
   ans:1,
   exp:"An e-flat (exponential) geodesic from P to Q has the form p_t ∝ p^{1-t} q^t (mixture in the log domain). The e-flat submanifold through P consists of all distributions in the exponential family generated by P. The m-flat submanifold is the mixture family through P."},
  {q:"Amari's α-connections ∇^{(α)} on a statistical manifold form a one-parameter family. The dually flat pair (e-flat, m-flat) corresponds to:",
   opts:["α = 0 and α = 1","α = 1 and α = −1","α = 0 and α = ∞","α = 2 and α = −2"],
   ans:1,
   exp:"The e-connection (α=+1) and m-connection (α=−1) are dual with respect to the Fisher metric: they are related by (∇^{(α)})^* = ∇^{(-α)} under metric duality. The Levi-Civita connection is α=0 (the Riemannian connection), which is its own dual."},
  {q:"The Pythagorean theorem in information geometry states that for three distributions P, Q, R where R is the e-geodesic projection of P onto an m-flat submanifold (or vice versa):",
   opts:["D(P||Q) = D(P||R) + D(R||Q)","D(P||Q) = D(P||R) · D(R||Q)","D(P||Q) ≥ D(P||R)","D(P||R) = D(Q||R)"],
   ans:0,
   exp:"Pythagorean theorem: if R is the e-projection of P onto an m-flat submanifold containing Q (or the m-projection onto an e-flat submanifold), then D(P||Q) = D(P||R) + D(R||Q). This is the information-geometric analogue of the Pythagorean theorem."},
  {q:"The saddlepoint approximation in statistics gives a highly accurate approximation to density functions via the cumulant generating function K(t) = log E[e^{tX}]. The saddlepoint density is:",
   opts:["p(x) ≈ e^{K(t̂) − t̂x} · (2πK''(t̂))^{-1/2} where t̂ solves K'(t̂) = x","p(x) ≈ e^{−x²/2}","p(x) ≈ K(x)^{-1}","p(x) ≈ e^{−K(x)}"],
   ans:0,
   exp:"Saddlepoint approximation: p̂(x) = (2πK''(t̂))^{-1/2} exp(K(t̂) − t̂x) where K'(t̂) = x. This is extremely accurate (relative error O(1/n) vs O(1/√n) for CLT) and is derived from the Legendre-Fenchel duality between the CGF K and the rate function I(x) = sup_t{tx − K(t)}."},
  {q:"The Amari-Nagaoka book (Methods of Information Geometry) shows that the maximum likelihood estimator θ̂_MLE is first-order efficient because it achieves:",
   opts:["Zero bias","The Cramér-Rao bound asymptotically: √n(θ̂ − θ) →_d N(0, G(θ)^{-1})","Exact Fisher efficiency for all sample sizes","The same variance for all estimators"],
   ans:1,
   exp:"MLE is first-order efficient: asymptotically it achieves the Cramér-Rao bound G(θ)^{-1}/n (where G(θ) is the Fisher information matrix). In information-geometric terms, MLE is the e-geodesic projection of the empirical distribution onto the model manifold."},
  {q:"The Bregman divergence D_F(P||Q) = F(P) − F(Q) − ⟨∇F(Q), P−Q⟩ for a strictly convex F generalises KL divergence. For F(P) = Σ p(x) log p(x) (negative entropy), D_F is:",
   opts:["Total variation","KL divergence D(P||Q)","Hellinger distance","χ²-divergence"],
   ans:1,
   exp:"F = Σ p log p (negative entropy): ∇F(Q) = (1 + log q(x)). Then D_F(P||Q) = Σ p(x)log p(x) − Σ q(x)log q(x) − Σ(1+log q(x))(p(x)−q(x)) = Σ p(x)log(p(x)/q(x)) = D(P||Q). So KL divergence is the Bregman divergence for negative entropy."},
  {q:"The geometric mean of two distributions P, Q in information geometry is the point M on the e-geodesic from P to Q at t=1/2, which equals:",
   opts:["(P+Q)/2 (arithmetic mean)","The normalized geometric mean M ∝ √(p(x)q(x))","The distribution minimising D(M||P) + D(M||Q)","The KL-centroid"],
   ans:1,
   exp:"The e-geodesic midpoint (exponential barycenter): p_t ∝ p(x)^{1-t} q(x)^t. At t=1/2: m(x) ∝ √(p(x)q(x)) (geometric mean, normalised). The m-geodesic midpoint is the arithmetic mean (p+q)/2. These differ—the two geodesics give different interpolations."},
],

};

const BASE = path.join(__dirname, 'questions');
let total = 0;
for (const [chStr, qs] of Object.entries(EXTRA)) {
  const ch = parseInt(chStr);
  const m = META[ch];
  const dir = path.join(BASE, m.dir, m.ch);
  const existing = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  const sample = JSON.parse(fs.readFileSync(path.join(dir, existing[0]),'utf8'));
  const {chTitle, part} = sample;
  qs.forEach((q,i) => {
    const n = existing.length + i + 1;
    const file = path.join(dir, `q${String(n).padStart(2,'0')}.json`);
    fs.writeFileSync(file, JSON.stringify({ch,part,chTitle,...q},null,2)+'\n');
    console.log('wrote', path.relative(__dirname,file));
    total++;
  });
}
console.log(`\nDone. ${total} questions written.`);
