use std::io::{self, BufRead, Write};

const BOLD: &str = "\x1b[1m";
const CYAN: &str = "\x1b[36m";
const GREEN: &str = "\x1b[32m";
const YELLOW: &str = "\x1b[33m";
const RED: &str = "\x1b[31m";
const DIM: &str = "\x1b[2m";
const RESET: &str = "\x1b[0m";

fn bold(s: &str) -> String { format!("{BOLD}{s}{RESET}") }
fn cyan(s: &str) -> String { format!("{CYAN}{s}{RESET}") }
fn green(s: &str) -> String { format!("{GREEN}{s}{RESET}") }
fn yellow(s: &str) -> String { format!("{YELLOW}{s}{RESET}") }
fn red(s: &str) -> String { format!("{RED}{s}{RESET}") }
fn dim(s: &str) -> String { format!("{DIM}{s}{RESET}") }

// ── Hopf Fibration ─────────────────────────────────────────────────────────────
//
//  η : S³ → S²   (the Hopf fibration)
//  Fiber over each point of S² is a circle S¹.
//
//  Long exact sequence of homotopy groups:
//    … → πₙ(S¹) → πₙ(S³) → πₙ(S²) → πₙ₋₁(S¹) → …
//
//  Key consequence: π₃(S²) = ℤ   (generated by η itself)
//
//  In HoTT: Hopf fibration is the join construction
//    Join(S¹, S¹) ≃ S³,  with projection to S²

fn les_map(n: usize, from: &str) -> String {
    match (n, from) {
        (1, "S1") => "ℤ".into(),
        (2, "S1") => "0".into(),
        (3, "S1") => "0".into(),
        (1, "S3") => "0".into(),
        (2, "S3") => "0".into(),
        (3, "S3") => "ℤ".into(),
        (4, "S3") => "ℤ/2ℤ".into(),
        (1, "S2") => "0".into(),
        (2, "S2") => "ℤ".into(),
        (3, "S2") => "ℤ  (generated by η)".into(),
        (4, "S2") => "ℤ/2ℤ".into(),
        (5, "S2") => "ℤ/2ℤ".into(),
        _ => format!("(see tables for π{n}({from}))"),
    }
}

// Complex number multiplication used in Hopf map definition
fn hopf_fiber_description(point: &str) -> String {
    match point {
        "N" | "north" => r"S¹  (fiber over north pole = S² \ {S})".into(),
        "S" | "south" => r"S¹  (fiber over south pole = S² \ {N})".into(),
        "equator" => "S¹  (all fibers over equator are the same circle S¹)".into(),
        _ => format!("S¹  (fiber over {point} in S²)"),
    }
}

struct Sandbox {
    computed: Vec<(String, String)>,
}

impl Sandbox {
    fn new() -> Self { Sandbox { computed: Vec::new() } }

    fn print_help() {
        println!("{}", bold("── Hopf Fibration ──────────────────────────────────────────────────"));
        println!("  {}         — define the Hopf map η: S³→S²", cyan("hopf"));
        println!("  {}  <point>   — fiber over a point (north/south/equator)", cyan("fiber"));
        println!("  {}         — long exact sequence of the fibration", cyan("les"));
        println!("  {}  n  <space> — πₙ of S1, S2, or S3", cyan("pi"));
        println!("{}", bold("── Structure ──────────────────────────────────────────────────────"));
        println!("  {}     — Hopf fibration as join construction", cyan("join"));
        println!("  {}     — all four Hopf fibrations (η, ν, σ, ?)", cyan("hopf-family"));
        println!("  {}  <n>     — linking number of two fibers", cyan("link"));
        println!("{}", bold("── HoTT Construction ─────────────────────────────────────────────"));
        println!("  {}    — Hopf construction in HoTT (join)", cyan("hott"));
        println!("  {}    — why π₃(S²)=ℤ follows from the LES", cyan("pi3"));
        println!("  {}    — the Hopf invariant and degree maps", cyan("invariant"));
        println!("  {}   — state of Hopf in HoTT proof assistants", cyan("formalized"));
    }

    fn handle(&mut self, line: &str) -> bool {
        let trimmed = line.trim();
        if trimmed.is_empty() { return true; }
        if trimmed == "quit" || trimmed == "exit" || trimmed == "q" { return false; }
        if trimmed == "help" || trimmed == "?" { Self::print_help(); return true; }

        let parts: Vec<&str> = trimmed.splitn(2, ' ').collect();
        let cmd = parts[0];
        let rest = if parts.len() > 1 { parts[1].trim() } else { "" };

        match cmd {
            "hopf" => {
                println!("{}", bold("── The Hopf Fibration η : S³ → S² ───────────────────────────────────"));
                println!("  S³ ⊂ ℂ² = {{(z,w) : |z|²+|w|² = 1}}");
                println!("  S² ≃ ℂP¹ = {{[z:w] : (z,w) ≠ (0,0)}} (complex projective line)");
                println!();
                println!("  η(z,w) = [z:w]  (map to complex projective line)");
                println!();
                println!("  Fiber:  η⁻¹([z:w]) = {{(λz, λw) : |λ|=1}} ≃ S¹");
                println!("  So S³ is an S¹-bundle over S².");
                println!();
                println!("  Key facts:");
                println!("    • η is not null-homotopic (generates π₃(S²) = ℤ)");
                println!("    • Any two distinct fibers are {} circles in S³", yellow("linked"));
                println!("    • Hopf invariant of η is 1");
                self.computed.push(("hopf".into(), "η: S³→S² defined".into()));
            }
            "fiber" => {
                let desc = hopf_fiber_description(if rest.is_empty() { "north" } else { rest });
                println!("  Fiber over {}: {}", cyan(rest.if_empty("north")), cyan(&desc));
                println!("  Each fiber S¹ is a great circle in S³.");
                println!("  Two distinct fibers (over distinct points of S²) are {} in S³.", yellow("linked once"));
                println!("  This linking number = Hopf invariant of η.");
                self.computed.push(("fiber".into(), format!("fiber over {rest}")));
            }
            "les" => {
                println!("{}", bold("── Long Exact Sequence of η: S³ → S² (fiber S¹) ────────────────────"));
                println!("  … → πₙ(S¹) → πₙ(S³) →^η* πₙ(S²) → πₙ₋₁(S¹) → …");
                println!();
                for n in (1..=5).rev() {
                    let s1 = les_map(n, "S1");
                    let s3 = les_map(n, "S3");
                    let s2 = les_map(n, "S2");
                    println!("  n={n}: π{n}(S¹)={} → π{n}(S³)={} →^η* π{n}(S²)={}",
                        cyan(&s1), cyan(&s3), cyan(&s2));
                }
                println!();
                println!("  At n=3: 0 → ℤ →^η* π₃(S²) → π₂(S¹)=0");
                println!("  So {}:  0 → ℤ → π₃(S²) → 0  ⟹  π₃(S²) = ℤ", green("exact"));
            }
            "pi" => {
                let args: Vec<&str> = rest.splitn(2, ' ').collect();
                let n: usize = args[0].parse().unwrap_or(3);
                let space = if args.len() > 1 { args[1].trim() } else { "S2" };
                let val = les_map(n, space);
                println!("  π{n}({space}) = {}", cyan(&val));
                if n == 3 && space == "S2" {
                    println!("  {} Generated by the Hopf map η: S³→S²", green("✓"));
                    println!("  η has Hopf invariant 1 — the unique (up to sign) element of Hopf invariant 1.");
                }
            }
            "join" => {
                println!("{}", bold("── Hopf Fibration as Join ─────────────────────────────────────────"));
                println!("  The join of two spaces: Join(A,B) = A * B");
                println!("  Points: [a, b, t] for a∈A, b∈B, t∈[0,1]");
                println!("  with [a,b,0]=[a,b',0] and [a,b,1]=[a',b,1]");
                println!();
                println!("  Key facts:");
                println!("    Join(S¹, S¹) ≃ S³    (two circles join to a 3-sphere)");
                println!("    Join(Sᵐ, Sⁿ) ≃ Sᵐ⁺ⁿ⁺¹");
                println!();
                println!("  Hopf fibration η: S³=Join(S¹,S¹) → S²=Susp(S¹)");
                println!("  is the canonical map from the join to the suspension.");
                println!();
                println!("  In HoTT (Brunerie 2016):");
                println!("  η : join(S¹,S¹) → Σ(S¹)  defined by:");
                println!("    inl(z) ↦ N");
                println!("    inr(w) ↦ S");
                println!("    push(z,w) ↦ merid(z·w)  (using S¹ group structure)");
            }
            "hopf-family" => {
                println!("{}", bold("── The Four Hopf Fibrations ────────────────────────────────────────"));
                println!("  All arise from normed division algebras:");
                println!();
                println!("  ℝ: η₁: S¹ → S¹   fiber S⁰={{±1}}  (over ℝP¹≃S¹)");
                println!("     π₁(S¹) = ℤ,  Hopf invariant = 1");
                println!();
                println!("  ℂ: η₂: S³ → S²   fiber S¹  (classic Hopf, over ℂP¹≃S²)");
                println!("     π₃(S²) = ℤ,  Hopf invariant = 1  [{}]", cyan("η"));
                println!();
                println!("  ℍ: ν: S⁷ → S⁴   fiber S³  (quaternionic, over ℍP¹≃S⁴)");
                println!("     π₇(S⁴) = ℤ⊕ℤ/12ℤ,  Hopf invariant = 1  [{}]", cyan("ν"));
                println!();
                println!("  𝕆: σ: S¹⁵ → S⁸  fiber S⁷  (octonionic, over 𝕆P¹≃S⁸)");
                println!("     π₁₅(S⁸) = ℤ⊕ℤ/120ℤ,  Hopf invariant = 1  [{}]", cyan("σ"));
                println!();
                println!("  Hopf invariant 1 theorem (Adams 1960):  only n=1,2,4,8 work.");
            }
            "link" => {
                let n: i64 = rest.parse().unwrap_or(1);
                println!("  Linking number of two Hopf fibers: {}", cyan(&n.to_string()));
                if n == 1 {
                    println!("  {} Any two distinct fibers of η are linked exactly once in S³.", green("✓"));
                    println!("  This is the Hopf invariant of η.");
                } else if n == 0 {
                    println!("  Linking number 0 means the curves don't link — not a Hopf fiber pair.");
                } else {
                    println!("  Linking number {n} — would correspond to a map of Hopf invariant {n}.");
                    println!("  {} Only Hopf invariant 1 is realizable by a map S³→S².", yellow("Note:"));
                }
            }
            "hott" => {
                println!("{}", bold("── Hopf Fibration in HoTT ──────────────────────────────────────────"));
                println!("  Constructed by Brunerie (2016) as part of his PhD thesis.");
                println!();
                println!("  Step 1: S¹ is a group (H-space) in HoTT.");
                println!("          S¹ acts on Join(S¹,S¹) by rotation.");
                println!();
                println!("  Step 2: The Hopf fibration is the type family:");
                println!("          hopf : S² → 𝒰");
                println!("          hopf(N) := S¹");
                println!("          hopf(S) := S¹");
                println!("          hopf(merid(x)) := ua(μₓ)  where μₓ: S¹≃S¹ is mult by x");
                println!();
                println!("  Step 3: Total space = Σ(s:S²). hopf(s)");
                println!("          This total space ≃ S³  (requires π₁(S¹)=ℤ, Freudenthal)");
                println!();
                println!("  Step 4: The projection Σ(s:S²). hopf(s) → S² is the Hopf map.");
                println!();
                println!("  Brunerie's number: π₄(S³) = ℤ/nℤ where n = Brunerie number");
                println!("  Computed to be {} (2022, using cubical Agda).", cyan("n=2"));
            }
            "pi3" => {
                println!("{}", bold("── Why π₃(S²) = ℤ ─────────────────────────────────────────────────"));
                println!("  From the long exact sequence:");
                println!("    π₃(S¹) → π₃(S³) →^η* π₃(S²) → π₂(S¹) → π₂(S³)");
                println!("      0    →   ℤ    →^η*  π₃(S²) →    0    →   0");
                println!();
                println!("  Exactness forces: η*: ℤ → π₃(S²) is an isomorphism.");
                println!("  So π₃(S²) = ℤ,  generated by η.");
                println!();
                println!("  The generator is the Hopf fibration η: S³→S² itself,");
                println!("  viewed as an element of π₃(S²) = [S³, S²].");
                println!();
                println!("  Every element n∈π₃(S²) = nη (the n-fold composite)");
                println!("  and has Hopf invariant n.");
            }
            "invariant" => {
                println!("{}", bold("── Hopf Invariant ──────────────────────────────────────────────────"));
                println!("  For a map f: S²ⁿ⁻¹ → Sⁿ, define the Hopf invariant H(f):");
                println!();
                println!("  Cone(f) = Sⁿ ∪_f D²ⁿ");
                println!("  H²ⁿ(Cone(f)) = ℤ·y,  Hⁿ(Cone(f)) = ℤ·x");
                println!("  y² = H(f)·x  in cohomology ring");
                println!("  H(f) is the Hopf invariant of f.");
                println!();
                println!("  Examples:");
                println!("    H(η) = 1   (Hopf fibration, n=2)");
                println!("    H(ν) = 1   (quaternionic Hopf, n=4)");
                println!("    H(σ) = 1   (octonionic Hopf, n=8)");
                println!("    H(2η) = 4  (since H is quadratic in π₃)");
                println!();
                println!("  Adams theorem: H(f)=1 only possible for n=1,2,4,8");
                println!("  (uses Adams spectral sequence / K-theory)");
            }
            "formalized" => {
                println!("{}", bold("── Hopf Fibration: Formalization Status ────────────────────────────"));
                println!("  Brunerie (2016): PhD thesis, constructed in Book HoTT");
                println!("    — Defines Hopf fibration via the join construction");
                println!("    — Proves π₃(S²) = ℤ");
                println!("    — Introduces Brunerie number β (π₄(S³) = ℤ/βℤ)");
                println!();
                println!("  Agda + HoTT library:");
                println!("    — Hopf.agda constructs the fibration and total space");
                println!("    — Proves π₃(S²) = ℤ");
                println!();
                println!("  Cubical Agda (Ljungström, Mörtberg 2022):");
                println!("    — Computes β = 2  (i.e., π₄(S³) = ℤ/2ℤ)");
                println!("    — First computational proof of Brunerie's number");
                println!();
                println!("  Lean 4 (in progress): partial formalizations exist");
            }
            _ => println!("  {} Unknown: {cmd}. Type {} for help.", red("✗"), cyan("help")),
        }
        true
    }
}

trait StrExt<'a> { fn if_empty(self, default: &'a str) -> &'a str; }
impl<'a> StrExt<'a> for &'a str {
    fn if_empty(self, default: &'a str) -> &'a str { if self.is_empty() { default } else { self } }
}

fn main() {
    println!("{}", bold("\n  ╔══════════════════════════════════════════════════════════╗"));
    println!("{}", bold("  ║    Hopf Fibration — Interactive Sandbox                  ║"));
    println!("{}", bold("  ╚══════════════════════════════════════════════════════════╝\n"));
    println!("  Explore the Hopf fibration η: S³ → S² and its consequences.");
    println!("  Why is π₃(S²) = ℤ? The Hopf map is the generator.");
    println!("  Type {} for the classic fibration, {} for the full story.\n",
        cyan("hopf"), cyan("hott"));

    let stdin = io::stdin();
    let mut sb = Sandbox::new();
    loop {
        print!("  {}hopf{} > ", CYAN, RESET);
        io::stdout().flush().unwrap();
        let mut line = String::new();
        match stdin.lock().read_line(&mut line) {
            Ok(0) | Err(_) => break,
            Ok(_) => { if !sb.handle(&line) { break; } }
        }
    }
    println!("  Goodbye.");
}
