use common::*;

fn show_help() -> String {
    help_string(&[
        ("weights <n>",         "Weight spaces of V(n) for sl(2): weights n,n-2,...,-n"),
        ("verma <lambda>",      "Verma module M(λ): infinite-dim, weights λ,λ-2,λ-4,..."),
        ("dim_formula <lambda>","Weyl dimension formula for sl(2): dim V(λ) = λ+1"),
        ("tensor_product <n> <m>", "Clebsch-Gordan: V(n)⊗V(m) = ⊕ V(k)"),
        ("character <n>",       "Character of V(n): ch = Σ e^μ over weights"),
        ("dominant <a> <b>",    "Check if (a,b) is a dominant integral weight for A2"),
        ("demo",                "Run a showcase of all commands"),
        ("help",                "Show this help"),
        ("quit",                "Exit"),
    ])
}

fn cmd_weights(n: i64) -> String {
    let mut out = String::new();
    if n < 0 { return "  n must be ≥ 0 (highest weight of irreducible sl(2)-module)\n".to_string(); }
    out.push_str(&format!("\n  ▸ Weight Spaces of V({}) for sl(2)\n", n));
    out.push_str(&format!("  V(n) = irreducible sl(2)-module with highest weight n.\n"));
    out.push_str(&format!("  Dimension: {}\n", n + 1));
    let mut weights = Vec::new();
    let mut w = n;
    while w >= -n { weights.push(w); w -= 2; }
    let wt_str: Vec<String> = weights.iter().map(|w| format!("{:+}", w)).collect();
    out.push_str(&format!("  Weights: {}\n\n", wt_str.join(", ")));
    out.push_str("  Basis vectors and sl(2) action:\n");
    out.push_str("  (basis: v_n = highest, v_{n-2}, ..., v_{-n})\n\n");
    for (k, &mu) in weights.iter().enumerate() {
        let bk = k as i64;
        let c_e = if k == 0 { 0 } else { bk * (n - bk + 1) };
        let c_f = if k as i64 == n { 0 } else { 1 };
        out.push_str(&format!("  v_{{{:+2}}}:  h·v = {:+2}·v", mu, mu));
        if k > 0 { out.push_str(&format!(",  e·v = {}·v_{{{:+2}}}", c_e, weights[k-1])); }
        else { out.push_str(",  e·v = 0          "); }
        if (k as i64) < n { out.push_str(&format!(",  f·v = {}·v_{{{:+2}}}\n", c_f, weights[k+1])); }
        else { out.push_str(",  f·v = 0\n"); }
    }
    out.push_str("\n  V(n) is the unique (n+1)-dimensional irrep of sl(2) with highest weight n.\n");
    out.push_str("  Each weight space is 1-dimensional: V(n) = ⊕_{k=0}^{n} ℂ·v_{n-2k}.\n");
    out.push_str("  f lowers weight by 2, e raises by 2. h measures weight (eigenvalue of h).\n");
    out
}

fn cmd_verma(lambda: i64) -> String {
    let mut out = String::new();
    out.push_str(&format!("\n  ▸ Verma Module M({}) for sl(2)\n", lambda));
    out.push_str("  Verma module M(λ) = U(sl(2)) ⊗_{U(b)} ℂ_λ, where b = span{e,h}.\n");
    out.push_str("  It is infinite-dimensional with a unique highest-weight vector v_λ.\n\n");
    out.push_str(&format!("  Weights of M({}): {}, {}, {}, {}, ...\n", lambda, lambda, lambda-2, lambda-4, lambda-6));
    out.push_str("  Each weight space dim = 1 (generated by fᵏ·v_λ for k≥0).\n\n");
    out.push_str(&format!("  Basis: {{ fᵏ·v_λ | k ≥ 0 }}\n"));
    out.push_str("  Action:\n");
    out.push_str("    h · fᵏ·v_λ = (λ - 2k) · fᵏ·v_λ\n");
    out.push_str("    f · fᵏ·v_λ = fᵏ⁺¹·v_λ\n");
    out.push_str("    e · fᵏ·v_λ = k(λ-k+1) · fᵏ⁻¹·v_λ\n\n");
    if lambda >= 0 {
        out.push_str(&format!("  Singular vector: f^{{{}}}·v_λ  (weight {} - 2·{} = {})\n",
            lambda+1, lambda, lambda+1, lambda - 2*(lambda+1)));
        out.push_str(&format!("  Maximal proper submodule: U(sl(2))·f^{{{}}}·v_λ\n", lambda+1));
        out.push_str("  Irreducible quotient: L(λ) = M(λ) / (maximal submodule)\n");
        out.push_str(&format!("  dim L({}) = {}\n", lambda, lambda+1));
        out.push_str(&format!("  M({0}) has a singular vector at weight {1}, giving quotient V({0})=L({0}).\n",
            lambda, -(lambda+2)));
    } else {
        out.push_str(&format!("  λ = {} < 0: M(λ) is irreducible (no singular vectors).\n", lambda));
        out.push_str("  For λ ∉ ℤ≥0, the Verma module is irreducible: M(λ) = L(λ).\n");
    }
    out.push_str("\n  Verma modules provide a uniform construction of all highest-weight modules.\n");
    out.push_str("  Category O: weight-decomposable modules, locally finite for n⁺.\n");
    out
}

fn cmd_dim_formula(lambda: i64) -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ Weyl Dimension Formula for sl(2)\n");
    if lambda < 0 { return "  λ must be ≥ 0 for a finite-dimensional irrep\n".to_string(); }
    out.push_str("  For sl(2) (rank 1, single positive root α, ρ = α/2):\n");
    out.push_str("  dim V(λ) = <λ+ρ, α∨> / <ρ, α∨>\n");
    out.push_str("           = (λ+1) / 1 = λ+1\n\n");
    out.push_str(&format!("  dim V({}) = {}\n\n", lambda, lambda+1));
    out.push_str("  Weyl Dimension Formula (General):\n");
    out.push_str("  For a semisimple Lie algebra g with highest weight λ:\n");
    out.push_str("    dim V(λ) = ∏_{α>0} <λ+ρ, α∨> / ∏_{α>0} <ρ, α∨>\n");
    out.push_str("  where ρ = (1/2)·Σ_{α>0} α = half-sum of positive roots.\n\n");
    out.push_str("  Example: sl(3) = A2, fundamental representations\n");
    out.push_str("  ρ = ω₁+ω₂ (sum of fundamental weights)\n");
    out.push_str("  Positive roots: α₁, α₂, α₁+α₂\n");
    out.push_str("  dim V(a,b) = (a+1)(b+1)(a+b+2)/2\n");
    for a in 0..=3i64 {
        for b in 0..=3i64 {
            let d = (a+1)*(b+1)*(a+b+2)/2;
            out.push_str(&format!("    V({},{}) : dim = {}\n", a, b, d));
        }
    }
    out.push_str("  The Weyl dimension formula shows dim grows as a polynomial of degree = #(pos roots).\n");
    out
}

fn cmd_tensor_product(n: i64, m: i64) -> String {
    let mut out = String::new();
    out.push_str(&format!("\n  ▸ Clebsch-Gordan: V({}) ⊗ V({})\n", n, m));
    if n < 0 || m < 0 { return "  n,m must be ≥ 0\n".to_string(); }
    let (big, small) = if n >= m { (n, m) } else { (m, n) };
    out.push_str(&format!("  V({}) ⊗ V({}) = V({}+{}) ⊕ V({}) ⊕ ... ⊕ V({})\n\n",
        n, m, big, small, big+small-2, big-small));
    let mut total_dim = 0i64;
    let mut k = big + small;
    out.push_str("  = ");
    let mut first = true;
    let mut summands = Vec::new();
    while k >= big - small {
        summands.push(k);
        total_dim += k + 1;
        k -= 2;
    }
    for (i, &s) in summands.iter().enumerate() {
        if !first { out.push_str(" ⊕ "); }
        out.push_str(&format!("V({})", s));
        first = false;
        if i > 0 && i % 5 == 0 { out.push_str("\n    "); }
    }
    out.push_str("\n\n");
    out.push_str(&format!("  Verification: total dim = {} = dim(V({}))·dim(V({})) = {}·{} = {}\n",
        total_dim, n, m, n+1, m+1, (n+1)*(m+1)));
    if total_dim == (n+1)*(m+1) {
        out.push_str("  Dimension check passed.\n");
    }
    out.push_str("\n  Weight multiplicity perspective:\n");
    out.push_str(&format!("  Weights of V({}) ⊗ V({}) are all μ₁+μ₂ where μ₁∈wts(V({})), μ₂∈wts(V({})).\n", n, m, n, m));
    let total_wt = n + m;
    let min_wt = -(n + m);
    out.push_str(&format!("  Weight range: {} to {} (step 2)\n", min_wt, total_wt));
    let mut w = total_wt;
    while w >= min_wt {
        let mut mult = 0i64;
        let mut m1 = n;
        while m1 >= -n {
            let m2 = w - m1;
            if m2 >= -m && m2 <= m && (m2 % 2).abs() == (m % 2).abs() { mult += 1; }
            m1 -= 2;
        }
        out.push_str(&format!("    weight {:+3}: multiplicity {}\n", w, mult));
        w -= 2;
    }
    out.push_str("  Clebsch-Gordan tells us how angular momentum states combine in quantum mechanics.\n");
    out
}

fn cmd_character(n: i64) -> String {
    let mut out = String::new();
    if n < 0 { return "  n must be ≥ 0\n".to_string(); }
    out.push_str(&format!("\n  ▸ Character of V({})\n", n));
    out.push_str("  ch V(n) = Σ_{weight μ} dim(V(n)_μ) · e^μ = Σ_{k=0}^{n} e^{n-2k}\n\n");
    out.push_str(&format!("  ch V({}) = ", n));
    let mut parts = Vec::new();
    let mut k = n;
    while k >= -n { parts.push(format!("e^{{{:+}}}", k)); k -= 2; }
    out.push_str(&format!("{}\n\n", parts.join(" + ")));
    out.push_str("  Weyl Character Formula:\n");
    out.push_str("  ch V(λ) = Σ_{w∈W} (-1)^{l(w)} e^{w(λ+ρ)} / Σ_{w∈W} (-1)^{l(w)} e^{w(ρ)}\n\n");
    out.push_str("  For sl(2): W={1,s}, ρ=1, l(1)=0, l(s)=1.\n");
    out.push_str(&format!("  Numerator:   e^{{{}}} - e^{{{}}}  = e^{{-{}}}(e^{{{}}} - 1)\n", n+1, -(n+1), n+1, 2*(n+1)));
    out.push_str("  Denominator: e¹ - e⁻¹\n");
    out.push_str(&format!("  ch V({}) = (e^{{{}}} - e^{{-{}}}) / (e¹ - e⁻¹)\n", n, n+1, n+1));
    out.push_str(&format!("           = e^{{{}}} + e^{{{}}} + ... + e^{{{}}}  (geometric series, {} terms)\n", n, n-2, -n, n+1));
    out.push_str("\n  Specialisation: Weyl Dimension Formula\n");
    out.push_str(&format!("  dim V(n) = ch V(n)|_{{e^μ=1}} = {}\n\n", n+1));
    let theta = std::f64::consts::PI / 4.0;
    let mut sum = 0.0_f64;
    let mut k2 = n;
    while k2 >= -n { sum += (k2 as f64 * theta).cos(); k2 -= 2; }
    out.push_str(&format!("  Evaluated at e^μ = e^{{iμπ/4}}: ch V({}) ≈ {:.4}\n", n, sum));
    out.push_str("  Characters are ring elements: ch(V⊕W)=chV+chW, ch(V⊗W)=chV·chW.\n");
    out.push_str("  The character ring Rep(g) ≅ ℤ[e^{±ω₁},...,e^{±ωᵣ}]^W.\n");
    out
}

fn cmd_dominant(a: i64, b: i64) -> String {
    let mut out = String::new();
    out.push_str(&format!("\n  ▸ Dominant Integral Weight ({},{}) for A2 = sl(3)\n", a, b));
    out.push_str("  For A2, simple roots α₁,α₂. Fundamental weights ω₁,ω₂ with <ωᵢ,αⱼ∨>=δᵢⱼ.\n");
    out.push_str("  A weight λ = aω₁+bω₂ is dominant integral iff a,b ∈ ℤ≥0.\n\n");
    out.push_str(&format!("  λ = {}·ω₁ + {}·ω₂\n", a, b));
    let dominant = a >= 0 && b >= 0;
    if dominant {
        out.push_str(&format!("  ({},{}) IS a dominant integral weight.\n", a, b));
    } else {
        out.push_str(&format!("  ({},{}) is NOT a dominant integral weight (need a,b ≥ 0).\n", a, b));
    }
    if dominant {
        let dim = (a+1)*(b+1)*(a+b+2)/2;
        out.push_str(&format!("  dim V(λ) by Weyl formula = {}\n\n", dim));
        out.push_str(&format!("  The {} weights of V({},{}):\n", dim, a, b));
        out.push_str("  (as (c,d) with weight c·α₁-coord + d·α₂-coord)\n");
        let mut weight_mults: Vec<((i64,i64), i64)> = Vec::new();
        for p in -((a+b+1) as i64)..=((a+b+1) as i64) {
            for q in -((a+b+1) as i64)..=((a+b+1) as i64) {
                let s = p + q;
                if p >= -(a as i64) - (b as i64) && q >= -(a as i64) - (b as i64)
                    && p <= (a as i64) + (b as i64) && q <= (a as i64) + (b as i64)
                    && s >= -(a as i64) - (b as i64) && s <= (a as i64) + (b as i64) {
                    let in_v = p <= a && q <= b && p >= -(b as i64) && q >= -(a as i64)
                        && p+q >= -std::cmp::max(a,b) && p+q <= std::cmp::max(a,b);
                    if in_v { weight_mults.push(((p,q),1)); }
                }
            }
        }
        if weight_mults.len() <= 20 {
            for ((p,q), mult) in &weight_mults {
                out.push_str(&format!("    ({:+},{:+}) mult={}\n", p, q, mult));
            }
        } else {
            out.push_str(&format!("    [showing first 20 of {} weights]\n", weight_mults.len()));
            for ((p,q), mult) in weight_mults.iter().take(20) {
                out.push_str(&format!("    ({:+},{:+}) mult={}\n", p, q, mult));
            }
        }
    }
    out.push_str("  Dominant integral weights parametrise irreducible finite-dim representations.\n");
    out.push_str("  Highest weight theorem: each dominant integral λ gives a unique irrep V(λ).\n");
    out
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_int(&mut s, "weight", 3);
    state_set_int(&mut s, "dominant_a", 2);
    state_set_int(&mut s, "dominant_b", 1);
    s
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "help" | "h" => show_help(),
        "weights" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
            state_set_int(state, "weight", n);
            cmd_weights(n)
        }
        "verma" => {
            let l = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
            state_set_int(state, "weight", l);
            cmd_verma(l)
        }
        "dim_formula" => {
            let l = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
            state_set_int(state, "weight", l);
            cmd_dim_formula(l)
        }
        "tensor_product" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok()).unwrap_or(2);
            let m = args.get(1).and_then(|s| s.parse::<i64>().ok()).unwrap_or(3);
            state_set_int(state, "tensor_n", n);
            state_set_int(state, "tensor_m", m);
            cmd_tensor_product(n, m)
        }
        "character" => {
            let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
            state_set_int(state, "weight", n);
            cmd_character(n)
        }
        "dominant" => {
            let a = args.get(0).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "dominant_a").unwrap_or(2));
            let b = args.get(1).and_then(|s| s.parse::<i64>().ok())
                .unwrap_or(state_get_int(state, "dominant_b").unwrap_or(1));
            state_set_int(state, "dominant_a", a);
            state_set_int(state, "dominant_b", b);
            cmd_dominant(a, b)
        }
        "demo" => {
            let mut out = cmd_weights(3);
            out.push_str(&cmd_tensor_product(2, 3));
            out.push_str(&cmd_character(4));
            out.push_str(&cmd_dominant(2, 1));
            out
        }
        _ => format!("Unknown command '{}'. Type 'help'.\n", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { println!("{}", out); }
    true
}

fn visualize_svg(c: &mut SvgCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    // Weight lattice diagram for sl(2)
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
    c.text_bold(350.0, 30.0, &format!("Weight Lattice of V({})", n), 16.0, "#212121", "middle");
    let cx = 350.0_f64;
    let cy = 260.0_f64;
    let step = 60.0_f64;
    // Draw weight axis
    c.arrow(cx - (n as f64 + 1.5) * step, cy, cx + (n as f64 + 1.5) * step, cy, "#aaaaaa", 1.5);
    c.text(cx + (n as f64 + 2.0) * step, cy, "weight", 11.0, "#666666", "start");
    // Draw weight spaces
    let mut k = n;
    while k >= -n {
        let x = cx + k as f64 * step;
        c.circle(x, cy, 18.0, "#4488ff", "#2244aa", 2.0);
        c.text(x, cy, &format!("{:+}", k), 11.0, "#ffffff", "middle");
        c.text(x, cy + 35.0, &format!("v_{{{:+}}}", k), 10.0, "#333333", "middle");
        // f arrow (lower)
        if k > -n {
            c.arrow(x + 5.0, cy - 25.0, x - step + 5.0, cy - 25.0, "#ff6644", 1.5);
            c.text(x - step/2.0, cy - 35.0, "f", 11.0, "#ff6644", "middle");
        }
        k -= 2;
    }
    c.text(350.0, 450.0, &format!("dim V({}) = {} weight spaces", n, n+1), 11.0, "#555555", "middle");
}

fn visualize_dot(g: &mut DotGraph, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
    let mut k = n;
    while k >= -n {
        let id = format!("w{}", if k >= 0 { format!("p{}", k) } else { format!("m{}", -k) });
        let lbl = format!("{:+}", k);
        g.node(&id, &[("label", &lbl), ("shape", "circle")]);
        k -= 2;
    }
    let mut k2 = n;
    while k2 > -n {
        let id1 = format!("w{}", if k2 >= 0 { format!("p{}", k2) } else { format!("m{}", -k2) });
        let id2 = format!("w{}", if k2-2 >= 0 { format!("p{}", k2-2) } else { format!("m{}", -(k2-2)) });
        g.edge(&id1, &id2, &[("label", "f")]);
        k2 -= 2;
    }
}

fn visualize_tex(t: &mut TikzDoc, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
    let mut k = n;
    while k >= -n {
        let id = format!("v{}", k + n);
        let lbl = format!("v_{{{:+}}}", k);
        t.node(&id, (k as f64) * 1.5, 0.0, &lbl, "circle,draw");
        k -= 2;
    }
}

fn visualize_ascii(a: &mut AsciiCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<i64>().ok())
        .unwrap_or(state_get_int(state, "weight").unwrap_or(3));
    a.text_at(2, 1, &format!("Weight lattice of V({}) for sl(2)", n));
    a.text_at(2, 3, "Weights:");
    let weights: Vec<String> = {
        let mut ws = Vec::new();
        let mut k = n;
        while k >= -n { ws.push(format!("{:+}", k)); k -= 2; }
        ws
    };
    a.text_at(2, 5, &weights.join(" <- f - "));
    a.text_at(2, 8, &format!("dim V({}) = {}", n, n+1));
    a.text_at(2, 10, "e raises weight +2, f lowers weight -2");
    a.text_at(2, 12, "h·v_mu = mu·v_mu (eigenvalue = weight)");
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };
    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg   => { let mut c = SvgCanvas::new(700.0, 500.0); visualize_svg(&mut c, cmd, &args_ref, &state); c.build() }
                OutputFormat::Dot   => { let mut g = DotGraph::digraph("ch50"); visualize_dot(&mut g, cmd, &args_ref, &state); g.build() }
                OutputFormat::Tex   => { let mut t = TikzDoc::standalone(); visualize_tex(&mut t, cmd, &args_ref, &state); t.build() }
                OutputFormat::Ascii => { let mut a = AsciiCanvas::new(80, 30); visualize_ascii(&mut a, cmd, &args_ref, &state); a.render() }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner("Chapter 50", "Highest Weight Theory",
                         "Classifying representations by their highest weight");
            repl("ch50> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
