use common::*;

fn show_help() -> String {
    help_string(&[
        ("flag_variety <n>",   "Flag variety GL_n/B: dimension, Bruhat cell decomposition"),
        ("schubert <perm>",    "Schubert cell C_w for permutation w ∈ Sₙ, dim=inv(w)"),
        ("springer",          "Springer correspondence: nilpotent orbits ↔ Weyl group reps"),
        ("perverse",          "Perverse sheaves on flag variety: IC sheaves"),
        ("bgg",               "BGG resolution: 0→M(w₀·λ)→...→M(λ)→L(λ)→0"),
        ("demo",              "Run a showcase of all commands"),
        ("help",              "Show this help"),
        ("quit",              "Exit"),
    ])
}

// Permutation helpers
fn inversions(perm: &[usize]) -> Vec<(usize,usize)> {
    let n = perm.len();
    let mut inv = Vec::new();
    for i in 0..n { for j in i+1..n { if perm[i] > perm[j] { inv.push((i,j)); } } }
    inv
}
fn perm_to_string(perm: &[usize]) -> String {
    perm.iter().map(|x| x.to_string()).collect::<Vec<_>>().join("")
}
fn perm_mul(sigma: &[usize], tau: &[usize]) -> Vec<usize> {
    tau.iter().map(|&t| sigma[t]).collect()
}
fn perm_inv(sigma: &[usize]) -> Vec<usize> {
    let n = sigma.len();
    let mut inv = vec![0usize; n];
    for (i, &s) in sigma.iter().enumerate() { inv[s] = i; }
    inv
}
fn longest_perm(n: usize) -> Vec<usize> { (0..n).rev().collect() }

fn parse_perm(args: &[&str]) -> Option<Vec<usize>> {
    if args.len() == 1 && args[0].chars().all(|c| c.is_ascii_digit()) {
        let perm: Vec<usize> = args[0].chars()
            .map(|c| c as usize - '1' as usize)
            .collect();
        let n = perm.len();
        let mut seen = vec![false; n];
        for &p in &perm { if p >= n { return None; } if seen[p] { return None; } seen[p] = true; }
        return Some(perm);
    }
    let v: Vec<usize> = args.iter().filter_map(|s| s.parse::<usize>().ok()
        .map(|x| x - 1)).collect();
    if v.is_empty() { return None; }
    let n = v.len();
    let mut seen = vec![false; n];
    for &p in &v { if p >= n { return None; } if seen[p] { return None; } seen[p] = true; }
    Some(v)
}

fn cmd_flag_variety(n: usize) -> String {
    let mut out = String::new();
    if n < 1 || n > 6 { return "  n must be 1–6\n".to_string(); }
    out.push_str(&format!("\n  ▸ Flag Variety FL({}) = GL_{}/B\n\n", n, n));
    let dim = n * (n - 1) / 2;
    out.push_str(&format!("  G = GL_{}(ℂ),  B = upper triangular Borel subgroup\n", n));
    out.push_str(&format!("  FL(n) = G/B = complete flag variety\n"));
    out.push_str(&format!("  dim FL({}) = n(n-1)/2 = {}\n\n", n, dim));
    out.push_str("  A complete flag in ℂⁿ is a chain of subspaces:\n");
    out.push_str("    0 = V₀ ⊂ V₁ ⊂ V₂ ⊂ ... ⊂ Vₙ = ℂⁿ  with dim Vₖ = k.\n\n");
    out.push_str("  Bruhat Decomposition:\n");
    out.push_str("    G = ⊔_{w ∈ Sₙ} B·w·B  (disjoint union of Bruhat cells)\n");
    out.push_str("    G/B = ⊔_{w ∈ Sₙ} C_w  where C_w = B·w·B/B ≅ ℂ^{l(w)}\n\n");
    let sn = all_perms(n);
    out.push_str(&format!("  Cells for n={} ({} total):\n", n, sn.len()));
    out.push_str(&format!("  {:width$}  {:8}  {:8}  {}\n", "w", "l(w)=inv", "dim(C_w)", "codim", width = n+2));
    out.push_str(&format!("  {}\n", "-".repeat(40)));
    let mut cells_by_dim: Vec<Vec<Vec<usize>>> = vec![vec![]; dim+1];
    for w in &sn {
        let linv = inversions(w).len();
        out.push_str(&format!("  [{:width$}]  {:8}  {:8}  {}\n",
            perm_to_string(w), linv, linv, dim - linv, width=n));
        if linv <= dim { cells_by_dim[linv].push(w.clone()); }
    }
    out.push_str(&format!("\n  Poincaré polynomial of FL({}):\n", n));
    out.push_str("  P(t) = ");
    let poincare: Vec<String> = cells_by_dim.iter().enumerate()
        .filter(|(_,cells)| !cells.is_empty())
        .map(|(k,cells)| {
            if k == 0 { "1".to_string() }
            else if cells.len() == 1 { format!("t^{}", 2*k) }
            else { format!("{}·t^{}", cells.len(), 2*k) }
        }).collect();
    out.push_str(&format!("{}\n\n", poincare.join(" + ")));
    let total_cells: usize = sn.len();
    out.push_str(&format!("  Total cells = |S_{}| = {}  (Euler characteristic)\n", n, total_cells));
    out.push_str("  FL(n) is a smooth projective variety with a cell decomposition by Schubert cells.\n");
    out.push_str("  H*(FL(n), ℤ) is generated by Schubert classes σ_w = [X̄_w] ∈ H^{2l(w)}.\n");
    out
}

fn all_perms(n: usize) -> Vec<Vec<usize>> {
    if n == 0 { return vec![vec![]]; }
    let smaller = all_perms(n-1);
    let mut result = Vec::new();
    for perm in smaller {
        for pos in 0..=perm.len() {
            let mut new_perm = perm.clone();
            new_perm.insert(pos, n-1);
            result.push(new_perm);
        }
    }
    result
}

fn cmd_schubert(args: &[&str]) -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ Schubert Cell C_w\n");
    let w = match parse_perm(args) {
        Some(p) => p,
        None => {
            return "  Usage: schubert <perm>  e.g. schubert 213  or  schubert 3 1 2\n  Enter permutation in 1-indexed notation, e.g. '213' means w(1)=2,w(2)=1,w(3)=3\n".to_string();
        }
    };
    let n = w.len();
    let inv = inversions(&w);
    let l = inv.len();
    let w1: Vec<usize> = w.iter().map(|x| x+1).collect();
    out.push_str(&format!("  w = ({}) ∈ S_{}\n",
        w1.iter().map(|x|x.to_string()).collect::<Vec<_>>().join(","), n));
    out.push_str(&format!("  l(w) = #{{inversions}} = {}\n", l));
    out.push_str(&format!("  Inversions: {{ {} }}\n",
        inv.iter().map(|(i,j)| format!("({},{})",i+1,j+1)).collect::<Vec<_>>().join(", ")));
    out.push_str(&format!("\n  Schubert cell C_w ≅ ℂ^{{l(w)}} = ℂ^{}\n", l));
    out.push_str(&format!("  Schubert variety X_w = closure(C_w) ⊆ GL_{}/B\n", n));
    out.push_str(&format!("  dim X_w = l(w) = {}\n\n", l));
    out.push_str("  Permutation matrix:\n");
    out.push_str("  ");
    for row in 0..n {
        for col in 0..n {
            if w[col] == row { out.push_str(" 1"); } else { out.push_str(" 0"); }
        }
        out.push_str("\n");
        if row + 1 < n { out.push_str("  "); }
    }
    out.push_str("\n  Schubert cell coordinates:\n");
    out.push_str("    C_w = { n_w · w · B / B : n_w ∈ N_w }\n");
    out.push_str(&format!("    Free coordinates: {} (= inversions of w)\n\n", l));
    out.push_str("  Bruhat order: v ≤ w if X_v ⊆ X_w  (closure containment).\n");
    let w0 = longest_perm(n);
    let l0 = inversions(&w0).len();
    out.push_str(&format!("  Longest element w₀ = ({}) has l(w₀) = {}\n",
        w0.iter().map(|x|(x+1).to_string()).collect::<Vec<_>>().join(","), l0));
    out.push_str("  Schubert calculus: intersection theory in H*(FL(n)) counts solutions to enumerative problems.\n");
    let _ = (perm_mul, perm_inv);
    out
}

fn cmd_springer() -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ Springer Correspondence\n\n");
    out.push_str("  The Springer correspondence is a bijection:\n");
    out.push_str("    { nilpotent orbits in g } ↔ { irreducible representations of W }\n");
    out.push_str("  where g = Lie(G) and W = Weyl group.\n\n");
    out.push_str("  Construction (Springer, 1976):\n");
    out.push_str("  For N ∈ g nilpotent, the Springer fiber is:\n");
    out.push_str("    B_N = { B ∈ G/B : N ∈ Lie(B) }  (flags preserved by N)\n");
    out.push_str("  The top cohomology H^{top}(B_N) carries a W-action.\n");
    out.push_str("  This gives all irreps of W: each appears exactly once as top cohomology.\n\n");
    out.push_str("  For GL_n / sl_n: nilpotent orbits ↔ partitions of n\n\n");
    out.push_str("  n=2: S_2 = ℤ/2ℤ  has 2 irreps: trivial and sign.\n");
    out.push_str("       sl_2 has 2 nilpotent orbits: {0} (partition 1+1) and regular (2).\n");
    out.push_str("       Springer: zero orbit ↔ sign rep; regular nilp ↔ trivial rep.\n\n");
    out.push_str("  n=3: S_3 has 3 irreps: trivial (1+1+1), standard (2+1), sign (3).\n");
    out.push_str("       sl_3 has 3 nilpotent orbits (by Jordan type):\n");
    out.push_str("         λ=(1,1,1): N=0,  dim orbit=0,  Springer ↔ trivial of S_3\n");
    out.push_str("         λ=(2,1):   subregular, dim orbit=4, Springer ↔ standard (2-dim)\n");
    out.push_str("         λ=(3):     regular, dim orbit=6,  Springer ↔ sign\n\n");
    out.push_str("  n=4: S_4 has 5 irreps; gl_4 has 5 nilpotent orbits:\n");
    for (partition, dim_orbit, irrep) in [
        ("(1,1,1,1)", 0, "trivial"),
        ("(2,1,1)",   6, "standard 3-dim"),
        ("(2,2)",     8, "2-dim (hook)"),
        ("(3,1)",    10, "3-dim (other)"),
        ("(4)",      12, "sign"),
    ] {
        out.push_str(&format!("    {:12}  dim orbit = {:2},  Springer ↔ {}\n", partition, dim_orbit, irrep));
    }
    out.push_str("\n  The Springer correspondence underlies the theory of character sheaves (Lusztig)\n");
    out.push_str("  and the geometric Satake correspondence.\n");
    out
}

fn cmd_perverse() -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ Perverse Sheaves and Intersection Cohomology\n\n");
    out.push_str("  Perverse sheaves on a stratified space X give a t-structure on D^b(X).\n");
    out.push_str("  The simple perverse sheaves are IC(X_w, ℒ) = intersection cohomology sheaves.\n\n");
    out.push_str("  IC Sheaves on the Flag Variety FL(n):\n");
    out.push_str("  For G/B with Schubert stratification G/B = ⊔ C_w:\n");
    out.push_str("    IC_w = j_{!*}(ℂ_{C_w}[l(w)])  = IC extension of constant sheaf on C_w\n");
    out.push_str("    Supported on X_w = closure of C_w (Schubert variety)\n\n");
    out.push_str("  Kazhdan-Lusztig Polynomials:\n");
    out.push_str("  The stalks of IC_w at a point in C_v (v ≤ w) are:\n");
    out.push_str("    dim H^k(IC_w)_v = coefficient of q^k in the KL polynomial P_{v,w}(q).\n\n");
    out.push_str("  KL polynomial P_{v,w}(q) ∈ ℤ≥0[q], deg ≤ (l(w)-l(v)-1)/2.\n");
    out.push_str("  P_{w,w}(q) = 1  for all w.\n");
    out.push_str("  P_{e,w}(q) = Poincaré polynomial of IC_w at identity.\n\n");
    out.push_str("  Example: S_3 case\n");
    let perms_s3 = vec![
        vec![0usize,1,2], vec![1,0,2], vec![0,2,1],
        vec![2,0,1], vec![1,2,0], vec![2,1,0]
    ];
    let names = ["e", "s₁", "s₂", "s₁s₂", "s₂s₁", "s₁s₂s₁"];
    out.push_str("  Bruhat order for S_3 (v ≤ w → IC_w nontrivial at C_v):\n");
    for (w, wn) in perms_s3.iter().zip(names.iter()) {
        let lw = inversions(w).len();
        let kl_trivial = "P=1  (S_3: all KL polys trivial)";
        out.push_str(&format!("    {} = {:10}  l={},  {}\n", wn,
            format!("({})", w.iter().map(|x|(x+1).to_string()).collect::<Vec<_>>().join(",")),
            lw, kl_trivial));
    }
    out.push_str("\n  For S_3 and S_4, all KL polynomials are 1 (trivial stalks).\n");
    out.push_str("  Non-trivial KL polys first appear for S_5 and type B,C,D.\n");
    out.push_str("  KL conjectures (proved by Beilinson-Bernstein and Brylinski-Kashiwara, 1981):\n");
    out.push_str("    [M(λ):L(μ)] = P_{w_μ, w_λ}(1) in Category O.\n\n");
    out.push_str("  BBD Decomposition Theorem:\n");
    out.push_str("  For any proper morphism f: X → Y of algebraic varieties:\n");
    out.push_str("    Rf_*(IC_X) ≅ ⊕ᵢ (IC_{Y_i})^{⊕mᵢ}[shifts]  (decomposition)\n");
    out
}

fn cmd_bgg() -> String {
    let mut out = String::new();
    out.push_str("\n  ▸ BGG Resolution\n\n");
    out.push_str("  Theorem (Bernstein-Gelfand-Gelfand, 1975): For g semisimple, dominant integral λ:\n");
    out.push_str("  There is a resolution of the irreducible module L(λ) by Verma modules:\n\n");
    out.push_str("  The BGG Resolution for sl(2), weight λ=n:\n");
    out.push_str("    0 → M(-n-2) → M(n) → L(n) → 0\n\n");
    out.push_str("    M(n) = Verma with highest weight n  (contains L(n) as quotient)\n");
    out.push_str("    M(-n-2) = Verma with weight -n-2 (the singular vector submodule)\n");
    out.push_str("    The map M(-n-2) → M(n) sends v_{-n-2} ↦ f^{n+1}·v_n  (singular vector).\n\n");
    for n in [0i64, 1, 2, 3, 4] {
        out.push_str(&format!("    λ={}:  0 → M({}) → M({}) → L({}) → 0\n", n, -n-2, n, n));
    }
    out.push_str("\n  For sl(3) = A2, weight λ=(a,b):\n");
    out.push_str("  The BGG resolution has length l(w₀) = 3  (longest element of S_3).\n");
    out.push_str("  0 → M(w₀·λ) → ⊕_{l(w)=2} M(w·λ) → ⊕_{l(w)=1} M(w·λ) → M(λ) → L(λ) → 0\n\n");
    out.push_str("  For λ=(1,0) (standard rep, dim=3):\n");
    out.push_str("  Weyl group orbits under dot action w·λ = w(λ+ρ)-ρ, ρ=(1,1):\n");
    out.push_str("    e·(1,0)    = (1,0)    [highest weight, length 0]\n");
    out.push_str("    s₁·(1,0)  = (-2,1)   [length 1]\n");
    out.push_str("    s₂·(1,0)  = (2,-2)   [length 1]\n");
    out.push_str("    s₁s₂·(1,0)= (-1,-1)  [length 2]\n");
    out.push_str("    s₂s₁·(1,0)= (1,-3)   [length 2]\n");
    out.push_str("    w₀·(1,0)  = (-2,-1)  [length 3, w₀=s₁s₂s₁]\n\n");
    out.push_str("  BGG resolution:  0→M(-2,-1)→M(-1,-1)⊕M(1,-3)→M(-2,1)⊕M(2,-2)→M(1,0)→L(1,0)→0\n\n");
    out.push_str("  The BGG resolution gives a free resolution of L(λ) in Category O.\n");
    out.push_str("  Taking Euler characteristic: Σ(-1)^k [M(w·λ)] = [L(λ)] in the Grothendieck group.\n");
    out.push_str("  This implies the Weyl character formula via alternating-sum over W.\n");
    out.push_str("  BGG resolution = geometric: push-forward of de Rham resolution on flag variety G/B.\n");
    out
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_int(&mut s, "flag_n", 3);
    s
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "help" | "h" => show_help(),
        "flag_variety" => {
            let n = args.get(0).and_then(|s| s.parse::<usize>().ok())
                .unwrap_or(state_get_int(state, "flag_n").unwrap_or(3) as usize);
            state_set_int(state, "flag_n", n as i64);
            cmd_flag_variety(n)
        }
        "schubert" => {
            state_set_str(state, "last_cmd", "schubert");
            if let Some(&p) = args.get(0) { state_set_str(state, "last_perm", p); }
            cmd_schubert(args)
        }
        "springer" => cmd_springer(),
        "perverse" => cmd_perverse(),
        "bgg" => cmd_bgg(),
        "demo" => {
            let mut out = cmd_flag_variety(3);
            out.push_str(&cmd_schubert(&["312"]));
            out.push_str(&cmd_bgg());
            out
        }
        _ => format!("Unknown command '{}'. Type 'help'.\n", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { println!("{}", out); }
    true
}

fn visualize_svg(c: &mut SvgCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    // Flag variety node diagram: Schubert cells by dimension
    let n = args.get(0).and_then(|s| s.parse::<usize>().ok())
        .unwrap_or(state_get_int(state, "flag_n").unwrap_or(3) as usize);
    c.text_bold(350.0, 30.0, &format!("Schubert Cell Decomposition of FL({})", n), 16.0, "#212121", "middle");
    let sn = all_perms(n);
    let dim = n * (n - 1) / 2;
    // Group cells by dimension
    let mut by_dim: Vec<Vec<Vec<usize>>> = vec![vec![]; dim + 1];
    for w in &sn {
        let l = inversions(w).len();
        if l <= dim { by_dim[l].push(w.clone()); }
    }
    let level_h = 70.0_f64;
    let _cx = 350.0_f64;
    for (d, cells) in by_dim.iter().enumerate() {
        if cells.is_empty() { continue; }
        let y = 80.0 + d as f64 * level_h;
        let spacing = 600.0 / (cells.len() + 1) as f64;
        for (i, w) in cells.iter().enumerate() {
            let x = 50.0 + spacing * (i + 1) as f64;
            c.node_circle(x, y, &format!("C_{}", perm_to_string(w)), "#b2ebf2", 22.0, 11.0);
        }
        c.text(30.0, y, &format!("l={}", d), 11.0, "#555555", "start");
    }
    c.text(350.0, 470.0, &format!("FL({}) has {} Schubert cells, dim={}", n, sn.len(), dim), 11.0, "#555555", "middle");
}

fn visualize_dot(g: &mut DotGraph, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<usize>().ok())
        .unwrap_or(state_get_int(state, "flag_n").unwrap_or(3) as usize).min(3);
    let sn = all_perms(n);
    for w in &sn {
        let id = perm_to_string(w);
        let l = inversions(w).len();
        let lbl = format!("w={} l={}", id, l);
        g.node(&id, &[("label", &lbl), ("shape", "circle")]);
    }
    // Bruhat order: cover relations
    for w in &sn {
        let lw = inversions(w).len();
        for v in &sn {
            let lv = inversions(v).len();
            if lw + 1 == lv {
                // v covers w in Bruhat order if they differ by one adjacent transposition
                let diffs: usize = w.iter().zip(v.iter()).filter(|(a,b)| a != b).count();
                if diffs == 2 {
                    let wid = perm_to_string(w);
                    let vid = perm_to_string(v);
                    g.edge(&wid, &vid, &[]);
                }
            }
        }
    }
}

fn visualize_tex(t: &mut TikzDoc, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<usize>().ok())
        .unwrap_or(state_get_int(state, "flag_n").unwrap_or(3) as usize).min(3);
    let sn = all_perms(n);
    let dim = n * (n - 1) / 2;
    let mut by_dim: Vec<Vec<Vec<usize>>> = vec![vec![]; dim + 1];
    for w in &sn { let l = inversions(w).len(); if l <= dim { by_dim[l].push(w.clone()); } }
    for (d, cells) in by_dim.iter().enumerate() {
        let y = d as f64 * 1.5;
        for (i, w) in cells.iter().enumerate() {
            let x = i as f64 * 2.0 - (cells.len() as f64 - 1.0);
            let id = perm_to_string(w);
            let lbl = format!("C_{{{}}}", id);
            t.node(&id, x, y, &lbl, "circle,draw,inner sep=1pt");
        }
    }
}

fn visualize_ascii(a: &mut AsciiCanvas, _cmd: &str, args: &[&str], state: &StateMap) {
    let n = args.get(0).and_then(|s| s.parse::<usize>().ok())
        .unwrap_or(state_get_int(state, "flag_n").unwrap_or(3) as usize).min(4);
    a.text_at(2, 1, &format!("Flag Variety FL({}) = GL_{}/B", n, n));
    a.text_at(2, 3, &format!("dim = {}, Schubert cells = {} (= |S_{}|)",
        n*(n-1)/2, (1..=n).product::<usize>(), n));
    a.text_at(2, 5, "Cells by codimension (Bruhat order):");
    let sn = all_perms(n);
    let dim = n * (n - 1) / 2;
    let mut by_dim: Vec<Vec<String>> = vec![vec![]; dim + 1];
    for w in &sn {
        let l = inversions(&w).len();
        if l <= dim { by_dim[l].push(perm_to_string(&w)); }
    }
    for (d, cells) in by_dim.iter().enumerate() {
        if !cells.is_empty() {
            a.text_at(2, (7 + d) as i32, &format!("l={}: {}", d, cells.join(", ")));
        }
    }
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };
    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg   => { let mut c = SvgCanvas::new(700.0, 500.0); visualize_svg(&mut c, cmd, &args_ref, &state); c.build() }
                OutputFormat::Dot   => { let mut g = DotGraph::digraph("ch52"); visualize_dot(&mut g, cmd, &args_ref, &state); g.build() }
                OutputFormat::Tex   => { let mut t = TikzDoc::standalone(); visualize_tex(&mut t, cmd, &args_ref, &state); t.build() }
                OutputFormat::Ascii => { let mut a = AsciiCanvas::new(80, 30); visualize_ascii(&mut a, cmd, &args_ref, &state); a.render() }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner("Chapter 52", "Geometric Representation Theory",
                         "Flag varieties, Schubert calculus, and perverse sheaves");
            repl("ch52> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
