#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Difficulty {
    Foundational,
    Intermediate,
    Advanced,
}

impl Difficulty {
    pub fn label(self) -> &'static str {
        match self {
            Difficulty::Foundational => "Foundational",
            Difficulty::Intermediate => "Intermediate",
            Difficulty::Advanced => "Advanced",
        }
    }
}

pub struct Question {
    pub unit: u8,
    pub text: &'static str,
    pub options: [&'static str; 4],
    pub correct: usize,
    pub explanation: &'static str,
    pub difficulty: Difficulty,
}

pub const QUESTIONS: &[Question] = &[
    // ── Unit I: First Principles ──────────────────────────────────────────────
    Question {
        unit: 1,
        text: "What are the three components of the SIA (Sense-Integrate-Act) triad that defines basal cognition?",
        options: [
            "Stimulus, Inhibition, Adaptation",
            "Sensing environmental information, integrating it, and acting in ways that serve continued organization",
            "Signaling, Information storage, Autonomy",
            "Synapse, Integration, Axon",
        ],
        correct: 1,
        explanation: "The SIA triad — Sense, Integrate, Act — captures the minimal functional definition of cognition: an organism must sense its environment, integrate that information, and act in ways that serve its continued organization. This is the book's core operational definition.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 1,
        text: "Pamela Lyon's 'biogenic approach' to cognition holds that cognition is:",
        options: [
            "A property exclusive to organisms with nervous systems",
            "A property that co-originates with life itself, present in all living systems",
            "A computational property defined by information processing speed",
            "A phenomenal property requiring conscious experience",
        ],
        correct: 1,
        explanation: "Lyon's biogenic approach holds that cognition co-originated with life — that the minimal conditions for life (self-maintenance, metabolism, responsiveness) are also the conditions for cognition. This contrasts with neurocentric views that restrict cognition to nervous systems.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 1,
        text: "The Minimal Cognitive Organism (MCO) framework of Barandiaran & Moreno requires which of the following as necessary conditions for cognition?",
        options: [
            "Neurons, synapses, and a centralized nervous system",
            "Adaptive autonomy, agency, and sensorimotor coordination",
            "Language, memory consolidation, and symbolic representation",
            "Social interaction, learning, and tool use",
        ],
        correct: 1,
        explanation: "Barandiaran & Moreno's MCO framework identifies adaptive autonomy (self-maintaining organization), agency (goal-directedness), and sensorimotor coordination as the necessary and sufficient conditions for minimal cognition — none of which require neurons.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 1,
        text: "What is the 'hard problem of consciousness' as formulated by David Chalmers?",
        options: [
            "The difficulty of measuring neural correlates of consciousness",
            "Why physical brain processes give rise to subjective experience at all",
            "How to build conscious AI systems",
            "The problem of explaining unconscious cognitive processes",
        ],
        correct: 1,
        explanation: "Chalmers' hard problem asks why any physical process — however complex — gives rise to subjective, first-person experience (qualia). It contrasts with 'easy problems' of explaining cognitive functions like attention and memory, which are difficult but tractable.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 1,
        text: "What does 'principled functional agnosticism' mean in the context of basal cognition research?",
        options: [
            "Refusing to study organisms we cannot communicate with",
            "Attributing rich subjective experience to all living organisms as a default",
            "Rigorously studying functional capacities while neither asserting nor denying phenomenal experience",
            "Eliminating all talk of experience from biological science",
        ],
        correct: 2,
        explanation: "Principled functional agnosticism means studying what organisms functionally do — sensing, integrating, acting — without making claims about whether there is 'something it is like' to be that organism. It avoids both overclaiming (projecting rich experience) and underclaiming (dismissing the question entirely).",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 1,
        text: "Multiple realizability in philosophy of mind holds that:",
        options: [
            "Mental states must be realized in carbon-based neural tissue",
            "The same mental state can be realized by many different physical substrates",
            "Consciousness can be replicated multiple times in artificial systems",
            "All cognitive systems converge on the same architecture through evolution",
        ],
        correct: 1,
        explanation: "Multiple realizability (Putnam) holds that a given mental or cognitive state can be realized by many different physical substrates — silicon, neurons, or biological molecules. This is crucial for basal cognition: if cognition can be realized by bacteria and plants, this follows naturally from multiple realizability.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit II: The Intelligent Cell ─────────────────────────────────────────
    Question {
        unit: 2,
        text: "Michael Levin's 'cognitive light cone' refers to:",
        options: [
            "The visual field of organisms with simple eyes",
            "The spatial and temporal scale over which a system's competencies are integrated",
            "The range of electromagnetic signals cells can detect",
            "A metaphor for how cognition evolved from simple light-sensing",
        ],
        correct: 1,
        explanation: "Levin's cognitive light cone defines the spatial and temporal horizon within which a system's goal-directed competencies are integrated. A bacterium has a small cone; a human brain's cone spans years and kilometers. The framework allows comparison of cognition across scales without requiring brains.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 2,
        text: "The lac operon in E. coli is a classic example of cellular cognition because it:",
        options: [
            "Allows E. coli to photosynthesize in the absence of glucose",
            "Integrates information about two environmental variables (lactose presence, glucose absence) to make a regulatory decision",
            "Enables E. coli to communicate with neighboring cells via quorum sensing",
            "Produces flagella that allow directed chemotaxis",
        ],
        correct: 1,
        explanation: "The lac operon is activated only when lactose is present AND glucose is absent — requiring the cell to integrate two independent signals before switching metabolic strategy. This AND-gate logic is a clear case of multi-signal integration, the 'I' in the SIA triad.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 2,
        text: "Which experiment demonstrated that E. coli can adapt its chemotaxis behavior to the temporal gradient of a stimulus, not just its current value?",
        options: [
            "The Adler (1966) capillary tube assay",
            "The Macnab & Koshland (1972) temporal gradient experiment",
            "The Monod (1942) diauxic growth study",
            "The Berg & Brown (1972) single-cell tracking study",
        ],
        correct: 1,
        explanation: "Macnab & Koshland (1972) showed that E. coli responds to the temporal derivative of attractant concentration — comparing 'now' to 'a moment ago' — rather than just current concentration. This temporal comparison requires a form of short-term memory implemented by methylation of chemoreceptors.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 2,
        text: "Cellular homeostasis is cognitive in the basal sense because:",
        options: [
            "Cells have neurons that regulate internal state",
            "Homeostatic mechanisms sense deviations, integrate signals, and act to restore set-points — the SIA triad",
            "Cells can communicate their internal state to other cells",
            "Homeostasis requires learning from past experience",
        ],
        correct: 1,
        explanation: "Homeostasis is a paradigm case of SIA cognition: sensors detect deviations from set-points, regulatory networks integrate multiple signals, and effectors act to restore balance. This operates without neurons in every living cell from bacteria to human hepatocytes.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 2,
        text: "What is the significance of bioelectricity at the cellular level for basal cognition?",
        options: [
            "It shows that all cells have action potentials identical to neurons",
            "Ion channels and membrane voltage create information-processing capabilities in non-neural cells that predate the evolution of nervous systems",
            "It proves that plants and bacteria are conscious",
            "Bioelectric signals only matter in muscle and nerve tissue",
        ],
        correct: 1,
        explanation: "Bioelectricity — the use of ion gradients and membrane voltage as information-carrying signals — is a universal cellular property, not a neural invention. Levin's work shows that bioelectric patterns encode positional and morphogenetic information in non-neural tissues, suggesting ancient cognitive functions.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 2,
        text: "Epigenetic memory in cells refers to:",
        options: [
            "Genetic mutations accumulated through experience",
            "Heritable changes in gene expression state that do not alter DNA sequence, persisting through cell divisions",
            "The storage of learned behaviors in protein conformation",
            "Short-term receptor sensitization lasting seconds to minutes",
        ],
        correct: 1,
        explanation: "Epigenetic memory involves heritable changes — methylation, histone modification, chromatin remodeling — that alter gene expression without changing DNA sequence. These states can persist through many cell divisions, constituting a form of cellular 'memory' of past environmental conditions.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit III: Bacterial Cognition ─────────────────────────────────────────
    Question {
        unit: 3,
        text: "Quorum sensing is best defined as:",
        options: [
            "The process by which bacteria vote on group decisions via flagella",
            "A population-density-dependent signaling system in which bacteria secrete and detect autoinducers to coordinate collective behavior",
            "The mechanism by which bacteria sense nutrient gradients and move toward food",
            "A form of bacterial memory that persists across generations",
        ],
        correct: 1,
        explanation: "Quorum sensing is the bacterial equivalent of a census: individual cells secrete small signaling molecules (autoinducers) and monitor their accumulation. When concentration exceeds a threshold, coordinated gene expression is triggered — allowing bacteria to 'know' when the population is large enough for collective action.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 3,
        text: "The term 'quorum sensing' was coined by:",
        options: [
            "E.O. Wilson, in the context of ant colony behavior",
            "Bonnie Bassler and J. Woodland Hastings",
            "J. Woodland Hastings and Kenneth Nealson (1970)",
            "J.W. Costerton, in the context of biofilm formation",
        ],
        correct: 2,
        explanation: "The density-dependent luminescence phenomenon in Vibrio fischeri was characterized by Hastings and Nealson (1970). The term 'quorum sensing' itself was introduced by Steven Fuqua, Stephen Winans, and E.P. Greenberg (1994), though Bassler later elucidated interspecies quorum sensing via AI-2.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 3,
        text: "Vibrio fischeri's bioluminescence is a textbook example of quorum sensing because:",
        options: [
            "Individual cells glow faintly at all population densities",
            "Luminescence is only triggered when autoinducer concentration indicates high cell density, coordinating light production across the whole population",
            "The bacteria communicate using light signals to coordinate behavior",
            "The light production is triggered by the host squid's nervous system",
        ],
        correct: 1,
        explanation: "Individual V. fischeri cells produce light only when autoinducer N-AHL accumulates above threshold — signaling high population density. Below threshold, the metabolic cost of luminescence is wasted; above it, all cells light up simultaneously. The squid host exploits this to generate its counterillumination camouflage.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 3,
        text: "Prindle et al. (2015) discovered that biofilms use electrical signaling for which purpose?",
        options: [
            "To attract nutrients from the environment via electrostatic gradients",
            "Long-range propagating potassium ion waves to coordinate metabolic states across spatially distant cells in the biofilm",
            "To repel competing bacterial species through electrical discharge",
            "To communicate with the host immune system",
        ],
        correct: 1,
        explanation: "Prindle et al. (2015, Nature) showed that B. subtilis biofilms use long-range electrical signaling via potassium ion waves to synchronize the metabolic state of interior cells with exterior cells. This allows the biofilm to regulate access to nutrients, preventing the interior from starving — a form of collective homeostasis.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 3,
        text: "Two-component signal transduction systems in bacteria consist of:",
        options: [
            "Two flagellar motors that rotate in opposite directions",
            "A membrane-spanning sensor histidine kinase and a cytoplasmic response regulator",
            "Two types of autoinducers: AHL and AI-2",
            "A chemoreceptor and a methyltransferase for adaptation",
        ],
        correct: 1,
        explanation: "Two-component systems (TCS) are the dominant signal transduction architecture in bacteria: a sensor kinase detects an environmental signal and autophosphorylates; it then transfers the phosphate to a response regulator, which modulates gene expression or behavior. Bacteria typically have dozens of TCS pairs, enabling parallel sensing of many signals.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 3,
        text: "AI-2 (autoinducer-2) is significant in bacterial signaling because:",
        options: [
            "It is specific to Gram-positive bacteria and signals intraspecies density only",
            "It is produced by a wide range of bacterial species and functions as an interspecies communication signal",
            "It triggers antibiotic resistance gene expression in biofilms",
            "It was the first autoinducer discovered, in Vibrio harveyi",
        ],
        correct: 1,
        explanation: "AI-2, derived from the metabolite DPD and produced by the LuxS enzyme present in hundreds of bacterial species, functions as a 'universal' interspecies signal. Bassler's work showed it enables cross-species coordination, making quorum sensing not just an intraspecies phenomenon but potentially a trans-kingdom communication system.",
        difficulty: Difficulty::Advanced,
    },

    // ── Unit IV: Protists and Simple Eukaryotes ───────────────────────────────
    Question {
        unit: 4,
        text: "The landmark Nakagaki et al. (2000) study demonstrated that Physarum polycephalum can:",
        options: [
            "Respond to light stimuli with directional growth toward blue wavelengths",
            "Solve a maze by finding the shortest path between food sources through network reorganization",
            "Produce electrical action potentials identical to those in neurons",
            "Form reproductive structures in response to environmental stress",
        ],
        correct: 1,
        explanation: "Nakagaki et al. (2000, Nature) placed P. polycephalum in a maze with oat flakes at the start and end. The slime mold explored all paths, then retracted from dead ends, leaving only the shortest route. This was published as evidence that a brainless organism could solve a classic computational problem.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 4,
        text: "Saigusa et al. (2008) showed that Physarum exhibits anticipatory behavior by:",
        options: [
            "Growing toward food sources before being exposed to them",
            "Slowing growth in anticipation of periodic cold shocks that had previously predicted unfavorable conditions",
            "Releasing spores before changes in atmospheric pressure predict rain",
            "Retracting pseudopods before touching noxious chemicals",
        ],
        correct: 1,
        explanation: "Saigusa et al. (2008, Physical Review Letters) exposed P. polycephalum to periodic cold shocks, which slowed its growth. After several cycles, when conditions returned to normal, the organism spontaneously slowed its growth at the expected time of the next shock — even without the shock occurring. This is anticipatory behavior based on temporal pattern learning.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 4,
        text: "The Tero et al. (2010) study used Physarum to model which real-world infrastructure network?",
        options: [
            "The internet backbone of Japan",
            "The Tokyo rail network",
            "The Mississippi River drainage basin",
            "The London Underground",
        ],
        correct: 1,
        explanation: "Tero et al. (2010, Science) placed food sources at positions corresponding to cities around Tokyo and found that Physarum's nutrient transport network closely mirrored the actual Tokyo rail network — optimizing for efficiency, redundancy, and cost in ways that took human engineers decades to achieve.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 4,
        text: "Dictyostelium discoideum is a model organism for studying collective cognition because:",
        options: [
            "Individual amoebae fuse to form a true multicellular organism with differentiated cell types when food is scarce",
            "It forms temporary aggregations where cells signal via cAMP waves to coordinate directed migration as a pseudoplasmodium",
            "It communicates via electrical signals identical to biofilm potassium waves",
            "Individual cells can solve mazes independently by sensing gradients",
        ],
        correct: 1,
        explanation: "When food is scarce, Dictyostelium amoebae aggregate by following cAMP (cyclic AMP) gradient waves in a relay system. They form a migrating slug that moves toward light and heat, then differentiates into a fruiting body — with some cells sacrificing themselves to form the stalk. This illustrates collective decision-making and altruism in a social microbe.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 4,
        text: "Stentor coeruleus is significant for basal cognition because experiments by Woodruff (and later Baluška and Levin) suggest it:",
        options: [
            "Is the largest single-celled organism capable of learning",
            "Displays graded, context-sensitive behavioral responses to irritants — effectively making 'decisions' without any neurons",
            "Produces action potentials identical to those in vertebrate neurons",
            "Can form memories that persist across multiple fissions",
        ],
        correct: 1,
        explanation: "Stentor, a large ciliate, responds to mechanical irritation with a hierarchy of behaviors: first bending away, then contracting, then reversing ciliary beat, then finally releasing from the substrate. This graded response — showing context-sensitivity and something like a 'decision' — was revisited by Dexter et al. (2019) as evidence of single-cell behavioral complexity.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 4,
        text: "Choanoflagellates are important to understanding the evolution of nervous systems because:",
        options: [
            "They are the only unicellular organisms known to have voltage-gated sodium channels",
            "As the closest living unicellular relatives of animals, they possess many synaptic signaling components, showing these predate multicellularity",
            "They evolved in parallel with early neurons in the Pre-Cambrian",
            "They form colonies that process information identically to simple brains",
        ],
        correct: 1,
        explanation: "Choanoflagellates (sister group to animals) possess cadherins, post-synaptic density proteins, and other components of the animal synapse, showing that the molecular toolkit for neural signaling predates multicellularity. This supports the view that nervous systems evolved by co-opting pre-existing cellular signaling machinery.",
        difficulty: Difficulty::Advanced,
    },

    // ── Unit V: Plant Cognition ───────────────────────────────────────────────
    Question {
        unit: 5,
        text: "Monica Gagliano et al. (2014) reported that Mimosa pudica could learn habituation, defined as:",
        options: [
            "Increasing response to repeated harmless stimuli",
            "Decreasing response to a repeatedly presented harmless stimulus — distinguishing it from sensitization or fatigue",
            "Associating a neutral stimulus with a previously aversive one",
            "Anticipating the timing of periodic stimuli",
        ],
        correct: 1,
        explanation: "Gagliano et al. (2014, Oecologia) dropped Mimosa plants repeatedly and found that they stopped folding their leaves after many drops — a reduction in response to a harmless repeated stimulus. Crucially, plants that were shaken (a different stimulus) continued to respond, ruling out simple fatigue. The response persisted for weeks.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 5,
        text: "The Taiz et al. (2019) critique of plant neurobiology argued that:",
        options: [
            "Plants have neurons but they operate too slowly to be considered cognitive",
            "The evidence for plant learning, memory, and consciousness is insufficient and often methodologically flawed, and 'plant neurobiology' misuses neural terminology",
            "Plants are more cognitively sophisticated than fungi but less so than protists",
            "All plant signaling can be explained by passive chemical diffusion without invoking cognition",
        ],
        correct: 1,
        explanation: "Taiz et al. (2019, Trends in Plant Science) published a strongly worded critique of plant neurobiology, arguing that terms like 'neurotransmitter,' 'learning,' and 'memory' are inappropriately applied to plant physiology, that experimental evidence is frequently overstated, and that consciousness claims are unsupported. This is the most cited skeptical position in the field.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 5,
        text: "The tritrophic interaction described by Turlings et al. (1990) involves plants that:",
        options: [
            "Secrete toxins that kill herbivores directly upon contact",
            "Release volatile organic compounds when damaged by caterpillars, attracting parasitoid wasps that parasitize the caterpillars",
            "Communicate through mycorrhizal networks to warn neighboring plants of herbivory",
            "Store herbivore saliva proteins to calibrate their defensive responses",
        ],
        correct: 1,
        explanation: "Turlings et al. (1990, Science) showed that corn plants damaged by caterpillars release specific blends of volatile compounds that attract parasitoid wasps — the natural enemies of the caterpillars. This indirect defense is highly specific: the blend differs based on herbivore species and time of day, suggesting sophisticated information integration.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 5,
        text: "Systemic Acquired Resistance (SAR) in plants is a form of basal cognition because:",
        options: [
            "It requires plant hormones to travel through the nervous system",
            "A local infection triggers a systemic, lasting change in the plant's defensive state — a form of immunological memory without immune cells",
            "Plants recognize specific pathogen species using MHC-like receptors",
            "SAR only occurs in woody plants with vascular tissue that can transmit electrical signals",
        ],
        correct: 1,
        explanation: "SAR occurs when a local infection (fungal, bacterial, or viral) triggers systemic expression of pathogenesis-related (PR) genes throughout the plant, resulting in enhanced resistance to subsequent infections. This systemic 'priming' persists for days to weeks and resembles immune memory — despite plants having no immune cells.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 5,
        text: "Vernalization in plants is relevant to basal cognition because it demonstrates:",
        options: [
            "That plants can photosynthesize using blue light wavelengths",
            "Epigenetic memory of winter cold exposure that persists through spring to regulate flowering time",
            "That plants adjust their growth direction based on prevailing wind patterns",
            "A learned response to pollinator timing that is passed to offspring",
        ],
        correct: 1,
        explanation: "Vernalization is the requirement for prolonged cold exposure before a plant can flower. The cold is 'remembered' through epigenetic silencing of the FLC gene (via Polycomb-group proteins and H3K27me3 marks), which persists through warm spring conditions. This is a clear case of heritable epigenetic memory tied to environmental history.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 5,
        text: "Charles Darwin, in 'The Power of Movement in Plants' (1880), proposed that the root apex functions as:",
        options: [
            "The primary site of photosynthesis and energy storage for the plant",
            "A 'brain-like' organ that controls the movements and orientation of the growing plant",
            "The main site of water and nutrient absorption, analogous to an animal's mouth",
            "A gravitational sensor that adjusts trunk orientation in mature trees",
        ],
        correct: 1,
        explanation: "Darwin and his son Francis observed that roots detect multiple stimuli (gravity, light, moisture, touch, temperature) and proposed that the root apex — the root tip — acts as a sensory-integrative center analogous to a primitive brain, controlling the movements of the plant as a whole. This prefigures the plant neurobiology debate by a century.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit VI: Fungal Cognition ─────────────────────────────────────────────
    Question {
        unit: 6,
        text: "The Armillaria ostoyae fungus in Malheur National Forest, Oregon, is noteworthy because:",
        options: [
            "It is the only fungus known to produce bioluminescence visible to the naked eye",
            "A single individual connected by mycelial cords covers 2,385 acres and is estimated to be thousands of years old — one of the largest and oldest organisms on Earth",
            "It communicates with its host trees using quorum sensing signals identical to bacteria",
            "Its mycelium forms a single large cell with thousands of nuclei (a plasmodium)",
        ],
        correct: 1,
        explanation: "The Malheur Armillaria is estimated to cover 2,385 acres (~965 hectares) and may be 2,000–8,650 years old. It is genetically one individual — all mycelial cords share the same genome — making it one of Earth's largest single organisms. Its distributed network raises genuine questions about individuality and decision-making at scale.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 6,
        text: "Suzanne Simard's 1997 Nature paper demonstrated that:",
        options: [
            "Douglas fir and birch trees compete destructively through mycorrhizal networks, releasing toxins",
            "Carbon is transferred bidirectionally between Douglas fir and birch trees via shared mycorrhizal networks, with direction depending on seasonal shading conditions",
            "Mycorrhizal fungi can solve spatial optimization problems comparable to Physarum polycephalum",
            "Fungal networks transmit electrical action potentials faster than plant phloem",
        ],
        correct: 1,
        explanation: "Simard et al. (1997, Nature) used stable and radioactive carbon isotope tracers to show bidirectional carbon transfer between paper birch and Douglas fir via shared mycorrhizal networks. In summer, shaded fir received carbon from birch; in fall, the flow reversed. This was the first direct evidence of interspecies carbon transfer via fungi.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 6,
        text: "The 'wood wide web' is a popular metaphor for mycorrhizal networks. Which of the following best captures the current scientific assessment?",
        options: [
            "The metaphor is accurate: trees communicate intentionally through fungal networks just as humans communicate via the internet",
            "The metaphor captures the real finding of networked carbon/nutrient transfer, but overstates intentionality and the 'communication' framing; it remains scientifically contested whether transfers are adaptive signals or passive leakage",
            "The wood wide web has been definitively disproven; carbon transfer is now known to occur only through root-to-root grafts",
            "The metaphor is accurate only for boreal forests; it does not apply to tropical or temperate ecosystems",
        ],
        correct: 1,
        explanation: "Mycorrhizal network research is real and growing, but the popular 'wood wide web' framing has been criticized (e.g., Karst et al., 2023, Nature Ecology & Evolution) for overstating the evidence for intentional signaling and mutualistic cooperation. The transfers are documented; whether they constitute 'communication' or 'decision-making' by the network remains contested.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 6,
        text: "Andrew Adamatzky's work on fungal electrical signals showed that:",
        options: [
            "Fungi produce electrical signals only in response to wounding, similar to plant responses to damage",
            "Mycelial networks propagate electrical spike trains of variable frequency that may encode information about substrate quality and environmental conditions",
            "Fungi produce voltage changes identical to mammalian action potentials, down to the same ion channel proteins",
            "Electrical signals in fungi propagate at the same speed as mammalian nerve impulses (70 m/s)",
        ],
        correct: 1,
        explanation: "Adamatzky and colleagues recorded electrical spiking patterns in various fungal species (including Physarum, Omphalotus, and Ghost fungi) and reported that spike train patterns differ across substrates and conditions, suggesting possible information encoding. The work is preliminary and its interpretation contested, but it suggests electrical information-processing in fungal networks.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 6,
        text: "Anastomosis in fungal networks refers to:",
        options: [
            "The death of old hyphal tips as the mycelium grows outward",
            "The fusion of hyphae from the same or compatible individuals, creating loops and redundant pathways in the network",
            "The release of spores from specialized reproductive structures",
            "The breakdown of wood cellulose by extracellular enzyme secretion",
        ],
        correct: 1,
        explanation: "Anastomosis is the fusion of hyphae — either within one mycelium or between compatible individuals — forming the looped, redundant topology characteristic of fungal networks. This creates multiple paths between any two network nodes, providing resilience against damage, a property that Marcus Fricker has shown optimizes both efficiency and robustness.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit VII: Collective Cognition ────────────────────────────────────────
    Question {
        unit: 7,
        text: "Stigmergy, as defined by Pierre-Paul Grassé in his studies of termite construction, refers to:",
        options: [
            "The chemical communication system by which insects identify nest-mates",
            "Indirect coordination through environmental modification — agents respond to traces left in the environment by previous agents rather than communicating directly",
            "The hierarchical command structure by which a queen bee directs worker behavior",
            "Aggressive competition between colony members that produces efficient division of labor",
        ],
        correct: 1,
        explanation: "Grassé (1959) coined stigmergy to describe how termites coordinate complex nest construction without any individual having a blueprint: each worker responds to local environmental cues (pheromone-marked soil pellets) that were deposited by previous workers. The environment carries the 'memory' of past actions, coordinating future ones.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 7,
        text: "Thomas Seeley's research on honeybee swarm decision-making showed that house-site selection is most similar to which cognitive process?",
        options: [
            "Majority voting with a designated queen casting the deciding vote",
            "Quorum sensing in bacteria, with scouts signaling via waggle dances until a quorum threshold is reached at the best site",
            "Random search followed by exploitation of the first adequate site found",
            "Hierarchical command with experienced scouts directing inexperienced workers",
        ],
        correct: 1,
        explanation: "Seeley's work (Honeybee Democracy, 2010) showed that scout bees advertise sites via waggle dances whose vigor reflects site quality. Scouts visit competitor sites and stop dancing for inferior ones. When approximately 15 scouts are present at the best site (a quorum), the swarm departs — a decision mechanism strikingly parallel to quorum sensing in bacteria.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 7,
        text: "Ant colony optimization (ACO) algorithms, inspired by ant foraging, exploit the property that:",
        options: [
            "Ants choose paths randomly, and colony-level order emerges from chaotic individual behavior",
            "Shorter paths are traversed more quickly, accumulating more pheromone per unit time, creating positive feedback that reinforces optimal routes",
            "Individual ants can evaluate path quality directly and communicate this to others via pheromone concentration",
            "Queen ants compute optimal foraging routes and communicate them via specialized signals",
        ],
        correct: 1,
        explanation: "Ants deposit pheromone as they walk, and pheromone evaporates over time. A shorter path between nest and food is traversed more times per unit time by returning ants, accumulating pheromone faster. Other ants preferentially follow stronger pheromone trails, creating positive feedback that concentrates traffic on the shortest path — a natural optimization algorithm.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 7,
        text: "John Maynard Smith and Eörs Szathmáry proposed 'major transitions in evolution' as:",
        options: [
            "The eight most significant mass extinctions in Earth's history",
            "Transitions in which formerly independent replicating units combine into new higher-level individuals with new forms of information transmission",
            "The phylogenetic transitions that produced each major animal body plan",
            "Evolutionary events driven primarily by sexual selection rather than natural selection",
        ],
        correct: 1,
        explanation: "Maynard Smith & Szathmáry (The Major Transitions in Evolution, 1995) identified transitions — genes to chromosomes, unicells to multicellular organisms, solitary animals to colonies with division of labor — as moments when independent entities became integrated units capable of transmitting information in new ways. Collective cognition fits this framework as a major transition in cognitive organization.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 7,
        text: "The concept of a 'superorganism,' as applied to insect colonies, implies:",
        options: [
            "A single insect individual that controls all colony behavior through pheromones",
            "That a colony exhibits emergent properties — physiology, homeostasis, division of labor — that parallel individual organisms, with workers as functionally analogous to cells",
            "That colony members share all genetic material and are effectively one genome",
            "That insect colonies have evolved intelligence equivalent to vertebrate brains",
        ],
        correct: 1,
        explanation: "The superorganism concept (Wheeler 1911, popularized by Wilson & Hölldobler 2009) holds that colonies like army ant nests or honeybee hives exhibit organismal-level properties: homeostatic temperature regulation, coordinated immune-like responses to pathogens, developmental stages, and collective physiology that cannot be attributed to any individual worker.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit VIII: The Evolution of Nervous Systems ───────────────────────────
    Question {
        unit: 8,
        text: "C. elegans, with exactly 302 neurons, is a model organism for neuroscience primarily because:",
        options: [
            "It is the only animal with a completely mapped connectome — every neuron and every synapse identified",
            "Its neurons are identical to human neurons, making it an ideal proxy for human brain disorders",
            "It is the simplest animal capable of operant conditioning and associative learning",
            "Its neurons can be individually ablated using laser microsurgery to test function",
        ],
        correct: 0,
        explanation: "White et al. (1986) published the complete wiring diagram of C. elegans — all 302 neurons and ~7,000 synaptic connections — making it the first (and for decades the only) complete animal connectome. This allows precise circuit-level hypotheses about behavior, uniquely bridging connectome structure and behavioral output.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 8,
        text: "Shomrat & Levin (2014) showed that planaria (flatworms) can retain memories of maze training after:",
        options: [
            "Being frozen and thawed, demonstrating cryogenic memory preservation",
            "Complete decapitation and head regeneration — the decapitated worm's body regenerated a new head that retained training",
            "Radical changes in neuroarchitecture induced by drug treatment",
            "Three weeks of sensory deprivation in isolation",
        ],
        correct: 1,
        explanation: "Shomrat & Levin (2014, Journal of Experimental Biology) trained planaria to navigate a textured environment, decapitated them, allowed head regeneration, then found that re-training the regenerated worms was significantly faster than training naive worms. This suggests that memories are stored in the body (perhaps bioelectrically) in ways that survive complete head loss.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 8,
        text: "Nervous systems are thought to have evolved independently multiple times because:",
        options: [
            "All nervous systems share identical neurotransmitter chemistry, proving a single origin",
            "Phylogenetic analysis of neural genes shows they arose separately in ctenophores, cnidarians, and bilaterians, with ctenophore synapses differing fundamentally from all others",
            "Fossil evidence shows neurons appearing simultaneously in the Cambrian explosion across all animal phyla",
            "No nervous system genes are shared between vertebrates and invertebrates",
        ],
        correct: 1,
        explanation: "Ctenophores (comb jellies) have nervous systems that use different neurotransmitters, different gene families, and different synaptic architecture from cnidarian and bilaterian nervous systems — leading to serious proposals (Moroz et al., 2014; Ryan et al., 2013) that ctenophore nervous systems evolved independently. This is a major active debate in evolutionary neuroscience.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 8,
        text: "Eric Kandel's Nobel Prize-winning work on Aplysia californica demonstrated that:",
        options: [
            "Sea slugs have a primitive consciousness detectable by behavioral indicators",
            "The molecular and synaptic mechanisms of learning and memory — sensitization, habituation, long-term potentiation — could be studied in a simple invertebrate nervous system",
            "All forms of learning require protein synthesis in the presynaptic neuron",
            "Memory consolidation requires sleep and hippocampal replay in all animals",
        ],
        correct: 1,
        explanation: "Kandel used Aplysia's large, individually identifiable neurons to work out the molecular basis of habituation, sensitization, and long-term memory. He showed that serotonin activates cAMP/PKA pathways, leading to CREB-dependent protein synthesis and lasting synaptic changes — mechanisms now known to be conserved across animals including mammals.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 8,
        text: "Hydra's nerve net is significant for understanding nervous system evolution because:",
        options: [
            "It is the simplest nervous system in which neurons form a true central ganglion",
            "It demonstrates that organized, coordinated behavior is possible with a diffuse nerve net lacking any centralization or hierarchy",
            "Hydra neurons are chemically identical to human spinal cord interneurons",
            "The Hydra nerve net can generate consciousness, as shown by its responses to anesthetics",
        ],
        correct: 1,
        explanation: "Hydra's neurons are distributed in a diffuse net with no brain or central ganglion, yet the animal coordinates feeding, locomotion, and escape responses with surprising sophistication. This shows that centralization is not required for behavioral coordination, and suggests the earliest nervous systems were decentralized networks that only later consolidated into ganglia and brains.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit IX: Theoretical Frameworks ──────────────────────────────────────
    Question {
        unit: 9,
        text: "In Maturana and Varela's autopoiesis theory, an autopoietic system is defined as:",
        options: [
            "Any system that can reproduce its own components using external materials",
            "A system that continuously produces and maintains the very components that compose it, within a boundary that the system itself creates",
            "A system whose behavior is self-directed rather than externally controlled",
            "A biological system capable of self-repair and regeneration after damage",
        ],
        correct: 1,
        explanation: "Autopoiesis (Maturana & Varela, 1972) defines living organization: a system is autopoietic if it continuously produces the molecules that constitute it, and these molecules in turn produce the system — within a boundary (membrane) that the system itself generates. Cognition, on this view, is the set of processes that realize the autopoiesis — making life and cognition inseparable.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 9,
        text: "Karl Friston's Free Energy Principle proposes that all living systems:",
        options: [
            "Maximize the entropy of their sensory states by seeking novel environments",
            "Minimize variational free energy — a bound on surprise — through perception (updating internal models) and action (changing sensory inputs to match predictions)",
            "Optimize energy acquisition and expenditure to maximize reproductive fitness",
            "Minimize the computational complexity of their world models to reduce metabolic cost",
        ],
        correct: 1,
        explanation: "The FEP (Friston, 2010) proposes that biological systems resist disorder by minimizing variational free energy — a measure of the discrepancy between their internal model and sensory data. This can be achieved by updating the model (perception/learning) or by acting to bring sensory inputs in line with predictions (active inference). The principle claims to unify perception, action, and even evolution.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 9,
        text: "Giulio Tononi's Integrated Information Theory (IIT) identifies consciousness with:",
        options: [
            "The complexity of neural connectivity patterns in the cerebral cortex",
            "Phi (Φ) — a measure of integrated information that cannot be reduced to the sum of its parts",
            "The binding of multiple sensory modalities into a unified percept",
            "The ratio of excitatory to inhibitory synaptic connections in a neural circuit",
        ],
        correct: 1,
        explanation: "IIT proposes that consciousness is identical to integrated information (Φ) — the amount of information generated by a system above and beyond its parts. A system with high Φ has experiences that cannot be decomposed into independent sub-experiences. IIT is controversial but notable for generating precise empirical predictions and for implying that very simple systems may have some degree of consciousness.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 9,
        text: "A Markov blanket, central to the Free Energy Principle, defines:",
        options: [
            "The set of synaptic connections that insulate one brain region from another",
            "The statistical boundary separating a system's internal states from the external world — the set of states that screens off internal from external states",
            "The thermal insulation layer of endothermic animals that maintains body temperature",
            "The epigenetic marks that separate gene regulatory regions from coding sequences",
        ],
        correct: 1,
        explanation: "In Friston's framework, a Markov blanket is the set of states (sensory and active states) that statistically insulate a system's internal states from direct influence by external states. Any system with a Markov blanket can be said to have an 'inside' and 'outside' — and to model its environment. Friston argues all living systems have Markov blankets, making the FEP universal.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 9,
        text: "Enactivism, as developed by Varela, Thompson, and Rosch in 'The Embodied Mind' (1991), holds that cognition is:",
        options: [
            "A computational process of internal representation, best studied by examining neural circuits in isolation",
            "The enactment of a world — an ongoing process of sense-making through embodied action in the environment, not internal representation of a pre-given world",
            "An emergent property of sufficiently large neural networks, requiring a minimum of 10,000 neurons",
            "A phylogenetically recent adaptation found only in vertebrates with prefrontal cortices",
        ],
        correct: 1,
        explanation: "Enactivism holds that cognition is not the manipulation of internal representations of an external world, but the enactment of a meaningful world through the organism's embodied coupling with its environment. This makes organism-environment interaction — not neural computation — the primary unit of analysis, and is particularly hospitable to basal cognition.",
        difficulty: Difficulty::Advanced,
    },

    // ── Unit X: Extended and Distributed Cognition ────────────────────────────
    Question {
        unit: 10,
        text: "The extended mind thesis, as formulated by Clark & Chalmers (1998), holds that:",
        options: [
            "The mind extends into the distant past through memory consolidation during sleep",
            "When an external object plays a functional role in a cognitive process equivalent to the role a brain state would play, it constitutes part of the cognitive system",
            "Consciousness extends beyond the skull into the social and cultural environment through language",
            "Human intelligence has been extended through evolution into increasingly complex social groups",
        ],
        correct: 1,
        explanation: "Clark & Chalmers' 'parity principle': if a process in the world plays the same functional role in cognition that a process in the head would play, and the coupling is reliable and accessible, then the external process is part of the cognitive system. Their example: Otto's notebook, playing the role of memory for an Alzheimer's patient, is part of Otto's mind.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 10,
        text: "Reid et al. (2012) showed that Physarum polycephalum could use an external object as a memory device by:",
        options: [
            "Depositing food into specific locations for later retrieval, similar to food-caching birds",
            "Leaving slime trails to mark explored paths, using the external slime as a spatial memory that guided future foraging decisions",
            "Growing toward previously experienced food locations more rapidly than novel locations",
            "Encoding previous light exposure patterns in differential mycelial density",
        ],
        correct: 1,
        explanation: "Reid et al. (2012, PNAS) showed that Physarum avoids previously visited areas by sensing its own externalized slime trails. The slime trace acts as an external memory that prevents the organism from revisiting depleted territories — a case of genuine extended cognition in which the cognitive process (spatial memory) is distributed between organism and environment.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 10,
        text: "Niche construction in the context of distributed cognition refers to:",
        options: [
            "The ecological process by which organisms construct physical shelters (nests, burrows)",
            "Organisms modifying their environment in ways that alter selection pressures on future generations and offload cognitive work onto environmental structure",
            "The evolutionary process by which organisms adapt to narrow ecological niches",
            "Cultural transmission of tool use patterns within social groups",
        ],
        correct: 1,
        explanation: "Niche construction (Odling-Smee et al., 2003) is the process by which organisms modify their selective environment through their own activity. In cognitive terms, this includes offloading cognitive work onto environmental structure: beaver dams, ant trails, termite mounds, and human writing systems are all cases of organisms extending their cognitive systems into the environment.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 10,
        text: "Morphological computation refers to the idea that:",
        options: [
            "Brain morphology determines the limits of an organism's computational capacity",
            "The physical structure and dynamics of an organism's body perform computational work, reducing the burden on the nervous system",
            "All computation in biology ultimately reduces to the morphology of protein active sites",
            "Evolutionary changes in body plan are driven by computational pressures from predator-prey interactions",
        ],
        correct: 1,
        explanation: "Morphological computation (Pfeifer & Bongard, 2007; Paul, 2006) holds that the body itself is a computational resource: compliant limbs that passively absorb shock, wing geometry that produces stable aerodynamics, and gut structure that pre-processes food all perform work that would otherwise require active neural computation. The body is part of the cognitive system.",
        difficulty: Difficulty::Advanced,
    },

    // ── Unit XI: Basal Cognition and AI ──────────────────────────────────────
    Question {
        unit: 11,
        text: "The DishBrain project (Kagan et al., 2022) is significant because it:",
        options: [
            "Created the first artificial neuron using organic compounds",
            "Showed that cortical neurons cultured on a multi-electrode array could learn to play Pong through closed-loop real-time feedback",
            "Demonstrated that organoids can develop spontaneous consciousness when cultured for longer than 6 months",
            "Proved that silicon transistors can be replaced by biological neurons in standard computers",
        ],
        correct: 1,
        explanation: "Kagan et al. (2022, Neuron) connected ~800,000 cortical neurons on a multi-electrode array to a Pong simulation: neural signals controlled the paddle; ball position/miss data were fed back as electrical stimulation. The neural culture improved performance over ~5 minutes, suggesting goal-directed plasticity in vitro. 'Synthetic biological intelligence' raises profound questions about cognition and moral status.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 11,
        text: "Leonard Adleman (1994) demonstrated that DNA could perform computation by:",
        options: [
            "Using DNA polymerase as a logic gate triggered by temperature changes",
            "Encoding the traveling salesman problem in DNA strands and using molecular biology operations to find solutions in parallel",
            "Creating the first self-replicating artificial DNA sequence capable of information storage",
            "Showing that CRISPR could be used to perform Boolean logic in living cells",
        ],
        correct: 1,
        explanation: "Adleman (1994, Science) encoded a 7-city traveling salesman problem in DNA: cities were sequences, paths were complementary strand pairs. Hybridization and selective amplification (PCR) operated in massive parallel on trillions of molecules simultaneously. This demonstrated that biological molecules could perform computation, founding the field of DNA computing.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 11,
        text: "Neuromorphic computing takes inspiration from basal cognition principles primarily by:",
        options: [
            "Using organic materials identical to those found in biological neurons",
            "Implementing spiking neural networks with co-located memory and processing, enabling event-driven, ultra-low-power computation that mimics biological neural efficiency",
            "Programming computers to solve the same optimization problems that slime molds solve",
            "Replacing digital binary logic with analog signals that vary continuously like biological gradients",
        ],
        correct: 1,
        explanation: "Neuromorphic chips (Intel's Loihi, IBM's TrueNorth) implement spiking neural networks where computation and memory are co-located (unlike the von Neumann bottleneck), and processing is event-driven — triggered by spikes rather than clock cycles. This matches biological neural architecture and achieves orders-of-magnitude better energy efficiency than conventional deep learning hardware.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 11,
        text: "The 'embodiment gap' in AI refers to:",
        options: [
            "The physical distance between AI servers and the sensors that feed them data",
            "The failure of current AI systems to develop human-like body schemas through training",
            "The observation that current AI, despite impressive task performance, lacks the flexible sensorimotor coupling to real environments that even simple organisms possess naturally",
            "The gap between simulated robot bodies and physical robot bodies in transfer learning",
        ],
        correct: 2,
        explanation: "Basal cognition research highlights how deeply biology's intelligence is grounded in real-time sensorimotor coupling with physical environments. Current AI systems (including large language models) process data in a fundamentally disembodied way — they have no body, no metabolism, no stakes. The embodiment gap captures what is arguably still missing from AI despite impressive benchmark performance.",
        difficulty: Difficulty::Advanced,
    },

    // ── Unit XII: Philosophy and Ethics ──────────────────────────────────────
    Question {
        unit: 12,
        text: "The 'combination problem' for panpsychism is:",
        options: [
            "The difficulty of combining mental and physical descriptions in a unified scientific theory",
            "How micro-level experiential properties of fundamental particles combine to produce the unified macro-level consciousness of complex organisms",
            "The problem of combining results from different consciousness research methodologies",
            "How to combine behavioral and neurological measures of consciousness in a single index",
        ],
        correct: 1,
        explanation: "If panpsychism is true (every physical entity has some experiential property), the combination problem asks how micro-experiences of electrons, molecules, or cells combine to produce the unified, qualitatively rich experience of a human mind. This is considered the hardest problem for panpsychism; it threatens to make the view unfalsifiable or incoherent.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 12,
        text: "Matthew Hall's 'Plants as Persons' (2011) argues that plant personhood should be recognized based on:",
        options: [
            "Evidence that plants have pain receptors functionally equivalent to nociceptors",
            "Animist and indigenous perspectives combined with Western plant science that together support a relational, non-hierarchical moral standing for plants",
            "Legal arguments derived from corporate personhood precedents",
            "The finding that plants have distributed consciousness detectable by behavioral measures",
        ],
        correct: 1,
        explanation: "Hall's argument draws on indigenous animist traditions (in which plants are relational persons rather than objects) and Western philosophical ethics to argue for extending moral consideration to plants — not on the basis of sentience, but on the basis of their agency, responsiveness, and participation in relational networks of life. It is explicitly a philosophical-ethical argument, not an empirical one.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 12,
        text: "The continuum hypothesis of mind holds that:",
        options: [
            "Consciousness evolved continuously from simple to complex organisms in a linear progression",
            "Mental properties exist on a graded spectrum across physical systems, with no sharp boundary between minded and non-minded entities",
            "All mental states can be reduced to a continuous mathematical manifold of neural activity",
            "Cognitive ability is continuous within species but discontinuous between phyla",
        ],
        correct: 1,
        explanation: "The continuum hypothesis holds that mind is not binary (present/absent) but graded — existing in degrees across the spectrum of physical complexity. This is the philosophical position most hospitable to basal cognition: it allows bacteria, plants, and fungi to have some (minimal) form of cognition without requiring them to be equivalent to humans.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 12,
        text: "Sender et al. (2016) revised earlier estimates to conclude that the human body contains:",
        options: [
            "Ten bacterial cells for every human cell",
            "Approximately equal numbers of bacterial and human cells (roughly 3.8 × 10¹³ each)",
            "Far more human cells than bacterial cells — bacteria are concentrated in the colon only",
            "A negligible number of bacteria compared to the 37 trillion human cells",
        ],
        correct: 1,
        explanation: "Sender, Fuchs & Milo (2016, Cell) revised the often-cited '10:1' ratio, calculating that an average human contains approximately 3.8 × 10¹³ bacteria and 3.0 × 10¹³ human cells — roughly 1:1. This finding has profound implications for the 'holobiont self': we are, in a literal cellular sense, roughly half non-human.",
        difficulty: Difficulty::Foundational,
    },
    Question {
        unit: 12,
        text: "The holobiont concept, applied to the self, suggests that:",
        options: [
            "Human identity is defined by the totality of one's microbiome composition",
            "The 'self' is not a bounded individual but a community of organisms — human cells, bacteria, archaea, viruses — whose interactions constitute what we call the individual",
            "Each person's gut microbiome is as unique as a fingerprint and should be considered part of personal identity legally",
            "The immune system evolved primarily to maintain the composition of the holobiont rather than to defend against pathogens",
        ],
        correct: 1,
        explanation: "The holobiont concept (Margulis; Zilber-Rosenberg & Rosenberg, 2008) holds that the 'individual' in biology is not a single genotype but a community of organisms — the host plus its microbiome — that evolve together. Applied to selfhood, this challenges the notion of the human self as a discrete, bounded entity and suggests we are better described as structured communities of interacting cognitive systems.",
        difficulty: Difficulty::Intermediate,
    },

    // ── Unit XIII: Frontiers ──────────────────────────────────────────────────
    Question {
        unit: 13,
        text: "The 'measurement problem' in basal cognition research refers to:",
        options: [
            "The difficulty of measuring electrical signals in organisms too small for conventional electrodes",
            "The lack of validated, operationally defined measures for cognitive capacities in non-model organisms — making cross-species comparison unreliable",
            "The quantum uncertainty principle applied to neurotransmitter release at individual synapses",
            "The impossibility of measuring subjective experience in non-verbal organisms",
        ],
        correct: 1,
        explanation: "A central challenge for basal cognition is that most cognitive capacities — learning, memory, decision-making — are defined and operationalized for animals, often for mammals. Applying these definitions to bacteria or plants requires either reformulating them (risking anthropomorphism) or creating new metrics (risking incommensurability). This measurement problem is a major barrier to scientific consensus.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 13,
        text: "Optogenetics as a tool for basal cognition research allows scientists to:",
        options: [
            "Image individual synapses with nanometer resolution using light microscopy",
            "Control specific cell types with millisecond precision by expressing light-sensitive channels, enabling causal tests of circuit function",
            "Map gene expression in individual cells without destroying tissue using fluorescent RNA probes",
            "Measure the electrical potential of plant cell membranes using light-based sensors",
        ],
        correct: 1,
        explanation: "Optogenetics (Boyden, Deisseroth et al., 2005) uses genetically encoded light-sensitive ion channels (channelrhodopsins) to activate or silence specific cell types with millisecond precision. In basal cognition, it enables causal tests in organisms like C. elegans and Drosophila — moving from correlation to causation in circuit function.",
        difficulty: Difficulty::Intermediate,
    },
    Question {
        unit: 13,
        text: "Kriegman et al. (2020) created 'xenobots' — novel living machines — from frog cells. Their significance for basal cognition is that:",
        options: [
            "They demonstrate that frog neurons can be transplanted into non-neural tissue and retain memory",
            "They show that cells self-organize into functional forms with goal-directed behaviors that were not designed or programmed by researchers — body plan and cognition can emerge from cell-level properties",
            "They are the first synthetic organisms capable of Darwinian evolution in the laboratory",
            "They prove that consciousness is substrate-independent, as the xenobots showed signs of distress when damaged",
        ],
        correct: 1,
        explanation: "Kriegman et al. (2020, PNAS) created living machines from Xenopus (frog) skin and cardiac cells. The cells self-organized into novel shapes not found in frogs, and the cardiac cells provided locomotion without any neural control. Some designs even showed kinematic self-replication. This demonstrates that cognitive-like goal-directed behavior can emerge from cell collectives reconfigured in ways evolution never produced.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 13,
        text: "Single-cell RNA sequencing (scRNA-seq) is transforming basal cognition research by enabling:",
        options: [
            "The measurement of membrane potential in individual bacteria with high temporal resolution",
            "Transcriptomic profiling of individual cells within biofilms, revealing unexpected cell-type heterogeneity and specialization in 'uniform' bacterial communities",
            "The sequencing of the complete genome of every microorganism in an environmental sample simultaneously",
            "Measurement of protein expression in real time in live cells without fixation",
        ],
        correct: 1,
        explanation: "scRNA-seq applied to biofilms (e.g., Dar et al., 2021 on B. subtilis) has revealed that what appear to be uniform bacterial communities contain distinct cell-type subpopulations with different transcriptional states and specialized functions. This 'division of labor' at the transcript level suggests that collective cognition in biofilms may rest on differentiated cellular roles analogous to tissues.",
        difficulty: Difficulty::Advanced,
    },
    Question {
        unit: 13,
        text: "The 'consciousness problem' in basal cognition refers specifically to:",
        options: [
            "Whether we should use the word 'conscious' to describe plants and bacteria in scientific papers",
            "The open question of whether any non-neural organisms have phenomenal experience — and how we could ever determine this given the hard problem",
            "The difficulty of defining consciousness in a way that is both scientifically useful and philosophically rigorous",
            "Whether consciousness evolved before or after the Cambrian explosion",
        ],
        correct: 1,
        explanation: "The consciousness problem in basal cognition is the most contested issue in the field: even if we accept that bacteria and plants exhibit functional cognition, the question of whether there is 'something it is like' to be these organisms — whether they have phenomenal experience — remains entirely open. The hard problem applies here with full force: no behavioral or functional test can definitively resolve it.",
        difficulty: Difficulty::Advanced,
    },
];
