use std::io::{self, BufRead, Write};

const BOLD: &str = "\x1b[1m";
const CYAN: &str = "\x1b[36m";
const GREEN: &str = "\x1b[32m";
const YELLOW: &str = "\x1b[33m";
const RED: &str = "\x1b[31m";
const DIM: &str = "\x1b[2m";
const RESET: &str = "\x1b[0m";

fn bold(s: &str) -> String { format!("{BOLD}{s}{RESET}") }
fn cyan(s: &str) -> String { format!("{CYAN}{s}{RESET}") }
fn green(s: &str) -> String { format!("{GREEN}{s}{RESET}") }
fn yellow(s: &str) -> String { format!("{YELLOW}{s}{RESET}") }
fn red(s: &str) -> String { format!("{RED}{s}{RESET}") }
fn dim(s: &str) -> String { format!("{DIM}{s}{RESET}") }

// ── Suspension and Freudenthal ─────────────────────────────────────────────────
//
// ΣX = pushout of 𝟙 ←- X -→ 𝟙
// Constructors: N : ΣX, S : ΣX, merid : X → N = S
//
// Key theorem: Freudenthal suspension theorem
//   If X is (n-1)-connected, then ΣX is n-connected,
//   and the map X → ΩΣX is a 2n-equivalence.
//
// Consequence: πₙ(Sⁿ) = ℤ for all n ≥ 1

fn pi_n_sphere(n: usize) -> String {
    match n {
        0 => "ℤ/2ℤ".into(),
        1 => "ℤ".into(),
        2 => "ℤ".into(),
        3 => "ℤ (generated by Hopf fibration η)".into(),
        4 => "ℤ/2ℤ".into(),
        5 => "ℤ/2ℤ".into(),
        6 => "ℤ/12ℤ".into(),
        7 => "ℤ/2ℤ".into(),
        k => format!("(complex — see homotopy group tables for π{k}(S{k}))"),
    }
}

fn connectivity(space: &str) -> Option<i64> {
    match space {
        "S0" => Some(-1),
        "S1" => Some(0),
        "S2" | "SS1" => Some(1),
        "S3" | "SS2" => Some(2),
        "Sn" | "SSn-1" => Some(-1), // generic
        _ => None,
    }
}

struct Sandbox {
    mode: String,
}

impl Sandbox {
    fn new() -> Self { Sandbox { mode: "suspension".into() } }

    fn print_help() {
        println!("{}", bold("── Suspension ──────────────────────────────────────────────────────"));
        println!("  {}  X               — compute ΣX (suspension of space X)", cyan("susp"));
        println!("  {}  X               — show connectivity of X", cyan("conn"));
        println!("  {}  n               — show πₙ(Sⁿ)", cyan("pi"));
        println!("  {}  n               — show Sⁿ = Σⁿ(S⁰)", cyan("sphere"));
        println!("{}", bold("── Freudenthal Theorem ─────────────────────────────────────────────"));
        println!("  {}         — state the Freudenthal theorem", cyan("freudenthal"));
        println!("  {}  n               — check stable range for Sⁿ", cyan("stable"));
        println!("{}", bold("── Key Spaces ───────────────────────────────────────────────────────"));
        println!("  S0, S1, S2, S3  (spheres)   SS1=S2, SS2=S3 (suspensions)");
        println!("  {}         — full homotopy groups table", cyan("table"));
        println!("  {}         — explain the suspension-loop adjunction", cyan("adjunction"));
    }

    fn handle(&mut self, line: &str) -> bool {
        let trimmed = line.trim();
        if trimmed.is_empty() { return true; }
        if trimmed == "quit" || trimmed == "exit" || trimmed == "q" { return false; }
        if trimmed == "help" || trimmed == "?" { Self::print_help(); return true; }

        let parts: Vec<&str> = trimmed.splitn(2, ' ').collect();
        let cmd = parts[0];
        let rest = if parts.len() > 1 { parts[1].trim() } else { "" };

        match cmd {
            "susp" | "Sigma" | "S" => {
                let result = match rest {
                    "S0" => "S¹  (π₀(S⁰) = ℤ/2ℤ → π₁(S¹) = ℤ)".into(),
                    "S1" => "S²  (Freudenthal: π₂(S²) = ℤ)".into(),
                    "S2" => "S³  (π₃(S³) = ℤ)".into(),
                    "S3" => "S⁴  (π₄(S⁴) = ℤ)".into(),
                    x => format!("Σ({x})"),
                };
                println!("  Σ({rest}) = {}", cyan(&result));
                println!("  Constructors: N : ΣX, S : ΣX, merid : X → N = S");
                println!("  {} ΣX has one fewer connectivity dimension than Sⁿ⁺¹", dim("Note:"));
            }
            "conn" => {
                match connectivity(rest) {
                    Some(c) => {
                        let desc = match c {
                            -1 => "empty (no points)",
                            0 => "non-empty (at most 1 path component)",
                            1 => "path-connected (any two points connected, but loops exist)",
                            _n => "highly connected",
                        };
                        println!("  {rest} is {}-connected: {}", cyan(&c.to_string()), desc);
                    }
                    None => {
                        println!("  {}", dim("Use: S0, S1, S2, S3, SS1, SS2"));
                    }
                }
            }
            "pi" => {
                let n: usize = rest.parse().unwrap_or(1);
                println!("  πₙ(Sⁿ) for n={}:", n);
                println!("  π{n}(S{n}) = {}", cyan(&pi_n_sphere(n)));
                if n >= 1 { println!("  {} All πₙ(Sⁿ) = ℤ for n ≥ 1 (follows from Freudenthal + π₁(S¹)=ℤ)", green("✓")); }
            }
            "sphere" => {
                let n: usize = rest.parse().unwrap_or(1);
                print!("  S{n} = ");
                let chain: Vec<String> = (0..n).map(|_| format!("Σ")).collect();
                println!("{}S⁰", chain.concat());
                let susp_str: String = if n == 0 { String::new() } else { "Σ".repeat(n) };
                println!("  = {}(S⁰)  ({n} suspensions of the 0-sphere S⁰ = {{{{N,S}}}}", susp_str);
                println!("  π{n}(S{n}) = {}", pi_n_sphere(n));
            }
            "freudenthal" => {
                println!("{}", bold("── Freudenthal Suspension Theorem ──────────────────────────────────"));
                println!("  If X is (n-1)-connected (i.e., πₖ(X) = 0 for k < n),");
                println!("  then the map X → ΩΣX is a (2n-1)-equivalence.");
                println!("  Equivalently: πₖ(X) ≃ πₖ₊₁(ΣX) for k ≤ 2n - 2.");
                println!();
                println!("  In HoTT: proved by Lumsdaine, Finster, Licata (2013)");
                println!("  using the encode-decode method on ΣX.");
                println!();
                println!("  Consequence: the suspension map  πₙ(Sⁿ) → πₙ₊₁(Sⁿ⁺¹)");
                println!("  is an isomorphism (both = ℤ), using S¹ is 0-connected.");
                println!();
                println!("  More precisely: π₁(S¹) = ℤ");
                println!("  Σ: π₂(S²) = π₁(S¹) = ℤ    (by Freudenthal, S¹ is 0-conn)");
                println!("  Σ: π₃(S³) = π₂(S²) = ℤ    (by Freudenthal, S² is 1-conn)");
                println!("  ...  and so on inductively.");
            }
            "stable" => {
                let n: usize = rest.parse().unwrap_or(2);
                println!("  Stable range for Sⁿ:");
                println!("  Sⁿ is (n-1)-connected, so Freudenthal applies for k ≤ 2(n-1)-1 = 2n-3.");
                println!("  πₖ(Sⁿ) ≃ πₖ₊₁(Sⁿ⁺¹) for k ≤ {}", 2*n.saturating_sub(3));
                println!("  Stable groups πₙ(Sⁿ) = ℤ for all n ≥ 1.");
            }
            "adjunction" => {
                println!("{}", bold("── Suspension-Loop Adjunction ────────────────────────────────────────"));
                println!("  ΣX is the suspension,  ΩY is the loop space of Y.");
                println!("  There is an adjunction:  Maps(ΣX, Y) ≃ Maps(X, ΩY)");
                println!("  Equivalently:  ΣX → Y  corresponds to  X → ΩY");
                println!();
                println!("  In HoTT this is the type-theoretic adjunction:");
                println!("  (ΣX → Y) ≃ (X → ΩY)  where ΩY = (y₀ = y₀) in Y");
                println!();
                println!("  Key: Ω and Σ are adjoint functors in the (∞,1)-category sense.");
                println!("  This gives the Freudenthal theorem as: connectivity of X");
                println!("  controls the connectivity of the adjunction unit X → ΩΣX.");
            }
            "table" => {
                println!("{}", bold("── Homotopy Groups of Spheres (selected) ─────────────────────────"));
                println!("       S⁰    S¹    S²    S³    S⁴");
                println!("  π₀: ℤ/2   0     0     0     0");
                println!("  π₁:  0    ℤ     0     0     0");
                println!("  π₂:  0    0     ℤ     0     0");
                println!("  π₃:  0    0     ℤ     ℤ     0");
                println!("  π₄:  0    0   ℤ/2  ℤ/2   ℤ");
                println!("  π₅:  0    0   ℤ/2  ℤ/2  ℤ/2");
                println!("  (diagonal: πₙ(Sⁿ) = ℤ for n≥1, by Freudenthal)");
            }
            _ => println!("  {} Unknown command: {cmd}. Type {} for help.", red("✗"), cyan("help")),
        }
        true
    }
}

fn main() {
    println!("{}", bold("\n  ╔══════════════════════════════════════════════════════════╗"));
    println!("{}", bold("  ║    Suspension & πₙ(Sⁿ) — Freudenthal Sandbox            ║"));
    println!("{}", bold("  ╚══════════════════════════════════════════════════════════╝\n"));
    println!("  Explore the suspension functor and Freudenthal's theorem.");
    println!("  See how Σ builds spheres and why πₙ(Sⁿ) = ℤ for all n.");
    println!("  Type {} for the theorem, {} for homotopy groups.\n", cyan("freudenthal"), cyan("table"));

    let stdin = io::stdin();
    let mut sb = Sandbox::new();
    loop {
        print!("  {}susp{} > ", CYAN, RESET);
        io::stdout().flush().unwrap();
        let mut line = String::new();
        match stdin.lock().read_line(&mut line) {
            Ok(0) | Err(_) => break,
            Ok(_) => { if !sb.handle(&line) { break; } }
        }
    }
    println!("  Goodbye.");
}
