use common::*;

fn show_help() -> String {
    help_string(&[
        ("tensor_zn <n> <m>",        "ℤ/nℤ ⊗_ℤ ℤ/mℤ ≅ ℤ/gcd(n,m)ℤ"),
        ("base_change <a> <b>",      "Illustrate base change Q ⊗_Z Z[√a]"),
        ("hom_tensor <n> <m> <k>",   "Hom-Tensor adjunction: both sides"),
        ("annihilate",               "Show ℤ/2ℤ ⊗ ℤ/3ℤ = 0"),
        ("outer_product <v1> <v2>",  "Outer product of two vectors (matrix)"),
        ("flat <n>",                 "Test if ℤ/nℤ is flat"),
        ("demo",                     "Run a showcase of key results"),
        ("help",                     "Show this help"),
        ("quit",                     "Exit"),
    ])
}

// Count homomorphisms ℤ/nℤ → ℤ/mℤ: exactly gcd(n,m) many
fn hom_count(n: i64, m: i64) -> i64 {
    gcd(n, m)
}

// List all homomorphisms ℤ/nℤ → ℤ/mℤ (they are x↦ax where am ≡ 0 mod n)
fn list_homs(n: i64, m: i64) -> Vec<i64> {
    let g = gcd(n, m);
    let step = m / g;
    (0..g).map(|k| k * step).collect()
}

fn cmd_tensor_zn(n: i64, m: i64) -> String {
    let mut out = String::new();
    out.push_str(&format!("=== ℤ/nℤ ⊗_ℤ ℤ/mℤ ===\n"));
    let g = gcd(n, m);
    out.push_str(&format!("  n = {}, m = {}, gcd(n,m) = {}\n", n, m, g));
    out.push_str("\nTheorem: ℤ/nℤ ⊗_ℤ ℤ/mℤ ≅ ℤ/gcd(n,m)ℤ\n");
    out.push_str("\nProof sketch:\n");
    out.push_str("  Every elementary tensor a⊗b in ℤ/nℤ ⊗ ℤ/mℤ satisfies:\n");
    out.push_str("    n·(a⊗b) = (na)⊗b = 0⊗b = 0\n");
    out.push_str("    m·(a⊗b) = a⊗(mb) = a⊗0 = 0\n");
    out.push_str("  So every element is annihilated by both n and m, hence by lcm(n,m).\n");
    out.push_str("  The tensor product is cyclic generated by 1⊗1,\n");
    out.push_str("  and the annihilator of 1⊗1 is gcd(n,m).\n\n");
    if g == 0 {
        out.push_str("ERROR: n and m cannot both be 0\n");
        return out;
    }
    out.push_str(&format!("Result: ℤ/nℤ ⊗_ℤ ℤ/mℤ = ℤ/{}ℤ\n", g));
    out.push_str(&format!("Order of tensor product: {}\n\n", g));
    if g == 1 {
        out.push_str("The tensor product is the trivial group {0}.\n");
        out.push_str("This happens because gcd(n,m)=1 means n and m are coprime.\n");
        out.push_str("The relation n·(1⊗1)=0 and m·(1⊗1)=0 forces 1⊗1=0.\n");
    } else {
        out.push_str(&format!("The tensor product has {} elements: {{0, 1⊗1, 2·(1⊗1), …}}\n", g));
        out.push_str("The generator is 1⊗1, and k·(1⊗1) = k⊗1 = 1⊗k (mod relations).\n");
    }
    out.push_str("\nVerification via universal property: bilinear maps\n");
    out.push_str(&format!("  ℤ/{}ℤ × ℤ/{}ℤ → A  ↔  ℤ/{}ℤ → A  (for any abelian group A)\n", n, m, g));
    out
}

fn cmd_base_change(a: i64, b: i64) -> String {
    let mut out = String::new();
    out.push_str("=== Base Change: ℚ ⊗_ℤ ℤ[√a] ≅ ℚ[√a] ===\n");
    out.push_str(&format!("  a = {}, b = {} (b is used as example integer)\n\n", a, b));
    out.push_str("Base change: if R → S is a ring map and M is an R-module,\n");
    out.push_str("then S ⊗_R M is an S-module (the 'base change' of M to S).\n\n");
    out.push_str("  Here: R = ℤ, S = ℚ, M = ℤ[√a] = {m + n√a : m,n ∈ ℤ}\n\n");
    out.push_str("  ℚ ⊗_ℤ ℤ[√a]:\n");
    out.push_str("    Every element is q⊗(m + n√a) = qm⊗1 + qn⊗√a\n");
    out.push_str("    Over ℚ we can clear denominators: r·1 + s·√a for r,s ∈ ℚ\n");
    out.push_str(&format!("Result: ℚ ⊗_ℤ ℤ[√{}] = {{r + s·√{} : r,s ∈ ℚ}}\n\n", a, a));
    out.push_str(&format!("  As ℚ-vector spaces, ℚ[√{}] has basis {{1, √{}}}.\n", a, a));
    if a > 0 {
        let sq = (a as f64).sqrt();
        if sq.fract() < 1e-10 {
            out.push_str(&format!("  Note: √{} = {} is rational, so ℚ[√{}] = ℚ\n", a, sq as i64, a));
        } else {
            out.push_str(&format!("  Note: √{} ≈ {:.4} is irrational, so [ℚ(√{}):ℚ] = 2\n", a, sq, a));
        }
    } else {
        out.push_str(&format!("  Note: a={} < 0, so √{} is purely imaginary\n", a, a));
        out.push_str("  ℚ[√a] is an imaginary quadratic field.\n");
    }
    let norm = b * b - a;
    out.push_str(&format!("\nConcrete example: ({b}+√{a})({b}−√{a}) = {} - {} = {}\n", b*b, a, norm));
    out.push_str("This is the norm map N(b+√a) = b² - a\n");
    out
}

fn cmd_hom_tensor(n: i64, m: i64, k: i64) -> String {
    let mut out = String::new();
    out.push_str("=== Hom-Tensor Adjunction ===\n");
    out.push_str(&format!("  n={}, m={}, k={}\n\n", n, m, k));
    out.push_str("Hom-Tensor Adjunction: Hom(A⊗B, C) ≅ Hom(A, Hom(B,C))\n");
    out.push_str("Here: A=ℤ/nℤ, B=ℤ/mℤ, C=ℤ/kℤ\n\n");

    let g = gcd(n, m);
    let lhs_count = hom_count(g, k);
    out.push_str(&format!("  LHS: Hom(ℤ/{}ℤ ⊗ ℤ/{}ℤ, ℤ/{}ℤ)\n", n, m, k));
    out.push_str(&format!("     = Hom(ℤ/{}ℤ, ℤ/{}ℤ)   [since ℤ/{}ℤ ⊗ ℤ/{}ℤ ≅ ℤ/{}ℤ]\n", g, k, n, m, g));
    out.push_str(&format!("     = gcd({},{}) = {}\n\n", g, k, lhs_count));

    let inner = gcd(m, k);
    let rhs_count = gcd(n, inner);
    out.push_str(&format!("  RHS: Hom(ℤ/{}ℤ, Hom(ℤ/{}ℤ, ℤ/{}ℤ))\n", n, m, k));
    out.push_str(&format!("     = Hom(ℤ/{}ℤ, ℤ/gcd({},{})ℤ)\n", n, m, k));
    out.push_str(&format!("     = Hom(ℤ/{}ℤ, ℤ/{}ℤ)\n", n, inner));
    out.push_str(&format!("     = gcd({},{}) = {}\n\n", n, inner, rhs_count));

    if lhs_count == rhs_count {
        out.push_str(&format!("Both sides have {} elements — adjunction verified!\n", lhs_count));
    } else {
        out.push_str(&format!("Mismatch: LHS={}, RHS={} (should not happen)\n", lhs_count, rhs_count));
    }
    out.push_str("\n  Explicit LHS homomorphisms (send generator of ℤ/gcd(n,m)ℤ to):\n");
    for a in list_homs(g, k) {
        out.push_str(&format!("    1 ↦ {}\n", a));
    }
    out.push_str("\n  Explicit RHS natural transformations (φ: ℤ/nℤ → Hom(ℤ/mℤ, ℤ/kℤ)):\n");
    out.push_str("    φ(1) is a homomorphism ℤ/mℤ → ℤ/kℤ, i.e. φ(1)(1) ∈ {0,..,gcd(m,k)-1}·(k/gcd(m,k))\n");
    out.push_str("The adjunction sends φ: A⊗B→C to the curried map a ↦ (b ↦ φ(a⊗b)).\n");
    out
}

fn cmd_annihilate() -> String {
    let mut out = String::new();
    out.push_str("=== ℤ/2ℤ ⊗_ℤ ℤ/3ℤ = 0 ===\n\n");
    out.push_str("Claim: ℤ/2ℤ ⊗_ℤ ℤ/3ℤ = 0 (the trivial group).\n\n");
    out.push_str("Proof: Take any elementary tensor a⊗b with a ∈ ℤ/2ℤ, b ∈ ℤ/3ℤ.\n");
    out.push_str("  a⊗b = a⊗(1·b)\n");
    out.push_str("  Since 1 = 3·1 − 2·1 and in ℤ/2ℤ we have 2a = 0:\n");
    out.push_str("    a⊗b = a⊗(3b − 2b)\n");
    out.push_str("  But we can also write:\n");
    out.push_str("    a⊗b = a⊗(1·b)\n");
    out.push_str("          [use 3 = 0 in ℤ/3ℤ]\n");
    out.push_str("    3·(a⊗b) = (3a)⊗b = a⊗(3b) = a⊗0 = 0\n");
    out.push_str("    2·(a⊗b) = (2a)⊗b = 0⊗b = 0\n");
    out.push_str("  So a⊗b is annihilated by both 2 and 3.\n");
    out.push_str("  Since gcd(2,3)=1, there exist integers s,t with 2s+3t=1.\n");
    out.push_str("  Therefore a⊗b = 1·(a⊗b) = (2s+3t)·(a⊗b) = s·0 + t·0 = 0.\n\n");
    let g = gcd(2, 3);
    out.push_str(&format!("gcd(2,3) = {}\n", g));
    out.push_str("ℤ/2ℤ ⊗_ℤ ℤ/3ℤ = ℤ/1ℤ = 0\n\n");
    out.push_str("Every tensor is zero — the module is trivial!\n\n");
    out.push_str("General rule: if gcd(n,m)=1 then ℤ/nℤ ⊗ ℤ/mℤ = 0.\n");
    out.push_str("The modules 'cancel each other out' due to coprime annihilators.\n\n");
    out.push_str("Contrast: ℤ/4ℤ ⊗ ℤ/6ℤ ≅ ℤ/2ℤ (since gcd(4,6)=2, non-trivial).\n");
    out
}

fn cmd_outer_product(v1: &[i64], v2: &[i64]) -> String {
    let mut out = String::new();
    out.push_str("=== Outer Product (Tensor Product of Vectors) ===\n");
    out.push_str(&format!("  v₁ = {:?}\n", v1));
    out.push_str(&format!("  v₂ = {:?}\n\n", v2));
    out.push_str("The outer product v₁ ⊗ v₂ is the matrix M where M[i][j] = v₁[i]·v₂[j].\n");
    out.push_str("This represents an element of ℝⁿ ⊗ ℝᵐ ≅ Mat(n×m, ℝ).\n\n");
    let n = v1.len();
    let m = v2.len();
    let mut data = vec![0i64; n * m];
    for i in 0..n {
        for j in 0..m {
            data[i * m + j] = v1[i] * v2[j];
        }
    }
    let mat = Mat::new(n, m, data);
    out.push_str(&format!("  v₁ ⊗ v₂ =\n{}\n\n", mat));
    out.push_str(&format!("  Rank: {} (outer product has rank ≤ 1)\n", if n > 0 && m > 0 { 1 } else { 0 }));
    out.push_str("An outer product is always a rank-1 matrix.\n");
    out.push_str("General elements of V⊗W are sums of such rank-1 matrices.\n");
    if n >= 2 && m >= 2 {
        let a = v1[0] * v2[0]; let b = v1[0] * v2[1];
        let c = v1[1] * v2[0]; let d_val = v1[1] * v2[1];
        let det = a * d_val - b * c;
        out.push_str(&format!("det of top-left 2×2 = {}\n", det));
        if det == 0 {
            out.push_str("Determinant is 0, confirming rank-1 structure.\n");
        }
    }
    out
}

fn cmd_flat(n: i64) -> String {
    let mut out = String::new();
    out.push_str(&format!("=== Flatness of ℤ/{}ℤ ===\n\n", n));
    out.push_str("M is flat if tensoring with M preserves exact sequences.\n");
    out.push_str("Test: does 0 → ℤ →(×n)→ ℤ remain exact after ⊗ ℤ/nℤ?\n\n");
    out.push_str("  Original injection: 0 → ℤ →(×n)→ ℤ  (injective since n≠0)\n\n");
    out.push_str(&format!("  After ⊗_ℤ ℤ/{}ℤ:\n", n));
    out.push_str(&format!("    0 → ℤ ⊗ ℤ/{}ℤ →(×n⊗1)→ ℤ ⊗ ℤ/{}ℤ\n", n, n));
    out.push_str(&format!("    0 → ℤ/{}ℤ →(×n)→ ℤ/{}ℤ\n\n", n, n));
    out.push_str(&format!("  The map ×n: ℤ/{}ℤ → ℤ/{}ℤ sends x ↦ nx mod {}\n", n, n, n));
    out.push_str(&format!("  But n·x = 0 for all x in ℤ/{}ℤ!\n", n));
    out.push_str("  So the image is {0}, but the domain is non-zero (if n > 1).\n\n");
    if n == 1 {
        out.push_str("ℤ/1ℤ = 0 is trivially flat (the zero module is flat).\n");
    } else {
        out.push_str(&format!("ℤ/{}ℤ is NOT flat!\n", n));
        out.push_str(&format!("  The map ×n: ℤ/{}ℤ → ℤ/{}ℤ is the zero map, not injective.\n", n, n));
        out.push_str("  Injectivity is destroyed by tensoring, so the module is not flat.\n\n");
        out.push_str("Only free modules (and projective modules) are flat over ℤ.\n");
        out.push_str("ℤ/nℤ has torsion, which always obstructs flatness.\n");
    }
    out.push_str(&format!("\n  Kernel of (×n: ℤ/{}ℤ → ℤ/{}ℤ):\n", n, n));
    let mut kernel = vec![];
    for x in 0..n {
        if (n * x) % n == 0 { kernel.push(x); }
    }
    out.push_str(&format!("    ker = {{{}}} = all of ℤ/{}ℤ\n",
        kernel.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "), n));
    out.push_str("The entire module is in the kernel, confirming the map is zero.\n");
    out
}

fn parse_vector(s: &str) -> Option<Vec<i64>> {
    let trimmed = s.trim_matches(|c| c == '[' || c == ']');
    let parts: Result<Vec<i64>, _> = trimmed.split(',').map(|x| x.trim().parse::<i64>()).collect();
    parts.ok()
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_int(&mut s, "n", 6);
    state_set_int(&mut s, "m", 4);
    s
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "tensor_zn" => {
            let n = match parse_int(args, 0, "n") { Some(v) => v, None => return "Missing arg n".to_string() };
            let m = match parse_int(args, 1, "m") { Some(v) => v, None => return "Missing arg m".to_string() };
            if n <= 0 || m <= 0 { return "n and m must be positive".to_string(); }
            state_set_int(state, "n", n);
            state_set_int(state, "m", m);
            cmd_tensor_zn(n, m)
        }
        "base_change" => {
            let a = match parse_int(args, 0, "a") { Some(v) => v, None => return "Missing arg a".to_string() };
            let b = match parse_int(args, 1, "b") { Some(v) => v, None => return "Missing arg b".to_string() };
            state_set_int(state, "a", a);
            state_set_int(state, "b", b);
            cmd_base_change(a, b)
        }
        "hom_tensor" => {
            let n = match parse_int(args, 0, "n") { Some(v) => v, None => return "Missing arg n".to_string() };
            let m = match parse_int(args, 1, "m") { Some(v) => v, None => return "Missing arg m".to_string() };
            let k = match parse_int(args, 2, "k") { Some(v) => v, None => return "Missing arg k".to_string() };
            if n <= 0 || m <= 0 || k <= 0 { return "n, m, k must be positive".to_string(); }
            cmd_hom_tensor(n, m, k)
        }
        "annihilate" => cmd_annihilate(),
        "outer_product" => {
            if args.len() < 2 {
                return "Usage: outer_product <v1> <v2>  e.g. outer_product 1,2,3 4,5".to_string();
            }
            let v1 = match parse_vector(args[0]) {
                Some(v) => v,
                None => return "Could not parse v1; use format: 1,2,3".to_string(),
            };
            let v2 = match parse_vector(args[1]) {
                Some(v) => v,
                None => return "Could not parse v2; use format: 4,5".to_string(),
            };
            cmd_outer_product(&v1, &v2)
        }
        "flat" => {
            let n = match parse_int(args, 0, "n") { Some(v) => v, None => return "Missing arg n".to_string() };
            if n <= 0 { return "n must be positive".to_string(); }
            state_set_int(state, "n", n);
            cmd_flat(n)
        }
        "demo" => {
            let mut out = String::new();
            out.push_str(&cmd_tensor_zn(6, 4));
            out.push_str("\n");
            out.push_str(&cmd_annihilate());
            out.push_str("\n");
            out.push_str(&cmd_hom_tensor(6, 4, 12));
            out.push_str("\n");
            out.push_str(&cmd_flat(6));
            out
        }
        "help" | "h" => show_help(),
        _ => format!("Unknown command '{}'. Type 'help' for commands.", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { println!("{out}"); }
    true
}

fn visualize_svg(c: &mut SvgCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "n").unwrap_or(6);
    let m = state_get_int(state, "m").unwrap_or(4);
    let g = gcd(n, m);
    // Bilinear map universal property diagram
    c.text_bold(350.0, 40.0, "Tensor Product Universal Property", 16.0, "#222", "middle");
    // Three nodes: M×N (top-left), M⊗N (top-right), A (bottom-right)
    c.node_circle(150.0, 120.0, &format!("Z/{}Z x Z/{}Z", n, m), "#eef", 38.0, 11.0);
    c.node_circle(500.0, 120.0, &format!("Z/{}Z@Z/{}Z", n, m), "#eef", 38.0, 11.0);
    c.node_circle(500.0, 350.0, "A", "#efe", 28.0, 14.0);
    // Arrows
    c.arrow(188.0, 120.0, 455.0, 120.0, "#444", 1.5);
    c.text(320.0, 105.0, "bilinear phi", 13.0, "#444", "middle");
    c.arrow(182.0, 140.0, 468.0, 325.0, "#444", 1.5);
    c.text(280.0, 255.0, "f (bilinear)", 13.0, "#444", "middle");
    c.arrow(500.0, 155.0, 500.0, 318.0, "#888", 1.5);
    c.text(518.0, 240.0, "exists! linear", 12.0, "#555", "start");
    // Result
    c.text(200.0, 250.0, &format!("Z/{}Z @ Z/{}Z = Z/{}Z", n, m, g), 13.0, "#222", "middle");
    c.text(200.0, 272.0, &format!("gcd({},{}) = {}", n, m, g), 13.0, "#555", "middle");
    c.rect(130.0, 232.0, 155.0, 55.0, "none", "#888", 1.0);
}

fn visualize_dot(g_dot: &mut DotGraph, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "n").unwrap_or(6);
    let m = state_get_int(state, "m").unwrap_or(4);
    let g = gcd(n, m);
    g_dot.node("MxN", &[("label", &format!("ℤ/{}ℤ × ℤ/{}ℤ", n, m)), ("shape", "box")]);
    g_dot.node("MtN", &[("label", &format!("ℤ/{}ℤ ⊗ ℤ/{}ℤ ≅ ℤ/{}ℤ", n, m, g)), ("shape", "box")]);
    g_dot.node("A",   &[("label", "A (any ab. group)"), ("shape", "ellipse")]);
    g_dot.edge("MxN", "MtN", &[("label", "universal bilinear")]);
    g_dot.edge("MxN", "A",   &[("label", "any bilinear f")]);
    g_dot.edge("MtN", "A",   &[("label", "∃! linear", )]);
}

fn visualize_tex(t: &mut TikzDoc, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "n").unwrap_or(6);
    let m = state_get_int(state, "m").unwrap_or(4);
    let g = gcd(n, m);
    t.node("MxN", 0.0, 0.0, &format!("$\\mathbb{{Z}}/{}\\mathbb{{Z}} \\times \\mathbb{{Z}}/{}\\mathbb{{Z}}$", n, m), "draw");
    t.node("MtN", 4.0, 0.0, &format!("$\\mathbb{{Z}}/{}\\mathbb{{Z}}$", g), "draw");
    t.node("A",   4.0, -3.0, "$A$", "draw,circle");
    t.arrow("MxN", "MtN", "$\\phi$", "->");
    t.arrow("MxN", "A",   "$f$", "->");
    t.arrow("MtN", "A",   "$\\exists!$", "->,dashed");
}

fn visualize_ascii(a: &mut AsciiCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "n").unwrap_or(6);
    let m = state_get_int(state, "m").unwrap_or(4);
    let g = gcd(n, m);
    a.text_at(2, 1, "Tensor Product Universal Property");
    a.text_at(2, 3, &format!("Z/{}Z x Z/{}Z -----> Z/{}Z tensor Z/{}Z", n, m, n, m));
    a.text_at(2, 4, "   |  (bilinear phi)             |");
    a.text_at(2, 5, "   |                              | exists!");
    a.text_at(2, 6, "   +-----------> A <-------------+");
    a.text_at(2, 8, &format!("Result: Z/{}Z tensor Z/{}Z = Z/{}Z  (gcd={}) ", n, m, g, g));
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };
    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg   => { let mut c = SvgCanvas::new(700.0, 500.0); visualize_svg(&mut c, cmd, &args_ref, &state); c.build() }
                OutputFormat::Dot   => { let mut g = DotGraph::digraph("ch28"); visualize_dot(&mut g, cmd, &args_ref, &state); g.build() }
                OutputFormat::Tex   => { let mut t = TikzDoc::standalone(); visualize_tex(&mut t, cmd, &args_ref, &state); t.build() }
                OutputFormat::Ascii => { let mut a = AsciiCanvas::new(80, 30); visualize_ascii(&mut a, cmd, &args_ref, &state); a.render() }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner("Chapter 28", "Tensor Products of Modules", "⊗ — the universal bilinear construction");
            print_note("Explore tensor products: ℤ/nℤ⊗ℤ/mℤ, flatness, Hom-Tensor adjunction.");
            println!("{}", show_help());
            repl("tensor> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
