use common::*;

fn help_text() -> String {
    help_string(&[
        ("noetherian <n>",          "ascending chain condition on ideals of Z/nZ"),
        ("localize <p>",            "describe Z_(p); elements inverted; residue field"),
        ("nullstellensatz <f...> <p>","zero set V(f) and rad(I(V(f))) over Z/pZ"),
        ("krull_z",                 "Krull dim of Z: chains of primes; dim = 1"),
        ("krull_poly <n>",          "Krull dim of k[x_1,...,x_n]: dim = n"),
        ("primary_decomp <n>",      "primary decomp of (0) in Z/nZ"),
        ("integral <a> <coeffs>",   "check if a satisfies monic poly with int coeffs"),
        ("demo",                    "showcase commutative algebra examples"),
        ("help",                    "show this help"),
        ("quit",                    "exit"),
    ])
}

fn cmd_noetherian(args: &[&str]) -> String {
    let n = match parse_uint(args, 0, "n") { Some(x) => x as usize, None => return String::new() };
    if n < 2 { return "n must be at least 2".to_string(); }
    let divs = divisors(n as u64);
    let mut out = format!("Ascending Chain Condition on Z/{}Z\n", n);
    out.push_str("  Ideals:\n");
    for &d in &divs {
        let size = n as u64 / d;
        out.push_str(&format!("    ({}) -- size {}\n", n as u64 / d, size));
    }
    let factors = factor(n as u64);
    let mut current = n as u64;
    let mut chain = vec![current];
    'outer: loop {
        for &(p, _) in &factors {
            if current % p == 0 { current /= p; chain.push(current); continue 'outer; }
        }
        break;
    }
    let chain_str: Vec<String> = chain.iter().map(|&d| {
        format!("({}) [size {}]", n as u64 / d, d)
    }).collect();
    out.push_str(&format!("  Maximal ascending chain: {}\n", chain_str.join(" < ")));
    out.push_str("  Z/nZ is Noetherian (and Artinian): every chain stabilizes.\n");
    out
}

fn cmd_localize(args: &[&str]) -> String {
    let p = match parse_uint(args, 0, "p") { Some(x) => x, None => return String::new() };
    if !is_prime(p) { return format!("{} is not prime.", p); }
    let inverted: Vec<i64> = (1..=20i64).filter(|&b| b % p as i64 != 0).collect();
    let mut out = format!("Localization Z_({}) = Z[1/b : p does not divide b]\n", p);
    out.push_str(&format!("  Inverted (first 10): {:?}\n", &inverted[..inverted.len().min(10)]));
    out.push_str(&format!("  NOT inverted: {}, {}, {}, ...\n", p, 2*p, 3*p));
    out.push_str(&format!("  Z_({}) is a local ring, unique maximal ideal ({})\n", p, p));
    out.push_str(&format!("  Residue field: Z_({}) / ({}) = F_{}\n", p, p, p));
    out.push_str(&format!("  Z_({}) is a DVR with uniformizer {}.\n", p, p));
    out
}

fn cmd_nullstellensatz(args: &[&str]) -> String {
    if args.len() < 2 { return "Usage: nullstellensatz <f coeffs...> <p>".to_string(); }
    let p = match args.last().and_then(|s| s.parse::<u64>().ok()) {
        Some(x) => x, None => return "Last arg must be prime p.".to_string(),
    };
    if !is_prime(p) { return format!("{} is not prime.", p); }
    let coeffs: Vec<i64> = args[..args.len()-1].iter().filter_map(|s| s.parse().ok()).collect();
    let f = Poly::new(coeffs);
    let zeros: Vec<u64> = (0..p).filter(|&x| f.eval_mod(x as i64, p as i64) == 0).collect();
    let mut out = format!("Nullstellensatz over F_{}\n  f(x) = {}\n", p, f);
    if zeros.is_empty() {
        out.push_str("  V(f) = {} (empty)\n  I(V(f)) = (1) = F_p[x]\n");
    } else {
        out.push_str(&format!("  V(f) = {:?} in F_{}\n", zeros, p));
        let mut g = Poly::new(vec![1]);
        for &a in &zeros {
            let linear = Poly::new(vec![-(a as i64), 1]);
            g = g.mul(&linear);
        }
        out.push_str(&format!("  I(V(f)) generated by product(x-a) = {}\n", g));
    }
    out.push_str("  Hilbert Nullstellensatz: over alg. closed field, rad(I(V(J))) = rad(J).\n");
    out
}

fn cmd_krull_z() -> String {
    let primes = primes_up_to(20);
    let mut out = String::from("Krull Dimension of Z\n");
    out.push_str("  Prime ideals: (0), and (p) for each prime p.\n");
    out.push_str("  Prime examples: ");
    out.push_str(&primes.iter().map(|&p| format!("({})", p)).collect::<Vec<_>>().join(", "));
    out.push('\n');
    out.push_str("  Maximal chain: (0) < (p)  length = 1\n");
    out.push_str("  dim Z = 1\n");
    out.push_str("  Z is a Dedekind domain (1-dimensional PID).\n");
    out
}

fn cmd_krull_poly(args: &[&str]) -> String {
    let n = match parse_uint(args, 0, "n") { Some(x) => x as usize, None => return String::new() };
    if n == 0 { return "n must be positive".to_string(); }
    if n > 6 { return "n too large (max 6)".to_string(); }
    let vars: Vec<String> = (1..=n).map(|i| format!("x_{}", i)).collect();
    let ring = format!("k[{}]", vars.join(","));
    let mut out = format!("Krull Dimension of {}\n", ring);
    let mut chain: Vec<String> = vec!["(0)".to_string()];
    for i in 1..=n {
        let ideal_gens: Vec<String> = (1..=i).map(|j| format!("x_{}", j)).collect();
        chain.push(format!("({})", ideal_gens.join(",")));
    }
    out.push_str(&format!("  Chain: {}\n", chain.join(" < ")));
    out.push_str(&format!("  dim {} = {}\n", ring, n));
    out.push_str(&format!("  dim k[x_1,...,x_n] = n for any field k.\n"));
    out
}

fn cmd_primary_decomp(args: &[&str]) -> String {
    let n = match parse_uint(args, 0, "n") { Some(x) => x, None => return String::new() };
    if n < 2 { return "n must be at least 2".to_string(); }
    let factors = factor(n);
    let mut out = format!("Primary Decomposition of (0) in Z/{}Z\n", n);
    out.push_str(&format!("  {} = {}\n", n,
        factors.iter().map(|&(p,e)| if e==1 { format!("{}",p) } else { format!("{}^{}",p,e) }).collect::<Vec<_>>().join(" * ")));
    out.push_str("  Primary components:\n");
    let mut ideals: Vec<String> = Vec::new();
    for &(p, e) in &factors {
        let pk = p.pow(e);
        out.push_str(&format!("    ({}) = ({}) -- {}-primary\n", pk, pk, p));
        ideals.push(format!("({})", pk));
    }
    out.push_str(&format!("  ({}) = {} in Z\n", n, ideals.join(" ∩ ")));
    out.push_str("  Primary decomp: analogue of prime factorization for ideals.\n");
    out
}

fn cmd_integral(args: &[&str]) -> String {
    if args.len() < 2 { return "Usage: integral <a> <monic poly coeffs...>".to_string(); }
    let a = match parse_int(args, 0, "a") { Some(x) => x, None => return String::new() };
    let coeffs: Vec<i64> = args[1..].iter().filter_map(|s| s.parse().ok()).collect();
    if coeffs.is_empty() { return "Provide polynomial coefficients (constant first).".to_string(); }
    let mut monic_coeffs = coeffs.clone();
    let last = monic_coeffs.len() - 1;
    if monic_coeffs[last] != 1 { monic_coeffs[last] = 1; }
    let f = Poly::new(monic_coeffs);
    let val = f.eval(a);
    let mut out = format!("Is {} integral over Z?\n  f(x) = {}\n  f({}) = {}\n", a, f, a, val);
    if val == 0 {
        out.push_str(&format!("  {} IS integral over Z (satisfies f).\n", a));
    } else {
        out.push_str(&format!("  {} does not satisfy this polynomial.\n", a));
        out.push_str(&format!("  (But {} is always integral via f(x) = x - {})\n", a, a));
    }
    out.push_str("  Algebraic integers: sqrt(2) (x^2-2=0), i (x^2+1=0), zeta_n (Phi_n(x)=0).\n");
    out.push_str("  Non-example: 1/2 satisfies 2x-1=0 but no MONIC integer polynomial.\n");
    out
}

fn cmd_demo() -> String {
    let mut out = String::from("Demo: Commutative Algebra\n");
    out.push_str(&cmd_noetherian(&["12"]));
    out.push_str(&cmd_localize(&["3"]));
    out.push_str(&cmd_krull_z());
    out.push_str(&cmd_primary_decomp(&["12"]));
    out
}

fn default_state() -> StateMap {
    let mut s = state_new();
    state_set_int(&mut s, "last_n", 12);
    state_set_int(&mut s, "last_p", 3);
    s
}

fn run_cmd(cmd: &str, args: &[&str], state: &mut StateMap) -> String {
    match cmd {
        "noetherian"      => { let r = cmd_noetherian(args); if let Some(n) = parse_uint(args,0,"n") { state_set_int(state,"last_n",n as i64); } r }
        "localize"        => { let r = cmd_localize(args); if let Some(p) = parse_uint(args,0,"p") { state_set_int(state,"last_p",p as i64); } r }
        "nullstellensatz" => { let r = cmd_nullstellensatz(args); if let Some(p) = args.last().and_then(|s| s.parse::<u64>().ok()) { state_set_int(state,"last_p",p as i64); } r }
        "krull_z"         => cmd_krull_z(),
        "krull_poly"      => { let r = cmd_krull_poly(args); if let Some(n) = parse_uint(args,0,"n") { state_set_int(state,"last_n",n as i64); } r }
        "primary_decomp"  => { let r = cmd_primary_decomp(args); if let Some(n) = parse_uint(args,0,"n") { state_set_int(state,"last_n",n as i64); } r }
        "integral"        => cmd_integral(args),
        "demo"            => cmd_demo(),
        "help" | "h"      => help_text(),
        _ => format!("Unknown command '{}'. Type 'help'.", cmd),
    }
}

fn run_cmd_bool(cmd: &str, args: &[&str], state: &mut StateMap) -> bool {
    if cmd == "quit" || cmd == "exit" || cmd == "q" { return false; }
    let out = run_cmd(cmd, args, state);
    if !out.is_empty() { println!("{out}"); }
    true
}

fn visualize_svg(c: &mut SvgCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "last_n").unwrap_or(12) as usize;
    c.title(&format!("Spec(Z/{}Z) -- Prime Spectrum", n));
    c.subtitle("Prime ideals as nodes", 44.0);
    // Spec = set of prime ideals = prime divisors of n
    let primes: Vec<u64> = factor(n as u64).iter().map(|&(p,_)| p).collect();
    let num_p = primes.len();
    let total_width = c.width - 100.0;
    let cx = c.width / 2.0;
    // Draw ring at top
    c.rrect(cx - 50.0, 70.0, 100.0, 36.0, 8.0, colors::HEADER_FILL, colors::CYAN, 1.5);
    c.text_bold(cx, 88.0, &format!("Z/{}Z", n), 13.0, colors::DARK, "middle");
    // Draw prime ideals
    for (i, &p) in primes.iter().enumerate() {
        let x = 80.0 + (i as f64 + 0.5) * total_width / num_p as f64;
        let y = 200.0;
        c.circle(x, y, 26.0, colors::LIGHT, colors::CYAN, 1.5);
        c.text_bold(x, y - 8.0, &format!("({})", p), 12.0, colors::DARK, "middle");
        c.text(x, y + 8.0, &format!("F_{}", p), 10.0, colors::GREY, "middle");
        c.arrow(cx, 106.0, x, 174.0, colors::GREY, 1.0);
        // Mark prime vs maximal
        c.text(x, y + 35.0, "prime & maximal", 9.0, colors::GREEN, "middle");
    }
    // Zero ideal at bottom
    let y_zero = 330.0;
    c.circle(cx, y_zero, 20.0, colors::LIGHT, colors::GREY, 1.0);
    c.text(cx, y_zero, "(0)", 12.0, colors::DARK, "middle");
    c.text(cx, y_zero + 30.0, "prime ideal (dim 0)", 10.0, colors::GREY, "middle");
    for (i, &_p) in primes.iter().enumerate() {
        let x = 80.0 + (i as f64 + 0.5) * total_width / num_p as f64;
        c.line(x, 226.0, cx, y_zero - 20.0, colors::GREY, 0.8);
    }
    c.text(cx, c.height - 20.0, "Krull dim = 0 (Artinian ring)", 11.0, colors::GREY, "middle");
}

fn visualize_dot(g: &mut DotGraph, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "last_n").unwrap_or(12) as usize;
    g.graph_attr("label", &format!("Spec(Z/{}Z)", n));
    g.graph_attr("rankdir", "TB");
    g.node_default("shape", "ellipse");
    g.node_default("style", "filled");
    g.node("ring", &[("label", &format!("Z/{}Z", n)), ("fillcolor", "#ffd54f")]);
    let primes: Vec<u64> = factor(n as u64).iter().map(|&(p,_)| p).collect();
    for &p in &primes {
        let id = format!("p{}", p);
        g.node(&id, &[("label", &format!("({})\nF_{}", p, p)), ("fillcolor", "#b2ebf2")]);
        g.edge("ring", &id, &[("label", "maximal ideal")]);
    }
    g.node("zero", &[("label", "(0)\nprime ideal"), ("fillcolor", "#e8f5e9")]);
    for &p in &primes {
        g.edge(&format!("p{}", p), "zero", &[("style", "dashed")]);
    }
}

fn visualize_tex(t: &mut TikzDoc, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "last_n").unwrap_or(12) as usize;
    t.raw(&format!("  % Spec(Z/{}Z)", n));
    t.node_math("ring", 0.0, 2.0,
                &format!("\\mathbb{{Z}}/{}\\mathbb{{Z}}", n), "draw,ellipse,fill=yellow!30");
    let primes: Vec<u64> = factor(n as u64).iter().map(|&(p,_)| p).collect();
    let num = primes.len();
    for (i, &p) in primes.iter().enumerate() {
        let x = (i as f64 - (num as f64 - 1.0)/2.0) * 2.5;
        t.node_math(&format!("p{}", p), x, 0.0,
                    &format!("({})", p), "draw,circle,fill=cyan!20");
        t.arrow("ring", &format!("p{}", p), "", "gray");
    }
    t.node_math("zero", 0.0, -2.0, "(0)", "draw,circle,fill=green!20");
    for &p in &primes {
        t.edge(&format!("p{}", p), "zero", "", "gray,dashed");
    }
}

fn visualize_ascii(a: &mut AsciiCanvas, _cmd: &str, _args: &[&str], state: &StateMap) {
    let n = state_get_int(state, "last_n").unwrap_or(12) as usize;
    a.text_at(2, 0, &format!("Spec(Z/{}Z) -- Prime Spectrum", n));
    a.hline(2, 1, 40, '-');
    let primes: Vec<u64> = factor(n as u64).iter().map(|&(p,_)| p).collect();
    a.text_at(2, 2, "Prime ideals (maximal in Z/nZ):");
    for (i, &p) in primes.iter().enumerate() {
        a.text_at(4, (3 + i) as i32, &format!("({}) -- quotient F_{} (field)", p, p));
    }
    let row = 3 + primes.len();
    a.text_at(2, row as i32, "(0) -- prime, non-maximal");
    a.text_at(2, (row + 1) as i32, &format!("Krull dim(Z/{}Z) = 0", n));
    a.text_at(2, (row + 2) as i32, "Krull dim(Z) = 1");
    a.text_at(2, (row + 3) as i32, "Krull dim(k[x1,...,xn]) = n");
}

fn main() {
    let app = AppArgs::parse();
    let mut state = if let Some(ref f) = app.load_file {
        load_state(f).unwrap_or_else(|_| default_state())
    } else { default_state() };
    match &app.mode {
        AppMode::Run { cmd, args } => {
            let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
            let out = match app.format {
                OutputFormat::Svg   => { let mut c = SvgCanvas::new(700.0, 500.0); visualize_svg(&mut c, cmd, &args_ref, &state); c.build() }
                OutputFormat::Dot   => { let mut g = DotGraph::digraph("ch24"); visualize_dot(&mut g, cmd, &args_ref, &state); g.build() }
                OutputFormat::Tex   => { let mut t = TikzDoc::standalone(); visualize_tex(&mut t, cmd, &args_ref, &state); t.build() }
                OutputFormat::Ascii => { let mut a = AsciiCanvas::new(80, 30); visualize_ascii(&mut a, cmd, &args_ref, &state); a.render() }
                _ => run_cmd(cmd, &args_ref, &mut state),
            };
            app.emit(&out);
            if let Some(ref f) = app.save_file { let _ = save_state(f, &state); }
        }
        AppMode::Interactive => {
            print_banner("Chapter 24", "Commutative Algebra",
                         "Noetherian rings, localization, Nullstellensatz, Krull dimension");
            println!("{}", help_text());
            repl("ch24> ", &mut |cmd, args| run_cmd_bool(cmd, args, &mut state));
        }
    }
}
